{
  "Amos-1": [
    "The words of Amos, one of the shepherds of Tekoa--what he saw concerning Israel two years before the earthquake, when Uzziah was king of Judah and Jeroboam son of Jehoash was king of Israel.",
    "He said: \"The LORD roars from Zion and thunders from Jerusalem; the pastures of the shepherds dry up, and the top of Carmel withers.\"",
    "This is what the LORD says: \"For three sins of Damascus, even for four, I will not turn back my wrath. Because she threshed Gilead with sledges having iron teeth,",
    "I will send fire upon the house of Hazael that will consume the fortresses of Ben-Hadad.",
    "I will break down the gate of Damascus; I will destroy the king who is in the Valley of Aven and the one who holds the scepter in Beth Eden. The people of Aram will go into exile to Kir,\" says the LORD.",
    "This is what the LORD says: \"For three sins of Gaza, even for four, I will not turn back my wrath. Because she took captive whole communities and sold them to Edom,",
    "I will send fire upon the walls of Gaza that will consume her fortresses.",
    "I will destroy the king of Ashdod and the one who holds the scepter in Ashkelon. I will turn my hand against Ekron, till the last of the Philistines is dead,\" says the Sovereign LORD.",
    "This is what the LORD says: \"For three sins of Tyre, even for four, I will not turn back my wrath. Because she sold whole communities of captives to Edom, disregarding a treaty of brotherhood,",
    "I will send fire upon the walls of Tyre that will consume her fortresses.\"",
    "This is what the LORD says: \"For three sins of Edom, even for four, I will not turn back my wrath. Because he pursued his brother with a sword, stifling all compassion, because his anger raged continually and his fury flamed unchecked,",
    "I will send fire upon Teman that will consume the fortresses of Bozrah.\"",
    "This is what the LORD says: \"For three sins of Ammon, even for four, I will not turn back my wrath. Because he ripped open the pregnant women of Gilead in order to extend his borders,",
    "I will set fire to the walls of Rabbah that will consume her fortresses amid war cries on the day of battle, amid violent winds on a stormy day.",
    "Her king will go into exile, he and his officials together,\" says the LORD."
  ],
  "Amos-2": [
    "This is what the LORD says: \"For three sins of Moab, even for four, I will not turn back my wrath. Because he burned, as if to lime, the bones of Edom's king,",
    "I will send fire upon Moab that will consume the fortresses of Kerioth. Moab will go down in great tumult amid war cries and the blast of the trumpet.",
    "I will destroy her ruler and kill all her officials with him,\" says the LORD.",
    "This is what the LORD says: \"For three sins of Judah, even for four, I will not turn back my wrath. Because they have rejected the law of the LORD and have not kept his decrees, because they have been led astray by false gods, the gods their ancestors followed,",
    "I will send fire upon Judah that will consume the fortresses of Jerusalem.\"",
    "This is what the LORD says: \"For three sins of Israel, even for four, I will not turn back my wrath. They sell the righteous for silver, and the needy for a pair of sandals.",
    "They trample on the heads of the poor as upon the dust of the ground and deny justice to the oppressed. Father and son use the same girl and so profane my holy name.",
    "They lie down beside every altar on garments taken in pledge. In the house of their god they drink wine taken as fines.",
    "\"I destroyed the Amorite before them, though he was tall as the cedars and strong as the oaks. I destroyed his fruit above and his roots below.",
    "\"I brought you up out of Egypt, and I led you forty years in the desert to give you the land of the Amorites.",
    "I also raised up prophets from among your sons and Nazirites from among your young men. Is this not true, people of Israel?\" declares the LORD.",
    "\"But you made the Nazirites drink wine and commanded the prophets not to prophesy.",
    "\"Now then, I will crush you as a cart crushes when loaded with grain.",
    "The swift will not escape, the strong will not muster their strength, and the warrior will not save his life.",
    "The archer will not stand his ground, the fleet-footed soldier will not get away, and the horseman will not save his life.",
    "Even the bravest warriors will flee naked on that day,\" declares the LORD."
  ],
  "Amos-3": [
    "Hear this word the LORD has spoken against you, O people of Israel--against the whole family I brought up out of Egypt:",
    "\"You only have I chosen of all the families of the earth; therefore I will punish you for all your sins.\"",
    "Do two walk together unless they have agreed to do so?",
    "Does a lion roar in the thicket when he has no prey? Does he growl in his den when he has caught nothing?",
    "Does a bird fall into a trap on the ground where no snare has been set? Does a trap spring up from the earth when there is nothing to catch?",
    "When a trumpet sounds in a city, do not the people tremble? When disaster comes to a city, has not the LORD caused it?",
    "Surely the Sovereign LORD does nothing without revealing his plan to his servants the prophets.",
    "The lion has roared--who will not fear? The Sovereign LORD has spoken--who can but prophesy?",
    "Proclaim to the fortresses of Ashdod and to the fortresses of Egypt: \"Assemble yourselves on the mountains of Samaria; see the great unrest within her and the oppression among her people.\"",
    "\"They do not know how to do right,\" declares the LORD, \"who hoard plunder and loot in their fortresses.\"",
    "Therefore this is what the Sovereign LORD says: \"An enemy will overrun the land; he will pull down your strongholds and plunder your fortresses.\"",
    "This is what the LORD says: \"As a shepherd saves from the lion's mouth only two leg bones or a piece of an ear, so will the Israelites be saved, those who sit in Samaria on the edge of their beds and in Damascus on their couches.\"",
    "\"Hear this and testify against the house of Jacob,\" declares the Lord, the LORD God Almighty.",
    "\"On the day I punish Israel for her sins, I will destroy the altars of Bethel; the horns of the altar will be cut off and fall to the ground.",
    "I will tear down the winter house along with the summer house; the houses adorned with ivory will be destroyed and the mansions will be demolished,\" declares the LORD."
  ],
  "Amos-4": [
    "Hear this word, you cows of Bashan on Mount Samaria, you women who oppress the poor and crush the needy and say to your husbands, \"Bring us some drinks!\"",
    "The Sovereign LORD has sworn by his holiness: \"The time will surely come when you will be taken away with hooks, the last of you with fishhooks.",
    "You will each go straight out through breaks in the wall, and you will be cast out toward Harmon,\" declares the LORD.",
    "\"Go to Bethel and sin; go to Gilgal and sin yet more. Bring your sacrifices every morning, your tithes every three years.",
    "Burn leavened bread as a thank offering and brag about your freewill offerings--boast about them, you Israelites, for this is what you love to do,\" declares the Sovereign LORD.",
    "\"I gave you empty stomachs in every city and lack of bread in every town, yet you have not returned to me,\" declares the LORD.",
    "\"I also withheld rain from you when the harvest was still three months away. I sent rain on one town, but withheld it from another. One field had rain; another had none and dried up.",
    "People staggered from town to town for water but did not get enough to drink, yet you have not returned to me,\" declares the LORD.",
    "\"Many times I struck your gardens and vineyards, I struck them with blight and mildew. Locusts devoured your fig and olive trees, yet you have not returned to me,\" declares the LORD.",
    "\"I sent plagues among you as I did to Egypt. I killed your young men with the sword, along with your captured horses. I filled your nostrils with the stench of your camps, yet you have not returned to me,\" declares the LORD.",
    "\"I overthrew some of you as I overthrew Sodom and Gomorrah. You were like a burning stick snatched from the fire, yet you have not returned to me,\" declares the LORD.",
    "\"Therefore this is what I will do to you, Israel, and because I will do this to you, prepare to meet your God, O Israel.\"",
    "He who forms the mountains, creates the wind, and reveals his thoughts to man, he who turns dawn to darkness, and treads the high places of the earth--the LORD God Almighty is his name."
  ],
  "Amos-5": [
    "Hear this word, O house of Israel, this lament I take up concerning you:",
    "\"Fallen is Virgin Israel, never to rise again, deserted in her own land, with no one to lift her up.\"",
    "This is what the Sovereign LORD says: \"The city that marches out a thousand strong for Israel will have only a hundred left; the town that marches out a hundred strong will have only ten left.\"",
    "This is what the LORD says to the house of Israel: \"Seek me and live;",
    "do not seek Bethel, do not go to Gilgal, do not journey to Beersheba. For Gilgal will surely go into exile, and Bethel will be reduced to nothing.\"",
    "Seek the LORD and live, or he will sweep through the house of Joseph like a fire; it will devour, and Bethel will have no one to quench it.",
    "You who turn justice into bitterness and cast righteousness to the ground",
    "(he who made the Pleiades and Orion, who turns blackness into dawn and darkens day into night, who calls for the waters of the sea and pours them out over the face of the land--the LORD is his name--",
    "he flashes destruction on the stronghold and brings the fortified city to ruin),",
    "you hate the one who reproves in court and despise him who tells the truth.",
    "You trample on the poor and force him to give you grain. Therefore, though you have built stone mansions, you will not live in them; though you have planted lush vineyards, you will not drink their wine.",
    "For I know how many are your offenses and how great your sins. You oppress the righteous and take bribes and you deprive the poor of justice in the courts.",
    "Therefore the prudent man keeps quiet in such times, for the times are evil.",
    "Seek good, not evil, that you may live. Then the LORD God Almighty will be with you, just as you say he is.",
    "Hate evil, love good; maintain justice in the courts. Perhaps the LORD God Almighty will have mercy on the remnant of Joseph.",
    "Therefore this is what the Lord, the LORD God Almighty, says: \"There will be wailing in all the streets and cries of anguish in every public square. The farmers will be summoned to weep and the mourners to wail.",
    "There will be wailing in all the vineyards, for I will pass through your midst,\" says the LORD.",
    "Woe to you who long for the day of the LORD! Why do you long for the day of the LORD? That day will be darkness, not light.",
    "It will be as though a man fled from a lion only to meet a bear, as though he entered his house and rested his hand on the wall only to have a snake bite him.",
    "Will not the day of the LORD be darkness, not light--pitch-dark, without a ray of brightness?",
    "\"I hate, I despise your religious feasts; I cannot stand your assemblies.",
    "Even though you bring me burnt offerings and grain offerings, I will not accept them. Though you bring choice fellowship offerings, I will have no regard for them.",
    "Away with the noise of your songs! I will not listen to the music of your harps.",
    "But let justice roll on like a river, righteousness like a never-failing stream!",
    "\"Did you bring me sacrifices and offerings forty years in the desert, O house of Israel?",
    "You have lifted up the shrine of your king, the pedestal of your idols, the star of your god--which you made for yourselves.",
    "Therefore I will send you into exile beyond Damascus,\" says the LORD, whose name is God Almighty."
  ],
  "Amos-6": [
    "Woe to you who are complacent in Zion, and to you who feel secure on Mount Samaria, you notable men of the foremost nation, to whom the people of Israel come!",
    "Go to Calneh and look at it; go from there to great Hamath, and then go down to Gath in Philistia. Are they better off than your two kingdoms? Is their land larger than yours?",
    "You put off the evil day and bring near a reign of terror.",
    "You lie on beds inlaid with ivory and lounge on your couches. You dine on choice lambs and fattened calves.",
    "You strum away on your harps like David and improvise on musical instruments.",
    "You drink wine by the bowlful and use the finest lotions, but you do not grieve over the ruin of Joseph.",
    "Therefore you will be among the first to go into exile; your feasting and lounging will end.",
    "The Sovereign LORD has sworn by himself--the LORD God Almighty declares: \"I abhor the pride of Jacob and detest his fortresses; I will deliver up the city and everything in it.\"",
    "If ten men are left in one house, they too will die.",
    "And if a relative who is to burn the bodies comes to carry them out of the house and asks anyone still hiding there, \"Is anyone with you?\" and he says, \"No,\" then he will say, \"Hush! We must not mention the name of the LORD.\"",
    "For the LORD has given the command, and he will smash the great house into pieces and the small house into bits.",
    "Do horses run on the rocky crags? Does one plow there with oxen? But you have turned justice into poison and the fruit of righteousness into bitterness--",
    "you who rejoice in the conquest of Lo Debar and say, \"Did we not take Karnaim by our own strength?\"",
    "For the LORD God Almighty declares, \"I will stir up a nation against you, O house of Israel, that will oppress you all the way from Lebo Hamath to the valley of the Arabah.\""
  ],
  "Amos-7": [
    "This is what the Sovereign LORD showed me: He was preparing swarms of locusts after the king's share had been harvested and just as the second crop was coming up.",
    "When they had stripped the land clean, I cried out, \"Sovereign LORD, forgive! How can Jacob survive? He is so small!\"",
    "So the LORD relented. \"This will not happen,\" the LORD said.",
    "This is what the Sovereign LORD showed me: The Sovereign LORD was calling for judgment by fire; it dried up the great deep and devoured the land.",
    "Then I cried out, \"Sovereign LORD, I beg you, stop! How can Jacob survive? He is so small!\"",
    "So the LORD relented. \"This will not happen either,\" the Sovereign LORD said.",
    "This is what he showed me: The Lord was standing by a wall that had been built true to plumb, with a plumb line in his hand.",
    "And the LORD asked me, \"What do you see, Amos?\" \"A plumb line,\" I replied. Then the Lord said, \"Look, I am setting a plumb line among my people Israel; I will spare them no longer.",
    "\"The high places of Isaac will be destroyed and the sanctuaries of Israel will be ruined; with my sword I will rise against the house of Jeroboam.\"",
    "Then Amaziah the priest of Bethel sent a message to Jeroboam king of Israel: \"Amos is raising a conspiracy against you in the very heart of Israel. The land cannot bear all his words.",
    "For this is what Amos is saying: \"'Jeroboam will die by the sword, and Israel will surely go into exile, away from their native land.'\"",
    "Then Amaziah said to Amos, \"Get out, you seer! Go back to the land of Judah. Earn your bread there and do your prophesying there.",
    "Don't prophesy anymore at Bethel, because this is the king's sanctuary and the temple of the kingdom.\"",
    "Amos answered Amaziah, \"I was neither a prophet nor a prophet's son, but I was a shepherd, and I also took care of sycamore-fig trees.",
    "But the LORD took me from tending the flock and said to me, 'Go, prophesy to my people Israel.'",
    "Now then, hear the word of the LORD. You say, \"'Do not prophesy against Israel, and stop preaching against the house of Isaac.'",
    "\"Therefore this is what the LORD says: \"'Your wife will become a prostitute in the city, and your sons and daughters will fall by the sword. Your land will be measured and divided up, and you yourself will die in a pagan country. And Israel will certainly go into exile, away from their native land.'\""
  ],
  "Amos-8": [
    "This is what the Sovereign LORD showed me: a basket of ripe fruit.",
    "\"What do you see, Amos?\" he asked. \"A basket of ripe fruit,\" I answered. Then the LORD said to me, \"The time is ripe for my people Israel; I will spare them no longer.",
    "\"In that day,\" declares the Sovereign LORD, \"the songs in the temple will turn to wailing. Many, many bodies--flung everywhere! Silence!\"",
    "Hear this, you who trample the needy and do away with the poor of the land,",
    "saying, \"When will the New Moon be over that we may sell grain, and the Sabbath be ended that we may market wheat?\"--skimping the measure, boosting the price and cheating with dishonest scales,",
    "buying the poor with silver and the needy for a pair of sandals, selling even the sweepings with the wheat.",
    "The LORD has sworn by the Pride of Jacob: \"I will never forget anything they have done.",
    "\"Will not the land tremble for this, and all who live in it mourn? The whole land will rise like the Nile; it will be stirred up and then sink like the river of Egypt.",
    "\"In that day,\" declares the Sovereign LORD, \"I will make the sun go down at noon and darken the earth in broad daylight.",
    "I will turn your religious feasts into mourning and all your singing into weeping. I will make all of you wear sackcloth and shave your heads. I will make that time like mourning for an only son and the end of it like a bitter day.",
    "\"The days are coming,\" declares the Sovereign LORD, \"when I will send a famine through the land--not a famine of food or a thirst for water, but a famine of hearing the words of the LORD.",
    "Men will stagger from sea to sea and wander from north to east, searching for the word of the LORD, but they will not find it.",
    "\"In that day \"the lovely young women and strong young men will faint because of thirst.",
    "They who swear by the shame of Samaria, or say, 'As surely as your god lives, O Dan,' or, 'As surely as the god of Beersheba lives'--they will fall, never to rise again.\""
  ],
  "Amos-9": [
    "I saw the Lord standing by the altar, and he said: \"Strike the tops of the pillars so that the thresholds shake. Bring them down on the heads of all the people; those who are left I will kill with the sword. Not one will get away, none will escape.",
    "Though they dig down to the depths of the grave, from there my hand will take them. Though they climb up to the heavens, from there I will bring them down.",
    "Though they hide themselves on the top of Carmel, there I will hunt them down and seize them. Though they hide from me at the bottom of the sea, there I will command the serpent to bite them.",
    "Though they are driven into exile by their enemies, there I will command the sword to slay them. I will fix my eyes upon them for evil and not for good.\"",
    "The Lord, the LORD Almighty, he who touches the earth and it melts, and all who live in it mourn--the whole land rises like the Nile, then sinks like the river of Egypt--",
    "he who builds his lofty palace in the heavens and sets its foundation on the earth, who calls for the waters of the sea and pours them out over the face of the land--the LORD is his name.",
    "\"Are not you Israelites the same to me as the Cushites?\" declares the LORD. \"Did I not bring Israel up from Egypt, the Philistines from Caphtor and the Arameans from Kir?",
    "\"Surely the eyes of the Sovereign LORD are on the sinful kingdom. I will destroy it from the face of the earth--yet I will not totally destroy the house of Jacob,\" declares the LORD.",
    "\"For I will give the command, and I will shake the house of Israel among all the nations as grain is shaken in a sieve, and not a pebble will reach the ground.",
    "All the sinners among my people will die by the sword, all those who say, 'Disaster will not overtake or meet us.'",
    "\"In that day I will restore David's fallen tent. I will repair its broken places, restore its ruins, and build it as it used to be,",
    "so that they may possess the remnant of Edom and all the nations that bear my name,\" declares the LORD, who will do these things.",
    "\"The days are coming,\" declares the LORD, \"when the reaper will be overtaken by the plowman and the planter by the one treading grapes. New wine will drip from the mountains and flow from all the hills.",
    "I will bring back my exiled people Israel; they will rebuild the ruined cities and live in them. They will plant vineyards and drink their wine; they will make gardens and eat their fruit.",
    "I will plant Israel in their own land, never again to be uprooted from the land I have given them,\" says the LORD your God."
  ]
}