{
  "Colossians-1": [
    "Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
    "To the holy and faithful brothers in Christ at Colosse: Grace and peace to you from God our Father.",
    "We always thank God, the Father of our Lord Jesus Christ, when we pray for you,",
    "because we have heard of your faith in Christ Jesus and of the love you have for all the saints--",
    "the faith and love that spring from the hope that is stored up for you in heaven and that you have already heard about in the word of truth, the gospel",
    "that has come to you. All over the world this gospel is bearing fruit and growing, just as it has been doing among you since the day you heard it and understood God's grace in all its truth.",
    "You learned it from Epaphras, our dear fellow servant, who is a faithful minister of Christ on our behalf,",
    "and who also told us of your love in the Spirit.",
    "For this reason, since the day we heard about you, we have not stopped praying for you and asking God to fill you with the knowledge of his will through all spiritual wisdom and understanding.",
    "And we pray this in order that you may live a life worthy of the Lord and may please him in every way: bearing fruit in every good work, growing in the knowledge of God,",
    "being strengthened with all power according to his glorious might so that you may have great endurance and patience, and joyfully",
    "giving thanks to the Father, who has qualified you to share in the inheritance of the saints in the kingdom of light.",
    "For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves,",
    "in whom we have redemption, the forgiveness of sins.",
    "He is the image of the invisible God, the firstborn over all creation.",
    "For by him all things were created: things in heaven and on earth, visible and invisible, whether thrones or powers or rulers or authorities; all things were created by him and for him.",
    "He is before all things, and in him all things hold together.",
    "And he is the head of the body, the church; he is the beginning and the firstborn from among the dead, so that in everything he might have the supremacy.",
    "For God was pleased to have all his fullness dwell in him,",
    "and through him to reconcile to himself all things, whether things on earth or things in heaven, by making peace through his blood, shed on the cross.",
    "Once you were alienated from God and were enemies in your minds because of your evil behavior.",
    "But now he has reconciled you by Christ's physical body through death to present you holy in his sight, without blemish and free from accusation--",
    "if you continue in your faith, established and firm, not moved from the hope held out in the gospel. This is the gospel that you heard and that has been proclaimed to every creature under heaven, and of which I, Paul, have become a servant.",
    "Now I rejoice in what was suffered for you, and I fill up in my flesh what is still lacking in regard to Christ's afflictions, for the sake of his body, which is the church.",
    "I have become its servant by the commission God gave me to present to you the word of God in its fullness--",
    "the mystery that has been kept hidden for ages and generations, but is now disclosed to the saints.",
    "To them God has chosen to make known among the Gentiles the glorious riches of this mystery, which is Christ in you, the hope of glory.",
    "We proclaim him, admonishing and teaching everyone with all wisdom, so that we may present everyone perfect in Christ.",
    "To this end I labor, struggling with all his energy, which so powerfully works in me."
  ],
  "Colossians-2": [
    "I want you to know how much I am struggling for you and for those at Laodicea, and for all who have not met me personally.",
    "My purpose is that they may be encouraged in heart and united in love, so that they may have the full riches of complete understanding, in order that they may know the mystery of God, namely, Christ,",
    "in whom are hidden all the treasures of wisdom and knowledge.",
    "I tell you this so that no one may deceive you by fine-sounding arguments.",
    "For though I am absent from you in body, I am present with you in spirit and delight to see how orderly you are and how firm your faith in Christ is.",
    "So then, just as you received Christ Jesus as Lord, continue to live in him,",
    "rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.",
    "See to it that no one takes you captive through hollow and deceptive philosophy, which depends on human tradition and the basic principles of this world rather than on Christ.",
    "For in Christ all the fullness of the Deity lives in bodily form,",
    "and you have been given fullness in Christ, who is the head over every power and authority.",
    "In him you were also circumcised, in the putting off of the sinful nature, not with a circumcision done by the hands of men but with the circumcision done by Christ,",
    "having been buried with him in baptism and raised with him through your faith in the power of God, who raised him from the dead.",
    "When you were dead in your sins and in the uncircumcision of your sinful nature, God made you alive with Christ. He forgave us all our sins,",
    "having canceled the written code, with its regulations, that was against us and that stood opposed to us; he took it away, nailing it to the cross.",
    "And having disarmed the powers and authorities, he made a public spectacle of them, triumphing over them by the cross.",
    "Therefore do not let anyone judge you by what you eat or drink, or with regard to a religious festival, a New Moon celebration or a Sabbath day.",
    "These are a shadow of the things that were to come; the reality, however, is found in Christ.",
    "Do not let anyone who delights in false humility and the worship of angels disqualify you for the prize. Such a person goes into great detail about what he has seen, and his unspiritual mind puffs him up with idle notions.",
    "He has lost connection with the Head, from whom the whole body, supported and held together by its ligaments and sinews, grows as God causes it to grow.",
    "Since you died with Christ to the basic principles of this world, why, as though you still belonged to it, do you submit to its rules:",
    "\"Do not handle! Do not taste! Do not touch!\"?",
    "These are all destined to perish with use, because they are based on human commands and teachings.",
    "Such regulations indeed have an appearance of wisdom, with their self-imposed worship, their false humility and their harsh treatment of the body, but they lack any value in restraining sensual indulgence."
  ],
  "Colossians-3": [
    "Since, then, you have been raised with Christ, set your hearts on things above, where Christ is seated at the right hand of God.",
    "Set your minds on things above, not on earthly things.",
    "For you died, and your life is now hidden with Christ in God.",
    "When Christ, who is your life, appears, then you also will appear with him in glory.",
    "Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry.",
    "Because of these, the wrath of God is coming.",
    "You used to walk in these ways, in the life you once lived.",
    "But now you must rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.",
    "Do not lie to each other, since you have taken off your old self with its practices",
    "and have put on the new self, which is being renewed in knowledge in the image of its Creator.",
    "Here there is no Greek or Jew, circumcised or uncircumcised, barbarian, Scythian, slave or free, but Christ is all, and is in all.",
    "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.",
    "Bear with each other and forgive whatever grievances you may have against one another. Forgive as the Lord forgave you.",
    "And over all these virtues put on love, which binds them all together in perfect unity.",
    "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.",
    "Let the word of Christ dwell in you richly as you teach and admonish one another with all wisdom, and as you sing psalms, hymns and spiritual songs with gratitude in your hearts to God.",
    "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.",
    "Wives, submit to your husbands, as is fitting in the Lord.",
    "Husbands, love your wives and do not be harsh with them.",
    "Children, obey your parents in everything, for this pleases the Lord.",
    "Fathers, do not embitter your children, or they will become discouraged.",
    "Slaves, obey your earthly masters in everything; and do it, not only when their eye is on you and to win their favor, but with sincerity of heart and reverence for the Lord.",
    "Whatever you do, work at it with all your heart, as working for the Lord, not for men,",
    "since you know that you will receive an inheritance from the Lord as a reward. It is the Lord Christ you are serving.",
    "Anyone who does wrong will be repaid for his wrong, and there is no favoritism."
  ],
  "Colossians-4": [
    "Masters, provide your slaves with what is right and fair, because you know that you also have a Master in heaven.",
    "Devote yourselves to prayer, being watchful and thankful.",
    "And pray for us, too, that God may open a door for our message, so that we may proclaim the mystery of Christ, for which I am in chains.",
    "Pray that I may proclaim it clearly, as I should.",
    "Be wise in the way you act toward outsiders; make the most of every opportunity.",
    "Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone.",
    "Tychicus will tell you all the news about me. He is a dear brother, a faithful minister and fellow servant in the Lord.",
    "I am sending him to you for the express purpose that you may know about our circumstances and that he may encourage your hearts.",
    "He is coming with Onesimus, our faithful and dear brother, who is one of you. They will tell you everything that is happening here.",
    "My fellow prisoner Aristarchus sends you his greetings, as does Mark, the cousin of Barnabas. (You have received instructions about him; if he comes to you, welcome him.)",
    "Jesus, who is called Justus, also sends greetings. These are the only Jews among my fellow workers for the kingdom of God, and they have proved a comfort to me.",
    "Epaphras, who is one of you and a servant of Christ Jesus, sends greetings. He is always wrestling in prayer for you, that you may stand firm in all the will of God, mature and fully assured.",
    "I vouch for him that he is working hard for you and for those at Laodicea and Hierapolis.",
    "Our dear friend Luke, the doctor, and Demas send greetings.",
    "Give my greetings to the brothers at Laodicea, and to Nympha and the church in her house.",
    "After this letter has been read to you, see that it is also read in the church of the Laodiceans and that you in turn read the letter from Laodicea.",
    "Tell Archippus: \"See to it that you complete the work you have received in the Lord.\"",
    "I, Paul, write this greeting in my own hand. Remember my chains. Grace be with you."
  ]
}