{
  "Corinthians1-1": [
    "Paul, called to be an apostle of Christ Jesus by the will of God, and our brother Sosthenes,",
    "To the church of God in Corinth, to those sanctified in Christ Jesus and called to be holy, together with all those everywhere who call on the name of our Lord Jesus Christ--their Lord and ours:",
    "Grace and peace to you from God our Father and the Lord Jesus Christ.",
    "I always thank God for you because of his grace given you in Christ Jesus.",
    "For in him you have been enriched in every way--in all your speaking and in all your knowledge--",
    "because our testimony about Christ was confirmed in you.",
    "Therefore you do not lack any spiritual gift as you eagerly wait for our Lord Jesus Christ to be revealed.",
    "He will keep you strong to the end, so that you will be blameless on the day of our Lord Jesus Christ.",
    "God, who has called you into fellowship with his Son Jesus Christ our Lord, is faithful.",
    "I appeal to you, brothers, in the name of our Lord Jesus Christ, that all of you agree with one another so that there may be no divisions among you and that you may be perfectly united in mind and thought.",
    "My brothers, some from Chloe's household have informed me that there are quarrels among you.",
    "What I mean is this: One of you says, \"I follow Paul\"; another, \"I follow Apollos\"; another, \"I follow Cephas\"; still another, \"I follow Christ.\"",
    "Is Christ divided? Was Paul crucified for you? Were you baptized into the name of Paul?",
    "I am thankful that I did not baptize any of you except Crispus and Gaius,",
    "so no one can say that you were baptized into my name.",
    "(Yes, I also baptized the household of Stephanas; beyond that, I don't remember if I baptized anyone else.)",
    "For Christ did not send me to baptize, but to preach the gospel--not with words of human wisdom, lest the cross of Christ be emptied of its power.",
    "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.",
    "For it is written: \"I will destroy the wisdom of the wise; the intelligence of the intelligent I will frustrate.\"",
    "Where is the wise man? Where is the scholar? Where is the philosopher of this age? Has not God made foolish the wisdom of the world?",
    "For since in the wisdom of God the world through its wisdom did not know him, God was pleased through the foolishness of what was preached to save those who believe.",
    "Jews demand miraculous signs and Greeks look for wisdom,",
    "but we preach Christ crucified: a stumbling block to Jews and foolishness to Gentiles,",
    "but to those whom God has called, both Jews and Greeks, Christ the power of God and the wisdom of God.",
    "For the foolishness of God is wiser than man's wisdom, and the weakness of God is stronger than man's strength.",
    "Brothers, think of what you were when you were called. Not many of you were wise by human standards; not many were influential; not many were of noble birth.",
    "But God chose the foolish things of the world to shame the wise; God chose the weak things of the world to shame the strong.",
    "He chose the lowly things of this world and the despised things--and the things that are not--to nullify the things that are,",
    "so that no one may boast before him.",
    "It is because of him that you are in Christ Jesus, who has become for us wisdom from God--that is, our righteousness, holiness and redemption.",
    "Therefore, as it is written: \"Let him who boasts boast in the Lord.\""
  ],
  "Corinthians1-2": [
    "When I came to you, brothers, I did not come with eloquence or superior wisdom as I proclaimed to you the testimony about God.",
    "For I resolved to know nothing while I was with you except Jesus Christ and him crucified.",
    "I came to you in weakness and fear, and with much trembling.",
    "My message and my preaching were not with wise and persuasive words, but with a demonstration of the Spirit's power,",
    "so that your faith might not rest on men's wisdom, but on God's power.",
    "We do, however, speak a message of wisdom among the mature, but not the wisdom of this age or of the rulers of this age, who are coming to nothing.",
    "No, we speak of God's secret wisdom, a wisdom that has been hidden and that God destined for our glory before time began.",
    "None of the rulers of this age understood it, for if they had, they would not have crucified the Lord of glory.",
    "However, as it is written: \"No eye has seen, no ear has heard, no mind has conceived what God has prepared for those who love him\"--",
    "but God has revealed it to us by his Spirit. The Spirit searches all things, even the deep things of God.",
    "For who among men knows the thoughts of a man except the man's spirit within him? In the same way no one knows the thoughts of God except the Spirit of God.",
    "We have not received the spirit of the world but the Spirit who is from God, that we may understand what God has freely given us.",
    "This is what we speak, not in words taught us by human wisdom but in words taught by the Spirit, expressing spiritual truths in spiritual words.",
    "The man without the Spirit does not accept the things that come from the Spirit of God, for they are foolishness to him, and he cannot understand them, because they are spiritually discerned.",
    "The spiritual man makes judgments about all things, but he himself is not subject to any man's judgment:",
    "\"For who has known the mind of the Lord that he may instruct him?\" But we have the mind of Christ."
  ],
  "Corinthians1-3": [
    "Brothers, I could not address you as spiritual but as worldly--mere infants in Christ.",
    "I gave you milk, not solid food, for you were not yet ready for it. Indeed, you are still not ready.",
    "You are still worldly. For since there is jealousy and quarreling among you, are you not worldly? Are you not acting like mere men?",
    "For when one says, \"I follow Paul,\" and another, \"I follow Apollos,\" are you not mere men?",
    "What, after all, is Apollos? And what is Paul? Only servants, through whom you came to believe--as the Lord has assigned to each his task.",
    "I planted the seed, Apollos watered it, but God made it grow.",
    "So neither he who plants nor he who waters is anything, but only God, who makes things grow.",
    "The man who plants and the man who waters have one purpose, and each will be rewarded according to his own labor.",
    "For we are God's fellow workers; you are God's field, God's building.",
    "By the grace God has given me, I laid a foundation as an expert builder, and someone else is building on it. But each one should be careful how he builds.",
    "For no one can lay any foundation other than the one already laid, which is Jesus Christ.",
    "If any man builds on this foundation using gold, silver, costly stones, wood, hay or straw,",
    "his work will be shown for what it is, because the Day will bring it to light. It will be revealed with fire, and the fire will test the quality of each man's work.",
    "If what he has built survives, he will receive his reward.",
    "If it is burned up, he will suffer loss; he himself will be saved, but only as one escaping through the flames.",
    "Don't you know that you yourselves are God's temple and that God's Spirit lives in you?",
    "If anyone destroys God's temple, God will destroy him; for God's temple is sacred, and you are that temple.",
    "Do not deceive yourselves. If any one of you thinks he is wise by the standards of this age, he should become a \"fool\" so that he may become wise.",
    "For the wisdom of this world is foolishness in God's sight. As it is written: \"He catches the wise in their craftiness\";",
    "and again, \"The Lord knows that the thoughts of the wise are futile.\"",
    "So then, no more boasting about men! All things are yours,",
    "whether Paul or Apollos or Cephas or the world or life or death or the present or the future--all are yours,",
    "and you are of Christ, and Christ is of God."
  ],
  "Corinthians1-4": [
    "So then, men ought to regard us as servants of Christ and as those entrusted with the secret things of God.",
    "Now it is required that those who have been given a trust must prove faithful.",
    "I care very little if I am judged by you or by any human court; indeed, I do not even judge myself.",
    "My conscience is clear, but that does not make me innocent. It is the Lord who judges me.",
    "Therefore judge nothing before the appointed time; wait till the Lord comes. He will bring to light what is hidden in darkness and will expose the motives of men's hearts. At that time each will receive his praise from God.",
    "Now, brothers, I have applied these things to myself and Apollos for your benefit, so that you may learn from us the meaning of the saying, \"Do not go beyond what is written.\" Then you will not take pride in one man over against another.",
    "For who makes you different from anyone else? What do you have that you did not receive? And if you did receive it, why do you boast as though you did not?",
    "Already you have all you want! Already you have become rich! You have become kings--and that without us! How I wish that you really had become kings so that we might be kings with you!",
    "For it seems to me that God has put us apostles on display at the end of the procession, like men condemned to die in the arena. We have been made a spectacle to the whole universe, to angels as well as to men.",
    "We are fools for Christ, but you are so wise in Christ! We are weak, but you are strong! You are honored, we are dishonored!",
    "To this very hour we go hungry and thirsty, we are in rags, we are brutally treated, we are homeless.",
    "We work hard with our own hands. When we are cursed, we bless; when we are persecuted, we endure it;",
    "when we are slandered, we answer kindly. Up to this moment we have become the scum of the earth, the refuse of the world.",
    "I am not writing this to shame you, but to warn you, as my dear children.",
    "Even though you have ten thousand guardians in Christ, you do not have many fathers, for in Christ Jesus I became your father through the gospel.",
    "Therefore I urge you to imitate me.",
    "For this reason I am sending to you Timothy, my son whom I love, who is faithful in the Lord. He will remind you of my way of life in Christ Jesus, which agrees with what I teach everywhere in every church.",
    "Some of you have become arrogant, as if I were not coming to you.",
    "But I will come to you very soon, if the Lord is willing, and then I will find out not only how these arrogant people are talking, but what power they have.",
    "For the kingdom of God is not a matter of talk but of power.",
    "What do you prefer? Shall I come to you with a whip, or in love and with a gentle spirit?"
  ],
  "Corinthians1-5": [
    "It is actually reported that there is sexual immorality among you, and of a kind that does not occur even among pagans: A man has his father's wife.",
    "And you are proud! Shouldn't you rather have been filled with grief and have put out of your fellowship the man who did this?",
    "Even though I am not physically present, I am with you in spirit. And I have already passed judgment on the one who did this, just as if I were present.",
    "When you are assembled in the name of our Lord Jesus and I am with you in spirit, and the power of our Lord Jesus is present,",
    "hand this man over to Satan, so that the sinful nature may be destroyed and his spirit saved on the day of the Lord.",
    "Your boasting is not good. Don't you know that a little yeast works through the whole batch of dough?",
    "Get rid of the old yeast that you may be a new batch without yeast--as you really are. For Christ, our Passover lamb, has been sacrificed.",
    "Therefore let us keep the Festival, not with the old yeast, the yeast of malice and wickedness, but with bread without yeast, the bread of sincerity and truth.",
    "I have written you in my letter not to associate with sexually immoral people--",
    "not at all meaning the people of this world who are immoral, or the greedy and swindlers, or idolaters. In that case you would have to leave this world.",
    "But now I am writing you that you must not associate with anyone who calls himself a brother but is sexually immoral or greedy, an idolater or a slanderer, a drunkard or a swindler. With such a man do not even eat.",
    "What business is it of mine to judge those outside the church? Are you not to judge those inside?",
    "God will judge those outside. \"Expel the wicked man from among you.\""
  ],
  "Corinthians1-6": [
    "If any of you has a dispute with another, dare he take it before the ungodly for judgment instead of before the saints?",
    "Do you not know that the saints will judge the world? And if you are to judge the world, are you not competent to judge trivial cases?",
    "Do you not know that we will judge angels? How much more the things of this life!",
    "Therefore, if you have disputes about such matters, appoint as judges even men of little account in the church!",
    "I say this to shame you. Is it possible that there is nobody among you wise enough to judge a dispute between believers?",
    "But instead, one brother goes to law against another--and this in front of unbelievers!",
    "The very fact that you have lawsuits among you means you have been completely defeated already. Why not rather be wronged? Why not rather be cheated?",
    "Instead, you yourselves cheat and do wrong, and you do this to your brothers.",
    "Do you not know that the wicked will not inherit the kingdom of God? Do not be deceived: Neither the sexually immoral nor idolaters nor adulterers nor male prostitutes nor homosexual offenders",
    "nor thieves nor the greedy nor drunkards nor slanderers nor swindlers will inherit the kingdom of God.",
    "And that is what some of you were. But you were washed, you were sanctified, you were justified in the name of the Lord Jesus Christ and by the Spirit of our God.",
    "\"Everything is permissible for me\"--but not everything is beneficial. \"Everything is permissible for me\"--but I will not be mastered by anything.",
    "\"Food for the stomach and the stomach for food\"--but God will destroy them both. The body is not meant for sexual immorality, but for the Lord, and the Lord for the body.",
    "By his power God raised the Lord from the dead, and he will raise us also.",
    "Do you not know that your bodies are members of Christ himself? Shall I then take the members of Christ and unite them with a prostitute? Never!",
    "Do you not know that he who unites himself with a prostitute is one with her in body? For it is said, \"The two will become one flesh.\"",
    "But he who unites himself with the Lord is one with him in spirit.",
    "Flee from sexual immorality. All other sins a man commits are outside his body, but he who sins sexually sins against his own body.",
    "Do you not know that your body is a temple of the Holy Spirit, who is in you, whom you have received from God? You are not your own;",
    "you were bought at a price. Therefore honor God with your body."
  ],
  "Corinthians1-7": [
    "Now for the matters you wrote about: It is good for a man not to marry.",
    "But since there is so much immorality, each man should have his own wife, and each woman her own husband.",
    "The husband should fulfill his marital duty to his wife, and likewise the wife to her husband.",
    "The wife's body does not belong to her alone but also to her husband. In the same way, the husband's body does not belong to him alone but also to his wife.",
    "Do not deprive each other except by mutual consent and for a time, so that you may devote yourselves to prayer. Then come together again so that Satan will not tempt you because of your lack of self-control.",
    "I say this as a concession, not as a command.",
    "I wish that all men were as I am. But each man has his own gift from God; one has this gift, another has that.",
    "Now to the unmarried and the widows I say: It is good for them to stay unmarried, as I am.",
    "But if they cannot control themselves, they should marry, for it is better to marry than to burn with passion.",
    "To the married I give this command (not I, but the Lord): A wife must not separate from her husband.",
    "But if she does, she must remain unmarried or else be reconciled to her husband. And a husband must not divorce his wife.",
    "To the rest I say this (I, not the Lord): If any brother has a wife who is not a believer and she is willing to live with him, he must not divorce her.",
    "And if a woman has a husband who is not a believer and he is willing to live with her, she must not divorce him.",
    "For the unbelieving husband has been sanctified through his wife, and the unbelieving wife has been sanctified through her believing husband. Otherwise your children would be unclean, but as it is, they are holy.",
    "But if the unbeliever leaves, let him do so. A believing man or woman is not bound in such circumstances; God has called us to live in peace.",
    "How do you know, wife, whether you will save your husband? Or, how do you know, husband, whether you will save your wife?",
    "Nevertheless, each one should retain the place in life that the Lord assigned to him and to which God has called him. This is the rule I lay down in all the churches.",
    "Was a man already circumcised when he was called? He should not become uncircumcised. Was a man uncircumcised when he was called? He should not be circumcised.",
    "Circumcision is nothing and uncircumcision is nothing. Keeping God's commands is what counts.",
    "Each one should remain in the situation which he was in when God called him.",
    "Were you a slave when you were called? Don't let it trouble you--although if you can gain your freedom, do so.",
    "For he who was a slave when he was called by the Lord is the Lord's freedman; similarly, he who was a free man when he was called is Christ's slave.",
    "You were bought at a price; do not become slaves of men.",
    "Brothers, each man, as responsible to God, should remain in the situation God called him to.",
    "Now about virgins: I have no command from the Lord, but I give a judgment as one who by the Lord's mercy is trustworthy.",
    "Because of the present crisis, I think that it is good for you to remain as you are.",
    "Are you married? Do not seek a divorce. Are you unmarried? Do not look for a wife.",
    "But if you do marry, you have not sinned; and if a virgin marries, she has not sinned. But those who marry will face many troubles in this life, and I want to spare you this.",
    "What I mean, brothers, is that the time is short. From now on those who have wives should live as if they had none;",
    "those who mourn, as if they did not; those who are happy, as if they were not; those who buy something, as if it were not theirs to keep;",
    "those who use the things of the world, as if not engrossed in them. For this world in its present form is passing away.",
    "I would like you to be free from concern. An unmarried man is concerned about the Lord's affairs--how he can please the Lord.",
    "But a married man is concerned about the affairs of this world--how he can please his wife--",
    "and his interests are divided. An unmarried woman or virgin is concerned about the Lord's affairs: Her aim is to be devoted to the Lord in both body and spirit. But a married woman is concerned about the affairs of this world--how she can please her husband.",
    "I am saying this for your own good, not to restrict you, but that you may live in a right way in undivided devotion to the Lord.",
    "If anyone thinks he is acting improperly toward the virgin he is engaged to, and if she is getting along in years and he feels he ought to marry, he should do as he wants. He is not sinning. They should get married.",
    "But the man who has settled the matter in his own mind, who is under no compulsion but has control over his own will, and who has made up his mind not to marry the virgin--this man also does the right thing.",
    "So then, he who marries the virgin does right, but he who does not marry her does even better.",
    "A woman is bound to her husband as long as he lives. But if her husband dies, she is free to marry anyone she wishes, but he must belong to the Lord.",
    "In my judgment, she is happier if she stays as she is--and I think that I too have the Spirit of God."
  ],
  "Corinthians1-8": [
    "Now about food sacrificed to idols: We know that we all possess knowledge. Knowledge puffs up, but love builds up.",
    "The man who thinks he knows something does not yet know as he ought to know.",
    "But the man who loves God is known by God.",
    "So then, about eating food sacrificed to idols: We know that an idol is nothing at all in the world and that there is no God but one.",
    "For even if there are so-called gods, whether in heaven or on earth (as indeed there are many \"gods\" and many \"lords\"),",
    "yet for us there is but one God, the Father, from whom all things came and for whom we live; and there is but one Lord, Jesus Christ, through whom all things came and through whom we live.",
    "But not everyone knows this. Some people are still so accustomed to idols that when they eat such food they think of it as having been sacrificed to an idol, and since their conscience is weak, it is defiled.",
    "But food does not bring us near to God; we are no worse if we do not eat, and no better if we do.",
    "Be careful, however, that the exercise of your freedom does not become a stumbling block to the weak.",
    "For if anyone with a weak conscience sees you who have this knowledge eating in an idol's temple, won't he be emboldened to eat what has been sacrificed to idols?",
    "So this weak brother, for whom Christ died, is destroyed by your knowledge.",
    "When you sin against your brothers in this way and wound their weak conscience, you sin against Christ.",
    "Therefore, if what I eat causes my brother to fall into sin, I will never eat meat again, so that I will not cause him to fall."
  ],
  "Corinthians1-9": [
    "Am I not free? Am I not an apostle? Have I not seen Jesus our Lord? Are you not the result of my work in the Lord?",
    "Even though I may not be an apostle to others, surely I am to you! For you are the seal of my apostleship in the Lord.",
    "This is my defense to those who sit in judgment on me.",
    "Don't we have the right to food and drink?",
    "Don't we have the right to take a believing wife along with us, as do the other apostles and the Lord's brothers and Cephas?",
    "Or is it only I and Barnabas who must work for a living?",
    "Who serves as a soldier at his own expense? Who plants a vineyard and does not eat of its grapes? Who tends a flock and does not drink of the milk?",
    "Do I say this merely from a human point of view? Doesn't the Law say the same thing?",
    "For it is written in the Law of Moses: \"Do not muzzle an ox while it is treading out the grain.\" Is it about oxen that God is concerned?",
    "Surely he says this for us, doesn't he? Yes, this was written for us, because when the plowman plows and the thresher threshes, they ought to do so in the hope of sharing in the harvest.",
    "If we have sown spiritual seed among you, is it too much if we reap a material harvest from you?",
    "If others have this right of support from you, shouldn't we have it all the more? But we did not use this right. On the contrary, we put up with anything rather than hinder the gospel of Christ.",
    "Don't you know that those who work in the temple get their food from the temple, and those who serve at the altar share in what is offered on the altar?",
    "In the same way, the Lord has commanded that those who preach the gospel should receive their living from the gospel.",
    "But I have not used any of these rights. And I am not writing this in the hope that you will do such things for me. I would rather die than have anyone deprive me of this boast.",
    "Yet when I preach the gospel, I cannot boast, for I am compelled to preach. Woe to me if I do not preach the gospel!",
    "If I preach voluntarily, I have a reward; if not voluntarily, I am simply discharging the trust committed to me.",
    "What then is my reward? Just this: that in preaching the gospel I may offer it free of charge, and so not make use of my rights in preaching it.",
    "Though I am free and belong to no man, I make myself a slave to everyone, to win as many as possible.",
    "To the Jews I became like a Jew, to win the Jews. To those under the law I became like one under the law (though I myself am not under the law), so as to win those under the law.",
    "To those not having the law I became like one not having the law (though I am not free from God's law but am under Christ's law), so as to win those not having the law.",
    "To the weak I became weak, to win the weak. I have become all things to all men so that by all possible means I might save some.",
    "I do all this for the sake of the gospel, that I may share in its blessings.",
    "Do you not know that in a race all the runners run, but only one gets the prize? Run in such a way as to get the prize.",
    "Everyone who competes in the games goes into strict training. They do it to get a crown that will not last; but we do it to get a crown that will last forever.",
    "Therefore I do not run like a man running aimlessly; I do not fight like a man beating the air.",
    "No, I beat my body and make it my slave so that after I have preached to others, I myself will not be disqualified for the prize."
  ],
  "Corinthians1-10": [
    "For I do not want you to be ignorant of the fact, brothers, that our forefathers were all under the cloud and that they all passed through the sea.",
    "They were all baptized into Moses in the cloud and in the sea.",
    "They all ate the same spiritual food",
    "and drank the same spiritual drink; for they drank from the spiritual rock that accompanied them, and that rock was Christ.",
    "Nevertheless, God was not pleased with most of them; their bodies were scattered over the desert.",
    "Now these things occurred as examples to keep us from setting our hearts on evil things as they did.",
    "Do not be idolaters, as some of them were; as it is written: \"The people sat down to eat and drink and got up to indulge in pagan revelry.\"",
    "We should not commit sexual immorality, as some of them did--and in one day twenty-three thousand of them died.",
    "We should not test the Lord, as some of them did--and were killed by snakes.",
    "And do not grumble, as some of them did--and were killed by the destroying angel.",
    "These things happened to them as examples and were written down as warnings for us, on whom the fulfillment of the ages has come.",
    "So, if you think you are standing firm, be careful that you don't fall!",
    "No temptation has seized you except what is common to man. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can stand up under it.",
    "Therefore, my dear friends, flee from idolatry.",
    "I speak to sensible people; judge for yourselves what I say.",
    "Is not the cup of thanksgiving for which we give thanks a participation in the blood of Christ? And is not the bread that we break a participation in the body of Christ?",
    "Because there is one loaf, we, who are many, are one body, for we all partake of the one loaf.",
    "Consider the people of Israel: Do not those who eat the sacrifices participate in the altar?",
    "Do I mean then that a sacrifice offered to an idol is anything, or that an idol is anything?",
    "No, but the sacrifices of pagans are offered to demons, not to God, and I do not want you to be participants with demons.",
    "You cannot drink the cup of the Lord and the cup of demons too; you cannot have a part in both the Lord's table and the table of demons.",
    "Are we trying to arouse the Lord's jealousy? Are we stronger than he?",
    "\"Everything is permissible\"--but not everything is beneficial. \"Everything is permissible\"--but not everything is constructive.",
    "Nobody should seek his own good, but the good of others.",
    "Eat anything sold in the meat market without raising questions of conscience,",
    "for, \"The earth is the Lord's, and everything in it.\"",
    "If some unbeliever invites you to a meal and you want to go, eat whatever is put before you without raising questions of conscience.",
    "But if anyone says to you, \"This has been offered in sacrifice,\" then do not eat it, both for the sake of the man who told you and for conscience' sake--",
    "the other man's conscience, I mean, not yours. For why should my freedom be judged by another's conscience?",
    "If I take part in the meal with thankfulness, why am I denounced because of something I thank God for?",
    "So whether you eat or drink or whatever you do, do it all for the glory of God.",
    "Do not cause anyone to stumble, whether Jews, Greeks or the church of God--",
    "even as I try to please everybody in every way. For I am not seeking my own good but the good of many, so that they may be saved."
  ],
  "Corinthians1-11": [
    "Follow my example, as I follow the example of Christ.",
    "I praise you for remembering me in everything and for holding to the teachings, just as I passed them on to you.",
    "Now I want you to realize that the head of every man is Christ, and the head of the woman is man, and the head of Christ is God.",
    "Every man who prays or prophesies with his head covered dishonors his head.",
    "And every woman who prays or prophesies with her head uncovered dishonors her head--it is just as though her head were shaved.",
    "If a woman does not cover her head, she should have her hair cut off; and if it is a disgrace for a woman to have her hair cut or shaved off, she should cover her head.",
    "A man ought not to cover his head, since he is the image and glory of God; but the woman is the glory of man.",
    "For man did not come from woman, but woman from man;",
    "neither was man created for woman, but woman for man.",
    "For this reason, and because of the angels, the woman ought to have a sign of authority on her head.",
    "In the Lord, however, woman is not independent of man, nor is man independent of woman.",
    "For as woman came from man, so also man is born of woman. But everything comes from God.",
    "Judge for yourselves: Is it proper for a woman to pray to God with her head uncovered?",
    "Does not the very nature of things teach you that if a man has long hair, it is a disgrace to him,",
    "but that if a woman has long hair, it is her glory? For long hair is given to her as a covering.",
    "If anyone wants to be contentious about this, we have no other practice--nor do the churches of God.",
    "In the following directives I have no praise for you, for your meetings do more harm than good.",
    "In the first place, I hear that when you come together as a church, there are divisions among you, and to some extent I believe it.",
    "No doubt there have to be differences among you to show which of you have God's approval.",
    "When you come together, it is not the Lord's Supper you eat,",
    "for as you eat, each of you goes ahead without waiting for anybody else. One remains hungry, another gets drunk.",
    "Don't you have homes to eat and drink in? Or do you despise the church of God and humiliate those who have nothing? What shall I say to you? Shall I praise you for this? Certainly not!",
    "For I received from the Lord what I also passed on to you: The Lord Jesus, on the night he was betrayed, took bread,",
    "and when he had given thanks, he broke it and said, \"This is my body, which is for you; do this in remembrance of me.\"",
    "In the same way, after supper he took the cup, saying, \"This cup is the new covenant in my blood; do this, whenever you drink it, in remembrance of me.\"",
    "For whenever you eat this bread and drink this cup, you proclaim the Lord's death until he comes.",
    "Therefore, whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of sinning against the body and blood of the Lord.",
    "A man ought to examine himself before he eats of the bread and drinks of the cup.",
    "For anyone who eats and drinks without recognizing the body of the Lord eats and drinks judgment on himself.",
    "That is why many among you are weak and sick, and a number of you have fallen asleep.",
    "But if we judged ourselves, we would not come under judgment.",
    "When we are judged by the Lord, we are being disciplined so that we will not be condemned with the world.",
    "So then, my brothers, when you come together to eat, wait for each other.",
    "If anyone is hungry, he should eat at home, so that when you meet together it may not result in judgment. And when I come I will give further directions."
  ],
  "Corinthians1-12": [
    "Now about spiritual gifts, brothers, I do not want you to be ignorant.",
    "You know that when you were pagans, somehow or other you were influenced and led astray to mute idols.",
    "Therefore I tell you that no one who is speaking by the Spirit of God says, \"Jesus be cursed,\" and no one can say, \"Jesus is Lord,\" except by the Holy Spirit.",
    "There are different kinds of gifts, but the same Spirit.",
    "There are different kinds of service, but the same Lord.",
    "There are different kinds of working, but the same God works all of them in all men.",
    "Now to each one the manifestation of the Spirit is given for the common good.",
    "To one there is given through the Spirit the message of wisdom, to another the message of knowledge by means of the same Spirit,",
    "to another faith by the same Spirit, to another gifts of healing by that one Spirit,",
    "to another miraculous powers, to another prophecy, to another distinguishing between spirits, to another speaking in different kinds of tongues, and to still another the interpretation of tongues.",
    "All these are the work of one and the same Spirit, and he gives them to each one, just as he determines.",
    "The body is a unit, though it is made up of many parts; and though all its parts are many, they form one body. So it is with Christ.",
    "For we were all baptized by one Spirit into one body--whether Jews or Greeks, slave or free--and we were all given the one Spirit to drink.",
    "Now the body is not made up of one part but of many.",
    "If the foot should say, \"Because I am not a hand, I do not belong to the body,\" it would not for that reason cease to be part of the body.",
    "And if the ear should say, \"Because I am not an eye, I do not belong to the body,\" it would not for that reason cease to be part of the body.",
    "If the whole body were an eye, where would the sense of hearing be? If the whole body were an ear, where would the sense of smell be?",
    "But in fact God has arranged the parts in the body, every one of them, just as he wanted them to be.",
    "If they were all one part, where would the body be?",
    "As it is, there are many parts, but one body.",
    "The eye cannot say to the hand, \"I don't need you!\" And the head cannot say to the feet, \"I don't need you!\"",
    "On the contrary, those parts of the body that seem to be weaker are indispensable,",
    "and the parts that we think are less honorable we treat with special honor. And the parts that are unpresentable are treated with special modesty,",
    "while our presentable parts need no special treatment. But God has combined the members of the body and has given greater honor to the parts that lacked it,",
    "so that there should be no division in the body, but that its parts should have equal concern for each other.",
    "If one part suffers, every part suffers with it; if one part is honored, every part rejoices with it.",
    "Now you are the body of Christ, and each one of you is a part of it.",
    "And in the church God has appointed first of all apostles, second prophets, third teachers, then workers of miracles, also those having gifts of healing, those able to help others, those with gifts of administration, and those speaking in different kinds of tongues.",
    "Are all apostles? Are all prophets? Are all teachers? Do all work miracles?",
    "Do all have gifts of healing? Do all speak in tongues? Do all interpret?",
    "But eagerly desire the greater gifts. And now I will show you the most excellent way."
  ],
  "Corinthians1-13": [
    "If I speak in the tongues of men and of angels, but have not love, I am only a resounding gong or a clanging cymbal.",
    "If I have the gift of prophecy and can fathom all mysteries and all knowledge, and if I have a faith that can move mountains, but have not love, I am nothing.",
    "If I give all I possess to the poor and surrender my body to the flames, but have not love, I gain nothing.",
    "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
    "It is not rude, it is not self-seeking, it is not easily angered, it keeps no record of wrongs.",
    "Love does not delight in evil but rejoices with the truth.",
    "It always protects, always trusts, always hopes, always perseveres.",
    "Love never fails. But where there are prophecies, they will cease; where there are tongues, they will be stilled; where there is knowledge, it will pass away.",
    "For we know in part and we prophesy in part,",
    "but when perfection comes, the imperfect disappears.",
    "When I was a child, I talked like a child, I thought like a child, I reasoned like a child. When I became a man, I put childish ways behind me.",
    "Now we see but a poor reflection as in a mirror; then we shall see face to face. Now I know in part; then I shall know fully, even as I am fully known.",
    "And now these three remain: faith, hope and love. But the greatest of these is love."
  ],
  "Corinthians1-14": [
    "Follow the way of love and eagerly desire spiritual gifts, especially the gift of prophecy.",
    "For anyone who speaks in a tongue does not speak to men but to God. Indeed, no one understands him; he utters mysteries with his spirit.",
    "But everyone who prophesies speaks to men for their strengthening, encouragement and comfort.",
    "He who speaks in a tongue edifies himself, but he who prophesies edifies the church.",
    "I would like every one of you to speak in tongues, but I would rather have you prophesy. He who prophesies is greater than one who speaks in tongues, unless he interprets, so that the church may be edified.",
    "Now, brothers, if I come to you and speak in tongues, what good will I be to you, unless I bring you some revelation or knowledge or prophecy or word of instruction?",
    "Even in the case of lifeless things that make sounds, such as the flute or harp, how will anyone know what tune is being played unless there is a distinction in the notes?",
    "Again, if the trumpet does not sound a clear call, who will get ready for battle?",
    "So it is with you. Unless you speak intelligible words with your tongue, how will anyone know what you are saying? You will just be speaking into the air.",
    "Undoubtedly there are all sorts of languages in the world, yet none of them is without meaning.",
    "If then I do not grasp the meaning of what someone is saying, I am a foreigner to the speaker, and he is a foreigner to me.",
    "So it is with you. Since you are eager to have spiritual gifts, try to excel in gifts that build up the church.",
    "For this reason anyone who speaks in a tongue should pray that he may interpret what he says.",
    "For if I pray in a tongue, my spirit prays, but my mind is unfruitful.",
    "So what shall I do? I will pray with my spirit, but I will also pray with my mind; I will sing with my spirit, but I will also sing with my mind.",
    "If you are praising God with your spirit, how can one who finds himself among those who do not understand say \"Amen\" to your thanksgiving, since he does not know what you are saying?",
    "You may be giving thanks well enough, but the other man is not edified.",
    "I thank God that I speak in tongues more than all of you.",
    "But in the church I would rather speak five intelligible words to instruct others than ten thousand words in a tongue.",
    "Brothers, stop thinking like children. In regard to evil be infants, but in your thinking be adults.",
    "In the Law it is written: \"Through men of strange tongues and through the lips of foreigners I will speak to this people, but even then they will not listen to me,\" says the Lord.",
    "Tongues, then, are a sign, not for believers but for unbelievers; prophecy, however, is for believers, not for unbelievers.",
    "So if the whole church comes together and everyone speaks in tongues, and some who do not understand or some unbelievers come in, will they not say that you are out of your mind?",
    "But if an unbeliever or someone who does not understand comes in while everybody is prophesying, he will be convinced by all that he is a sinner and will be judged by all,",
    "and the secrets of his heart will be laid bare. So he will fall down and worship God, exclaiming, \"God is really among you!\"",
    "What then shall we say, brothers? When you come together, everyone has a hymn, or a word of instruction, a revelation, a tongue or an interpretation. All of these must be done for the strengthening of the church.",
    "If anyone speaks in a tongue, two--or at the most three--should speak, one at a time, and someone must interpret.",
    "If there is no interpreter, the speaker should keep quiet in the church and speak to himself and God.",
    "Two or three prophets should speak, and the others should weigh carefully what is said.",
    "And if a revelation comes to someone who is sitting down, the first speaker should stop.",
    "For you can all prophesy in turn so that everyone may be instructed and encouraged.",
    "The spirits of prophets are subject to the control of prophets.",
    "For God is not a God of disorder but of peace. As in all the congregations of the saints,",
    "women should remain silent in the churches. They are not allowed to speak, but must be in submission, as the Law says.",
    "If they want to inquire about something, they should ask their own husbands at home; for it is disgraceful for a woman to speak in the church.",
    "Did the word of God originate with you? Or are you the only people it has reached?",
    "If anybody thinks he is a prophet or spiritually gifted, let him acknowledge that what I am writing to you is the Lord's command.",
    "If he ignores this, he himself will be ignored.",
    "Therefore, my brothers, be eager to prophesy, and do not forbid speaking in tongues.",
    "But everything should be done in a fitting and orderly way."
  ],
  "Corinthians1-15": [
    "Now, brothers, I want to remind you of the gospel I preached to you, which you received and on which you have taken your stand.",
    "By this gospel you are saved, if you hold firmly to the word I preached to you. Otherwise, you have believed in vain.",
    "For what I received I passed on to you as of first importance: that Christ died for our sins according to the Scriptures,",
    "that he was buried, that he was raised on the third day according to the Scriptures,",
    "and that he appeared to Peter, and then to the Twelve.",
    "After that, he appeared to more than five hundred of the brothers at the same time, most of whom are still living, though some have fallen asleep.",
    "Then he appeared to James, then to all the apostles,",
    "and last of all he appeared to me also, as to one abnormally born.",
    "For I am the least of the apostles and do not even deserve to be called an apostle, because I persecuted the church of God.",
    "But by the grace of God I am what I am, and his grace to me was not without effect. No, I worked harder than all of them--yet not I, but the grace of God that was with me.",
    "Whether, then, it was I or they, this is what we preach, and this is what you believed.",
    "But if it is preached that Christ has been raised from the dead, how can some of you say that there is no resurrection of the dead?",
    "If there is no resurrection of the dead, then not even Christ has been raised.",
    "And if Christ has not been raised, our preaching is useless and so is your faith.",
    "More than that, we are then found to be false witnesses about God, for we have testified about God that he raised Christ from the dead. But he did not raise him if in fact the dead are not raised.",
    "For if the dead are not raised, then Christ has not been raised either.",
    "And if Christ has not been raised, your faith is futile; you are still in your sins.",
    "Then those also who have fallen asleep in Christ are lost.",
    "If only for this life we have hope in Christ, we are to be pitied more than all men.",
    "But Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep.",
    "For since death came through a man, the resurrection of the dead comes also through a man.",
    "For as in Adam all die, so in Christ all will be made alive.",
    "But each in his own turn: Christ, the firstfruits; then, when he comes, those who belong to him.",
    "Then the end will come, when he hands over the kingdom to God the Father after he has destroyed all dominion, authority and power.",
    "For he must reign until he has put all his enemies under his feet.",
    "The last enemy to be destroyed is death.",
    "For he \"has put everything under his feet.\" Now when it says that \"everything\" has been put under him, it is clear that this does not include God himself, who put everything under Christ.",
    "When he has done this, then the Son himself will be made subject to him who put everything under him, so that God may be all in all.",
    "Now if there is no resurrection, what will those do who are baptized for the dead? If the dead are not raised at all, why are people baptized for them?",
    "And as for us, why do we endanger ourselves every hour?",
    "I die every day--I mean that, brothers--just as surely as I glory over you in Christ Jesus our Lord.",
    "If I fought wild beasts in Ephesus for merely human reasons, what have I gained? If the dead are not raised, \"Let us eat and drink, for tomorrow we die.\"",
    "Do not be misled: \"Bad company corrupts good character.\"",
    "Come back to your senses as you ought, and stop sinning; for there are some who are ignorant of God--I say this to your shame.",
    "But someone may ask, \"How are the dead raised? With what kind of body will they come?\"",
    "How foolish! What you sow does not come to life unless it dies.",
    "When you sow, you do not plant the body that will be, but just a seed, perhaps of wheat or of something else.",
    "But God gives it a body as he has determined, and to each kind of seed he gives its own body.",
    "All flesh is not the same: Men have one kind of flesh, animals have another, birds another and fish another.",
    "There are also heavenly bodies and there are earthly bodies; but the splendor of the heavenly bodies is one kind, and the splendor of the earthly bodies is another.",
    "The sun has one kind of splendor, the moon another and the stars another; and star differs from star in splendor.",
    "So will it be with the resurrection of the dead. The body that is sown is perishable, it is raised imperishable;",
    "it is sown in dishonor, it is raised in glory; it is sown in weakness, it is raised in power;",
    "it is sown a natural body, it is raised a spiritual body. If there is a natural body, there is also a spiritual body.",
    "So it is written: \"The first man Adam became a living being\"; the last Adam, a life-giving spirit.",
    "The spiritual did not come first, but the natural, and after that the spiritual.",
    "The first man was of the dust of the earth, the second man from heaven.",
    "As was the earthly man, so are those who are of the earth; and as is the man from heaven, so also are those who are of heaven.",
    "And just as we have borne the likeness of the earthly man, so shall we bear the likeness of the man from heaven.",
    "I declare to you, brothers, that flesh and blood cannot inherit the kingdom of God, nor does the perishable inherit the imperishable.",
    "Listen, I tell you a mystery: We will not all sleep, but we will all be changed--",
    "in a flash, in the twinkling of an eye, at the last trumpet. For the trumpet will sound, the dead will be raised imperishable, and we will be changed.",
    "For the perishable must clothe itself with the imperishable, and the mortal with immortality.",
    "When the perishable has been clothed with the imperishable, and the mortal with immortality, then the saying that is written will come true: \"Death has been swallowed up in victory.\"",
    "\"Where, O death, is your victory? Where, O death, is your sting?\"",
    "The sting of death is sin, and the power of sin is the law.",
    "But thanks be to God! He gives us the victory through our Lord Jesus Christ.",
    "Therefore, my dear brothers, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain."
  ],
  "Corinthians1-16": [
    "Now about the collection for God's people: Do what I told the Galatian churches to do.",
    "On the first day of every week, each one of you should set aside a sum of money in keeping with his income, saving it up, so that when I come no collections will have to be made.",
    "Then, when I arrive, I will give letters of introduction to the men you approve and send them with your gift to Jerusalem.",
    "If it seems advisable for me to go also, they will accompany me.",
    "After I go through Macedonia, I will come to you--for I will be going through Macedonia.",
    "Perhaps I will stay with you awhile, or even spend the winter, so that you can help me on my journey, wherever I go.",
    "I do not want to see you now and make only a passing visit; I hope to spend some time with you, if the Lord permits.",
    "But I will stay on at Ephesus until Pentecost,",
    "because a great door for effective work has opened to me, and there are many who oppose me.",
    "If Timothy comes, see to it that he has nothing to fear while he is with you, for he is carrying on the work of the Lord, just as I am.",
    "No one, then, should refuse to accept him. Send him on his way in peace so that he may return to me. I am expecting him along with the brothers.",
    "Now about our brother Apollos: I strongly urged him to go to you with the brothers. He was quite unwilling to go now, but he will go when he has the opportunity.",
    "Be on your guard; stand firm in the faith; be men of courage; be strong.",
    "Do everything in love.",
    "You know that the household of Stephanas were the first converts in Achaia, and they have devoted themselves to the service of the saints. I urge you, brothers,",
    "to submit to such as these and to everyone who joins in the work, and labors at it.",
    "I was glad when Stephanas, Fortunatus and Achaicus arrived, because they have supplied what was lacking from you.",
    "For they refreshed my spirit and yours also. Such men deserve recognition.",
    "The churches in the province of Asia send you greetings. Aquila and Priscilla greet you warmly in the Lord, and so does the church that meets at their house.",
    "All the brothers here send you greetings. Greet one another with a holy kiss.",
    "I, Paul, write this greeting in my own hand.",
    "If anyone does not love the Lord--a curse be on him. Come, O Lord!",
    "The grace of the Lord Jesus be with you.",
    "My love to all of you in Christ Jesus. Amen."
  ]
}