{
  "Ezra-1": [
    "In the first year of Cyrus king of Persia, in order to fulfill the word of the LORD spoken by Jeremiah, the LORD moved the heart of Cyrus king of Persia to make a proclamation throughout his realm and to put it in writing:",
    "\"This is what Cyrus king of Persia says: \"'The LORD, the God of heaven, has given me all the kingdoms of the earth and he has appointed me to build a temple for him at Jerusalem in Judah.",
    "Anyone of his people among you--may his God be with him, and let him go up to Jerusalem in Judah and build the temple of the LORD, the God of Israel, the God who is in Jerusalem.",
    "And the people of any place where survivors may now be living are to provide him with silver and gold, with goods and livestock, and with freewill offerings for the temple of God in Jerusalem.'\"",
    "Then the family heads of Judah and Benjamin, and the priests and Levites--everyone whose heart God had moved--prepared to go up and build the house of the LORD in Jerusalem.",
    "All their neighbors assisted them with articles of silver and gold, with goods and livestock, and with valuable gifts, in addition to all the freewill offerings.",
    "Moreover, King Cyrus brought out the articles belonging to the temple of the LORD, which Nebuchadnezzar had carried away from Jerusalem and had placed in the temple of his god.",
    "Cyrus king of Persia had them brought by Mithredath the treasurer, who counted them out to Sheshbazzar the prince of Judah.",
    "This was the inventory: gold dishes 30 silver dishes 1,000 silver pans 29",
    "gold bowls 30 matching silver bowls 410 other articles 1,000",
    "In all, there were 5,400 articles of gold and of silver. Sheshbazzar brought all these along when the exiles came up from Babylon to Jerusalem."
  ],
  "Ezra-2": [
    "Now these are the people of the province who came up from the captivity of the exiles, whom Nebuchadnezzar king of Babylon had taken captive to Babylon (they returned to Jerusalem and Judah, each to his own town,",
    "in company with Zerubbabel, Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mispar, Bigvai, Rehum and Baanah): The list of the men of the people of Israel:",
    "the descendants of Parosh 2,172",
    "of Shephatiah 372",
    "of Arah 775",
    "of Pahath-Moab (through the line of Jeshua and Joab) 2,812",
    "of Elam 1,254",
    "of Zattu 945",
    "of Zaccai 760",
    "of Bani 642",
    "of Bebai 623",
    "of Azgad 1,222",
    "of Adonikam 666",
    "of Bigvai 2,056",
    "of Adin 454",
    "of Ater (through Hezekiah) 98",
    "of Bezai 323",
    "of Jorah 112",
    "of Hashum 223",
    "of Gibbar 95",
    "the men of Bethlehem 123",
    "of Netophah 56",
    "of Anathoth 128",
    "of Azmaveth 42",
    "of Kiriath Jearim, Kephirah and Beeroth 743",
    "of Ramah and Geba 621",
    "of Micmash 122",
    "of Bethel and Ai 223",
    "of Nebo 52",
    "of Magbish 156",
    "of the other Elam 1,254",
    "of Harim 320",
    "of Lod, Hadid and Ono 725",
    "of Jericho 345",
    "of Senaah 3,630",
    "The priests: the descendants of Jedaiah (through the family of Jeshua) 973",
    "of Immer 1,052",
    "of Pashhur 1,247",
    "of Harim 1,017",
    "The Levites: the descendants of Jeshua and Kadmiel (through the line of Hodaviah) 74",
    "The singers: the descendants of Asaph 128",
    "The gatekeepers of the temple: the descendants of Shallum, Ater, Talmon, Akkub, Hatita and Shobai 139",
    "The temple servants: the descendants of Ziha, Hasupha, Tabbaoth,",
    "Keros, Siaha, Padon,",
    "Lebanah, Hagabah, Akkub,",
    "Hagab, Shalmai, Hanan,",
    "Giddel, Gahar, Reaiah,",
    "Rezin, Nekoda, Gazzam,",
    "Uzza, Paseah, Besai,",
    "Asnah, Meunim, Nephussim,",
    "Bakbuk, Hakupha, Harhur,",
    "Bazluth, Mehida, Harsha,",
    "Barkos, Sisera, Temah,",
    "Neziah and Hatipha",
    "The descendants of the servants of Solomon: the descendants of Sotai, Hassophereth, Peruda,",
    "Jaala, Darkon, Giddel,",
    "Shephatiah, Hattil, Pokereth-Hazzebaim and Ami",
    "The temple servants and the descendants of the servants of Solomon 392",
    "The following came up from the towns of Tel Melah, Tel Harsha, Kerub, Addon and Immer, but they could not show that their families were descended from Israel:",
    "The descendants of Delaiah, Tobiah and Nekoda 652",
    "And from among the priests: The descendants of Hobaiah, Hakkoz and Barzillai (a man who had married a daughter of Barzillai the Gileadite and was called by that name).",
    "These searched for their family records, but they could not find them and so were excluded from the priesthood as unclean.",
    "The governor ordered them not to eat any of the most sacred food until there was a priest ministering with the Urim and Thummim.",
    "The whole company numbered 42,360,",
    "besides their 7,337 menservants and maidservants; and they also had 200 men and women singers.",
    "They had 736 horses, 245 mules,",
    "435 camels and 6,720 donkeys.",
    "When they arrived at the house of the LORD in Jerusalem, some of the heads of the families gave freewill offerings toward the rebuilding of the house of God on its site.",
    "According to their ability they gave to the treasury for this work 61,000 drachmas of gold, 5,000 minas of silver and 100 priestly garments.",
    "The priests, the Levites, the singers, the gatekeepers and the temple servants settled in their own towns, along with some of the other people, and the rest of the Israelites settled in their towns."
  ],
  "Ezra-3": [
    "When the seventh month came and the Israelites had settled in their towns, the people assembled as one man in Jerusalem.",
    "Then Jeshua son of Jozadak and his fellow priests and Zerubbabel son of Shealtiel and his associates began to build the altar of the God of Israel to sacrifice burnt offerings on it, in accordance with what is written in the Law of Moses the man of God.",
    "Despite their fear of the peoples around them, they built the altar on its foundation and sacrificed burnt offerings on it to the LORD, both the morning and evening sacrifices.",
    "Then in accordance with what is written, they celebrated the Feast of Tabernacles with the required number of burnt offerings prescribed for each day.",
    "After that, they presented the regular burnt offerings, the New Moon sacrifices and the sacrifices for all the appointed sacred feasts of the LORD, as well as those brought as freewill offerings to the LORD.",
    "On the first day of the seventh month they began to offer burnt offerings to the LORD, though the foundation of the LORD'S temple had not yet been laid.",
    "Then they gave money to the masons and carpenters, and gave food and drink and oil to the people of Sidon and Tyre, so that they would bring cedar logs by sea from Lebanon to Joppa, as authorized by Cyrus king of Persia.",
    "In the second month of the second year after their arrival at the house of God in Jerusalem, Zerubbabel son of Shealtiel, Jeshua son of Jozadak and the rest of their brothers (the priests and the Levites and all who had returned from the captivity to Jerusalem) began the work, appointing Levites twenty years of age and older to supervise the building of the house of the LORD.",
    "Jeshua and his sons and brothers and Kadmiel and his sons (descendants of Hodaviah) and the sons of Henadad and their sons and brothers--all Levites--joined together in supervising those working on the house of God.",
    "When the builders laid the foundation of the temple of the LORD, the priests in their vestments and with trumpets, and the Levites (the sons of Asaph) with cymbals, took their places to praise the LORD, as prescribed by David king of Israel.",
    "With praise and thanksgiving they sang to the LORD: \"He is good; his love to Israel endures forever.\" And all the people gave a great shout of praise to the LORD, because the foundation of the house of the LORD was laid.",
    "But many of the older priests and Levites and family heads, who had seen the former temple, wept aloud when they saw the foundation of this temple being laid, while many others shouted for joy.",
    "No one could distinguish the sound of the shouts of joy from the sound of weeping, because the people made so much noise. And the sound was heard far away."
  ],
  "Ezra-4": [
    "When the enemies of Judah and Benjamin heard that the exiles were building a temple for the LORD, the God of Israel,",
    "they came to Zerubbabel and to the heads of the families and said, \"Let us help you build because, like you, we seek your God and have been sacrificing to him since the time of Esarhaddon king of Assyria, who brought us here.\"",
    "But Zerubbabel, Jeshua and the rest of the heads of the families of Israel answered, \"You have no part with us in building a temple to our God. We alone will build it for the LORD, the God of Israel, as King Cyrus, the king of Persia, commanded us.\"",
    "Then the peoples around them set out to discourage the people of Judah and make them afraid to go on building.",
    "They hired counselors to work against them and frustrate their plans during the entire reign of Cyrus king of Persia and down to the reign of Darius king of Persia.",
    "At the beginning of the reign of Xerxes, they lodged an accusation against the people of Judah and Jerusalem.",
    "And in the days of Artaxerxes king of Persia, Bishlam, Mithredath, Tabeel and the rest of his associates wrote a letter to Artaxerxes. The letter was written in Aramaic script and in the Aramaic language.",
    "Rehum the commanding officer and Shimshai the secretary wrote a letter against Jerusalem to Artaxerxes the king as follows:",
    "Rehum the commanding officer and Shimshai the secretary, together with the rest of their associates--the judges and officials over the men from Tripolis, Persia, Erech and Babylon, the Elamites of Susa,",
    "and the other people whom the great and honorable Ashurbanipal deported and settled in the city of Samaria and elsewhere in Trans-Euphrates.",
    "(This is a copy of the letter they sent him.) To King Artaxerxes, From your servants, the men of Trans-Euphrates:",
    "The king should know that the Jews who came up to us from you have gone to Jerusalem and are rebuilding that rebellious and wicked city. They are restoring the walls and repairing the foundations.",
    "Furthermore, the king should know that if this city is built and its walls are restored, no more taxes, tribute or duty will be paid, and the royal revenues will suffer.",
    "Now since we are under obligation to the palace and it is not proper for us to see the king dishonored, we are sending this message to inform the king,",
    "so that a search may be made in the archives of your predecessors. In these records you will find that this city is a rebellious city, troublesome to kings and provinces, a place of rebellion from ancient times. That is why this city was destroyed.",
    "We inform the king that if this city is built and its walls are restored, you will be left with nothing in Trans-Euphrates.",
    "The king sent this reply: To Rehum the commanding officer, Shimshai the secretary and the rest of their associates living in Samaria and elsewhere in Trans-Euphrates: Greetings.",
    "The letter you sent us has been read and translated in my presence.",
    "I issued an order and a search was made, and it was found that this city has a long history of revolt against kings and has been a place of rebellion and sedition.",
    "Jerusalem has had powerful kings ruling over the whole of Trans-Euphrates, and taxes, tribute and duty were paid to them.",
    "Now issue an order to these men to stop work, so that this city will not be rebuilt until I so order.",
    "Be careful not to neglect this matter. Why let this threat grow, to the detriment of the royal interests?",
    "As soon as the copy of the letter of King Artaxerxes was read to Rehum and Shimshai the secretary and their associates, they went immediately to the Jews in Jerusalem and compelled them by force to stop.",
    "Thus the work on the house of God in Jerusalem came to a standstill until the second year of the reign of Darius king of Persia."
  ],
  "Ezra-5": [
    "Now Haggai the prophet and Zechariah the prophet, a descendant of Iddo, prophesied to the Jews in Judah and Jerusalem in the name of the God of Israel, who was over them.",
    "Then Zerubbabel son of Shealtiel and Jeshua son of Jozadak set to work to rebuild the house of God in Jerusalem. And the prophets of God were with them, helping them.",
    "At that time Tattenai, governor of Trans-Euphrates, and Shethar-Bozenai and their associates went to them and asked, \"Who authorized you to rebuild this temple and restore this structure?\"",
    "They also asked, \"What are the names of the men constructing this building?\"",
    "But the eye of their God was watching over the elders of the Jews, and they were not stopped until a report could go to Darius and his written reply be received.",
    "This is a copy of the letter that Tattenai, governor of Trans-Euphrates, and Shethar-Bozenai and their associates, the officials of Trans-Euphrates, sent to King Darius.",
    "The report they sent him read as follows: To King Darius: Cordial greetings.",
    "The king should know that we went to the district of Judah, to the temple of the great God. The people are building it with large stones and placing the timbers in the walls. The work is being carried on with diligence and is making rapid progress under their direction.",
    "We questioned the elders and asked them, \"Who authorized you to rebuild this temple and restore this structure?\"",
    "We also asked them their names, so that we could write down the names of their leaders for your information.",
    "This is the answer they gave us: \"We are the servants of the God of heaven and earth, and we are rebuilding the temple that was built many years ago, one that a great king of Israel built and finished.",
    "But because our fathers angered the God of heaven, he handed them over to Nebuchadnezzar the Chaldean, king of Babylon, who destroyed this temple and deported the people to Babylon.",
    "\"However, in the first year of Cyrus king of Babylon, King Cyrus issued a decree to rebuild this house of God.",
    "He even removed from the temple of Babylon the gold and silver articles of the house of God, which Nebuchadnezzar had taken from the temple in Jerusalem and brought to the temple in Babylon. \"Then King Cyrus gave them to a man named Sheshbazzar, whom he had appointed governor,",
    "and he told him, 'Take these articles and go and deposit them in the temple in Jerusalem. And rebuild the house of God on its site.'",
    "So this Sheshbazzar came and laid the foundations of the house of God in Jerusalem. From that day to the present it has been under construction but is not yet finished.\"",
    "Now if it pleases the king, let a search be made in the royal archives of Babylon to see if King Cyrus did in fact issue a decree to rebuild this house of God in Jerusalem. Then let the king send us his decision in this matter."
  ],
  "Ezra-6": [
    "King Darius then issued an order, and they searched in the archives stored in the treasury at Babylon.",
    "A scroll was found in the citadel of Ecbatana in the province of Media, and this was written on it: Memorandum:",
    "In the first year of King Cyrus, the king issued a decree concerning the temple of God in Jerusalem: Let the temple be rebuilt as a place to present sacrifices, and let its foundations be laid. It is to be ninety feet high and ninety feet wide,",
    "with three courses of large stones and one of timbers. The costs are to be paid by the royal treasury.",
    "Also, the gold and silver articles of the house of God, which Nebuchadnezzar took from the temple in Jerusalem and brought to Babylon, are to be returned to their places in the temple in Jerusalem; they are to be deposited in the house of God.",
    "Now then, Tattenai, governor of Trans-Euphrates, and Shethar-Bozenai and you, their fellow officials of that province, stay away from there.",
    "Do not interfere with the work on this temple of God. Let the governor of the Jews and the Jewish elders rebuild this house of God on its site.",
    "Moreover, I hereby decree what you are to do for these elders of the Jews in the construction of this house of God: The expenses of these men are to be fully paid out of the royal treasury, from the revenues of Trans-Euphrates, so that the work will not stop.",
    "Whatever is needed--young bulls, rams, male lambs for burnt offerings to the God of heaven, and wheat, salt, wine and oil, as requested by the priests in Jerusalem--must be given them daily without fail,",
    "so that they may offer sacrifices pleasing to the God of heaven and pray for the well-being of the king and his sons.",
    "Furthermore, I decree that if anyone changes this edict, a beam is to be pulled from his house and he is to be lifted up and impaled on it. And for this crime his house is to be made a pile of rubble.",
    "May God, who has caused his Name to dwell there, overthrow any king or people who lifts a hand to change this decree or to destroy this temple in Jerusalem. I Darius have decreed it. Let it be carried out with diligence.",
    "Then, because of the decree King Darius had sent, Tattenai, governor of Trans-Euphrates, and Shethar-Bozenai and their associates carried it out with diligence.",
    "So the elders of the Jews continued to build and prosper under the preaching of Haggai the prophet and Zechariah, a descendant of Iddo. They finished building the temple according to the command of the God of Israel and the decrees of Cyrus, Darius and Artaxerxes, kings of Persia.",
    "The temple was completed on the third day of the month Adar, in the sixth year of the reign of King Darius.",
    "Then the people of Israel--the priests, the Levites and the rest of the exiles--celebrated the dedication of the house of God with joy.",
    "For the dedication of this house of God they offered a hundred bulls, two hundred rams, four hundred male lambs and, as a sin offering for all Israel, twelve male goats, one for each of the tribes of Israel.",
    "And they installed the priests in their divisions and the Levites in their groups for the service of God at Jerusalem, according to what is written in the Book of Moses.",
    "On the fourteenth day of the first month, the exiles celebrated the Passover.",
    "The priests and Levites had purified themselves and were all ceremonially clean. The Levites slaughtered the Passover lamb for all the exiles, for their brothers the priests and for themselves.",
    "So the Israelites who had returned from the exile ate it, together with all who had separated themselves from the unclean practices of their Gentile neighbors in order to seek the LORD, the God of Israel.",
    "For seven days they celebrated with joy the Feast of Unleavened Bread, because the LORD had filled them with joy by changing the attitude of the king of Assyria, so that he assisted them in the work on the house of God, the God of Israel."
  ],
  "Ezra-7": [
    "After these things, during the reign of Artaxerxes king of Persia, Ezra son of Seraiah, the son of Azariah, the son of Hilkiah,",
    "the son of Shallum, the son of Zadok, the son of Ahitub,",
    "the son of Amariah, the son of Azariah, the son of Meraioth,",
    "the son of Zerahiah, the son of Uzzi, the son of Bukki,",
    "the son of Abishua, the son of Phinehas, the son of Eleazar, the son of Aaron the chief priest--",
    "this Ezra came up from Babylon. He was a teacher well versed in the Law of Moses, which the LORD, the God of Israel, had given. The king had granted him everything he asked, for the hand of the LORD his God was on him.",
    "Some of the Israelites, including priests, Levites, singers, gatekeepers and temple servants, also came up to Jerusalem in the seventh year of King Artaxerxes.",
    "Ezra arrived in Jerusalem in the fifth month of the seventh year of the king.",
    "He had begun his journey from Babylon on the first day of the first month, and he arrived in Jerusalem on the first day of the fifth month, for the gracious hand of his God was on him.",
    "For Ezra had devoted himself to the study and observance of the Law of the LORD, and to teaching its decrees and laws in Israel.",
    "This is a copy of the letter King Artaxerxes had given to Ezra the priest and teacher, a man learned in matters concerning the commands and decrees of the LORD for Israel:",
    "Artaxerxes, king of kings, To Ezra the priest, a teacher of the Law of the God of heaven: Greetings.",
    "Now I decree that any of the Israelites in my kingdom, including priests and Levites, who wish to go to Jerusalem with you, may go.",
    "You are sent by the king and his seven advisers to inquire about Judah and Jerusalem with regard to the Law of your God, which is in your hand.",
    "Moreover, you are to take with you the silver and gold that the king and his advisers have freely given to the God of Israel, whose dwelling is in Jerusalem,",
    "together with all the silver and gold you may obtain from the province of Babylon, as well as the freewill offerings of the people and priests for the temple of their God in Jerusalem.",
    "With this money be sure to buy bulls, rams and male lambs, together with their grain offerings and drink offerings, and sacrifice them on the altar of the temple of your God in Jerusalem.",
    "You and your brother Jews may then do whatever seems best with the rest of the silver and gold, in accordance with the will of your God.",
    "Deliver to the God of Jerusalem all the articles entrusted to you for worship in the temple of your God.",
    "And anything else needed for the temple of your God that you may have occasion to supply, you may provide from the royal treasury.",
    "Now I, King Artaxerxes, order all the treasurers of Trans-Euphrates to provide with diligence whatever Ezra the priest, a teacher of the Law of the God of heaven, may ask of you--",
    "up to a hundred talents of silver, a hundred cors of wheat, a hundred baths of wine, a hundred baths of olive oil, and salt without limit.",
    "Whatever the God of heaven has prescribed, let it be done with diligence for the temple of the God of heaven. Why should there be wrath against the realm of the king and of his sons?",
    "You are also to know that you have no authority to impose taxes, tribute or duty on any of the priests, Levites, singers, gatekeepers, temple servants or other workers at this house of God.",
    "And you, Ezra, in accordance with the wisdom of your God, which you possess, appoint magistrates and judges to administer justice to all the people of Trans-Euphrates--all who know the laws of your God. And you are to teach any who do not know them.",
    "Whoever does not obey the law of your God and the law of the king must surely be punished by death, banishment, confiscation of property, or imprisonment.",
    "Praise be to the LORD, the God of our fathers, who has put it into the king's heart to bring honor to the house of the LORD in Jerusalem in this way",
    "and who has extended his good favor to me before the king and his advisers and all the king's powerful officials. Because the hand of the LORD my God was on me, I took courage and gathered leading men from Israel to go up with me."
  ],
  "Ezra-8": [
    "These are the family heads and those registered with them who came up with me from Babylon during the reign of King Artaxerxes:",
    "of the descendants of Phinehas, Gershom; of the descendants of Ithamar, Daniel; of the descendants of David, Hattush",
    "of the descendants of Shecaniah; of the descendants of Parosh, Zechariah, and with him were registered 150 men;",
    "of the descendants of Pahath-Moab, Eliehoenai son of Zerahiah, and with him 200 men;",
    "of the descendants of Zattu, Shecaniah son of Jahaziel, and with him 300 men;",
    "of the descendants of Adin, Ebed son of Jonathan, and with him 50 men;",
    "of the descendants of Elam, Jeshaiah son of Athaliah, and with him 70 men;",
    "of the descendants of Shephatiah, Zebadiah son of Michael, and with him 80 men;",
    "of the descendants of Joab, Obadiah son of Jehiel, and with him 218 men;",
    "of the descendants of Bani, Shelomith son of Josiphiah, and with him 160 men;",
    "of the descendants of Bebai, Zechariah son of Bebai, and with him 28 men;",
    "of the descendants of Azgad, Johanan son of Hakkatan, and with him 110 men;",
    "of the descendants of Adonikam, the last ones, whose names were Eliphelet, Jeuel and Shemaiah, and with them 60 men;",
    "of the descendants of Bigvai, Uthai and Zaccur, and with them 70 men.",
    "I assembled them at the canal that flows toward Ahava, and we camped there three days. When I checked among the people and the priests, I found no Levites there.",
    "So I summoned Eliezer, Ariel, Shemaiah, Elnathan, Jarib, Elnathan, Nathan, Zechariah and Meshullam, who were leaders, and Joiarib and Elnathan, who were men of learning,",
    "and I sent them to Iddo, the leader in Casiphia. I told them what to say to Iddo and his kinsmen, the temple servants in Casiphia, so that they might bring attendants to us for the house of our God.",
    "Because the gracious hand of our God was on us, they brought us Sherebiah, a capable man, from the descendants of Mahli son of Levi, the son of Israel, and Sherebiah's sons and brothers, 18 men;",
    "and Hashabiah, together with Jeshaiah from the descendants of Merari, and his brothers and nephews, 20 men.",
    "They also brought 220 of the temple servants--a body that David and the officials had established to assist the Levites. All were registered by name.",
    "There, by the Ahava Canal, I proclaimed a fast, so that we might humble ourselves before our God and ask him for a safe journey for us and our children, with all our possessions.",
    "I was ashamed to ask the king for soldiers and horsemen to protect us from enemies on the road, because we had told the king, \"The gracious hand of our God is on everyone who looks to him, but his great anger is against all who forsake him.\"",
    "So we fasted and petitioned our God about this, and he answered our prayer.",
    "Then I set apart twelve of the leading priests, together with Sherebiah, Hashabiah and ten of their brothers,",
    "and I weighed out to them the offering of silver and gold and the articles that the king, his advisers, his officials and all Israel present there had donated for the house of our God.",
    "I weighed out to them 650 talents of silver, silver articles weighing 100 talents, 100 talents of gold,",
    "20 bowls of gold valued at 1,000 darics, and two fine articles of polished bronze, as precious as gold.",
    "I said to them, \"You as well as these articles are consecrated to the LORD. The silver and gold are a freewill offering to the LORD, the God of your fathers.",
    "Guard them carefully until you weigh them out in the chambers of the house of the LORD in Jerusalem before the leading priests and the Levites and the family heads of Israel.\"",
    "Then the priests and Levites received the silver and gold and sacred articles that had been weighed out to be taken to the house of our God in Jerusalem.",
    "On the twelfth day of the first month we set out from the Ahava Canal to go to Jerusalem. The hand of our God was on us, and he protected us from enemies and bandits along the way.",
    "So we arrived in Jerusalem, where we rested three days.",
    "On the fourth day, in the house of our God, we weighed out the silver and gold and the sacred articles into the hands of Meremoth son of Uriah, the priest. Eleazar son of Phinehas was with him, and so were the Levites Jozabad son of Jeshua and Noadiah son of Binnui.",
    "Everything was accounted for by number and weight, and the entire weight was recorded at that time.",
    "Then the exiles who had returned from captivity sacrificed burnt offerings to the God of Israel: twelve bulls for all Israel, ninety-six rams, seventy-seven male lambs and, as a sin offering, twelve male goats. All this was a burnt offering to the LORD.",
    "They also delivered the king's orders to the royal satraps and to the governors of Trans-Euphrates, who then gave assistance to the people and to the house of God."
  ],
  "Ezra-9": [
    "After these things had been done, the leaders came to me and said, \"The people of Israel, including the priests and the Levites, have not kept themselves separate from the neighboring peoples with their detestable practices, like those of the Canaanites, Hittites, Perizzites, Jebusites, Ammonites, Moabites, Egyptians and Amorites.",
    "They have taken some of their daughters as wives for themselves and their sons, and have mingled the holy race with the peoples around them. And the leaders and officials have led the way in this unfaithfulness.\"",
    "When I heard this, I tore my tunic and cloak, pulled hair from my head and beard and sat down appalled.",
    "Then everyone who trembled at the words of the God of Israel gathered around me because of this unfaithfulness of the exiles. And I sat there appalled until the evening sacrifice.",
    "Then, at the evening sacrifice, I rose from my self-abasement, with my tunic and cloak torn, and fell on my knees with my hands spread out to the LORD my God",
    "and prayed: \"O my God, I am too ashamed and disgraced to lift up my face to you, my God, because our sins are higher than our heads and our guilt has reached to the heavens.",
    "From the days of our forefathers until now, our guilt has been great. Because of our sins, we and our kings and our priests have been subjected to the sword and captivity, to pillage and humiliation at the hand of foreign kings, as it is today.",
    "\"But now, for a brief moment, the LORD our God has been gracious in leaving us a remnant and giving us a firm place in his sanctuary, and so our God gives light to our eyes and a little relief in our bondage.",
    "Though we are slaves, our God has not deserted us in our bondage. He has shown us kindness in the sight of the kings of Persia: He has granted us new life to rebuild the house of our God and repair its ruins, and he has given us a wall of protection in Judah and Jerusalem.",
    "\"But now, O our God, what can we say after this? For we have disregarded the commands",
    "you gave through your servants the prophets when you said: 'The land you are entering to possess is a land polluted by the corruption of its peoples. By their detestable practices they have filled it with their impurity from one end to the other.",
    "Therefore, do not give your daughters in marriage to their sons or take their daughters for your sons. Do not seek a treaty of friendship with them at any time, that you may be strong and eat the good things of the land and leave it to your children as an everlasting inheritance.'",
    "\"What has happened to us is a result of our evil deeds and our great guilt, and yet, our God, you have punished us less than our sins have deserved and have given us a remnant like this.",
    "Shall we again break your commands and intermarry with the peoples who commit such detestable practices? Would you not be angry enough with us to destroy us, leaving us no remnant or survivor?",
    "O LORD, God of Israel, you are righteous! We are left this day as a remnant. Here we are before you in our guilt, though because of it not one of us can stand in your presence.\""
  ],
  "Ezra-10": [
    "While Ezra was praying and confessing, weeping and throwing himself down before the house of God, a large crowd of Israelites--men, women and children--gathered around him. They too wept bitterly.",
    "Then Shecaniah son of Jehiel, one of the descendants of Elam, said to Ezra, \"We have been unfaithful to our God by marrying foreign women from the peoples around us. But in spite of this, there is still hope for Israel.",
    "Now let us make a covenant before our God to send away all these women and their children, in accordance with the counsel of my lord and of those who fear the commands of our God. Let it be done according to the Law.",
    "Rise up; this matter is in your hands. We will support you, so take courage and do it.\"",
    "So Ezra rose up and put the leading priests and Levites and all Israel under oath to do what had been suggested. And they took the oath.",
    "Then Ezra withdrew from before the house of God and went to the room of Jehohanan son of Eliashib. While he was there, he ate no food and drank no water, because he continued to mourn over the unfaithfulness of the exiles.",
    "A proclamation was then issued throughout Judah and Jerusalem for all the exiles to assemble in Jerusalem.",
    "Anyone who failed to appear within three days would forfeit all his property, in accordance with the decision of the officials and elders, and would himself be expelled from the assembly of the exiles.",
    "Within the three days, all the men of Judah and Benjamin had gathered in Jerusalem. And on the twentieth day of the ninth month, all the people were sitting in the square before the house of God, greatly distressed by the occasion and because of the rain.",
    "Then Ezra the priest stood up and said to them, \"You have been unfaithful; you have married foreign women, adding to Israel's guilt.",
    "Now make confession to the LORD, the God of your fathers, and do his will. Separate yourselves from the peoples around you and from your foreign wives.\"",
    "The whole assembly responded with a loud voice: \"You are right! We must do as you say.",
    "But there are many people here and it is the rainy season; so we cannot stand outside. Besides, this matter cannot be taken care of in a day or two, because we have sinned greatly in this thing.",
    "Let our officials act for the whole assembly. Then let everyone in our towns who has married a foreign woman come at a set time, along with the elders and judges of each town, until the fierce anger of our God in this matter is turned away from us.\"",
    "Only Jonathan son of Asahel and Jahzeiah son of Tikvah, supported by Meshullam and Shabbethai the Levite, opposed this.",
    "So the exiles did as was proposed. Ezra the priest selected men who were family heads, one from each family division, and all of them designated by name. On the first day of the tenth month they sat down to investigate the cases,",
    "and by the first day of the first month they finished dealing with all the men who had married foreign women.",
    "Among the descendants of the priests, the following had married foreign women: From the descendants of Jeshua son of Jozadak, and his brothers: Maaseiah, Eliezer, Jarib and Gedaliah.",
    "(They all gave their hands in pledge to put away their wives, and for their guilt they each presented a ram from the flock as a guilt offering.)",
    "From the descendants of Immer: Hanani and Zebadiah.",
    "From the descendants of Harim: Maaseiah, Elijah, Shemaiah, Jehiel and Uzziah.",
    "From the descendants of Pashhur: Elioenai, Maaseiah, Ishmael, Nethanel, Jozabad and Elasah.",
    "Among the Levites: Jozabad, Shimei, Kelaiah (that is, Kelita), Pethahiah, Judah and Eliezer.",
    "From the singers: Eliashib. From the gatekeepers: Shallum, Telem and Uri.",
    "And among the other Israelites: From the descendants of Parosh: Ramiah, Izziah, Malkijah, Mijamin, Eleazar, Malkijah and Benaiah.",
    "From the descendants of Elam: Mattaniah, Zechariah, Jehiel, Abdi, Jeremoth and Elijah.",
    "From the descendants of Zattu: Elioenai, Eliashib, Mattaniah, Jeremoth, Zabad and Aziza.",
    "From the descendants of Bebai: Jehohanan, Hananiah, Zabbai and Athlai.",
    "From the descendants of Bani: Meshullam, Malluch, Adaiah, Jashub, Sheal and Jeremoth.",
    "From the descendants of Pahath-Moab: Adna, Kelal, Benaiah, Maaseiah, Mattaniah, Bezalel, Binnui and Manasseh.",
    "From the descendants of Harim: Eliezer, Ishijah, Malkijah, Shemaiah, Shimeon,",
    "Benjamin, Malluch and Shemariah.",
    "From the descendants of Hashum: Mattenai, Mattattah, Zabad, Eliphelet, Jeremai, Manasseh and Shimei.",
    "From the descendants of Bani: Maadai, Amram, Uel,",
    "Benaiah, Bedeiah, Keluhi,",
    "Vaniah, Meremoth, Eliashib,",
    "Mattaniah, Mattenai and Jaasu.",
    "From the descendants of Binnui: Shimei,",
    "Shelemiah, Nathan, Adaiah,",
    "Macnadebai, Shashai, Sharai,",
    "Azarel, Shelemiah, Shemariah,",
    "Shallum, Amariah and Joseph.",
    "From the descendants of Nebo: Jeiel, Mattithiah, Zabad, Zebina, Jaddai, Joel and Benaiah.",
    "All these had married foreign women, and some of them had children by these wives."
  ]
}