{
  "Galatians-1": [
    "Paul, an apostle--sent not from men nor by man, but by Jesus Christ and God the Father, who raised him from the dead--",
    "and all the brothers with me, To the churches in Galatia:",
    "Grace and peace to you from God our Father and the Lord Jesus Christ,",
    "who gave himself for our sins to rescue us from the present evil age, according to the will of our God and Father,",
    "to whom be glory for ever and ever. Amen.",
    "I am astonished that you are so quickly deserting the one who called you by the grace of Christ and are turning to a different gospel--",
    "which is really no gospel at all. Evidently some people are throwing you into confusion and are trying to pervert the gospel of Christ.",
    "But even if we or an angel from heaven should preach a gospel other than the one we preached to you, let him be eternally condemned!",
    "As we have already said, so now I say again: If anybody is preaching to you a gospel other than what you accepted, let him be eternally condemned!",
    "Am I now trying to win the approval of men, or of God? Or am I trying to please men? If I were still trying to please men, I would not be a servant of Christ.",
    "I want you to know, brothers, that the gospel I preached is not something that man made up.",
    "I did not receive it from any man, nor was I taught it; rather, I received it by revelation from Jesus Christ.",
    "For you have heard of my previous way of life in Judaism, how intensely I persecuted the church of God and tried to destroy it.",
    "I was advancing in Judaism beyond many Jews of my own age and was extremely zealous for the traditions of my fathers.",
    "But when God, who set me apart from birth and called me by his grace, was pleased",
    "to reveal his Son in me so that I might preach him among the Gentiles, I did not consult any man,",
    "nor did I go up to Jerusalem to see those who were apostles before I was, but I went immediately into Arabia and later returned to Damascus.",
    "Then after three years, I went up to Jerusalem to get acquainted with Peter and stayed with him fifteen days.",
    "I saw none of the other apostles--only James, the Lord's brother.",
    "I assure you before God that what I am writing you is no lie.",
    "Later I went to Syria and Cilicia.",
    "I was personally unknown to the churches of Judea that are in Christ.",
    "They only heard the report: \"The man who formerly persecuted us is now preaching the faith he once tried to destroy.\"",
    "And they praised God because of me."
  ],
  "Galatians-2": [
    "Fourteen years later I went up again to Jerusalem, this time with Barnabas. I took Titus along also.",
    "I went in response to a revelation and set before them the gospel that I preach among the Gentiles. But I did this privately to those who seemed to be leaders, for fear that I was running or had run my race in vain.",
    "Yet not even Titus, who was with me, was compelled to be circumcised, even though he was a Greek.",
    "This matter arose because some false brothers had infiltrated our ranks to spy on the freedom we have in Christ Jesus and to make us slaves.",
    "We did not give in to them for a moment, so that the truth of the gospel might remain with you.",
    "As for those who seemed to be important--whatever they were makes no difference to me; God does not judge by external appearance--those men added nothing to my message.",
    "On the contrary, they saw that I had been entrusted with the task of preaching the gospel to the Gentiles, just as Peter had been to the Jews.",
    "For God, who was at work in the ministry of Peter as an apostle to the Jews, was also at work in my ministry as an apostle to the Gentiles.",
    "James, Peter and John, those reputed to be pillars, gave me and Barnabas the right hand of fellowship when they recognized the grace given to me. They agreed that we should go to the Gentiles, and they to the Jews.",
    "All they asked was that we should continue to remember the poor, the very thing I was eager to do.",
    "When Peter came to Antioch, I opposed him to his face, because he was clearly in the wrong.",
    "Before certain men came from James, he used to eat with the Gentiles. But when they arrived, he began to draw back and separate himself from the Gentiles because he was afraid of those who belonged to the circumcision group.",
    "The other Jews joined him in his hypocrisy, so that by their hypocrisy even Barnabas was led astray.",
    "When I saw that they were not acting in line with the truth of the gospel, I said to Peter in front of them all, \"You are a Jew, yet you live like a Gentile and not like a Jew. How is it, then, that you force Gentiles to follow Jewish customs?",
    "\"We who are Jews by birth and not 'Gentile sinners'",
    "know that a man is not justified by observing the law, but by faith in Jesus Christ. So we, too, have put our faith in Christ Jesus that we may be justified by faith in Christ and not by observing the law, because by observing the law no one will be justified.",
    "\"If, while we seek to be justified in Christ, it becomes evident that we ourselves are sinners, does that mean that Christ promotes sin? Absolutely not!",
    "If I rebuild what I destroyed, I prove that I am a lawbreaker.",
    "For through the law I died to the law so that I might live for God.",
    "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loved me and gave himself for me.",
    "I do not set aside the grace of God, for if righteousness could be gained through the law, Christ died for nothing!\""
  ],
  "Galatians-3": [
    "You foolish Galatians! Who has bewitched you? Before your very eyes Jesus Christ was clearly portrayed as crucified.",
    "I would like to learn just one thing from you: Did you receive the Spirit by observing the law, or by believing what you heard?",
    "Are you so foolish? After beginning with the Spirit, are you now trying to attain your goal by human effort?",
    "Have you suffered so much for nothing--if it really was for nothing?",
    "Does God give you his Spirit and work miracles among you because you observe the law, or because you believe what you heard?",
    "Consider Abraham: \"He believed God, and it was credited to him as righteousness.\"",
    "Understand, then, that those who believe are children of Abraham.",
    "The Scripture foresaw that God would justify the Gentiles by faith, and announced the gospel in advance to Abraham: \"All nations will be blessed through you.\"",
    "So those who have faith are blessed along with Abraham, the man of faith.",
    "All who rely on observing the law are under a curse, for it is written: \"Cursed is everyone who does not continue to do everything written in the Book of the Law.\"",
    "Clearly no one is justified before God by the law, because, \"The righteous will live by faith.\"",
    "The law is not based on faith; on the contrary, \"The man who does these things will live by them.\"",
    "Christ redeemed us from the curse of the law by becoming a curse for us, for it is written: \"Cursed is everyone who is hung on a tree.\"",
    "He redeemed us in order that the blessing given to Abraham might come to the Gentiles through Christ Jesus, so that by faith we might receive the promise of the Spirit.",
    "Brothers, let me take an example from everyday life. Just as no one can set aside or add to a human covenant that has been duly established, so it is in this case.",
    "The promises were spoken to Abraham and to his seed. The Scripture does not say \"and to seeds,\" meaning many people, but \"and to your seed,\" meaning one person, who is Christ.",
    "What I mean is this: The law, introduced 430 years later, does not set aside the covenant previously established by God and thus do away with the promise.",
    "For if the inheritance depends on the law, then it no longer depends on a promise; but God in his grace gave it to Abraham through a promise.",
    "What, then, was the purpose of the law? It was added because of transgressions until the Seed to whom the promise referred had come. The law was put into effect through angels by a mediator.",
    "A mediator, however, does not represent just one party; but God is one.",
    "Is the law, therefore, opposed to the promises of God? Absolutely not! For if a law had been given that could impart life, then righteousness would certainly have come by the law.",
    "But the Scripture declares that the whole world is a prisoner of sin, so that what was promised, being given through faith in Jesus Christ, might be given to those who believe.",
    "Before this faith came, we were held prisoners by the law, locked up until faith should be revealed.",
    "So the law was put in charge to lead us to Christ that we might be justified by faith.",
    "Now that faith has come, we are no longer under the supervision of the law.",
    "You are all sons of God through faith in Christ Jesus,",
    "for all of you who were baptized into Christ have clothed yourselves with Christ.",
    "There is neither Jew nor Greek, slave nor free, male nor female, for you are all one in Christ Jesus.",
    "If you belong to Christ, then you are Abraham's seed, and heirs according to the promise."
  ],
  "Galatians-4": [
    "What I am saying is that as long as the heir is a child, he is no different from a slave, although he owns the whole estate.",
    "He is subject to guardians and trustees until the time set by his father.",
    "So also, when we were children, we were in slavery under the basic principles of the world.",
    "But when the time had fully come, God sent his Son, born of a woman, born under law,",
    "to redeem those under law, that we might receive the full rights of sons.",
    "Because you are sons, God sent the Spirit of his Son into our hearts, the Spirit who calls out, \"Abba , Father.\"",
    "So you are no longer a slave, but a son; and since you are a son, God has made you also an heir.",
    "Formerly, when you did not know God, you were slaves to those who by nature are not gods.",
    "But now that you know God--or rather are known by God--how is it that you are turning back to those weak and miserable principles? Do you wish to be enslaved by them all over again?",
    "You are observing special days and months and seasons and years!",
    "I fear for you, that somehow I have wasted my efforts on you.",
    "I plead with you, brothers, become like me, for I became like you. You have done me no wrong.",
    "As you know, it was because of an illness that I first preached the gospel to you.",
    "Even though my illness was a trial to you, you did not treat me with contempt or scorn. Instead, you welcomed me as if I were an angel of God, as if I were Christ Jesus himself.",
    "What has happened to all your joy? I can testify that, if you could have done so, you would have torn out your eyes and given them to me.",
    "Have I now become your enemy by telling you the truth?",
    "Those people are zealous to win you over, but for no good. What they want is to alienate you from us, so that you may be zealous for them.",
    "It is fine to be zealous, provided the purpose is good, and to be so always and not just when I am with you.",
    "My dear children, for whom I am again in the pains of childbirth until Christ is formed in you,",
    "how I wish I could be with you now and change my tone, because I am perplexed about you!",
    "Tell me, you who want to be under the law, are you not aware of what the law says?",
    "For it is written that Abraham had two sons, one by the slave woman and the other by the free woman.",
    "His son by the slave woman was born in the ordinary way; but his son by the free woman was born as the result of a promise.",
    "These things may be taken figuratively, for the women represent two covenants. One covenant is from Mount Sinai and bears children who are to be slaves: This is Hagar.",
    "Now Hagar stands for Mount Sinai in Arabia and corresponds to the present city of Jerusalem, because she is in slavery with her children.",
    "But the Jerusalem that is above is free, and she is our mother.",
    "For it is written: \"Be glad, O barren woman, who bears no children; break forth and cry aloud, you who have no labor pains; because more are the children of the desolate woman than of her who has a husband.\"",
    "Now you, brothers, like Isaac, are children of promise.",
    "At that time the son born in the ordinary way persecuted the son born by the power of the Spirit. It is the same now.",
    "But what does the Scripture say? \"Get rid of the slave woman and her son, for the slave woman's son will never share in the inheritance with the free woman's son.\"",
    "Therefore, brothers, we are not children of the slave woman, but of the free woman."
  ],
  "Galatians-5": [
    "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.",
    "Mark my words! I, Paul, tell you that if you let yourselves be circumcised, Christ will be of no value to you at all.",
    "Again I declare to every man who lets himself be circumcised that he is obligated to obey the whole law.",
    "You who are trying to be justified by law have been alienated from Christ; you have fallen away from grace.",
    "But by faith we eagerly await through the Spirit the righteousness for which we hope.",
    "For in Christ Jesus neither circumcision nor uncircumcision has any value. The only thing that counts is faith expressing itself through love.",
    "You were running a good race. Who cut in on you and kept you from obeying the truth?",
    "That kind of persuasion does not come from the one who calls you.",
    "\"A little yeast works through the whole batch of dough.\"",
    "I am confident in the Lord that you will take no other view. The one who is throwing you into confusion will pay the penalty, whoever he may be.",
    "Brothers, if I am still preaching circumcision, why am I still being persecuted? In that case the offense of the cross has been abolished.",
    "As for those agitators, I wish they would go the whole way and emasculate themselves!",
    "You, my brothers, were called to be free. But do not use your freedom to indulge the sinful nature; rather, serve one another in love.",
    "The entire law is summed up in a single command: \"Love your neighbor as yourself.\"",
    "If you keep on biting and devouring each other, watch out or you will be destroyed by each other.",
    "So I say, live by the Spirit, and you will not gratify the desires of the sinful nature.",
    "For the sinful nature desires what is contrary to the Spirit, and the Spirit what is contrary to the sinful nature. They are in conflict with each other, so that you do not do what you want.",
    "But if you are led by the Spirit, you are not under law.",
    "The acts of the sinful nature are obvious: sexual immorality, impurity and debauchery;",
    "idolatry and witchcraft; hatred, discord, jealousy, fits of rage, selfish ambition, dissensions, factions",
    "and envy; drunkenness, orgies, and the like. I warn you, as I did before, that those who live like this will not inherit the kingdom of God.",
    "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness,",
    "gentleness and self-control. Against such things there is no law.",
    "Those who belong to Christ Jesus have crucified the sinful nature with its passions and desires.",
    "Since we live by the Spirit, let us keep in step with the Spirit.",
    "Let us not become conceited, provoking and envying each other."
  ],
  "Galatians-6": [
    "Brothers, if someone is caught in a sin, you who are spiritual should restore him gently. But watch yourself, or you also may be tempted.",
    "Carry each other's burdens, and in this way you will fulfill the law of Christ.",
    "If anyone thinks he is something when he is nothing, he deceives himself.",
    "Each one should test his own actions. Then he can take pride in himself, without comparing himself to somebody else,",
    "for each one should carry his own load.",
    "Anyone who receives instruction in the word must share all good things with his instructor.",
    "Do not be deceived: God cannot be mocked. A man reaps what he sows.",
    "The one who sows to please his sinful nature, from that nature will reap destruction; the one who sows to please the Spirit, from the Spirit will reap eternal life.",
    "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
    "Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.",
    "See what large letters I use as I write to you with my own hand!",
    "Those who want to make a good impression outwardly are trying to compel you to be circumcised. The only reason they do this is to avoid being persecuted for the cross of Christ.",
    "Not even those who are circumcised obey the law, yet they want you to be circumcised that they may boast about your flesh.",
    "May I never boast except in the cross of our Lord Jesus Christ, through which the world has been crucified to me, and I to the world.",
    "Neither circumcision nor uncircumcision means anything; what counts is a new creation.",
    "Peace and mercy to all who follow this rule, even to the Israel of God.",
    "Finally, let no one cause me trouble, for I bear on my body the marks of Jesus.",
    "The grace of our Lord Jesus Christ be with your spirit, brothers. Amen."
  ]
}