{
  "Habakkuk-1": [
    "The oracle that Habakkuk the prophet received.",
    "How long, O LORD, must I call for help, but you do not listen? Or cry out to you, \"Violence!\" but you do not save?",
    "Why do you make me look at injustice? Why do you tolerate wrong? Destruction and violence are before me; there is strife, and conflict abounds.",
    "Therefore the law is paralyzed, and justice never prevails. The wicked hem in the righteous, so that justice is perverted.",
    "\"Look at the nations and watch--and be utterly amazed. For I am going to do something in your days that you would not believe, even if you were told.",
    "I am raising up the Babylonians, that ruthless and impetuous people, who sweep across the whole earth to seize dwelling places not their own.",
    "They are a feared and dreaded people; they are a law to themselves and promote their own honor.",
    "Their horses are swifter than leopards, fiercer than wolves at dusk. Their cavalry gallops headlong; their horsemen come from afar. They fly like a vulture swooping to devour;",
    "they all come bent on violence. Their hordes advance like a desert wind and gather prisoners like sand.",
    "They deride kings and scoff at rulers. They laugh at all fortified cities; they build earthen ramps and capture them.",
    "Then they sweep past like the wind and go on--guilty men, whose own strength is their god.\"",
    "O LORD, are you not from everlasting? My God, my Holy One, we will not die. O LORD, you have appointed them to execute judgment; O Rock, you have ordained them to punish.",
    "Your eyes are too pure to look on evil; you cannot tolerate wrong. Why then do you tolerate the treacherous? Why are you silent while the wicked swallow up those more righteous than themselves?",
    "You have made men like fish in the sea, like sea creatures that have no ruler.",
    "The wicked foe pulls all of them up with hooks, he catches them in his net, he gathers them up in his dragnet; and so he rejoices and is glad.",
    "Therefore he sacrifices to his net and burns incense to his dragnet, for by his net he lives in luxury and enjoys the choicest food.",
    "Is he to keep on emptying his net, destroying nations without mercy?"
  ],
  "Habakkuk-2": [
    "I will stand at my watch and station myself on the ramparts; I will look to see what he will say to me, and what answer I am to give to this complaint.",
    "Then the LORD replied: \"Write down the revelation and make it plain on tablets so that a herald may run with it.",
    "For the revelation awaits an appointed time; it speaks of the end and will not prove false. Though it linger, wait for it; it will certainly come and will not delay.",
    "\"See, he is puffed up; his desires are not upright--but the righteous will live by his faith--",
    "indeed, wine betrays him; he is arrogant and never at rest. Because he is as greedy as the grave and like death is never satisfied, he gathers to himself all the nations and takes captive all the peoples.",
    "\"Will not all of them taunt him with ridicule and scorn, saying, \"'Woe to him who piles up stolen goods and makes himself wealthy by extortion! How long must this go on?'",
    "Will not your debtors suddenly arise? Will they not wake up and make you tremble? Then you will become their victim.",
    "Because you have plundered many nations, the peoples who are left will plunder you. For you have shed man's blood; you have destroyed lands and cities and everyone in them.",
    "\"Woe to him who builds his realm by unjust gain to set his nest on high, to escape the clutches of ruin!",
    "You have plotted the ruin of many peoples, shaming your own house and forfeiting your life.",
    "The stones of the wall will cry out, and the beams of the woodwork will echo it.",
    "\"Woe to him who builds a city with bloodshed and establishes a town by crime!",
    "Has not the LORD Almighty determined that the people's labor is only fuel for the fire, that the nations exhaust themselves for nothing?",
    "For the earth will be filled with the knowledge of the glory of the LORD, as the waters cover the sea.",
    "\"Woe to him who gives drink to his neighbors, pouring it from the wineskin till they are drunk, so that he can gaze on their naked bodies.",
    "You will be filled with shame instead of glory. Now it is your turn! Drink and be exposed! The cup from the LORD'S right hand is coming around to you, and disgrace will cover your glory.",
    "The violence you have done to Lebanon will overwhelm you, and your destruction of animals will terrify you. For you have shed man's blood; you have destroyed lands and cities and everyone in them.",
    "\"Of what value is an idol, since a man has carved it? Or an image that teaches lies? For he who makes it trusts in his own creation; he makes idols that cannot speak.",
    "Woe to him who says to wood, 'Come to life!' Or to lifeless stone, 'Wake up!' Can it give guidance? It is covered with gold and silver; there is no breath in it.",
    "But the LORD is in his holy temple; let all the earth be silent before him.\""
  ],
  "Habakkuk-3": [
    "A prayer of Habakkuk the prophet. On shigionoth .",
    "LORD, I have heard of your fame; I stand in awe of your deeds, O LORD. Renew them in our day, in our time make them known; in wrath remember mercy.",
    "God came from Teman, the Holy One from Mount Paran. Selah His glory covered the heavens and his praise filled the earth.",
    "His splendor was like the sunrise; rays flashed from his hand, where his power was hidden.",
    "Plague went before him; pestilence followed his steps.",
    "He stood, and shook the earth; he looked, and made the nations tremble. The ancient mountains crumbled and the age-old hills collapsed. His ways are eternal.",
    "I saw the tents of Cushan in distress, the dwellings of Midian in anguish.",
    "Were you angry with the rivers, O LORD? Was your wrath against the streams? Did you rage against the sea when you rode with your horses and your victorious chariots?",
    "You uncovered your bow, you called for many arrows. Selah You split the earth with rivers;",
    "the mountains saw you and writhed. Torrents of water swept by; the deep roared and lifted its waves on high.",
    "Sun and moon stood still in the heavens at the glint of your flying arrows, at the lightning of your flashing spear.",
    "In wrath you strode through the earth and in anger you threshed the nations.",
    "You came out to deliver your people, to save your anointed one. You crushed the leader of the land of wickedness, you stripped him from head to foot. Selah",
    "With his own spear you pierced his head when his warriors stormed out to scatter us, gloating as though about to devour the wretched who were in hiding.",
    "You trampled the sea with your horses, churning the great waters.",
    "I heard and my heart pounded, my lips quivered at the sound; decay crept into my bones, and my legs trembled. Yet I will wait patiently for the day of calamity to come on the nation invading us.",
    "Though the fig tree does not bud and there are no grapes on the vines, though the olive crop fails and the fields produce no food, though there are no sheep in the pen and no cattle in the stalls,",
    "yet I will rejoice in the LORD, I will be joyful in God my Savior.",
    "The Sovereign LORD is my strength; he makes my feet like the feet of a deer, he enables me to go on the heights. For the director of music. On my stringed instruments."
  ]
}