{
  "Hebrews-1": [
    "In the past God spoke to our forefathers through the prophets at many times and in various ways,",
    "but in these last days he has spoken to us by his Son, whom he appointed heir of all things, and through whom he made the universe.",
    "The Son is the radiance of God's glory and the exact representation of his being, sustaining all things by his powerful word. After he had provided purification for sins, he sat down at the right hand of the Majesty in heaven.",
    "So he became as much superior to the angels as the name he has inherited is superior to theirs.",
    "For to which of the angels did God ever say, \"You are my Son; today I have become your Father\"? Or again, \"I will be his Father, and he will be my Son\"?",
    "And again, when God brings his firstborn into the world, he says, \"Let all God's angels worship him.\"",
    "In speaking of the angels he says, \"He makes his angels winds, his servants flames of fire.\"",
    "But about the Son he says, \"Your throne, O God, will last for ever and ever, and righteousness will be the scepter of your kingdom.",
    "You have loved righteousness and hated wickedness; therefore God, your God, has set you above your companions by anointing you with the oil of joy.\"",
    "He also says, \"In the beginning, O Lord, you laid the foundations of the earth, and the heavens are the work of your hands.",
    "They will perish, but you remain; they will all wear out like a garment.",
    "You will roll them up like a robe; like a garment they will be changed. But you remain the same, and your years will never end.\"",
    "To which of the angels did God ever say, \"Sit at my right hand until I make your enemies a footstool for your feet\"?",
    "Are not all angels ministering spirits sent to serve those who will inherit salvation?"
  ],
  "Hebrews-2": [
    "We must pay more careful attention, therefore, to what we have heard, so that we do not drift away.",
    "For if the message spoken by angels was binding, and every violation and disobedience received its just punishment,",
    "how shall we escape if we ignore such a great salvation? This salvation, which was first announced by the Lord, was confirmed to us by those who heard him.",
    "God also testified to it by signs, wonders and various miracles, and gifts of the Holy Spirit distributed according to his will.",
    "It is not to angels that he has subjected the world to come, about which we are speaking.",
    "But there is a place where someone has testified: \"What is man that you are mindful of him, the son of man that you care for him?",
    "You made him a little lower than the angels; you crowned him with glory and honor",
    "and put everything under his feet.\" In putting everything under him, God left nothing that is not subject to him. Yet at present we do not see everything subject to him.",
    "But we see Jesus, who was made a little lower than the angels, now crowned with glory and honor because he suffered death, so that by the grace of God he might taste death for everyone.",
    "In bringing many sons to glory, it was fitting that God, for whom and through whom everything exists, should make the author of their salvation perfect through suffering.",
    "Both the one who makes men holy and those who are made holy are of the same family. So Jesus is not ashamed to call them brothers.",
    "He says, \"I will declare your name to my brothers; in the presence of the congregation I will sing your praises.\"",
    "And again, \"I will put my trust in him.\" And again he says, \"Here am I, and the children God has given me.\"",
    "Since the children have flesh and blood, he too shared in their humanity so that by his death he might destroy him who holds the power of death--that is, the devil--",
    "and free those who all their lives were held in slavery by their fear of death.",
    "For surely it is not angels he helps, but Abraham's descendants.",
    "For this reason he had to be made like his brothers in every way, in order that he might become a merciful and faithful high priest in service to God, and that he might make atonement for the sins of the people.",
    "Because he himself suffered when he was tempted, he is able to help those who are being tempted."
  ],
  "Hebrews-3": [
    "Therefore, holy brothers, who share in the heavenly calling, fix your thoughts on Jesus, the apostle and high priest whom we confess.",
    "He was faithful to the one who appointed him, just as Moses was faithful in all God's house.",
    "Jesus has been found worthy of greater honor than Moses, just as the builder of a house has greater honor than the house itself.",
    "For every house is built by someone, but God is the builder of everything.",
    "Moses was faithful as a servant in all God's house, testifying to what would be said in the future.",
    "But Christ is faithful as a son over God's house. And we are his house, if we hold on to our courage and the hope of which we boast.",
    "So, as the Holy Spirit says: \"Today, if you hear his voice,",
    "do not harden your hearts as you did in the rebellion, during the time of testing in the desert,",
    "where your fathers tested and tried me and for forty years saw what I did.",
    "That is why I was angry with that generation, and I said, 'Their hearts are always going astray, and they have not known my ways.'",
    "So I declared on oath in my anger, 'They shall never enter my rest.'\"",
    "See to it, brothers, that none of you has a sinful, unbelieving heart that turns away from the living God.",
    "But encourage one another daily, as long as it is called Today, so that none of you may be hardened by sin's deceitfulness.",
    "We have come to share in Christ if we hold firmly till the end the confidence we had at first.",
    "As has just been said: \"Today, if you hear his voice, do not harden your hearts as you did in the rebellion.\"",
    "Who were they who heard and rebelled? Were they not all those Moses led out of Egypt?",
    "And with whom was he angry for forty years? Was it not with those who sinned, whose bodies fell in the desert?",
    "And to whom did God swear that they would never enter his rest if not to those who disobeyed?",
    "So we see that they were not able to enter, because of their unbelief."
  ],
  "Hebrews-4": [
    "Therefore, since the promise of entering his rest still stands, let us be careful that none of you be found to have fallen short of it.",
    "For we also have had the gospel preached to us, just as they did; but the message they heard was of no value to them, because those who heard did not combine it with faith.",
    "Now we who have believed enter that rest, just as God has said, \"So I declared on oath in my anger, 'They shall never enter my rest.'\" And yet his work has been finished since the creation of the world.",
    "For somewhere he has spoken about the seventh day in these words: \"And on the seventh day God rested from all his work.\"",
    "And again in the passage above he says, \"They shall never enter my rest.\"",
    "It still remains that some will enter that rest, and those who formerly had the gospel preached to them did not go in, because of their disobedience.",
    "Therefore God again set a certain day, calling it Today, when a long time later he spoke through David, as was said before: \"Today, if you hear his voice, do not harden your hearts.\"",
    "For if Joshua had given them rest, God would not have spoken later about another day.",
    "There remains, then, a Sabbath-rest for the people of God;",
    "for anyone who enters God's rest also rests from his own work, just as God did from his.",
    "Let us, therefore, make every effort to enter that rest, so that no one will fall by following their example of disobedience.",
    "For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart.",
    "Nothing in all creation is hidden from God's sight Everything is uncovered and laid bare before the eyes of him to whom we must give account.",
    "Therefore, since we have a great high priest who has gone through the heavens, Jesus the Son of God, let us hold firmly to the faith we profess.",
    "For we do not have a high priest who is unable to sympathize with our weaknesses, but we have one who has been tempted in every way, just as we are--yet was without sin.",
    "Let us then approach the throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need."
  ],
  "Hebrews-5": [
    "Every high priest is selected from among men and is appointed to represent them in matters related to God, to offer gifts and sacrifices for sins.",
    "He is able to deal gently with those who are ignorant and are going astray, since he himself is subject to weakness.",
    "This is why he has to offer sacrifices for his own sins, as well as for the sins of the people.",
    "No one takes this honor upon himself; he must be called by God, just as Aaron was.",
    "So Christ also did not take upon himself the glory of becoming a high priest. But God said to him, \"You are my Son; today I have become your Father.\"",
    "And he says in another place, \"You are a priest forever, in the order of Melchizedek.\"",
    "During the days of Jesus' life on earth, he offered up prayers and petitions with loud cries and tears to the one who could save him from death, and he was heard because of his reverent submission.",
    "Although he was a son, he learned obedience from what he suffered",
    "and, once made perfect, he became the source of eternal salvation for all who obey him",
    "and was designated by God to be high priest in the order of Melchizedek.",
    "We have much to say about this, but it is hard to explain because you are slow to learn.",
    "In fact, though by this time you ought to be teachers, you need someone to teach you the elementary truths of God's word all over again. You need milk, not solid food!",
    "Anyone who lives on milk, being still an infant, is not acquainted with the teaching about righteousness.",
    "But solid food is for the mature, who by constant use have trained themselves to distinguish good from evil."
  ],
  "Hebrews-6": [
    "Therefore let us leave the elementary teachings about Christ and go on to maturity, not laying again the foundation of repentance from acts that lead to death, and of faith in God,",
    "instruction about baptisms, the laying on of hands, the resurrection of the dead, and eternal judgment.",
    "And God permitting, we will do so.",
    "It is impossible for those who have once been enlightened, who have tasted the heavenly gift, who have shared in the Holy Spirit,",
    "who have tasted the goodness of the word of God and the powers of the coming age,",
    "if they fall away, to be brought back to repentance, because to their loss they are crucifying the Son of God all over again and subjecting him to public disgrace.",
    "Land that drinks in the rain often falling on it and that produces a crop useful to those for whom it is farmed receives the blessing of God.",
    "But land that produces thorns and thistles is worthless and is in danger of being cursed. In the end it will be burned.",
    "Even though we speak like this, dear friends, we are confident of better things in your case--things that accompany salvation.",
    "God is not unjust; he will not forget your work and the love you have shown him as you have helped his people and continue to help them.",
    "We want each of you to show this same diligence to the very end, in order to make your hope sure.",
    "We do not want you to become lazy, but to imitate those who through faith and patience inherit what has been promised.",
    "When God made his promise to Abraham, since there was no one greater for him to swear by, he swore by himself,",
    "saying, \"I will surely bless you and give you many descendants.\"",
    "And so after waiting patiently, Abraham received what was promised.",
    "Men swear by someone greater than themselves, and the oath confirms what is said and puts an end to all argument.",
    "Because God wanted to make the unchanging nature of his purpose very clear to the heirs of what was promised, he confirmed it with an oath.",
    "God did this so that, by two unchangeable things in which it is impossible for God to lie, we who have fled to take hold of the hope offered to us may be greatly encouraged.",
    "We have this hope as an anchor for the soul, firm and secure. It enters the inner sanctuary behind the curtain,",
    "where Jesus, who went before us, has entered on our behalf. He has become a high priest forever, in the order of Melchizedek."
  ],
  "Hebrews-7": [
    "This Melchizedek was king of Salem and priest of God Most High. He met Abraham returning from the defeat of the kings and blessed him,",
    "and Abraham gave him a tenth of everything. First, his name means \"king of righteousness\"; then also, \"king of Salem\" means \"king of peace.\"",
    "Without father or mother, without genealogy, without beginning of days or end of life, like the Son of God he remains a priest forever.",
    "Just think how great he was: Even the patriarch Abraham gave him a tenth of the plunder!",
    "Now the law requires the descendants of Levi who become priests to collect a tenth from the people--that is, their brothers--even though their brothers are descended from Abraham.",
    "This man, however, did not trace his descent from Levi, yet he collected a tenth from Abraham and blessed him who had the promises.",
    "And without doubt the lesser person is blessed by the greater.",
    "In the one case, the tenth is collected by men who die; but in the other case, by him who is declared to be living.",
    "One might even say that Levi, who collects the tenth, paid the tenth through Abraham,",
    "because when Melchizedek met Abraham, Levi was still in the body of his ancestor.",
    "If perfection could have been attained through the Levitical priesthood (for on the basis of it the law was given to the people), why was there still need for another priest to come--one in the order of Melchizedek, not in the order of Aaron?",
    "For when there is a change of the priesthood, there must also be a change of the law.",
    "He of whom these things are said belonged to a different tribe, and no one from that tribe has ever served at the altar.",
    "For it is clear that our Lord descended from Judah, and in regard to that tribe Moses said nothing about priests.",
    "And what we have said is even more clear if another priest like Melchizedek appears,",
    "one who has become a priest not on the basis of a regulation as to his ancestry but on the basis of the power of an indestructible life.",
    "For it is declared: \"You are a priest forever, in the order of Melchizedek.\"",
    "The former regulation is set aside because it was weak and useless",
    "(for the law made nothing perfect), and a better hope is introduced, by which we draw near to God.",
    "And it was not without an oath! Others became priests without any oath,",
    "but he became a priest with an oath when God said to him: \"The Lord has sworn and will not change his mind: 'You are a priest forever.'\"",
    "Because of this oath, Jesus has become the guarantee of a better covenant.",
    "Now there have been many of those priests, since death prevented them from continuing in office;",
    "but because Jesus lives forever, he has a permanent priesthood.",
    "Therefore he is able to save completely those who come to God through him, because he always lives to intercede for them.",
    "Such a high priest meets our need--one who is holy, blameless, pure, set apart from sinners, exalted above the heavens.",
    "Unlike the other high priests, he does not need to offer sacrifices day after day, first for his own sins, and then for the sins of the people. He sacrificed for their sins once for all when he offered himself.",
    "For the law appoints as high priests men who are weak; but the oath, which came after the law, appointed the Son, who has been made perfect forever."
  ],
  "Hebrews-8": [
    "The point of what we are saying is this: We do have such a high priest, who sat down at the right hand of the throne of the Majesty in heaven,",
    "and who serves in the sanctuary, the true tabernacle set up by the Lord, not by man.",
    "Every high priest is appointed to offer both gifts and sacrifices, and so it was necessary for this one also to have something to offer.",
    "If he were on earth, he would not be a priest, for there are already men who offer the gifts prescribed by the law.",
    "They serve at a sanctuary that is a copy and shadow of what is in heaven. This is why Moses was warned when he was about to build the tabernacle: \"See to it that you make everything according to the pattern shown you on the mountain.\"",
    "But the ministry Jesus has received is as superior to theirs as the covenant of which he is mediator is superior to the old one, and it is founded on better promises.",
    "For if there had been nothing wrong with that first covenant, no place would have been sought for another.",
    "But God found fault with the people and said: \"The time is coming, declares the Lord, when I will make a new covenant with the house of Israel and with the house of Judah.",
    "It will not be like the covenant I made with their forefathers when I took them by the hand to lead them out of Egypt, because they did not remain faithful to my covenant, and I turned away from them, declares the Lord.",
    "This is the covenant I will make with the house of Israel after that time, declares the Lord. I will put my laws in their minds and write them on their hearts. I will be their God, and they will be my people.",
    "No longer will a man teach his neighbor, or a man his brother, saying, 'Know the Lord,' because they will all know me, from the least of them to the greatest.",
    "For I will forgive their wickedness and will remember their sins no more.\"",
    "By calling this covenant \"new,\" he has made the first one obsolete; and what is obsolete and aging will soon disappear."
  ],
  "Hebrews-9": [
    "Now the first covenant had regulations for worship and also an earthly sanctuary.",
    "A tabernacle was set up. In its first room were the lampstand, the table and the consecrated bread; this was called the Holy Place.",
    "Behind the second curtain was a room called the Most Holy Place,",
    "which had the golden altar of incense and the gold-covered ark of the covenant. This ark contained the gold jar of manna, Aaron's staff that had budded, and the stone tablets of the covenant.",
    "Above the ark were the cherubim of the Glory, overshadowing the atonement cover. But we cannot discuss these things in detail now.",
    "When everything had been arranged like this, the priests entered regularly into the outer room to carry on their ministry.",
    "But only the high priest entered the inner room, and that only once a year, and never without blood, which he offered for himself and for the sins the people had committed in ignorance.",
    "The Holy Spirit was showing by this that the way into the Most Holy Place had not yet been disclosed as long as the first tabernacle was still standing.",
    "This is an illustration for the present time, indicating that the gifts and sacrifices being offered were not able to clear the conscience of the worshiper.",
    "They are only a matter of food and drink and various ceremonial washings--external regulations applying until the time of the new order.",
    "When Christ came as high priest of the good things that are already here, he went through the greater and more perfect tabernacle that is not man-made, that is to say, not a part of this creation.",
    "He did not enter by means of the blood of goats and calves; but he entered the Most Holy Place once for all by his own blood, having obtained eternal redemption.",
    "The blood of goats and bulls and the ashes of a heifer sprinkled on those who are ceremonially unclean sanctify them so that they are outwardly clean.",
    "How much more, then, will the blood of Christ, who through the eternal Spirit offered himself unblemished to God, cleanse our consciences from acts that lead to death, so that we may serve the living God!",
    "For this reason Christ is the mediator of a new covenant, that those who are called may receive the promised eternal inheritance--now that he has died as a ransom to set them free from the sins committed under the first covenant.",
    "In the case of a will, it is necessary to prove the death of the one who made it,",
    "because a will is in force only when somebody has died; it never takes effect while the one who made it is living.",
    "This is why even the first covenant was not put into effect without blood.",
    "When Moses had proclaimed every commandment of the law to all the people, he took the blood of calves, together with water, scarlet wool and branches of hyssop, and sprinkled the scroll and all the people.",
    "He said, \"This is the blood of the covenant, which God has commanded you to keep.\"",
    "In the same way, he sprinkled with the blood both the tabernacle and everything used in its ceremonies.",
    "In fact, the law requires that nearly everything be cleansed with blood, and without the shedding of blood there is no forgiveness.",
    "It was necessary, then, for the copies of the heavenly things to be purified with these sacrifices, but the heavenly things themselves with better sacrifices than these.",
    "For Christ did not enter a man-made sanctuary that was only a copy of the true one; he entered heaven itself, now to appear for us in God's presence.",
    "Nor did he enter heaven to offer himself again and again, the way the high priest enters the Most Holy Place every year with blood that is not his own.",
    "Then Christ would have had to suffer many times since the creation of the world. But now he has appeared once for all at the end of the ages to do away with sin by the sacrifice of himself.",
    "Just as man is destined to die once, and after that to face judgment,",
    "so Christ was sacrificed once to take away the sins of many people; and he will appear a second time, not to bear sin, but to bring salvation to those who are waiting for him."
  ],
  "Hebrews-10": [
    "The law is only a shadow of the good things that are coming--not the realities themselves. For this reason it can never, by the same sacrifices repeated endlessly year after year, make perfect those who draw near to worship.",
    "If it could, would they not have stopped being offered? For the worshipers would have been cleansed once for all, and would no longer have felt guilty for their sins.",
    "But those sacrifices are an annual reminder of sins,",
    "because it is impossible for the blood of bulls and goats to take away sins.",
    "Therefore, when Christ came into the world, he said: \"Sacrifice and offering you did not desire, but a body you prepared for me;",
    "with burnt offerings and sin offerings you were not pleased.",
    "Then I said, 'Here I am--it is written about me in the scroll--I have come to do your will, O God.'\"",
    "First he said, \"Sacrifices and offerings, burnt offerings and sin offerings you did not desire, nor were you pleased with them\" (although the law required them to be made).",
    "Then he said, \"Here I am, I have come to do your will.\" He sets aside the first to establish the second.",
    "And by that will, we have been made holy through the sacrifice of the body of Jesus Christ once for all.",
    "Day after day every priest stands and performs his religious duties; again and again he offers the same sacrifices, which can never take away sins.",
    "But when this priest had offered for all time one sacrifice for sins, he sat down at the right hand of God.",
    "Since that time he waits for his enemies to be made his footstool,",
    "because by one sacrifice he has made perfect forever those who are being made holy.",
    "The Holy Spirit also testifies to us about this. First he says:",
    "\"This is the covenant I will make with them after that time, says the Lord. I will put my laws in their hearts, and I will write them on their minds.\"",
    "Then he adds: \"Their sins and lawless acts I will remember no more.\"",
    "And where these have been forgiven, there is no longer any sacrifice for sin.",
    "Therefore, brothers, since we have confidence to enter the Most Holy Place by the blood of Jesus,",
    "by a new and living way opened for us through the curtain, that is, his body,",
    "and since we have a great priest over the house of God,",
    "let us draw near to God with a sincere heart in full assurance of faith, having our hearts sprinkled to cleanse us from a guilty conscience and having our bodies washed with pure water.",
    "Let us hold unswervingly to the hope we profess, for he who promised is faithful.",
    "And let us consider how we may spur one another on toward love and good deeds.",
    "Let us not give up meeting together, as some are in the habit of doing, but let us encourage one another--and all the more as you see the Day approaching.",
    "If we deliberately keep on sinning after we have received the knowledge of the truth, no sacrifice for sins is left,",
    "but only a fearful expectation of judgment and of raging fire that will consume the enemies of God.",
    "Anyone who rejected the law of Moses died without mercy on the testimony of two or three witnesses.",
    "How much more severely do you think a man deserves to be punished who has trampled the Son of God under foot, who has treated as an unholy thing the blood of the covenant that sanctified him, and who has insulted the Spirit of grace?",
    "For we know him who said, \"It is mine to avenge; I will repay,\" and again, \"The Lord will judge his people.\"",
    "It is a dreadful thing to fall into the hands of the living God.",
    "Remember those earlier days after you had received the light, when you stood your ground in a great contest in the face of suffering.",
    "Sometimes you were publicly exposed to insult and persecution; at other times you stood side by side with those who were so treated.",
    "You sympathized with those in prison and joyfully accepted the confiscation of your property, because you knew that you yourselves had better and lasting possessions.",
    "So do not throw away your confidence; it will be richly rewarded.",
    "You need to persevere so that when you have done the will of God, you will receive what he has promised.",
    "For in just a very little while, \"He who is coming will come and will not delay.",
    "But my righteous one will live by faith. And if he shrinks back, I will not be pleased with him.\"",
    "But we are not of those who shrink back and are destroyed, but of those who believe and are saved."
  ],
  "Hebrews-11": [
    "Now faith is being sure of what we hope for and certain of what we do not see.",
    "This is what the ancients were commended for.",
    "By faith we understand that the universe was formed at God's command, so that what is seen was not made out of what was visible.",
    "By faith Abel offered God a better sacrifice than Cain did. By faith he was commended as a righteous man, when God spoke well of his offerings. And by faith he still speaks, even though he is dead.",
    "By faith Enoch was taken from this life, so that he did not experience death; he could not be found, because God had taken him away. For before he was taken, he was commended as one who pleased God.",
    "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.",
    "By faith Noah, when warned about things not yet seen, in holy fear built an ark to save his family. By his faith he condemned the world and became heir of the righteousness that comes by faith.",
    "By faith Abraham, when called to go to a place he would later receive as his inheritance, obeyed and went, even though he did not know where he was going.",
    "By faith he made his home in the promised land like a stranger in a foreign country; he lived in tents, as did Isaac and Jacob, who were heirs with him of the same promise.",
    "For he was looking forward to the city with foundations, whose architect and builder is God.",
    "By faith Abraham, even though he was past age--and Sarah herself was barren--was enabled to become a father because he considered him faithful who had made the promise.",
    "And so from this one man, and he as good as dead, came descendants as numerous as the stars in the sky and as countless as the sand on the seashore.",
    "All these people were still living by faith when they died. They did not receive the things promised; they only saw them and welcomed them from a distance. And they admitted that they were aliens and strangers on earth.",
    "People who say such things show that they are looking for a country of their own.",
    "If they had been thinking of the country they had left, they would have had opportunity to return.",
    "Instead, they were longing for a better country--a heavenly one. Therefore God is not ashamed to be called their God, for he has prepared a city for them.",
    "By faith Abraham, when God tested him, offered Isaac as a sacrifice. He who had received the promises was about to sacrifice his one and only son,",
    "even though God had said to him, \"It is through Isaac that your offspring will be reckoned.\"",
    "Abraham reasoned that God could raise the dead, and figuratively speaking, he did receive Isaac back from death.",
    "By faith Isaac blessed Jacob and Esau in regard to their future.",
    "By faith Jacob, when he was dying, blessed each of Joseph's sons, and worshiped as he leaned on the top of his staff.",
    "By faith Joseph, when his end was near, spoke about the exodus of the Israelites from Egypt and gave instructions about his bones.",
    "By faith Moses' parents hid him for three months after he was born, because they saw he was no ordinary child, and they were not afraid of the king's edict.",
    "By faith Moses, when he had grown up, refused to be known as the son of Pharaoh's daughter.",
    "He chose to be mistreated along with the people of God rather than to enjoy the pleasures of sin for a short time.",
    "He regarded disgrace for the sake of Christ as of greater value than the treasures of Egypt, because he was looking ahead to his reward.",
    "By faith he left Egypt, not fearing the king's anger; he persevered because he saw him who is invisible.",
    "By faith he kept the Passover and the sprinkling of blood, so that the destroyer of the firstborn would not touch the firstborn of Israel.",
    "By faith the people passed through the Red Sea as on dry land; but when the Egyptians tried to do so, they were drowned.",
    "By faith the walls of Jericho fell, after the people had marched around them for seven days.",
    "By faith the prostitute Rahab, because she welcomed the spies, was not killed with those who were disobedient.",
    "And what more shall I say? I do not have time to tell about Gideon, Barak, Samson, Jephthah, David, Samuel and the prophets,",
    "who through faith conquered kingdoms, administered justice, and gained what was promised; who shut the mouths of lions,",
    "quenched the fury of the flames, and escaped the edge of the sword; whose weakness was turned to strength; and who became powerful in battle and routed foreign armies.",
    "Women received back their dead, raised to life again. Others were tortured and refused to be released, so that they might gain a better resurrection.",
    "Some faced jeers and flogging, while still others were chained and put in prison.",
    "They were stoned; they were sawed in two; they were put to death by the sword. They went about in sheepskins and goatskins, destitute, persecuted and mistreated--",
    "the world was not worthy of them. They wandered in deserts and mountains, and in caves and holes in the ground.",
    "These were all commended for their faith, yet none of them received what had been promised.",
    "God had planned something better for us so that only together with us would they be made perfect."
  ],
  "Hebrews-12": [
    "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles, and let us run with perseverance the race marked out for us.",
    "Let us fix our eyes on Jesus, the author and perfecter of our faith, who for the joy set before him endured the cross, scorning its shame, and sat down at the right hand of the throne of God.",
    "Consider him who endured such opposition from sinful men, so that you will not grow weary and lose heart.",
    "In your struggle against sin, you have not yet resisted to the point of shedding your blood.",
    "And you have forgotten that word of encouragement that addresses you as sons: \"My son, do not make light of the Lord's discipline, and do not lose heart when he rebukes you,",
    "because the Lord disciplines those he loves, and he punishes everyone he accepts as a son.\"",
    "Endure hardship as discipline; God is treating you as sons. For what son is not disciplined by his father?",
    "If you are not disciplined (and everyone undergoes discipline), then you are illegitimate children and not true sons.",
    "Moreover, we have all had human fathers who disciplined us and we respected them for it. How much more should we submit to the Father of our spirits and live!",
    "Our fathers disciplined us for a little while as they thought best; but God disciplines us for our good, that we may share in his holiness.",
    "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it.",
    "Therefore, strengthen your feeble arms and weak knees.",
    "\"Make level paths for your feet,\" so that the lame may not be disabled, but rather healed.",
    "Make every effort to live in peace with all men and to be holy; without holiness no one will see the Lord.",
    "See to it that no one misses the grace of God and that no bitter root grows up to cause trouble and defile many.",
    "See that no one is sexually immoral, or is godless like Esau, who for a single meal sold his inheritance rights as the oldest son.",
    "Afterward, as you know, when he wanted to inherit this blessing, he was rejected. He could bring about no change of mind, though he sought the blessing with tears.",
    "You have not come to a mountain that can be touched and that is burning with fire; to darkness, gloom and storm;",
    "to a trumpet blast or to such a voice speaking words that those who heard it begged that no further word be spoken to them,",
    "because they could not bear what was commanded: \"If even an animal touches the mountain, it must be stoned.\"",
    "The sight was so terrifying that Moses said, \"I am trembling with fear.\"",
    "But you have come to Mount Zion, to the heavenly Jerusalem, the city of the living God. You have come to thousands upon thousands of angels in joyful assembly,",
    "to the church of the firstborn, whose names are written in heaven. You have come to God, the judge of all men, to the spirits of righteous men made perfect,",
    "to Jesus the mediator of a new covenant, and to the sprinkled blood that speaks a better word than the blood of Abel.",
    "See to it that you do not refuse him who speaks. If they did not escape when they refused him who warned them on earth, how much less will we, if we turn away from him who warns us from heaven?",
    "At that time his voice shook the earth, but now he has promised, \"Once more I will shake not only the earth but also the heavens.\"",
    "The words \"once more\" indicate the removing of what can be shaken--that is, created things--so that what cannot be shaken may remain.",
    "Therefore, since we are receiving a kingdom that cannot be shaken, let us be thankful, and so worship God acceptably with reverence and awe,",
    "for our \"God is a consuming fire.\""
  ],
  "Hebrews-13": [
    "Keep on loving each other as brothers.",
    "Do not forget to entertain strangers, for by so doing some people have entertained angels without knowing it.",
    "Remember those in prison as if you were their fellow prisoners, and those who are mistreated as if you yourselves were suffering.",
    "Marriage should be honored by all, and the marriage bed kept pure, for God will judge the adulterer and all the sexually immoral.",
    "Keep your lives free from the love of money and be content with what you have, because God has said, \"Never will I leave you; never will I forsake you.\"",
    "So we say with confidence, \"The Lord is my helper; I will not be afraid. What can man do to me?\"",
    "Remember your leaders, who spoke the word of God to you. Consider the outcome of their way of life and imitate their faith.",
    "Jesus Christ is the same yesterday and today and forever.",
    "Do not be carried away by all kinds of strange teachings. It is good for our hearts to be strengthened by grace, not by ceremonial foods, which are of no value to those who eat them.",
    "We have an altar from which those who minister at the tabernacle have no right to eat.",
    "The high priest carries the blood of animals into the Most Holy Place as a sin offering, but the bodies are burned outside the camp.",
    "And so Jesus also suffered outside the city gate to make the people holy through his own blood.",
    "Let us, then, go to him outside the camp, bearing the disgrace he bore.",
    "For here we do not have an enduring city, but we are looking for the city that is to come.",
    "Through Jesus, therefore, let us continually offer to God a sacrifice of praise--the fruit of lips that confess his name.",
    "And do not forget to do good and to share with others, for with such sacrifices God is pleased.",
    "Obey your leaders and submit to their authority. They keep watch over you as men who must give an account. Obey them so that their work will be a joy, not a burden, for that would be of no advantage to you.",
    "Pray for us. We are sure that we have a clear conscience and desire to live honorably in every way.",
    "I particularly urge you to pray so that I may be restored to you soon.",
    "May the God of peace, who through the blood of the eternal covenant brought back from the dead our Lord Jesus, that great Shepherd of the sheep,",
    "equip you with everything good for doing his will, and may he work in us what is pleasing to him, through Jesus Christ, to whom be glory for ever and ever. Amen.",
    "Brothers, I urge you to bear with my word of exhortation, for I have written you only a short letter.",
    "I want you to know that our brother Timothy has been released. If he arrives soon, I will come with him to see you.",
    "Greet all your leaders and all God's people. Those from Italy send you their greetings.",
    "Grace be with you all."
  ]
}