{
  "Job-1": [
    "In the land of Uz there lived a man whose name was Job. This man was blameless and upright; he feared God and shunned evil.",
    "He had seven sons and three daughters,",
    "and he owned seven thousand sheep, three thousand camels, five hundred yoke of oxen and five hundred donkeys, and had a large number of servants. He was the greatest man among all the people of the East.",
    "His sons used to take turns holding feasts in their homes, and they would invite their three sisters to eat and drink with them.",
    "When a period of feasting had run its course, Job would send and have them purified. Early in the morning he would sacrifice a burnt offering for each of them, thinking, \"Perhaps my children have sinned and cursed God in their hearts.\" This was Job's regular custom.",
    "One day the angels came to present themselves before the LORD, and Satan also came with them.",
    "The LORD said to Satan, \"Where have you come from?\" Satan answered the LORD, \"From roaming through the earth and going back and forth in it.\"",
    "Then the LORD said to Satan, \"Have you considered my servant Job? There is no one on earth like him; he is blameless and upright, a man who fears God and shuns evil.\"",
    "\"Does Job fear God for nothing?\" Satan replied.",
    "\"Have you not put a hedge around him and his household and everything he has? You have blessed the work of his hands, so that his flocks and herds are spread throughout the land.",
    "But stretch out your hand and strike everything he has, and he will surely curse you to your face.\"",
    "The LORD said to Satan, \"Very well, then, everything he has is in your hands, but on the man himself do not lay a finger.\" Then Satan went out from the presence of the LORD.",
    "One day when Job's sons and daughters were feasting and drinking wine at the oldest brother's house,",
    "a messenger came to Job and said, \"The oxen were plowing and the donkeys were grazing nearby,",
    "and the Sabeans attacked and carried them off. They put the servants to the sword, and I am the only one who has escaped to tell you!\"",
    "While he was still speaking, another messenger came and said, \"The fire of God fell from the sky and burned up the sheep and the servants, and I am the only one who has escaped to tell you!\"",
    "While he was still speaking, another messenger came and said, \"The Chaldeans formed three raiding parties and swept down on your camels and carried them off. They put the servants to the sword, and I am the only one who has escaped to tell you!\"",
    "While he was still speaking, yet another messenger came and said, \"Your sons and daughters were feasting and drinking wine at the oldest brother's house,",
    "when suddenly a mighty wind swept in from the desert and struck the four corners of the house. It collapsed on them and they are dead, and I am the only one who has escaped to tell you!\"",
    "At this, Job got up and tore his robe and shaved his head. Then he fell to the ground in worship",
    "and said: \"Naked I came from my mother's womb, and naked I will depart. The LORD gave and the LORD has taken away; may the name of the LORD be praised.\"",
    "In all this, Job did not sin by charging God with wrongdoing."
  ],
  "Job-2": [
    "On another day the angels came to present themselves before the LORD, and Satan also came with them to present himself before him.",
    "And the LORD said to Satan, \"Where have you come from?\" Satan answered the LORD, \"From roaming through the earth and going back and forth in it.\"",
    "Then the LORD said to Satan, \"Have you considered my servant Job? There is no one on earth like him; he is blameless and upright, a man who fears God and shuns evil. And he still maintains his integrity, though you incited me against him to ruin him without any reason.\"",
    "\"Skin for skin!\" Satan replied. \"A man will give all he has for his own life.",
    "But stretch out your hand and strike his flesh and bones, and he will surely curse you to your face.\"",
    "The LORD said to Satan, \"Very well, then, he is in your hands; but you must spare his life.\"",
    "So Satan went out from the presence of the LORD and afflicted Job with painful sores from the soles of his feet to the top of his head.",
    "Then Job took a piece of broken pottery and scraped himself with it as he sat among the ashes.",
    "His wife said to him, \"Are you still holding on to your integrity? Curse God and die!\"",
    "He replied, \"You are talking like a foolish woman. Shall we accept good from God, and not trouble?\" In all this, Job did not sin in what he said.",
    "When Job's three friends, Eliphaz the Temanite, Bildad the Shuhite and Zophar the Naamathite, heard about all the troubles that had come upon him, they set out from their homes and met together by agreement to go and sympathize with him and comfort him.",
    "When they saw him from a distance, they could hardly recognize him; they began to weep aloud, and they tore their robes and sprinkled dust on their heads.",
    "Then they sat on the ground with him for seven days and seven nights. No one said a word to him, because they saw how great his suffering was."
  ],
  "Job-3": [
    "After this, Job opened his mouth and cursed the day of his birth.",
    "He said:",
    "\"May the day of my birth perish, and the night it was said, 'A boy is born!'",
    "That day--may it turn to darkness; may God above not care about it; may no light shine upon it.",
    "May darkness and deep shadow claim it once more; may a cloud settle over it; may blackness overwhelm its light.",
    "That night--may thick darkness seize it; may it not be included among the days of the year nor be entered in any of the months.",
    "May that night be barren; may no shout of joy be heard in it.",
    "May those who curse days curse that day, those who are ready to rouse Leviathan.",
    "May its morning stars become dark; may it wait for daylight in vain and not see the first rays of dawn,",
    "for it did not shut the doors of the womb on me to hide trouble from my eyes.",
    "\"Why did I not perish at birth, and die as I came from the womb?",
    "Why were there knees to receive me and breasts that I might be nursed?",
    "For now I would be lying down in peace; I would be asleep and at rest",
    "with kings and counselors of the earth, who built for themselves places now lying in ruins,",
    "with rulers who had gold, who filled their houses with silver.",
    "Or why was I not hidden in the ground like a stillborn child, like an infant who never saw the light of day?",
    "There the wicked cease from turmoil, and there the weary are at rest.",
    "Captives also enjoy their ease; they no longer hear the slave driver's shout.",
    "The small and the great are there, and the slave is freed from his master.",
    "\"Why is light given to those in misery, and life to the bitter of soul,",
    "to those who long for death that does not come, who search for it more than for hidden treasure,",
    "who are filled with gladness and rejoice when they reach the grave?",
    "Why is life given to a man whose way is hidden, whom God has hedged in?",
    "For sighing comes to me instead of food; my groans pour out like water.",
    "What I feared has come upon me; what I dreaded has happened to me.",
    "I have no peace, no quietness; I have no rest, but only turmoil.\""
  ],
  "Job-4": [
    "Then Eliphaz the Temanite replied:",
    "\"If someone ventures a word with you, will you be impatient? But who can keep from speaking?",
    "Think how you have instructed many, how you have strengthened feeble hands.",
    "Your words have supported those who stumbled; you have strengthened faltering knees.",
    "But now trouble comes to you, and you are discouraged; it strikes you, and you are dismayed.",
    "Should not your piety be your confidence and your blameless ways your hope?",
    "\"Consider now: Who, being innocent, has ever perished? Where were the upright ever destroyed?",
    "As I have observed, those who plow evil and those who sow trouble reap it.",
    "At the breath of God they are destroyed; at the blast of his anger they perish.",
    "The lions may roar and growl, yet the teeth of the great lions are broken.",
    "The lion perishes for lack of prey, and the cubs of the lioness are scattered.",
    "\"A word was secretly brought to me, my ears caught a whisper of it.",
    "Amid disquieting dreams in the night, when deep sleep falls on men,",
    "fear and trembling seized me and made all my bones shake.",
    "A spirit glided past my face, and the hair on my body stood on end.",
    "It stopped, but I could not tell what it was. A form stood before my eyes, and I heard a hushed voice:",
    "'Can a mortal be more righteous than God? Can a man be more pure than his Maker?",
    "If God places no trust in his servants, if he charges his angels with error,",
    "how much more those who live in houses of clay, whose foundations are in the dust, who are crushed more readily than a moth!",
    "Between dawn and dusk they are broken to pieces; unnoticed, they perish forever.",
    "Are not the cords of their tent pulled up, so that they die without wisdom?'"
  ],
  "Job-5": [
    "\"Call if you will, but who will answer you? To which of the holy ones will you turn?",
    "Resentment kills a fool, and envy slays the simple.",
    "I myself have seen a fool taking root, but suddenly his house was cursed.",
    "His children are far from safety, crushed in court without a defender.",
    "The hungry consume his harvest, taking it even from among thorns, and the thirsty pant after his wealth.",
    "For hardship does not spring from the soil, nor does trouble sprout from the ground.",
    "Yet man is born to trouble as surely as sparks fly upward.",
    "\"But if it were I, I would appeal to God; I would lay my cause before him.",
    "He performs wonders that cannot be fathomed, miracles that cannot be counted.",
    "He bestows rain on the earth; he sends water upon the countryside.",
    "The lowly he sets on high, and those who mourn are lifted to safety.",
    "He thwarts the plans of the crafty, so that their hands achieve no success.",
    "He catches the wise in their craftiness, and the schemes of the wily are swept away.",
    "Darkness comes upon them in the daytime; at noon they grope as in the night.",
    "He saves the needy from the sword in their mouth; he saves them from the clutches of the powerful.",
    "So the poor have hope, and injustice shuts its mouth.",
    "\"Blessed is the man whom God corrects; so do not despise the discipline of the Almighty.",
    "For he wounds, but he also binds up; he injures, but his hands also heal.",
    "From six calamities he will rescue you; in seven no harm will befall you.",
    "In famine he will ransom you from death, and in battle from the stroke of the sword.",
    "You will be protected from the lash of the tongue, and need not fear when destruction comes.",
    "You will laugh at destruction and famine, and need not fear the beasts of the earth.",
    "For you will have a covenant with the stones of the field, and the wild animals will be at peace with you.",
    "You will know that your tent is secure; you will take stock of your property and find nothing missing.",
    "You will know that your children will be many, and your descendants like the grass of the earth.",
    "You will come to the grave in full vigor, like sheaves gathered in season.",
    "\"We have examined this, and it is true. So hear it and apply it to yourself.\""
  ],
  "Job-6": [
    "Then Job replied:",
    "\"If only my anguish could be weighed and all my misery be placed on the scales!",
    "It would surely outweigh the sand of the seas--no wonder my words have been impetuous.",
    "The arrows of the Almighty are in me, my spirit drinks in their poison; God's terrors are marshaled against me.",
    "Does a wild donkey bray when it has grass, or an ox bellow when it has fodder?",
    "Is tasteless food eaten without salt, or is there flavor in the white of an egg?",
    "I refuse to touch it; such food makes me ill.",
    "\"Oh, that I might have my request, that God would grant what I hope for,",
    "that God would be willing to crush me, to let loose his hand and cut me off!",
    "Then I would still have this consolation--my joy in unrelenting pain--that I had not denied the words of the Holy One.",
    "\"What strength do I have, that I should still hope? What prospects, that I should be patient?",
    "Do I have the strength of stone? Is my flesh bronze?",
    "Do I have any power to help myself, now that success has been driven from me?",
    "\"A despairing man should have the devotion of his friends, even though he forsakes the fear of the Almighty.",
    "But my brothers are as undependable as intermittent streams, as the streams that overflow",
    "when darkened by thawing ice and swollen with melting snow,",
    "but that cease to flow in the dry season, and in the heat vanish from their channels.",
    "Caravans turn aside from their routes; they go up into the wasteland and perish.",
    "The caravans of Tema look for water, the traveling merchants of Sheba look in hope.",
    "They are distressed, because they had been confident; they arrive there, only to be disappointed.",
    "Now you too have proved to be of no help; you see something dreadful and are afraid.",
    "Have I ever said, 'Give something on my behalf, pay a ransom for me from your wealth,",
    "deliver me from the hand of the enemy, ransom me from the clutches of the ruthless'?",
    "\"Teach me, and I will be quiet; show me where I have been wrong.",
    "How painful are honest words! But what do your arguments prove?",
    "Do you mean to correct what I say, and treat the words of a despairing man as wind?",
    "You would even cast lots for the fatherless and barter away your friend.",
    "\"But now be so kind as to look at me. Would I lie to your face?",
    "Relent, do not be unjust; reconsider, for my integrity is at stake.",
    "Is there any wickedness on my lips? Can my mouth not discern malice?"
  ],
  "Job-7": [
    "\"Does not man have hard service on earth? Are not his days like those of a hired man?",
    "Like a slave longing for the evening shadows, or a hired man waiting eagerly for his wages,",
    "so I have been allotted months of futility, and nights of misery have been assigned to me.",
    "When I lie down I think, 'How long before I get up?' The night drags on, and I toss till dawn.",
    "My body is clothed with worms and scabs, my skin is broken and festering.",
    "\"My days are swifter than a weaver's shuttle, and they come to an end without hope.",
    "Remember, O God, that my life is but a breath; my eyes will never see happiness again.",
    "The eye that now sees me will see me no longer; you will look for me, but I will be no more.",
    "As a cloud vanishes and is gone, so he who goes down to the grave does not return.",
    "He will never come to his house again; his place will know him no more.",
    "\"Therefore I will not keep silent; I will speak out in the anguish of my spirit, I will complain in the bitterness of my soul.",
    "Am I the sea, or the monster of the deep, that you put me under guard?",
    "When I think my bed will comfort me and my couch will ease my complaint,",
    "even then you frighten me with dreams and terrify me with visions,",
    "so that I prefer strangling and death, rather than this body of mine.",
    "I despise my life; I would not live forever. Let me alone; my days have no meaning.",
    "\"What is man that you make so much of him, that you give him so much attention,",
    "that you examine him every morning and test him every moment?",
    "Will you never look away from me, or let me alone even for an instant?",
    "If I have sinned, what have I done to you, O watcher of men? Why have you made me your target? Have I become a burden to you?",
    "Why do you not pardon my offenses and forgive my sins? For I will soon lie down in the dust; you will search for me, but I will be no more.\""
  ],
  "Job-8": [
    "Then Bildad the Shuhite replied:",
    "\"How long will you say such things? Your words are a blustering wind.",
    "Does God pervert justice? Does the Almighty pervert what is right?",
    "When your children sinned against him, he gave them over to the penalty of their sin.",
    "But if you will look to God and plead with the Almighty,",
    "if you are pure and upright, even now he will rouse himself on your behalf and restore you to your rightful place.",
    "Your beginnings will seem humble, so prosperous will your future be.",
    "\"Ask the former generations and find out what their fathers learned,",
    "for we were born only yesterday and know nothing, and our days on earth are but a shadow.",
    "Will they not instruct you and tell you? Will they not bring forth words from their understanding?",
    "Can papyrus grow tall where there is no marsh? Can reeds thrive without water?",
    "While still growing and uncut, they wither more quickly than grass.",
    "Such is the destiny of all who forget God; so perishes the hope of the godless.",
    "What he trusts in is fragile; what he relies on is a spider's web.",
    "He leans on his web, but it gives way; he clings to it, but it does not hold.",
    "He is like a well-watered plant in the sunshine, spreading its shoots over the garden;",
    "it entwines its roots around a pile of rocks and looks for a place among the stones.",
    "But when it is torn from its spot, that place disowns it and says, 'I never saw you.'",
    "Surely its life withers away, and from the soil other plants grow.",
    "\"Surely God does not reject a blameless man or strengthen the hands of evildoers.",
    "He will yet fill your mouth with laughter and your lips with shouts of joy.",
    "Your enemies will be clothed in shame, and the tents of the wicked will be no more.\""
  ],
  "Job-9": [
    "Then Job replied:",
    "\"Indeed, I know that this is true. But how can a mortal be righteous before God?",
    "Though one wished to dispute with him, he could not answer him one time out of a thousand.",
    "His wisdom is profound, his power is vast. Who has resisted him and come out unscathed?",
    "He moves mountains without their knowing it and overturns them in his anger.",
    "He shakes the earth from its place and makes its pillars tremble.",
    "He speaks to the sun and it does not shine; he seals off the light of the stars.",
    "He alone stretches out the heavens and treads on the waves of the sea.",
    "He is the Maker of the Bear and Orion, the Pleiades and the constellations of the south.",
    "He performs wonders that cannot be fathomed, miracles that cannot be counted.",
    "When he passes me, I cannot see him; when he goes by, I cannot perceive him.",
    "If he snatches away, who can stop him? Who can say to him, 'What are you doing?'",
    "God does not restrain his anger; even the cohorts of Rahab cowered at his feet.",
    "\"How then can I dispute with him? How can I find words to argue with him?",
    "Though I were innocent, I could not answer him; I could only plead with my Judge for mercy.",
    "Even if I summoned him and he responded, I do not believe he would give me a hearing.",
    "He would crush me with a storm and multiply my wounds for no reason.",
    "He would not let me regain my breath but would overwhelm me with misery.",
    "If it is a matter of strength, he is mighty! And if it is a matter of justice, who will summon him?",
    "Even if I were innocent, my mouth would condemn me; if I were blameless, it would pronounce me guilty.",
    "\"Although I am blameless, I have no concern for myself; I despise my own life.",
    "It is all the same; that is why I say, 'He destroys both the blameless and the wicked.'",
    "When a scourge brings sudden death, he mocks the despair of the innocent.",
    "When a land falls into the hands of the wicked, he blindfolds its judges. If it is not he, then who is it?",
    "\"My days are swifter than a runner; they fly away without a glimpse of joy.",
    "They skim past like boats of papyrus, like eagles swooping down on their prey.",
    "If I say, 'I will forget my complaint, I will change my expression, and smile,'",
    "I still dread all my sufferings, for I know you will not hold me innocent.",
    "Since I am already found guilty, why should I struggle in vain?",
    "Even if I washed myself with soap and my hands with washing soda,",
    "you would plunge me into a slime pit so that even my clothes would detest me.",
    "\"He is not a man like me that I might answer him, that we might confront each other in court.",
    "If only there were someone to arbitrate between us, to lay his hand upon us both,",
    "someone to remove God's rod from me, so that his terror would frighten me no more.",
    "Then I would speak up without fear of him, but as it now stands with me, I cannot."
  ],
  "Job-10": [
    "\"I loathe my very life; therefore I will give free rein to my complaint and speak out in the bitterness of my soul.",
    "I will say to God: Do not condemn me, but tell me what charges you have against me.",
    "Does it please you to oppress me, to spurn the work of your hands, while you smile on the schemes of the wicked?",
    "Do you have eyes of flesh? Do you see as a mortal sees?",
    "Are your days like those of a mortal or your years like those of a man,",
    "that you must search out my faults and probe after my sin--",
    "though you know that I am not guilty and that no one can rescue me from your hand?",
    "\"Your hands shaped me and made me. Will you now turn and destroy me?",
    "Remember that you molded me like clay. Will you now turn me to dust again?",
    "Did you not pour me out like milk and curdle me like cheese,",
    "clothe me with skin and flesh and knit me together with bones and sinews?",
    "You gave me life and showed me kindness, and in your providence watched over my spirit.",
    "\"But this is what you concealed in your heart, and I know that this was in your mind:",
    "If I sinned, you would be watching me and would not let my offense go unpunished.",
    "If I am guilty--woe to me! Even if I am innocent, I cannot lift my head, for I am full of shame and drowned in my affliction.",
    "If I hold my head high, you stalk me like a lion and again display your awesome power against me.",
    "You bring new witnesses against me and increase your anger toward me; your forces come against me wave upon wave.",
    "\"Why then did you bring me out of the womb? I wish I had died before any eye saw me.",
    "If only I had never come into being, or had been carried straight from the womb to the grave!",
    "Are not my few days almost over? Turn away from me so I can have a moment's joy",
    "before I go to the place of no return, to the land of gloom and deep shadow,",
    "to the land of deepest night, of deep shadow and disorder, where even the light is like darkness.\""
  ],
  "Job-11": [
    "Then Zophar the Naamathite replied:",
    "\"Are all these words to go unanswered? Is this talker to be vindicated?",
    "Will your idle talk reduce men to silence? Will no one rebuke you when you mock?",
    "You say to God, 'My beliefs are flawless and I am pure in your sight.'",
    "Oh, how I wish that God would speak, that he would open his lips against you",
    "and disclose to you the secrets of wisdom, for true wisdom has two sides. Know this: God has even forgotten some of your sin.",
    "\"Can you fathom the mysteries of God? Can you probe the limits of the Almighty?",
    "They are higher than the heavens--what can you do? They are deeper than the depths of the grave--what can you know?",
    "Their measure is longer than the earth and wider than the sea.",
    "\"If he comes along and confines you in prison and convenes a court, who can oppose him?",
    "Surely he recognizes deceitful men; and when he sees evil, does he not take note?",
    "But a witless man can no more become wise than a wild donkey's colt can be born a man.",
    "\"Yet if you devote your heart to him and stretch out your hands to him,",
    "if you put away the sin that is in your hand and allow no evil to dwell in your tent,",
    "then you will lift up your face without shame; you will stand firm and without fear.",
    "You will surely forget your trouble, recalling it only as waters gone by.",
    "Life will be brighter than noonday, and darkness will become like morning.",
    "You will be secure, because there is hope; you will look about you and take your rest in safety.",
    "You will lie down, with no one to make you afraid, and many will court your favor.",
    "But the eyes of the wicked will fail, and escape will elude them; their hope will become a dying gasp.\""
  ],
  "Job-12": [
    "Then Job replied:",
    "\"Doubtless you are the people, and wisdom will die with you!",
    "But I have a mind as well as you; I am not inferior to you. Who does not know all these things?",
    "\"I have become a laughingstock to my friends, though I called upon God and he answered--a mere laughingstock, though righteous and blameless!",
    "Men at ease have contempt for misfortune as the fate of those whose feet are slipping.",
    "The tents of marauders are undisturbed, and those who provoke God are secure--those who carry their god in their hands.",
    "\"But ask the animals, and they will teach you, or the birds of the air, and they will tell you;",
    "or speak to the earth, and it will teach you, or let the fish of the sea inform you.",
    "Which of all these does not know that the hand of the LORD has done this?",
    "In his hand is the life of every creature and the breath of all mankind.",
    "Does not the ear test words as the tongue tastes food?",
    "Is not wisdom found among the aged? Does not long life bring understanding?",
    "\"To God belong wisdom and power; counsel and understanding are his.",
    "What he tears down cannot be rebuilt; the man he imprisons cannot be released.",
    "If he holds back the waters, there is drought; if he lets them loose, they devastate the land.",
    "To him belong strength and victory; both deceived and deceiver are his.",
    "He leads counselors away stripped and makes fools of judges.",
    "He takes off the shackles put on by kings and ties a loincloth around their waist.",
    "He leads priests away stripped and overthrows men long established.",
    "He silences the lips of trusted advisers and takes away the discernment of elders.",
    "He pours contempt on nobles and disarms the mighty.",
    "He reveals the deep things of darkness and brings deep shadows into the light.",
    "He makes nations great, and destroys them; he enlarges nations, and disperses them.",
    "He deprives the leaders of the earth of their reason; he sends them wandering through a trackless waste.",
    "They grope in darkness with no light; he makes them stagger like drunkards."
  ],
  "Job-13": [
    "\"My eyes have seen all this, my ears have heard and understood it.",
    "What you know, I also know; I am not inferior to you.",
    "But I desire to speak to the Almighty and to argue my case with God.",
    "You, however, smear me with lies; you are worthless physicians, all of you!",
    "If only you would be altogether silent! For you, that would be wisdom.",
    "Hear now my argument; listen to the plea of my lips.",
    "Will you speak wickedly on God's behalf? Will you speak deceitfully for him?",
    "Will you show him partiality? Will you argue the case for God?",
    "Would it turn out well if he examined you? Could you deceive him as you might deceive men?",
    "He would surely rebuke you if you secretly showed partiality.",
    "Would not his splendor terrify you? Would not the dread of him fall on you?",
    "Your maxims are proverbs of ashes; your defenses are defenses of clay.",
    "\"Keep silent and let me speak; then let come to me what may.",
    "Why do I put myself in jeopardy and take my life in my hands?",
    "Though he slay me, yet will I hope in him; I will surely defend my ways to his face.",
    "Indeed, this will turn out for my deliverance, for no godless man would dare come before him!",
    "Listen carefully to my words; let your ears take in what I say.",
    "Now that I have prepared my case, I know I will be vindicated.",
    "Can anyone bring charges against me? If so, I will be silent and die.",
    "\"Only grant me these two things, O God, and then I will not hide from you:",
    "Withdraw your hand far from me, and stop frightening me with your terrors.",
    "Then summon me and I will answer, or let me speak, and you reply.",
    "How many wrongs and sins have I committed? Show me my offense and my sin.",
    "Why do you hide your face and consider me your enemy?",
    "Will you torment a windblown leaf? Will you chase after dry chaff?",
    "For you write down bitter things against me and make me inherit the sins of my youth.",
    "You fasten my feet in shackles; you keep close watch on all my paths by putting marks on the soles of my feet.",
    "\"So man wastes away like something rotten, like a garment eaten by moths."
  ],
  "Job-14": [
    "\"Man born of woman is of few days and full of trouble.",
    "He springs up like a flower and withers away; like a fleeting shadow, he does not endure.",
    "Do you fix your eye on such a one? Will you bring him before you for judgment?",
    "Who can bring what is pure from the impure? No one!",
    "Man's days are determined; you have decreed the number of his months and have set limits he cannot exceed.",
    "So look away from him and let him alone, till he has put in his time like a hired man.",
    "\"At least there is hope for a tree: If it is cut down, it will sprout again, and its new shoots will not fail.",
    "Its roots may grow old in the ground and its stump die in the soil,",
    "yet at the scent of water it will bud and put forth shoots like a plant.",
    "But man dies and is laid low; he breathes his last and is no more.",
    "As water disappears from the sea or a riverbed becomes parched and dry,",
    "so man lies down and does not rise; till the heavens are no more, men will not awake or be roused from their sleep.",
    "\"If only you would hide me in the grave and conceal me till your anger has passed! If only you would set me a time and then remember me!",
    "If a man dies, will he live again? All the days of my hard service I will wait for my renewal to come.",
    "You will call and I will answer you; you will long for the creature your hands have made.",
    "Surely then you will count my steps but not keep track of my sin.",
    "My offenses will be sealed up in a bag; you will cover over my sin.",
    "\"But as a mountain erodes and crumbles and as a rock is moved from its place,",
    "as water wears away stones and torrents wash away the soil, so you destroy man's hope.",
    "You overpower him once for all, and he is gone; you change his countenance and send him away.",
    "If his sons are honored, he does not know it; if they are brought low, he does not see it.",
    "He feels but the pain of his own body and mourns only for himself.\""
  ],
  "Job-15": [
    "Then Eliphaz the Temanite replied:",
    "\"Would a wise man answer with empty notions or fill his belly with the hot east wind?",
    "Would he argue with useless words, with speeches that have no value?",
    "But you even undermine piety and hinder devotion to God.",
    "Your sin prompts your mouth; you adopt the tongue of the crafty.",
    "Your own mouth condemns you, not mine; your own lips testify against you.",
    "\"Are you the first man ever born? Were you brought forth before the hills?",
    "Do you listen in on God's council? Do you limit wisdom to yourself?",
    "What do you know that we do not know? What insights do you have that we do not have?",
    "The gray-haired and the aged are on our side, men even older than your father.",
    "Are God's consolations not enough for you, words spoken gently to you?",
    "Why has your heart carried you away, and why do your eyes flash,",
    "so that you vent your rage against God and pour out such words from your mouth?",
    "\"What is man, that he could be pure, or one born of woman, that he could be righteous?",
    "If God places no trust in his holy ones, if even the heavens are not pure in his eyes,",
    "how much less man, who is vile and corrupt, who drinks up evil like water!",
    "\"Listen to me and I will explain to you; let me tell you what I have seen,",
    "what wise men have declared, hiding nothing received from their fathers",
    "(to whom alone the land was given when no alien passed among them):",
    "All his days the wicked man suffers torment, the ruthless through all the years stored up for him.",
    "Terrifying sounds fill his ears; when all seems well, marauders attack him.",
    "He despairs of escaping the darkness; he is marked for the sword.",
    "He wanders about--food for vultures; he knows the day of darkness is at hand.",
    "Distress and anguish fill him with terror; they overwhelm him, like a king poised to attack,",
    "because he shakes his fist at God and vaunts himself against the Almighty,",
    "defiantly charging against him with a thick, strong shield.",
    "\"Though his face is covered with fat and his waist bulges with flesh,",
    "he will inhabit ruined towns and houses where no one lives, houses crumbling to rubble.",
    "He will no longer be rich and his wealth will not endure, nor will his possessions spread over the land.",
    "He will not escape the darkness; a flame will wither his shoots, and the breath of God's mouth will carry him away.",
    "Let him not deceive himself by trusting what is worthless, for he will get nothing in return.",
    "Before his time he will be paid in full, and his branches will not flourish.",
    "He will be like a vine stripped of its unripe grapes, like an olive tree shedding its blossoms.",
    "For the company of the godless will be barren, and fire will consume the tents of those who love bribes.",
    "They conceive trouble and give birth to evil; their womb fashions deceit.\""
  ],
  "Job-16": [
    "Then Job replied:",
    "\"I have heard many things like these; miserable comforters are you all!",
    "Will your long-winded speeches never end? What ails you that you keep on arguing?",
    "I also could speak like you, if you were in my place; I could make fine speeches against you and shake my head at you.",
    "But my mouth would encourage you; comfort from my lips would bring you relief.",
    "\"Yet if I speak, my pain is not relieved; and if I refrain, it does not go away.",
    "Surely, O God, you have worn me out; you have devastated my entire household.",
    "You have bound me--and it has become a witness; my gauntness rises up and testifies against me.",
    "God assails me and tears me in his anger and gnashes his teeth at me; my opponent fastens on me his piercing eyes.",
    "Men open their mouths to jeer at me; they strike my cheek in scorn and unite together against me.",
    "God has turned me over to evil men and thrown me into the clutches of the wicked.",
    "All was well with me, but he shattered me; he seized me by the neck and crushed me. He has made me his target;",
    "his archers surround me. Without pity, he pierces my kidneys and spills my gall on the ground.",
    "Again and again he bursts upon me; he rushes at me like a warrior.",
    "\"I have sewed sackcloth over my skin and buried my brow in the dust.",
    "My face is red with weeping, deep shadows ring my eyes;",
    "yet my hands have been free of violence and my prayer is pure.",
    "\"O earth, do not cover my blood; may my cry never be laid to rest!",
    "Even now my witness is in heaven; my advocate is on high.",
    "My intercessor is my friend as my eyes pour out tears to God;",
    "on behalf of a man he pleads with God as a man pleads for his friend.",
    "\"Only a few years will pass before I go on the journey of no return."
  ],
  "Job-17": [
    "My spirit is broken, my days are cut short, the grave awaits me.",
    "Surely mockers surround me; my eyes must dwell on their hostility.",
    "\"Give me, O God, the pledge you demand. Who else will put up security for me?",
    "You have closed their minds to understanding; therefore you will not let them triumph.",
    "If a man denounces his friends for reward, the eyes of his children will fail.",
    "\"God has made me a byword to everyone, a man in whose face people spit.",
    "My eyes have grown dim with grief; my whole frame is but a shadow.",
    "Upright men are appalled at this; the innocent are aroused against the ungodly.",
    "Nevertheless, the righteous will hold to their ways, and those with clean hands will grow stronger.",
    "\"But come on, all of you, try again! I will not find a wise man among you.",
    "My days have passed, my plans are shattered, and so are the desires of my heart.",
    "These men turn night into day; in the face of darkness they say, 'Light is near.'",
    "If the only home I hope for is the grave, if I spread out my bed in darkness,",
    "if I say to corruption, 'You are my father,' and to the worm, 'My mother' or 'My sister,'",
    "where then is my hope? Who can see any hope for me?",
    "Will it go down to the gates of death? Will we descend together into the dust?\""
  ],
  "Job-18": [
    "Then Bildad the Shuhite replied:",
    "\"When will you end these speeches? Be sensible, and then we can talk.",
    "Why are we regarded as cattle and considered stupid in your sight?",
    "You who tear yourself to pieces in your anger, is the earth to be abandoned for your sake? Or must the rocks be moved from their place?",
    "\"The lamp of the wicked is snuffed out; the flame of his fire stops burning.",
    "The light in his tent becomes dark; the lamp beside him goes out.",
    "The vigor of his step is weakened; his own schemes throw him down.",
    "His feet thrust him into a net and he wanders into its mesh.",
    "A trap seizes him by the heel; a snare holds him fast.",
    "A noose is hidden for him on the ground; a trap lies in his path.",
    "Terrors startle him on every side and dog his every step.",
    "Calamity is hungry for him; disaster is ready for him when he falls.",
    "It eats away parts of his skin; death's firstborn devours his limbs.",
    "He is torn from the security of his tent and marched off to the king of terrors.",
    "Fire resides in his tent; burning sulfur is scattered over his dwelling.",
    "His roots dry up below and his branches wither above.",
    "The memory of him perishes from the earth; he has no name in the land.",
    "He is driven from light into darkness and is banished from the world.",
    "He has no offspring or descendants among his people, no survivor where once he lived.",
    "Men of the west are appalled at his fate; men of the east are seized with horror.",
    "Surely such is the dwelling of an evil man; such is the place of one who knows not God.\""
  ],
  "Job-19": [
    "Then Job replied:",
    "\"How long will you torment me and crush me with words?",
    "Ten times now you have reproached me; shamelessly you attack me.",
    "If it is true that I have gone astray, my error remains my concern alone.",
    "If indeed you would exalt yourselves above me and use my humiliation against me,",
    "then know that God has wronged me and drawn his net around me.",
    "\"Though I cry, 'I've been wronged!' I get no response; though I call for help, there is no justice.",
    "He has blocked my way so I cannot pass; he has shrouded my paths in darkness.",
    "He has stripped me of my honor and removed the crown from my head.",
    "He tears me down on every side till I am gone; he uproots my hope like a tree.",
    "His anger burns against me; he counts me among his enemies.",
    "His troops advance in force; they build a siege ramp against me and encamp around my tent.",
    "\"He has alienated my brothers from me; my acquaintances are completely estranged from me.",
    "My kinsmen have gone away; my friends have forgotten me.",
    "My guests and my maidservants count me a stranger; they look upon me as an alien.",
    "I summon my servant, but he does not answer, though I beg him with my own mouth.",
    "My breath is offensive to my wife; I am loathsome to my own brothers.",
    "Even the little boys scorn me; when I appear, they ridicule me.",
    "All my intimate friends detest me; those I love have turned against me.",
    "I am nothing but skin and bones; I have escaped with only the skin of my teeth.",
    "\"Have pity on me, my friends, have pity, for the hand of God has struck me.",
    "Why do you pursue me as God does? Will you never get enough of my flesh?",
    "\"Oh, that my words were recorded, that they were written on a scroll,",
    "that they were inscribed with an iron tool on lead, or engraved in rock forever!",
    "I know that my Redeemer lives, and that in the end he will stand upon the earth.",
    "And after my skin has been destroyed, yet in my flesh I will see God;",
    "I myself will see him with my own eyes--I, and not another. How my heart yearns within me!",
    "\"If you say, 'How we will hound him, since the root of the trouble lies in him,'",
    "you should fear the sword yourselves; for wrath will bring punishment by the sword, and then you will know that there is judgment.\""
  ],
  "Job-20": [
    "Then Zophar the Naamathite replied:",
    "\"My troubled thoughts prompt me to answer because I am greatly disturbed.",
    "I hear a rebuke that dishonors me, and my understanding inspires me to reply.",
    "\"Surely you know how it has been from of old, ever since man was placed on the earth,",
    "that the mirth of the wicked is brief, the joy of the godless lasts but a moment.",
    "Though his pride reaches to the heavens and his head touches the clouds,",
    "he will perish forever, like his own dung; those who have seen him will say, 'Where is he?'",
    "Like a dream he flies away, no more to be found, banished like a vision of the night.",
    "The eye that saw him will not see him again; his place will look on him no more.",
    "His children must make amends to the poor; his own hands must give back his wealth.",
    "The youthful vigor that fills his bones will lie with him in the dust.",
    "\"Though evil is sweet in his mouth and he hides it under his tongue,",
    "though he cannot bear to let it go and keeps it in his mouth,",
    "yet his food will turn sour in his stomach; it will become the venom of serpents within him.",
    "He will spit out the riches he swallowed; God will make his stomach vomit them up.",
    "He will suck the poison of serpents; the fangs of an adder will kill him.",
    "He will not enjoy the streams, the rivers flowing with honey and cream.",
    "What he toiled for he must give back uneaten; he will not enjoy the profit from his trading.",
    "For he has oppressed the poor and left them destitute; he has seized houses he did not build.",
    "\"Surely he will have no respite from his craving; he cannot save himself by his treasure.",
    "Nothing is left for him to devour; his prosperity will not endure.",
    "In the midst of his plenty, distress will overtake him; the full force of misery will come upon him.",
    "When he has filled his belly, God will vent his burning anger against him and rain down his blows upon him.",
    "Though he flees from an iron weapon, a bronze-tipped arrow pierces him.",
    "He pulls it out of his back, the gleaming point out of his liver. Terrors will come over him;",
    "total darkness lies in wait for his treasures. A fire unfanned will consume him and devour what is left in his tent.",
    "The heavens will expose his guilt; the earth will rise up against him.",
    "A flood will carry off his house, rushing waters on the day of God's wrath.",
    "Such is the fate God allots the wicked, the heritage appointed for them by God.\""
  ],
  "Job-21": [
    "Then Job replied:",
    "\"Listen carefully to my words; let this be the consolation you give me.",
    "Bear with me while I speak, and after I have spoken, mock on.",
    "\"Is my complaint directed to man? Why should I not be impatient?",
    "Look at me and be astonished; clap your hand over your mouth.",
    "When I think about this, I am terrified; trembling seizes my body.",
    "Why do the wicked live on, growing old and increasing in power?",
    "They see their children established around them, their offspring before their eyes.",
    "Their homes are safe and free from fear; the rod of God is not upon them.",
    "Their bulls never fail to breed; their cows calve and do not miscarry.",
    "They send forth their children as a flock; their little ones dance about.",
    "They sing to the music of tambourine and harp; they make merry to the sound of the flute.",
    "They spend their years in prosperity and go down to the grave in peace.",
    "Yet they say to God, 'Leave us alone! We have no desire to know your ways.",
    "Who is the Almighty, that we should serve him? What would we gain by praying to him?'",
    "But their prosperity is not in their own hands, so I stand aloof from the counsel of the wicked.",
    "\"Yet how often is the lamp of the wicked snuffed out? How often does calamity come upon them, the fate God allots in his anger?",
    "How often are they like straw before the wind, like chaff swept away by a gale?",
    "It is said,'God stores up a man's punishment for his sons.' Let him repay the man himself, so that he will know it!",
    "Let his own eyes see his destruction; let him drink of the wrath of the Almighty.",
    "For what does he care about the family he leaves behind when his allotted months come to an end?",
    "\"Can anyone teach knowledge to God, since he judges even the highest?",
    "One man dies in full vigor, completely secure and at ease,",
    "his body well nourished, his bones rich with marrow.",
    "Another man dies in bitterness of soul, never having enjoyed anything good.",
    "Side by side they lie in the dust, and worms cover them both.",
    "\"I know full well what you are thinking, the schemes by which you would wrong me.",
    "You say, 'Where now is the great man's house, the tents where wicked men lived?'",
    "Have you never questioned those who travel? Have you paid no regard to their accounts--",
    "that the evil man is spared from the day of calamity, that he is delivered from the day of wrath?",
    "Who denounces his conduct to his face? Who repays him for what he has done?",
    "He is carried to the grave, and watch is kept over his tomb.",
    "The soil in the valley is sweet to him; all men follow after him, and a countless throng goes before him.",
    "\"So how can you console me with your nonsense? Nothing is left of your answers but falsehood!\""
  ],
  "Job-22": [
    "Then Eliphaz the Temanite replied:",
    "\"Can a man be of benefit to God? Can even a wise man benefit him?",
    "What pleasure would it give the Almighty if you were righteous? What would he gain if your ways were blameless?",
    "\"Is it for your piety that he rebukes you and brings charges against you?",
    "Is not your wickedness great? Are not your sins endless?",
    "You demanded security from your brothers for no reason; you stripped men of their clothing, leaving them naked.",
    "You gave no water to the weary and you withheld food from the hungry,",
    "though you were a powerful man, owning land--an honored man, living on it.",
    "And you sent widows away empty-handed and broke the strength of the fatherless.",
    "That is why snares are all around you, why sudden peril terrifies you,",
    "why it is so dark you cannot see, and why a flood of water covers you.",
    "\"Is not God in the heights of heaven? And see how lofty are the highest stars!",
    "Yet you say, 'What does God know? Does he judge through such darkness?",
    "Thick clouds veil him, so he does not see us as he goes about in the vaulted heavens.'",
    "Will you keep to the old path that evil men have trod?",
    "They were carried off before their time, their foundations washed away by a flood.",
    "They said to God, 'Leave us alone! What can the Almighty do to us?'",
    "Yet it was he who filled their houses with good things, so I stand aloof from the counsel of the wicked.",
    "\"The righteous see their ruin and rejoice; the innocent mock them, saying,",
    "'Surely our foes are destroyed, and fire devours their wealth.'",
    "\"Submit to God and be at peace with him; in this way prosperity will come to you.",
    "Accept instruction from his mouth and lay up his words in your heart.",
    "If you return to the Almighty, you will be restored: If you remove wickedness far from your tent",
    "and assign your nuggets to the dust, your gold of Ophir to the rocks in the ravines,",
    "then the Almighty will be your gold, the choicest silver for you.",
    "Surely then you will find delight in the Almighty and will lift up your face to God.",
    "You will pray to him, and he will hear you, and you will fulfill your vows.",
    "What you decide on will be done, and light will shine on your ways.",
    "When men are brought low and you say, 'Lift them up!' then he will save the downcast.",
    "He will deliver even one who is not innocent, who will be delivered through the cleanness of your hands.\""
  ],
  "Job-23": [
    "Then Job replied:",
    "\"Even today my complaint is bitter; his hand is heavy in spite of my groaning.",
    "If only I knew where to find him; if only I could go to his dwelling!",
    "I would state my case before him and fill my mouth with arguments.",
    "I would find out what he would answer me, and consider what he would say.",
    "Would he oppose me with great power? No, he would not press charges against me.",
    "There an upright man could present his case before him, and I would be delivered forever from my judge.",
    "\"But if I go to the east, he is not there; if I go to the west, I do not find him.",
    "When he is at work in the north, I do not see him; when he turns to the south, I catch no glimpse of him.",
    "But he knows the way that I take; when he has tested me, I will come forth as gold.",
    "My feet have closely followed his steps; I have kept to his way without turning aside.",
    "I have not departed from the commands of his lips; I have treasured the words of his mouth more than my daily bread.",
    "\"But he stands alone, and who can oppose him? He does whatever he pleases.",
    "He carries out his decree against me, and many such plans he still has in store.",
    "That is why I am terrified before him; when I think of all this, I fear him.",
    "God has made my heart faint; the Almighty has terrified me.",
    "Yet I am not silenced by the darkness, by the thick darkness that covers my face."
  ],
  "Job-24": [
    "\"Why does the Almighty not set times for judgment? Why must those who know him look in vain for such days?",
    "Men move boundary stones; they pasture flocks they have stolen.",
    "They drive away the orphan's donkey and take the widow's ox in pledge.",
    "They thrust the needy from the path and force all the poor of the land into hiding.",
    "Like wild donkeys in the desert, the poor go about their labor of foraging food; the wasteland provides food for their children.",
    "They gather fodder in the fields and glean in the vineyards of the wicked.",
    "Lacking clothes, they spend the night naked; they have nothing to cover themselves in the cold.",
    "They are drenched by mountain rains and hug the rocks for lack of shelter.",
    "The fatherless child is snatched from the breast; the infant of the poor is seized for a debt.",
    "Lacking clothes, they go about naked; they carry the sheaves, but still go hungry.",
    "They crush olives among the terraces; they tread the winepresses, yet suffer thirst.",
    "The groans of the dying rise from the city, and the souls of the wounded cry out for help. But God charges no one with wrongdoing.",
    "\"There are those who rebel against the light, who do not know its ways or stay in its paths.",
    "When daylight is gone, the murderer rises up and kills the poor and needy; in the night he steals forth like a thief.",
    "The eye of the adulterer watches for dusk; he thinks, 'No eye will see me,' and he keeps his face concealed.",
    "In the dark, men break into houses, but by day they shut themselves in; they want nothing to do with the light.",
    "For all of them, deep darkness is their morning; they make friends with the terrors of darkness.",
    "\"Yet they are foam on the surface of the water; their portion of the land is cursed, so that no one goes to the vineyards.",
    "As heat and drought snatch away the melted snow, so the grave snatches away those who have sinned.",
    "The womb forgets them, the worm feasts on them; evil men are no longer remembered but are broken like a tree.",
    "They prey on the barren and childless woman, and to the widow show no kindness.",
    "But God drags away the mighty by his power; though they become established, they have no assurance of life.",
    "He may let them rest in a feeling of security, but his eyes are on their ways.",
    "For a little while they are exalted, and then they are gone; they are brought low and gathered up like all others; they are cut off like heads of grain.",
    "\"If this is not so, who can prove me false and reduce my words to nothing?\""
  ],
  "Job-25": [
    "Then Bildad the Shuhite replied:",
    "\"Dominion and awe belong to God; he establishes order in the heights of heaven.",
    "Can his forces be numbered? Upon whom does his light not rise?",
    "How then can a man be righteous before God? How can one born of woman be pure?",
    "If even the moon is not bright and the stars are not pure in his eyes,",
    "how much less man, who is but a maggot--a son of man, who is only a worm!\""
  ],
  "Job-26": [
    "Then Job replied:",
    "\"How you have helped the powerless! How you have saved the arm that is feeble!",
    "What advice you have offered to one without wisdom! And what great insight you have displayed!",
    "Who has helped you utter these words? And whose spirit spoke from your mouth?",
    "\"The dead are in deep anguish, those beneath the waters and all that live in them.",
    "Death is naked before God; Destruction lies uncovered.",
    "He spreads out the northern skies over empty space; he suspends the earth over nothing.",
    "He wraps up the waters in his clouds, yet the clouds do not burst under their weight.",
    "He covers the face of the full moon, spreading his clouds over it.",
    "He marks out the horizon on the face of the waters for a boundary between light and darkness.",
    "The pillars of the heavens quake, aghast at his rebuke.",
    "By his power he churned up the sea; by his wisdom he cut Rahab to pieces.",
    "By his breath the skies became fair; his hand pierced the gliding serpent.",
    "And these are but the outer fringe of his works; how faint the whisper we hear of him! Who then can understand the thunder of his power?\""
  ],
  "Job-27": [
    "And Job continued his discourse:",
    "\"As surely as God lives, who has denied me justice, the Almighty, who has made me taste bitterness of soul,",
    "as long as I have life within me, the breath of God in my nostrils,",
    "my lips will not speak wickedness, and my tongue will utter no deceit.",
    "I will never admit you are in the right; till I die, I will not deny my integrity.",
    "I will maintain my righteousness and never let go of it; my conscience will not reproach me as long as I live.",
    "\"May my enemies be like the wicked, my adversaries like the unjust!",
    "For what hope has the godless when he is cut off, when God takes away his life?",
    "Does God listen to his cry when distress comes upon him?",
    "Will he find delight in the Almighty? Will he call upon God at all times?",
    "\"I will teach you about the power of God; the ways of the Almighty I will not conceal.",
    "You have all seen this yourselves. Why then this meaningless talk?",
    "\"Here is the fate God allots to the wicked, the heritage a ruthless man receives from the Almighty:",
    "However many his children, their fate is the sword; his offspring will never have enough to eat.",
    "The plague will bury those who survive him, and their widows will not weep for them.",
    "Though he heaps up silver like dust and clothes like piles of clay,",
    "what he lays up the righteous will wear, and the innocent will divide his silver.",
    "The house he builds is like a moth's cocoon, like a hut made by a watchman.",
    "He lies down wealthy, but will do so no more; when he opens his eyes, all is gone.",
    "Terrors overtake him like a flood; a tempest snatches him away in the night.",
    "The east wind carries him off, and he is gone; it sweeps him out of his place.",
    "It hurls itself against him without mercy as he flees headlong from its power.",
    "It claps its hands in derision and hisses him out of his place."
  ],
  "Job-28": [
    "\"There is a mine for silver and a place where gold is refined.",
    "Iron is taken from the earth, and copper is smelted from ore.",
    "Man puts an end to the darkness; he searches the farthest recesses for ore in the blackest darkness.",
    "Far from where people dwell he cuts a shaft, in places forgotten by the foot of man; far from men he dangles and sways.",
    "The earth, from which food comes, is transformed below as by fire;",
    "sapphires come from its rocks, and its dust contains nuggets of gold.",
    "No bird of prey knows that hidden path, no falcon's eye has seen it.",
    "Proud beasts do not set foot on it, and no lion prowls there.",
    "Man's hand assaults the flinty rock and lays bare the roots of the mountains.",
    "He tunnels through the rock; his eyes see all its treasures.",
    "He searches the sources of the rivers and brings hidden things to light.",
    "\"But where can wisdom be found? Where does understanding dwell?",
    "Man does not comprehend its worth; it cannot be found in the land of the living.",
    "The deep says, 'It is not in me'; the sea says, 'It is not with me.'",
    "It cannot be bought with the finest gold, nor can its price be weighed in silver.",
    "It cannot be bought with the gold of Ophir, with precious onyx or sapphires.",
    "Neither gold nor crystal can compare with it, nor can it be had for jewels of gold.",
    "Coral and jasper are not worthy of mention; the price of wisdom is beyond rubies.",
    "The topaz of Cush cannot compare with it; it cannot be bought with pure gold.",
    "\"Where then does wisdom come from? Where does understanding dwell?",
    "It is hidden from the eyes of every living thing, concealed even from the birds of the air.",
    "Destruction and Death say, 'Only a rumor of it has reached our ears.'",
    "God understands the way to it and he alone knows where it dwells,",
    "for he views the ends of the earth and sees everything under the heavens.",
    "When he established the force of the wind and measured out the waters,",
    "when he made a decree for the rain and a path for the thunderstorm,",
    "then he looked at wisdom and appraised it; he confirmed it and tested it.",
    "And he said to man, 'The fear of the Lord--that is wisdom, and to shun evil is understanding.'\""
  ],
  "Job-29": [
    "Job continued his discourse:",
    "\"How I long for the months gone by, for the days when God watched over me,",
    "when his lamp shone upon my head and by his light I walked through darkness!",
    "Oh, for the days when I was in my prime, when God's intimate friendship blessed my house,",
    "when the Almighty was still with me and my children were around me,",
    "when my path was drenched with cream and the rock poured out for me streams of olive oil.",
    "\"When I went to the gate of the city and took my seat in the public square,",
    "the young men saw me and stepped aside and the old men rose to their feet;",
    "the chief men refrained from speaking and covered their mouths with their hands;",
    "the voices of the nobles were hushed, and their tongues stuck to the roof of their mouths.",
    "Whoever heard me spoke well of me, and those who saw me commended me,",
    "because I rescued the poor who cried for help, and the fatherless who had none to assist him.",
    "The man who was dying blessed me; I made the widow's heart sing.",
    "I put on righteousness as my clothing; justice was my robe and my turban.",
    "I was eyes to the blind and feet to the lame.",
    "I was a father to the needy; I took up the case of the stranger.",
    "I broke the fangs of the wicked and snatched the victims from their teeth.",
    "\"I thought, 'I will die in my own house, my days as numerous as the grains of sand.",
    "My roots will reach to the water, and the dew will lie all night on my branches.",
    "My glory will remain fresh in me, the bow ever new in my hand.'",
    "\"Men listened to me expectantly, waiting in silence for my counsel.",
    "After I had spoken, they spoke no more; my words fell gently on their ears.",
    "They waited for me as for showers and drank in my words as the spring rain.",
    "When I smiled at them, they scarcely believed it; the light of my face was precious to them.",
    "I chose the way for them and sat as their chief; I dwelt as a king among his troops; I was like one who comforts mourners."
  ],
  "Job-30": [
    "\"But now they mock me, men younger than I, whose fathers I would have disdained to put with my sheep dogs.",
    "Of what use was the strength of their hands to me, since their vigor had gone from them?",
    "Haggard from want and hunger, they roamed the parched land in desolate wastelands at night.",
    "In the brush they gathered salt herbs, and their food was the root of the broom tree.",
    "They were banished from their fellow men, shouted at as if they were thieves.",
    "They were forced to live in the dry stream beds, among the rocks and in holes in the ground.",
    "They brayed among the bushes and huddled in the undergrowth.",
    "A base and nameless brood, they were driven out of the land.",
    "\"And now their sons mock me in song; I have become a byword among them.",
    "They detest me and keep their distance; they do not hesitate to spit in my face.",
    "Now that God has unstrung my bow and afflicted me, they throw off restraint in my presence.",
    "On my right the tribe attacks; they lay snares for my feet, they build their siege ramps against me.",
    "They break up my road; they succeed in destroying me--without anyone's helping them.",
    "They advance as through a gaping breach; amid the ruins they come rolling in.",
    "Terrors overwhelm me; my dignity is driven away as by the wind, my safety vanishes like a cloud.",
    "\"And now my life ebbs away; days of suffering grip me.",
    "Night pierces my bones; my gnawing pains never rest.",
    "In his great power God becomes like clothing to me; he binds me like the neck of my garment.",
    "He throws me into the mud, and I am reduced to dust and ashes.",
    "\"I cry out to you, O God, but you do not answer; I stand up, but you merely look at me.",
    "You turn on me ruthlessly; with the might of your hand you attack me.",
    "You snatch me up and drive me before the wind; you toss me about in the storm.",
    "I know you will bring me down to death, to the place appointed for all the living.",
    "\"Surely no one lays a hand on a broken man when he cries for help in his distress.",
    "Have I not wept for those in trouble? Has not my soul grieved for the poor?",
    "Yet when I hoped for good, evil came; when I looked for light, then came darkness.",
    "The churning inside me never stops; days of suffering confront me.",
    "I go about blackened, but not by the sun; I stand up in the assembly and cry for help.",
    "I have become a brother of jackals, a companion of owls.",
    "My skin grows black and peels; my body burns with fever.",
    "My harp is tuned to mourning, and my flute to the sound of wailing."
  ],
  "Job-31": [
    "\"I made a covenant with my eyes not to look lustfully at a girl.",
    "For what is man's lot from God above, his heritage from the Almighty on high?",
    "Is it not ruin for the wicked, disaster for those who do wrong?",
    "Does he not see my ways and count my every step?",
    "\"If I have walked in falsehood or my foot has hurried after deceit--",
    "let God weigh me in honest scales and he will know that I am blameless--",
    "if my steps have turned from the path, if my heart has been led by my eyes, or if my hands have been defiled,",
    "then may others eat what I have sown, and may my crops be uprooted.",
    "\"If my heart has been enticed by a woman, or if I have lurked at my neighbor's door,",
    "then may my wife grind another man's grain, and may other men sleep with her.",
    "For that would have been shameful, a sin to be judged.",
    "It is a fire that burns to Destruction; it would have uprooted my harvest.",
    "\"If I have denied justice to my menservants and maidservants when they had a grievance against me,",
    "what will I do when God confronts me? What will I answer when called to account?",
    "Did not he who made me in the womb make them? Did not the same one form us both within our mothers?",
    "\"If I have denied the desires of the poor or let the eyes of the widow grow weary,",
    "if I have kept my bread to myself, not sharing it with the fatherless--",
    "but from my youth I reared him as would a father, and from my birth I guided the widow--",
    "if I have seen anyone perishing for lack of clothing, or a needy man without a garment,",
    "and his heart did not bless me for warming him with the fleece from my sheep,",
    "if I have raised my hand against the fatherless, knowing that I had influence in court,",
    "then let my arm fall from the shoulder, let it be broken off at the joint.",
    "For I dreaded destruction from God, and for fear of his splendor I could not do such things.",
    "\"If I have put my trust in gold or said to pure gold, 'You are my security,'",
    "if I have rejoiced over my great wealth, the fortune my hands had gained,",
    "if I have regarded the sun in its radiance or the moon moving in splendor,",
    "so that my heart was secretly enticed and my hand offered them a kiss of homage,",
    "then these also would be sins to be judged, for I would have been unfaithful to God on high.",
    "\"If I have rejoiced at my enemy's misfortune or gloated over the trouble that came to him--",
    "I have not allowed my mouth to sin by invoking a curse against his life--",
    "if the men of my household have never said, 'Who has not had his fill of Job's meat?'--",
    "but no stranger had to spend the night in the street, for my door was always open to the traveler--",
    "if I have concealed my sin as men do, by hiding my guilt in my heart",
    "because I so feared the crowd and so dreaded the contempt of the clans that I kept silent and would not go outside",
    "(\"Oh, that I had someone to hear me! I sign now my defense--let the Almighty answer me; let my accuser put his indictment in writing.",
    "Surely I would wear it on my shoulder, I would put it on like a crown.",
    "I would give him an account of my every step; like a prince I would approach him.)--",
    "\"if my land cries out against me and all its furrows are wet with tears,",
    "if I have devoured its yield without payment or broken the spirit of its tenants,",
    "then let briers come up instead of wheat and weeds instead of barley.\" The words of Job are ended."
  ],
  "Job-32": [
    "So these three men stopped answering Job, because he was righteous in his own eyes.",
    "But Elihu son of Barakel the Buzite, of the family of Ram, became very angry with Job for justifying himself rather than God.",
    "He was also angry with the three friends, because they had found no way to refute Job, and yet had condemned him.",
    "Now Elihu had waited before speaking to Job because they were older than he.",
    "But when he saw that the three men had nothing more to say, his anger was aroused.",
    "So Elihu son of Barakel the Buzite said: \"I am young in years, and you are old; that is why I was fearful, not daring to tell you what I know.",
    "I thought, 'Age should speak; advanced years should teach wisdom.'",
    "But it is the spirit in a man, the breath of the Almighty, that gives him understanding.",
    "It is not only the old who are wise, not only the aged who understand what is right.",
    "\"Therefore I say: Listen to me; I too will tell you what I know.",
    "I waited while you spoke, I listened to your reasoning; while you were searching for words,",
    "I gave you my full attention. But not one of you has proved Job wrong; none of you has answered his arguments.",
    "Do not say, 'We have found wisdom; let God refute him, not man.'",
    "But Job has not marshaled his words against me, and I will not answer him with your arguments.",
    "\"They are dismayed and have no more to say; words have failed them.",
    "Must I wait, now that they are silent, now that they stand there with no reply?",
    "I too will have my say; I too will tell what I know.",
    "For I am full of words, and the spirit within me compels me;",
    "inside I am like bottled-up wine, like new wineskins ready to burst.",
    "I must speak and find relief; I must open my lips and reply.",
    "I will show partiality to no one, nor will I flatter any man;",
    "for if I were skilled in flattery, my Maker would soon take me away."
  ],
  "Job-33": [
    "\"But now, Job, listen to my words; pay attention to everything I say.",
    "I am about to open my mouth; my words are on the tip of my tongue.",
    "My words come from an upright heart; my lips sincerely speak what I know.",
    "The Spirit of God has made me; the breath of the Almighty gives me life.",
    "Answer me then, if you can; prepare yourself and confront me.",
    "I am just like you before God; I too have been taken from clay.",
    "No fear of me should alarm you, nor should my hand be heavy upon you.",
    "\"But you have said in my hearing--I heard the very words--",
    "'I am pure and without sin; I am clean and free from guilt.",
    "Yet God has found fault with me; he considers me his enemy.",
    "He fastens my feet in shackles; he keeps close watch on all my paths.'",
    "\"But I tell you, in this you are not right, for God is greater than man.",
    "Why do you complain to him that he answers none of man's words?",
    "For God does speak--now one way, now another--though man may not perceive it.",
    "In a dream, in a vision of the night, when deep sleep falls on men as they slumber in their beds,",
    "he may speak in their ears and terrify them with warnings,",
    "to turn man from wrongdoing and keep him from pride,",
    "to preserve his soul from the pit, his life from perishing by the sword.",
    "Or a man may be chastened on a bed of pain with constant distress in his bones,",
    "so that his very being finds food repulsive and his soul loathes the choicest meal.",
    "His flesh wastes away to nothing, and his bones, once hidden, now stick out.",
    "His soul draws near to the pit, and his life to the messengers of death.",
    "\"Yet if there is an angel on his side as a mediator, one out of a thousand, to tell a man what is right for him,",
    "to be gracious to him and say, 'Spare him from going down to the pit; I have found a ransom for him'--",
    "then his flesh is renewed like a child's; it is restored as in the days of his youth.",
    "He prays to God and finds favor with him, he sees God's face and shouts for joy; he is restored by God to his righteous state.",
    "Then he comes to men and says, 'I sinned, and perverted what was right, but I did not get what I deserved.",
    "He redeemed my soul from going down to the pit, and I will live to enjoy the light.'",
    "\"God does all these things to a man--twice, even three times--",
    "to turn back his soul from the pit, that the light of life may shine on him.",
    "\"Pay attention, Job, and listen to me; be silent, and I will speak.",
    "If you have anything to say, answer me; speak up, for I want you to be cleared.",
    "But if not, then listen to me; be silent, and I will teach you wisdom.\""
  ],
  "Job-34": [
    "Then Elihu said:",
    "\"Hear my words, you wise men; listen to me, you men of learning.",
    "For the ear tests words as the tongue tastes food.",
    "Let us discern for ourselves what is right; let us learn together what is good.",
    "\"Job says, 'I am innocent, but God denies me justice.",
    "Although I am right, I am considered a liar; although I am guiltless, his arrow inflicts an incurable wound.'",
    "What man is like Job, who drinks scorn like water?",
    "He keeps company with evildoers; he associates with wicked men.",
    "For he says, 'It profits a man nothing when he tries to please God.'",
    "\"So listen to me, you men of understanding. Far be it from God to do evil, from the Almighty to do wrong.",
    "He repays a man for what he has done; he brings upon him what his conduct deserves.",
    "It is unthinkable that God would do wrong, that the Almighty would pervert justice.",
    "Who appointed him over the earth? Who put him in charge of the whole world?",
    "If it were his intention and he withdrew his spirit and breath,",
    "all mankind would perish together and man would return to the dust.",
    "\"If you have understanding, hear this; listen to what I say.",
    "Can he who hates justice govern? Will you condemn the just and mighty One?",
    "Is he not the One who says to kings, 'You are worthless,' and to nobles, 'You are wicked,'",
    "who shows no partiality to princes and does not favor the rich over the poor, for they are all the work of his hands?",
    "They die in an instant, in the middle of the night; the people are shaken and they pass away; the mighty are removed without human hand.",
    "\"His eyes are on the ways of men; he sees their every step.",
    "There is no dark place, no deep shadow, where evildoers can hide.",
    "God has no need to examine men further, that they should come before him for judgment.",
    "Without inquiry he shatters the mighty and sets up others in their place.",
    "Because he takes note of their deeds, he overthrows them in the night and they are crushed.",
    "He punishes them for their wickedness where everyone can see them,",
    "because they turned from following him and had no regard for any of his ways.",
    "They caused the cry of the poor to come before him, so that he heard the cry of the needy.",
    "But if he remains silent, who can condemn him? If he hides his face, who can see him? Yet he is over man and nation alike,",
    "to keep a godless man from ruling, from laying snares for the people.",
    "\"Suppose a man says to God, 'I am guilty but will offend no more.",
    "Teach me what I cannot see; if I have done wrong, I will not do so again.'",
    "Should God then reward you on your terms, when you refuse to repent? You must decide, not I; so tell me what you know.",
    "\"Men of understanding declare, wise men who hear me say to me,",
    "'Job speaks without knowledge; his words lack insight.'",
    "Oh, that Job might be tested to the utmost for answering like a wicked man!",
    "To his sin he adds rebellion; scornfully he claps his hands among us and multiplies his words against God.\""
  ],
  "Job-35": [
    "Then Elihu said:",
    "\"Do you think this is just? You say, 'I will be cleared by God.'",
    "Yet you ask him, 'What profit is it to me, and what do I gain by not sinning?'",
    "\"I would like to reply to you and to your friends with you.",
    "Look up at the heavens and see; gaze at the clouds so high above you.",
    "If you sin, how does that affect him? If your sins are many, what does that do to him?",
    "If you are righteous, what do you give to him, or what does he receive from your hand?",
    "Your wickedness affects only a man like yourself, and your righteousness only the sons of men.",
    "\"Men cry out under a load of oppression; they plead for relief from the arm of the powerful.",
    "But no one says, 'Where is God my Maker, who gives songs in the night,",
    "who teaches more to us than to the beasts of the earth and makes us wiser than the birds of the air?'",
    "He does not answer when men cry out because of the arrogance of the wicked.",
    "Indeed, God does not listen to their empty plea; the Almighty pays no attention to it.",
    "How much less, then, will he listen when you say that you do not see him, that your case is before him and you must wait for him,",
    "and further, that his anger never punishes and he does not take the least notice of wickedness.",
    "So Job opens his mouth with empty talk; without knowledge he multiplies words.\""
  ],
  "Job-36": [
    "Elihu continued:",
    "\"Bear with me a little longer and I will show you that there is more to be said in God's behalf.",
    "I get my knowledge from afar; I will ascribe justice to my Maker.",
    "Be assured that my words are not false; one perfect in knowledge is with you.",
    "\"God is mighty, but does not despise men; he is mighty, and firm in his purpose.",
    "He does not keep the wicked alive but gives the afflicted their rights.",
    "He does not take his eyes off the righteous; he enthrones them with kings and exalts them forever.",
    "But if men are bound in chains, held fast by cords of affliction,",
    "he tells them what they have done--that they have sinned arrogantly.",
    "He makes them listen to correction and commands them to repent of their evil.",
    "If they obey and serve him, they will spend the rest of their days in prosperity and their years in contentment.",
    "But if they do not listen, they will perish by the sword and die without knowledge.",
    "\"The godless in heart harbor resentment; even when he fetters them, they do not cry for help.",
    "They die in their youth, among male prostitutes of the shrines.",
    "But those who suffer he delivers in their suffering; he speaks to them in their affliction.",
    "\"He is wooing you from the jaws of distress to a spacious place free from restriction, to the comfort of your table laden with choice food.",
    "But now you are laden with the judgment due the wicked; judgment and justice have taken hold of you.",
    "Be careful that no one entices you by riches; do not let a large bribe turn you aside.",
    "Would your wealth or even all your mighty efforts sustain you so you would not be in distress?",
    "Do not long for the night, to drag people away from their homes.",
    "Beware of turning to evil, which you seem to prefer to affliction.",
    "\"God is exalted in his power. Who is a teacher like him?",
    "Who has prescribed his ways for him, or said to him, 'You have done wrong'?",
    "Remember to extol his work, which men have praised in song.",
    "All mankind has seen it; men gaze on it from afar.",
    "How great is God--beyond our understanding! The number of his years is past finding out.",
    "\"He draws up the drops of water, which distill as rain to the streams;",
    "the clouds pour down their moisture and abundant showers fall on mankind.",
    "Who can understand how he spreads out the clouds, how he thunders from his pavilion?",
    "See how he scatters his lightning about him, bathing the depths of the sea.",
    "This is the way he governs the nations and provides food in abundance.",
    "He fills his hands with lightning and commands it to strike its mark.",
    "His thunder announces the coming storm; even the cattle make known its approach."
  ],
  "Job-37": [
    "\"At this my heart pounds and leaps from its place.",
    "Listen! Listen to the roar of his voice, to the rumbling that comes from his mouth.",
    "He unleashes his lightning beneath the whole heaven and sends it to the ends of the earth.",
    "After that comes the sound of his roar; he thunders with his majestic voice. When his voice resounds, he holds nothing back.",
    "God's voice thunders in marvelous ways; he does great things beyond our understanding.",
    "He says to the snow, 'Fall on the earth,' and to the rain shower, 'Be a mighty downpour.'",
    "So that all men he has made may know his work, he stops every man from his labor.",
    "The animals take cover; they remain in their dens.",
    "The tempest comes out from its chamber, the cold from the driving winds.",
    "The breath of God produces ice, and the broad waters become frozen.",
    "He loads the clouds with moisture; he scatters his lightning through them.",
    "At his direction they swirl around over the face of the whole earth to do whatever he commands them.",
    "He brings the clouds to punish men, or to water his earth and show his love.",
    "\"Listen to this, Job; stop and consider God's wonders.",
    "Do you know how God controls the clouds and makes his lightning flash?",
    "Do you know how the clouds hang poised, those wonders of him who is perfect in knowledge?",
    "You who swelter in your clothes when the land lies hushed under the south wind,",
    "can you join him in spreading out the skies, hard as a mirror of cast bronze?",
    "\"Tell us what we should say to him; we cannot draw up our case because of our darkness.",
    "Should he be told that I want to speak? Would any man ask to be swallowed up?",
    "Now no one can look at the sun, bright as it is in the skies after the wind has swept them clean.",
    "Out of the north he comes in golden splendor; God comes in awesome majesty.",
    "The Almighty is beyond our reach and exalted in power; in his justice and great righteousness, he does not oppress.",
    "Therefore, men revere him, for does he not have regard for all the wise in heart?\""
  ],
  "Job-38": [
    "Then the LORD answered Job out of the storm. He said:",
    "\"Who is this that darkens my counsel with words without knowledge?",
    "Brace yourself like a man; I will question you, and you shall answer me.",
    "\"Where were you when I laid the earth's foundation? Tell me, if you understand.",
    "Who marked off its dimensions? Surely you know! Who stretched a measuring line across it?",
    "On what were its footings set, or who laid its cornerstone--",
    "while the morning stars sang together and all the angels shouted for joy?",
    "\"Who shut up the sea behind doors when it burst forth from the womb,",
    "when I made the clouds its garment and wrapped it in thick darkness,",
    "when I fixed limits for it and set its doors and bars in place,",
    "when I said, 'This far you may come and no farther; here is where your proud waves halt'?",
    "\"Have you ever given orders to the morning, or shown the dawn its place,",
    "that it might take the earth by the edges and shake the wicked out of it?",
    "The earth takes shape like clay under a seal; its features stand out like those of a garment.",
    "The wicked are denied their light, and their upraised arm is broken.",
    "\"Have you journeyed to the springs of the sea or walked in the recesses of the deep?",
    "Have the gates of death been shown to you? Have you seen the gates of the shadow of death?",
    "Have you comprehended the vast expanses of the earth? Tell me, if you know all this.",
    "\"What is the way to the abode of light? And where does darkness reside?",
    "Can you take them to their places? Do you know the paths to their dwellings?",
    "Surely you know, for you were already born! You have lived so many years!",
    "\"Have you entered the storehouses of the snow or seen the storehouses of the hail,",
    "which I reserve for times of trouble, for days of war and battle?",
    "What is the way to the place where the lightning is dispersed, or the place where the east winds are scattered over the earth?",
    "Who cuts a channel for the torrents of rain, and a path for the thunderstorm,",
    "to water a land where no man lives, a desert with no one in it,",
    "to satisfy a desolate wasteland and make it sprout with grass?",
    "Does the rain have a father? Who fathers the drops of dew?",
    "From whose womb comes the ice? Who gives birth to the frost from the heavens",
    "when the waters become hard as stone, when the surface of the deep is frozen?",
    "\"Can you bind the beautiful Pleiades? Can you loose the cords of Orion?",
    "Can you bring forth the constellations in their seasons or lead out the Bear with its cubs?",
    "Do you know the laws of the heavens? Can you set up God'sdominion over the earth?",
    "\"Can you raise your voice to the clouds and cover yourself with a flood of water?",
    "Do you send the lightning bolts on their way? Do they report to you, 'Here we are'?",
    "Who endowed the heart with wisdom or gave understanding to the mind?",
    "Who has the wisdom to count the clouds? Who can tip over the water jars of the heavens",
    "when the dust becomes hard and the clods of earth stick together?",
    "\"Do you hunt the prey for the lioness and satisfy the hunger of the lions",
    "when they crouch in their dens or lie in wait in a thicket?",
    "Who provides food for the raven when its young cry out to God and wander about for lack of food?"
  ],
  "Job-39": [
    "\"Do you know when the mountain goats give birth? Do you watch when the doe bears her fawn?",
    "Do you count the months till they bear? Do you know the time they give birth?",
    "They crouch down and bring forth their young; their labor pains are ended.",
    "Their young thrive and grow strong in the wilds; they leave and do not return.",
    "\"Who let the wild donkey go free? Who untied his ropes?",
    "I gave him the wasteland as his home, the salt flats as his habitat.",
    "He laughs at the commotion in the town; he does not hear a driver's shout.",
    "He ranges the hills for his pasture and searches for any green thing.",
    "\"Will the wild ox consent to serve you? Will he stay by your manger at night?",
    "Can you hold him to the furrow with a harness? Will he till the valleys behind you?",
    "Will you rely on him for his great strength? Will you leave your heavy work to him?",
    "Can you trust him to bring in your grain and gather it to your threshing floor?",
    "\"The wings of the ostrich flap joyfully, but they cannot compare with the pinions and feathers of the stork.",
    "She lays her eggs on the ground and lets them warm in the sand,",
    "unmindful that a foot may crush them, that some wild animal may trample them.",
    "She treats her young harshly, as if they were not hers; she cares not that her labor was in vain,",
    "for God did not endow her with wisdom or give her a share of good sense.",
    "Yet when she spreads her feathers to run, she laughs at horse and rider.",
    "\"Do you give the horse his strength or clothe his neck with a flowing mane?",
    "Do you make him leap like a locust, striking terror with his proud snorting?",
    "He paws fiercely, rejoicing in his strength, and charges into the fray.",
    "He laughs at fear, afraid of nothing; he does not shy away from the sword.",
    "The quiver rattles against his side, along with the flashing spear and lance.",
    "In frenzied excitement he eats up the ground; he cannot stand still when the trumpet sounds.",
    "At the blast of the trumpet he snorts, 'Aha!' He catches the scent of battle from afar, the shout of commanders and the battle cry.",
    "\"Does the hawk take flight by your wisdom and spread his wings toward the south?",
    "Does the eagle soar at your command and build his nest on high?",
    "He dwells on a cliff and stays there at night; a rocky crag is his stronghold.",
    "From there he seeks out his food; his eyes detect it from afar.",
    "His young ones feast on blood, and where the slain are, there is he.\""
  ],
  "Job-40": [
    "The LORD said to Job:",
    "\"Will the one who contends with the Almighty correct him? Let him who accuses God answer him!\"",
    "Then Job answered the LORD:",
    "\"I am unworthy--how can I reply to you? I put my hand over my mouth.",
    "I spoke once, but I have no answer--twice, but I will say no more.\"",
    "Then the LORD spoke to Job out of the storm:",
    "\"Brace yourself like a man; I will question you, and you shall answer me.",
    "\"Would you discredit my justice? Would you condemn me to justify yourself?",
    "Do you have an arm like God's, and can your voice thunder like his?",
    "Then adorn yourself with glory and splendor, and clothe yourself in honor and majesty.",
    "Unleash the fury of your wrath, look at every proud man and bring him low,",
    "look at every proud man and humble him, crush the wicked where they stand.",
    "Bury them all in the dust together; shroud their faces in the grave.",
    "Then I myself will admit to you that your own right hand can save you.",
    "\"Look at the behemoth, which I made along with you and which feeds on grass like an ox.",
    "What strength he has in his loins, what power in the muscles of his belly!",
    "His tail sways like a cedar; the sinews of his thighs are close-knit.",
    "His bones are tubes of bronze, his limbs like rods of iron.",
    "He ranks first among the works of God, yet his Maker can approach him with his sword.",
    "The hills bring him their produce, and all the wild animals play nearby.",
    "Under the lotus plants he lies, hidden among the reeds in the marsh.",
    "The lotuses conceal him in their shadow; the poplars by the stream surround him.",
    "When the river rages, he is not alarmed; he is secure, though the Jordan should surge against his mouth.",
    "Can anyone capture him by the eyes, or trap him and pierce his nose?"
  ],
  "Job-41": [
    "\"Can you pull in the leviathan with a fishhook or tie down his tongue with a rope?",
    "Can you put a cord through his nose or pierce his jaw with a hook?",
    "Will he keep begging you for mercy? Will he speak to you with gentle words?",
    "Will he make an agreement with you for you to take him as your slave for life?",
    "Can you make a pet of him like a bird or put him on a leash for your girls?",
    "Will traders barter for him? Will they divide him up among the merchants?",
    "Can you fill his hide with harpoons or his head with fishing spears?",
    "If you lay a hand on him, you will remember the struggle and never do it again!",
    "Any hope of subduing him is false; the mere sight of him is overpowering.",
    "No one is fierce enough to rouse him. Who then is able to stand against me?",
    "Who has a claim against me that I must pay? Everything under heaven belongs to me.",
    "\"I will not fail to speak of his limbs, his strength and his graceful form.",
    "Who can strip off his outer coat? Who would approach him with a bridle?",
    "Who dares open the doors of his mouth, ringed about with his fearsome teeth?",
    "His back has rows of shields tightly sealed together;",
    "each is so close to the next that no air can pass between.",
    "They are joined fast to one another; they cling together and cannot be parted.",
    "His snorting throws out flashes of light; his eyes are like the rays of dawn.",
    "Firebrands stream from his mouth; sparks of fire shoot out.",
    "Smoke pours from his nostrils as from a boiling pot over a fire of reeds.",
    "His breath sets coals ablaze, and flames dart from his mouth.",
    "Strength resides in his neck; dismay goes before him.",
    "The folds of his flesh are tightly joined; they are firm and immovable.",
    "His chest is hard as rock, hard as a lower millstone.",
    "When he rises up, the mighty are terrified; they retreat before his thrashing.",
    "The sword that reaches him has no effect, nor does the spear or the dart or the javelin.",
    "Iron he treats like straw and bronze like rotten wood.",
    "Arrows do not make him flee; slingstones are like chaff to him.",
    "A club seems to him but a piece of straw; he laughs at the rattling of the lance.",
    "His undersides are jagged potsherds, leaving a trail in the mud like a threshing sledge.",
    "He makes the depths churn like a boiling caldron and stirs up the sea like a pot of ointment.",
    "Behind him he leaves a glistening wake; one would think the deep had white hair.",
    "Nothing on earth is his equal--a creature without fear.",
    "He looks down on all that are haughty; he is king over all that are proud.\""
  ],
  "Job-42": [
    "Then Job replied to the LORD:",
    "\"I know that you can do all things; no plan of yours can be thwarted.",
    "You asked,'Who is this that obscures my counsel without knowledge?' Surely I spoke of things I did not understand, things too wonderful for me to know.",
    "\"You said,'Listen now, and I will speak; I will question you, and you shall answer me.'",
    "My ears had heard of you but now my eyes have seen you.",
    "Therefore I despise myself and repent in dust and ashes.\"",
    "After the LORD had said these things to Job, he said to Eliphaz the Temanite, \"I am angry with you and your two friends, because you have not spoken of me what is right, as my servant Job has.",
    "So now take seven bulls and seven rams and go to my servant Job and sacrifice a burnt offering for yourselves. My servant Job will pray for you, and I will accept his prayer and not deal with you according to your folly. You have not spoken of me what is right, as my servant Job has.\"",
    "So Eliphaz the Temanite, Bildad the Shuhite and Zophar the Naamathite did what the LORD told them; and the LORD accepted Job's prayer.",
    "After Job had prayed for his friends, the LORD made him prosperous again and gave him twice as much as he had before.",
    "All his brothers and sisters and everyone who had known him before came and ate with him in his house. They comforted and consoled him over all the trouble the LORD had brought upon him, and each one gave him a piece of silver and a gold ring.",
    "The LORD blessed the latter part of Job's life more than the first. He had fourteen thousand sheep, six thousand camels, a thousand yoke of oxen and a thousand donkeys.",
    "And he also had seven sons and three daughters.",
    "The first daughter he named Jemimah, the second Keziah and the third Keren-Happuch.",
    "Nowhere in all the land were there found women as beautiful as Job's daughters, and their father granted them an inheritance along with their brothers.",
    "After this, Job lived a hundred and forty years; he saw his children and their children to the fourth generation.",
    "And so he died, old and full of years."
  ]
}