{
  "Joel-1": [
    "The word of the LORD that came to Joel son of Pethuel.",
    "Hear this, you elders; listen, all who live in the land. Has anything like this ever happened in your days or in the days of your forefathers?",
    "Tell it to your children, and let your children tell it to their children, and their children to the next generation.",
    "What the locust swarm has left the great locusts have eaten; what the great locusts have left the young locusts have eaten; what the young locusts have left other locusts have eaten.",
    "Wake up, you drunkards, and weep! Wail, all you drinkers of wine; wail because of the new wine, for it has been snatched from your lips.",
    "A nation has invaded my land, powerful and without number; it has the teeth of a lion, the fangs of a lioness.",
    "It has laid waste my vines and ruined my fig trees. It has stripped off their bark and thrown it away, leaving their branches white.",
    "Mourn like a virgin in sackcloth grieving for the husband of her youth.",
    "Grain offerings and drink offerings are cut off from the house of the LORD. The priests are in mourning, those who minister before the LORD.",
    "The fields are ruined, the ground is dried up; the grain is destroyed, the new wine is dried up, the oil fails.",
    "Despair, you farmers, wail, you vine growers; grieve for the wheat and the barley, because the harvest of the field is destroyed.",
    "The vine is dried up and the fig tree is withered; the pomegranate, the palm and the apple tree--all the trees of the field--are dried up. Surely the joy of mankind is withered away.",
    "Put on sackcloth, O priests, and mourn; wail, you who minister before the altar. Come, spend the night in sackcloth, you who minister before my God; for the grain offerings and drink offerings are withheld from the house of your God.",
    "Declare a holy fast; call a sacred assembly. Summon the elders and all who live in the land to the house of the LORD your God, and cry out to the LORD.",
    "Alas for that day! For the day of the LORD is near; it will come like destruction from the Almighty.",
    "Has not the food been cut off before our very eyes--joy and gladness from the house of our God?",
    "The seeds are shriveled beneath the clods. The storehouses are in ruins, the granaries have been broken down, for the grain has dried up.",
    "How the cattle moan! The herds mill about because they have no pasture; even the flocks of sheep are suffering.",
    "To you, O LORD, I call, for fire has devoured the open pastures and flames have burned up all the trees of the field.",
    "Even the wild animals pant for you; the streams of water have dried up and fire has devoured the open pastures."
  ],
  "Joel-2": [
    "Blow the trumpet in Zion; sound the alarm on my holy hill. Let all who live in the land tremble, for the day of the LORD is coming. It is close at hand--",
    "a day of darkness and gloom, a day of clouds and blackness. Like dawn spreading across the mountains a large and mighty army comes, such as never was of old nor ever will be in ages to come.",
    "Before them fire devours, behind them a flame blazes. Before them the land is like the garden of Eden, behind them, a desert waste--nothing escapes them.",
    "They have the appearance of horses; they gallop along like cavalry.",
    "With a noise like that of chariots they leap over the mountaintops, like a crackling fire consuming stubble, like a mighty army drawn up for battle.",
    "At the sight of them, nations are in anguish; every face turns pale.",
    "They charge like warriors; they scale walls like soldiers. They all march in line, not swerving from their course.",
    "They do not jostle each other; each marches straight ahead. They plunge through defenses without breaking ranks.",
    "They rush upon the city; they run along the wall. They climb into the houses; like thieves they enter through the windows.",
    "Before them the earth shakes, the sky trembles, the sun and moon are darkened, and the stars no longer shine.",
    "The LORD thunders at the head of his army; his forces are beyond number, and mighty are those who obey his command. The day of the LORD is great; it is dreadful. Who can endure it?",
    "'Even now,' declares the LORD, 'return to me with all your heart, with fasting and weeping and mourning.'",
    "Rend your heart and not your garments. Return to the LORD your God, for he is gracious and compassionate, slow to anger and abounding in love, and he relents from sending calamity.",
    "Who knows? He may turn and have pity and leave behind a blessing--grain offerings and drink offerings for the LORD your God.",
    "Blow the trumpet in Zion, declare a holy fast, call a sacred assembly.",
    "Gather the people, consecrate the assembly; bring together the elders, gather the children, those nursing at the breast. Let the bridegroom leave his room and the bride her chamber.",
    "Let the priests, who minister before the LORD, weep between the temple porch and the altar. Let them say, 'Spare your people, O LORD. Do not make your inheritance an object of scorn, a byword among the nations. Why should they say among the peoples, 'Where is their God?''",
    "Then the LORD will be jealous for his land and take pity on his people.",
    "The LORD will reply to them: 'I am sending you grain, new wine and oil, enough to satisfy you fully; never again will I make you an object of scorn to the nations.",
    "'I will drive the northern army far from you, pushing it into a parched and barren land, with its front columns going into the eastern sea and those in the rear into the western sea. And its stench will go up; its smell will rise.' Surely he has done great things.",
    "Be not afraid, O land; be glad and rejoice. Surely the LORD has done great things.",
    "Be not afraid, O wild animals, for the open pastures are becoming green. The trees are bearing their fruit; the fig tree and the vine yield their riches.",
    "Be glad, O people of Zion, rejoice in the LORD your God, for he has given you the autumn rains in righteousness. He sends you abundant showers, both autumn and spring rains, as before.",
    "The threshing floors will be filled with grain; the vats will overflow with new wine and oil.",
    "'I will repay you for the years the locusts have eaten--the great locust and the young locust, the other locusts and the locust swarm--my great army that I sent among you.",
    "You will have plenty to eat, until you are full, and you will praise the name of the LORD your God, who has worked wonders for you; never again will my people be shamed.",
    "Then you will know that I am in Israel, that I am the LORD your God, and that there is no other; never again will my people be shamed.",
    "'And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy, your old men will dream dreams, your young men will see visions.",
    "Even on my servants, both men and women, I will pour out my Spirit in those days.",
    "I will show wonders in the heavens and on the earth, blood and fire and billows of smoke.",
    "The sun will be turned to darkness and the moon to blood before the coming of the great and dreadful day of the LORD.",
    "And everyone who calls on the name of the LORD will be saved; for on Mount Zion and in Jerusalem there will be deliverance, as the LORD has said, among the survivors whom the LORD calls."
  ],
  "Joel-3": [
    "'In those days and at that time, when I restore the fortunes of Judah and Jerusalem,",
    "I will gather all nations and bring them down to the Valley of Jehoshaphat. There I will enter into judgment against them concerning my inheritance, my people Israel, for they scattered my people among the nations and divided up my land.",
    "They cast lots for my people and traded boys for prostitutes; they sold girls for wine that they might drink.",
    "'Now what have you against me, O Tyre and Sidon and all you regions of Philistia? Are you repaying me for something I have done? If you are paying me back, I will swiftly and speedily return on your own heads what you have done.",
    "For you took my silver and my gold and carried off my finest treasures to your temples.",
    "You sold the people of Judah and Jerusalem to the Greeks, that you might send them far from their homeland.",
    "'See, I am going to rouse them out of the places to which you sold them, and I will return on your own heads what you have done.",
    "I will sell your sons and daughters to the people of Judah, and they will sell them to the Sabeans, a nation far away.' The LORD has spoken.",
    "Proclaim this among the nations: Prepare for war! Rouse the warriors! Let all the fighting men draw near and attack.",
    "Beat your plowshares into swords and your pruning hooks into spears. Let the weakling say, 'I am strong!'",
    "Come quickly, all you nations from every side, and assemble there. Bring down your warriors, O LORD!",
    "'Let the nations be roused; let them advance into the Valley of Jehoshaphat, for there I will sit to judge all the nations on every side.",
    "Swing the sickle, for the harvest is ripe. Come, trample the grapes, for the winepress is full and the vats overflow--so great is their wickedness!'",
    "Multitudes, multitudes in the valley of decision! For the day of the LORD is near in the valley of decision.",
    "The sun and moon will be darkened, and the stars no longer shine.",
    "The LORD will roar from Zion and thunder from Jerusalem; the earth and the sky will tremble. But the LORD will be a refuge for his people, a stronghold for the people of Israel.",
    "'Then you will know that I, the LORD your God, dwell in Zion, my holy hill. Jerusalem will be holy; never again will foreigners invade her.",
    "'In that day the mountains will drip new wine, and the hills will flow with milk; all the ravines of Judah will run with water. A fountain will flow out of the LORD'S house and will water the valley of acacias.",
    "But Egypt will be desolate, Edom a desert waste, because of violence done to the people of Judah, in whose land they shed innocent blood.",
    "Judah will be inhabited forever and Jerusalem through all generations.",
    "Their bloodguilt, which I have not pardoned, I will pardon.' The LORD dwells in Zion!"
  ]
}