{
  "Peter1-1": [
    "Peter, an apostle of Jesus Christ, To God's elect, strangers in the world, scattered throughout Pontus, Galatia, Cappadocia, Asia and Bithynia,",
    "who have been chosen according to the foreknowledge of God the Father, through the sanctifying work of the Spirit, for obedience to Jesus Christ and sprinkling by his blood: Grace and peace be yours in abundance.",
    "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead,",
    "and into an inheritance that can never perish, spoil or fade--kept in heaven for you,",
    "who through faith are shielded by God's power until the coming of the salvation that is ready to be revealed in the last time.",
    "In this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials.",
    "These have come so that your faith--of greater worth than gold, which perishes even though refined by fire--may be proved genuine and may result in praise, glory and honor when Jesus Christ is revealed.",
    "Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy,",
    "for you are receiving the goal of your faith, the salvation of your souls.",
    "Concerning this salvation, the prophets, who spoke of the grace that was to come to you, searched intently and with the greatest care,",
    "trying to find out the time and circumstances to which the Spirit of Christ in them was pointing when he predicted the sufferings of Christ and the glories that would follow.",
    "It was revealed to them that they were not serving themselves but you, when they spoke of the things that have now been told you by those who have preached the gospel to you by the Holy Spirit sent from heaven. Even angels long to look into these things.",
    "Therefore, prepare your minds for action; be self-controlled; set your hope fully on the grace to be given you when Jesus Christ is revealed.",
    "As obedient children, do not conform to the evil desires you had when you lived in ignorance.",
    "But just as he who called you is holy, so be holy in all you do;",
    "for it is written: \"Be holy, because I am holy.\"",
    "Since you call on a Father who judges each man's work impartially, live your lives as strangers here in reverent fear.",
    "For you know that it was not with perishable things such as silver or gold that you were redeemed from the empty way of life handed down to you from your forefathers,",
    "but with the precious blood of Christ, a lamb without blemish or defect.",
    "He was chosen before the creation of the world, but was revealed in these last times for your sake.",
    "Through him you believe in God, who raised him from the dead and glorified him, and so your faith and hope are in God.",
    "Now that you have purified yourselves by obeying the truth so that you have sincere love for your brothers, love one another deeply, from the heart.",
    "For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God.",
    "For, \"All men are like grass, and all their glory is like the flowers of the field; the grass withers and the flowers fall,",
    "but the word of the Lord stands forever.\" And this is the word that was preached to you."
  ],
  "Peter1-2": [
    "Therefore, rid yourselves of all malice and all deceit, hypocrisy, envy, and slander of every kind.",
    "Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation,",
    "now that you have tasted that the Lord is good.",
    "As you come to him, the living Stone--rejected by men but chosen by God and precious to him--",
    "you also, like living stones, are being built into a spiritual house to be a holy priesthood, offering spiritual sacrifices acceptable to God through Jesus Christ.",
    "For in Scripture it says: \"See, I lay a stone in Zion, a chosen and precious cornerstone, and the one who trusts in him will never be put to shame.\"",
    "Now to you who believe, this stone is precious. But to those who do not believe, \"The stone the builders rejected has become the capstone,\"",
    "and, \"A stone that causes men to stumble and a rock that makes them fall.\" They stumble because they disobey the message--which is also what they were destined for.",
    "But you are a chosen people, a royal priesthood, a holy nation, a people belonging to God, that you may declare the praises of him who called you out of darkness into his wonderful light.",
    "Once you were not a people, but now you are the people of God; once you had not received mercy, but now you have received mercy.",
    "Dear friends, I urge you, as aliens and strangers in the world, to abstain from sinful desires, which war against your soul.",
    "Live such good lives among the pagans that, though they accuse you of doing wrong, they may see your good deeds and glorify God on the day he visits us.",
    "Submit yourselves for the Lord's sake to every authority instituted among men: whether to the king, as the supreme authority,",
    "or to governors, who are sent by him to punish those who do wrong and to commend those who do right.",
    "For it is God's will that by doing good you should silence the ignorant talk of foolish men.",
    "Live as free men, but do not use your freedom as a cover-up for evil; live as servants of God.",
    "Show proper respect to everyone: Love the brotherhood of believers, fear God, honor the king.",
    "Slaves, submit yourselves to your masters with all respect, not only to those who are good and considerate, but also to those who are harsh.",
    "For it is commendable if a man bears up under the pain of unjust suffering because he is conscious of God.",
    "But how is it to your credit if you receive a beating for doing wrong and endure it? But if you suffer for doing good and you endure it, this is commendable before God.",
    "To this you were called, because Christ suffered for you, leaving you an example, that you should follow in his steps.",
    "\"He committed no sin, and no deceit was found in his mouth.\"",
    "When they hurled their insults at him, he did not retaliate; when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly.",
    "He himself bore our sins in his body on the tree, so that we might die to sins and live for righteousness; by his wounds you have been healed.",
    "For you were like sheep going astray, but now you have returned to the Shepherd and Overseer of your souls."
  ],
  "Peter1-3": [
    "Wives, in the same way be submissive to your husbands so that, if any of them do not believe the word, they may be won over without words by the behavior of their wives,",
    "when they see the purity and reverence of your lives.",
    "Your beauty should not come from outward adornment, such as braided hair and the wearing of gold jewelry and fine clothes.",
    "Instead, it should be that of your inner self, the unfading beauty of a gentle and quiet spirit, which is of great worth in God's sight.",
    "For this is the way the holy women of the past who put their hope in God used to make themselves beautiful. They were submissive to their own husbands,",
    "like Sarah, who obeyed Abraham and called him her master. You are her daughters if you do what is right and do not give way to fear.",
    "Husbands, in the same way be considerate as you live with your wives, and treat them with respect as the weaker partner and as heirs with you of the gracious gift of life, so that nothing will hinder your prayers.",
    "Finally, all of you, live in harmony with one another; be sympathetic, love as brothers, be compassionate and humble.",
    "Do not repay evil with evil or insult with insult, but with blessing, because to this you were called so that you may inherit a blessing.",
    "For, \"Whoever would love life and see good days must keep his tongue from evil and his lips from deceitful speech.",
    "He must turn from evil and do good; he must seek peace and pursue it.",
    "For the eyes of the Lord are on the righteous and his ears are attentive to their prayer, but the face of the Lord is against those who do evil.\"",
    "Who is going to harm you if you are eager to do good?",
    "But even if you should suffer for what is right, you are blessed. \"Do not fear what they fear; do not be frightened.\"",
    "But in your hearts set apart Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect,",
    "keeping a clear conscience, so that those who speak maliciously against your good behavior in Christ may be ashamed of their slander.",
    "It is better, if it is God's will, to suffer for doing good than for doing evil.",
    "For Christ died for sins once for all, the righteous for the unrighteous, to bring you to God. He was put to death in the body but made alive by the Spirit,",
    "through whom also he went and preached to the spirits in prison",
    "who disobeyed long ago when God waited patiently in the days of Noah while the ark was being built. In it only a few people, eight in all, were saved through water,",
    "and this water symbolizes baptism that now saves you also--not the removal of dirt from the body but the pledge of a good conscience toward God. It saves you by the resurrection of Jesus Christ,",
    "who has gone into heaven and is at God's right hand--with angels, authorities and powers in submission to him."
  ],
  "Peter1-4": [
    "Therefore, since Christ suffered in his body, arm yourselves also with the same attitude, because he who has suffered in his body is done with sin.",
    "As a result, he does not live the rest of his earthly life for evil human desires, but rather for the will of God.",
    "For you have spent enough time in the past doing what pagans choose to do--living in debauchery, lust, drunkenness, orgies, carousing and detestable idolatry.",
    "They think it strange that you do not plunge with them into the same flood of dissipation, and they heap abuse on you.",
    "But they will have to give account to him who is ready to judge the living and the dead.",
    "For this is the reason the gospel was preached even to those who are now dead, so that they might be judged according to men in regard to the body, but live according to God in regard to the spirit.",
    "The end of all things is near. Therefore be clear minded and self-controlled so that you can pray.",
    "Above all, love each other deeply, because love covers over a multitude of sins.",
    "Offer hospitality to one another without grumbling.",
    "Each one should use whatever gift he has received to serve others, faithfully administering God's grace in its various forms.",
    "If anyone speaks, he should do it as one speaking the very words of God. If anyone serves, he should do it with the strength God provides, so that in all things God may be praised through Jesus Christ. To him be the glory and the power for ever and ever. Amen.",
    "Dear friends, do not be surprised at the painful trial you are suffering, as though something strange were happening to you.",
    "But rejoice that you participate in the sufferings of Christ, so that you may be overjoyed when his glory is revealed.",
    "If you are insulted because of the name of Christ, you are blessed, for the Spirit of glory and of God rests on you.",
    "If you suffer, it should not be as a murderer or thief or any other kind of criminal, or even as a meddler.",
    "However, if you suffer as a Christian, do not be ashamed, but praise God that you bear that name.",
    "For it is time for judgment to begin with the family of God; and if it begins with us, what will the outcome be for those who do not obey the gospel of God?",
    "And, \"If it is hard for the righteous to be saved, what will become of the ungodly and the sinner?\"",
    "So then, those who suffer according to God's will should commit themselves to their faithful Creator and continue to do good."
  ],
  "Peter1-5": [
    "To the elders among you, I appeal as a fellow elder, a witness of Christ's sufferings and one who also will share in the glory to be revealed:",
    "Be shepherds of God's flock that is under your care, serving as overseers--not because you must, but because you are willing, as God wants you to be; not greedy for money, but eager to serve;",
    "not lording it over those entrusted to you, but being examples to the flock.",
    "And when the Chief Shepherd appears, you will receive the crown of glory that will never fade away.",
    "Young men, in the same way be submissive to those who are older. All of you, clothe yourselves with humility toward one another, because, \"God opposes the proud but gives grace to the humble.\"",
    "Humble yourselves, therefore, under God's mighty hand, that he may lift you up in due time.",
    "Cast all your anxiety on him because he cares for you.",
    "Be self-controlled and alert. Your enemy the devil prowls around like a roaring lion looking for someone to devour.",
    "Resist him, standing firm in the faith, because you know that your brothers throughout the world are undergoing the same kind of sufferings.",
    "And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast.",
    "To him be the power for ever and ever. Amen.",
    "With the help of Silas, whom I regard as a faithful brother, I have written to you briefly, encouraging you and testifying that this is the true grace of God. Stand fast in it.",
    "She who is in Babylon, chosen together with you, sends you her greetings, and so does my son Mark.",
    "Greet one another with a kiss of love. Peace to all of you who are in Christ."
  ]
}