{
  "Thessalonians2-1": [
    "Paul, Silas and Timothy, To the church of the Thessalonians in God our Father and the Lord Jesus Christ:",
    "Grace and peace to you from God the Father and the Lord Jesus Christ.",
    "We ought always to thank God for you, brothers, and rightly so, because your faith is growing more and more, and the love every one of you has for each other is increasing.",
    "Therefore, among God's churches we boast about your perseverance and faith in all the persecutions and trials you are enduring.",
    "All this is evidence that God's judgment is right, and as a result you will be counted worthy of the kingdom of God, for which you are suffering.",
    "God is just: He will pay back trouble to those who trouble you",
    "and give relief to you who are troubled, and to us as well. This will happen when the Lord Jesus is revealed from heaven in blazing fire with his powerful angels.",
    "He will punish those who do not know God and do not obey the gospel of our Lord Jesus.",
    "They will be punished with everlasting destruction and shut out from the presence of the Lord and from the majesty of his power",
    "on the day he comes to be glorified in his holy people and to be marveled at among all those who have believed. This includes you, because you believed our testimony to you.",
    "With this in mind, we constantly pray for you, that our God may count you worthy of his calling, and that by his power he may fulfill every good purpose of yours and every act prompted by your faith.",
    "We pray this so that the name of our Lord Jesus may be glorified in you, and you in him, according to the grace of our God and the Lord Jesus Christ."
  ],
  "Thessalonians2-2": [
    "Concerning the coming of our Lord Jesus Christ and our being gathered to him, we ask you, brothers,",
    "not to become easily unsettled or alarmed by some prophecy, report or letter supposed to have come from us, saying that the day of the Lord has already come.",
    "Don't let anyone deceive you in any way, for that day will not come until the rebellion occurs and the man of lawlessness is revealed, the man doomed to destruction.",
    "He will oppose and will exalt himself over everything that is called God or is worshiped, so that he sets himself up in God's temple, proclaiming himself to be God.",
    "Don't you remember that when I was with you I used to tell you these things?",
    "And now you know what is holding him back, so that he may be revealed at the proper time.",
    "For the secret power of lawlessness is already at work; but the one who now holds it back will continue to do so till he is taken out of the way.",
    "And then the lawless one will be revealed, whom the Lord Jesus will overthrow with the breath of his mouth and destroy by the splendor of his coming.",
    "The coming of the lawless one will be in accordance with the work of Satan displayed in all kinds of counterfeit miracles, signs and wonders,",
    "and in every sort of evil that deceives those who are perishing. They perish because they refused to love the truth and so be saved.",
    "For this reason God sends them a powerful delusion so that they will believe the lie",
    "and so that all will be condemned who have not believed the truth but have delighted in wickedness.",
    "But we ought always to thank God for you, brothers loved by the Lord, because from the beginning God chose you to be saved through the sanctifying work of the Spirit and through belief in the truth.",
    "He called you to this through our gospel, that you might share in the glory of our Lord Jesus Christ.",
    "So then, brothers, stand firm and hold to the teachings we passed on to you, whether by word of mouth or by letter.",
    "May our Lord Jesus Christ himself and God our Father, who loved us and by his grace gave us eternal encouragement and good hope,",
    "encourage your hearts and strengthen you in every good deed and word."
  ],
  "Thessalonians2-3": [
    "Finally, brothers, pray for us that the message of the Lord may spread rapidly and be honored, just as it was with you.",
    "And pray that we may be delivered from wicked and evil men, for not everyone has faith.",
    "But the Lord is faithful, and he will strengthen and protect you from the evil one.",
    "We have confidence in the Lord that you are doing and will continue to do the things we command.",
    "May the Lord direct your hearts into God's love and Christ's perseverance.",
    "In the name of the Lord Jesus Christ, we command you, brothers, to keep away from every brother who is idle and does not live according to the teaching you received from us.",
    "For you yourselves know how you ought to follow our example. We were not idle when we were with you,",
    "nor did we eat anyone's food without paying for it. On the contrary, we worked night and day, laboring and toiling so that we would not be a burden to any of you.",
    "We did this, not because we do not have the right to such help, but in order to make ourselves a model for you to follow.",
    "For even when we were with you, we gave you this rule: \"If a man will not work, he shall not eat.\"",
    "We hear that some among you are idle. They are not busy; they are busybodies.",
    "Such people we command and urge in the Lord Jesus Christ to settle down and earn the bread they eat.",
    "And as for you, brothers, never tire of doing what is right.",
    "If anyone does not obey our instruction in this letter, take special note of him. Do not associate with him, in order that he may feel ashamed.",
    "Yet do not regard him as an enemy, but warn him as a brother.",
    "Now may the Lord of peace himself give you peace at all times and in every way. The Lord be with all of you.",
    "I, Paul, write this greeting in my own hand, which is the distinguishing mark in all my letters. This is how I write.",
    "The grace of our Lord Jesus Christ be with you all."
  ]
}