{
  "Thessalonians1-1": [
    "Paul, Silas and Timothy, To the church of the Thessalonians in God the Father and the Lord Jesus Christ: Grace and peace to you.",
    "We always thank God for all of you, mentioning you in our prayers.",
    "We continually remember before our God and Father your work produced by faith, your labor prompted by love, and your endurance inspired by hope in our Lord Jesus Christ.",
    "For we know, brothers loved by God, that he has chosen you,",
    "because our gospel came to you not simply with words, but also with power, with the Holy Spirit and with deep conviction. You know how we lived among you for your sake.",
    "You became imitators of us and of the Lord; in spite of severe suffering, you welcomed the message with the joy given by the Holy Spirit.",
    "And so you became a model to all the believers in Macedonia and Achaia.",
    "The Lord's message rang out from you not only in Macedonia and Achaia--your faith in God has become known everywhere. Therefore we do not need to say anything about it,",
    "for they themselves report what kind of reception you gave us. They tell how you turned to God from idols to serve the living and true God,",
    "and to wait for his Son from heaven, whom he raised from the dead--Jesus, who rescues us from the coming wrath."
  ],
  "Thessalonians1-2": [
    "You know, brothers, that our visit to you was not a failure.",
    "We had previously suffered and been insulted in Philippi, as you know, but with the help of our God we dared to tell you his gospel in spite of strong opposition.",
    "For the appeal we make does not spring from error or impure motives, nor are we trying to trick you.",
    "On the contrary, we speak as men approved by God to be entrusted with the gospel. We are not trying to please men but God, who tests our hearts.",
    "You know we never used flattery, nor did we put on a mask to cover up greed--God is our witness.",
    "We were not looking for praise from men, not from you or anyone else. As apostles of Christ we could have been a burden to you,",
    "but we were gentle among you, like a mother caring for her little children.",
    "We loved you so much that we were delighted to share with you not only the gospel of God but our lives as well, because you had become so dear to us.",
    "Surely you remember, brothers, our toil and hardship; we worked night and day in order not to be a burden to anyone while we preached the gospel of God to you.",
    "You are witnesses, and so is God, of how holy, righteous and blameless we were among you who believed.",
    "For you know that we dealt with each of you as a father deals with his own children,",
    "encouraging, comforting and urging you to live lives worthy of God, who calls you into his kingdom and glory.",
    "And we also thank God continually because, when you received the word of God, which you heard from us, you accepted it not as the word of men, but as it actually is, the word of God, which is at work in you who believe.",
    "For you, brothers, became imitators of God's churches in Judea, which are in Christ Jesus: You suffered from your own countrymen the same things those churches suffered from the Jews,",
    "who killed the Lord Jesus and the prophets and also drove us out. They displease God and are hostile to all men",
    "in their effort to keep us from speaking to the Gentiles so that they may be saved. In this way they always heap up their sins to the limit. The wrath of God has come upon them at last.",
    "But, brothers, when we were torn away from you for a short time (in person, not in thought), out of our intense longing we made every effort to see you.",
    "For we wanted to come to you--certainly I, Paul, did, again and again--but Satan stopped us.",
    "For what is our hope, our joy, or the crown in which we will glory in the presence of our Lord Jesus when he comes? Is it not you?",
    "Indeed, you are our glory and joy."
  ],
  "Thessalonians1-3": [
    "So when we could stand it no longer, we thought it best to be left by ourselves in Athens.",
    "We sent Timothy, who is our brother and God's fellow worker in spreading the gospel of Christ, to strengthen and encourage you in your faith,",
    "so that no one would be unsettled by these trials. You know quite well that we were destined for them.",
    "In fact, when we were with you, we kept telling you that we would be persecuted. And it turned out that way, as you well know.",
    "For this reason, when I could stand it no longer, I sent to find out about your faith. I was afraid that in some way the tempter might have tempted you and our efforts might have been useless.",
    "But Timothy has just now come to us from you and has brought good news about your faith and love. He has told us that you always have pleasant memories of us and that you long to see us, just as we also long to see you.",
    "Therefore, brothers, in all our distress and persecution we were encouraged about you because of your faith.",
    "For now we really live, since you are standing firm in the Lord.",
    "How can we thank God enough for you in return for all the joy we have in the presence of our God because of you?",
    "Night and day we pray most earnestly that we may see you again and supply what is lacking in your faith.",
    "Now may our God and Father himself and our Lord Jesus clear the way for us to come to you.",
    "May the Lord make your love increase and overflow for each other and for everyone else, just as ours does for you.",
    "May he strengthen your hearts so that you will be blameless and holy in the presence of our God and Father when our Lord Jesus comes with all his holy ones."
  ],
  "Thessalonians1-4": [
    "Finally, brothers, we instructed you how to live in order to please God, as in fact you are living. Now we ask you and urge you in the Lord Jesus to do this more and more.",
    "For you know what instructions we gave you by the authority of the Lord Jesus.",
    "It is God's will that you should be sanctified: that you should avoid sexual immorality;",
    "that each of you should learn to control his own body in a way that is holy and honorable,",
    "not in passionate lust like the heathen, who do not know God;",
    "and that in this matter no one should wrong his brother or take advantage of him. The Lord will punish men for all such sins, as we have already told you and warned you.",
    "For God did not call us to be impure, but to live a holy life.",
    "Therefore, he who rejects this instruction does not reject man but God, who gives you his Holy Spirit.",
    "Now about brotherly love we do not need to write to you, for you yourselves have been taught by God to love each other.",
    "And in fact, you do love all the brothers throughout Macedonia. Yet we urge you, brothers, to do so more and more.",
    "Make it your ambition to lead a quiet life, to mind your own business and to work with your hands, just as we told you,",
    "so that your daily life may win the respect of outsiders and so that you will not be dependent on anybody.",
    "Brothers, we do not want you to be ignorant about those who fall asleep, or to grieve like the rest of men, who have no hope.",
    "We believe that Jesus died and rose again and so we believe that God will bring with Jesus those who have fallen asleep in him.",
    "According to the Lord's own word, we tell you that we who are still alive, who are left till the coming of the Lord, will certainly not precede those who have fallen asleep.",
    "For the Lord himself will come down from heaven, with a loud command, with the voice of the archangel and with the trumpet call of God, and the dead in Christ will rise first.",
    "After that, we who are still alive and are left will be caught up together with them in the clouds to meet the Lord in the air. And so we will be with the Lord forever.",
    "Therefore encourage each other with these words."
  ],
  "Thessalonians1-5": [
    "Now, brothers, about times and dates we do not need to write to you,",
    "for you know very well that the day of the Lord will come like a thief in the night.",
    "While people are saying, \"Peace and safety,\" destruction will come on them suddenly, as labor pains on a pregnant woman, and they will not escape.",
    "But you, brothers, are not in darkness so that this day should surprise you like a thief.",
    "You are all sons of the light and sons of the day. We do not belong to the night or to the darkness.",
    "So then, let us not be like others, who are asleep, but let us be alert and self-controlled.",
    "For those who sleep, sleep at night, and those who get drunk, get drunk at night.",
    "But since we belong to the day, let us be self-controlled, putting on faith and love as a breastplate, and the hope of salvation as a helmet.",
    "For God did not appoint us to suffer wrath but to receive salvation through our Lord Jesus Christ.",
    "He died for us so that, whether we are awake or asleep, we may live together with him.",
    "Therefore encourage one another and build each other up, just as in fact you are doing.",
    "Now we ask you, brothers, to respect those who work hard among you, who are over you in the Lord and who admonish you.",
    "Hold them in the highest regard in love because of their work. Live in peace with each other.",
    "And we urge you, brothers, warn those who are idle, encourage the timid, help the weak, be patient with everyone.",
    "Make sure that nobody pays back wrong for wrong, but always try to be kind to each other and to everyone else.",
    "Be joyful always;",
    "pray continually;",
    "give thanks in all circumstances, for this is God's will for you in Christ Jesus.",
    "Do not put out the Spirit's fire;",
    "do not treat prophecies with contempt.",
    "Test everything. Hold on to the good.",
    "Avoid every kind of evil.",
    "May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ.",
    "The one who calls you is faithful and he will do it.",
    "Brothers, pray for us.",
    "Greet all the brothers with a holy kiss.",
    "I charge you before the Lord to have this letter read to all the brothers.",
    "The grace of our Lord Jesus Christ be with you."
  ]
}