{
  "Timothy1-1": [
    "Paul, an apostle of Christ Jesus by the command of God our Savior and of Christ Jesus our hope,",
    "To Timothy my true son in the faith: Grace, mercy and peace from God the Father and Christ Jesus our Lord.",
    "As I urged you when I went into Macedonia, stay there in Ephesus so that you may command certain men not to teach false doctrines any longer",
    "nor to devote themselves to myths and endless genealogies. These promote controversies rather than God's work--which is by faith.",
    "The goal of this command is love, which comes from a pure heart and a good conscience and a sincere faith.",
    "Some have wandered away from these and turned to meaningless talk.",
    "They want to be teachers of the law, but they do not know what they are talking about or what they so confidently affirm.",
    "We know that the law is good if one uses it properly.",
    "We also know that law is made not for the righteous but for lawbreakers and rebels, the ungodly and sinful, the unholy and irreligious; for those who kill their fathers or mothers, for murderers,",
    "for adulterers and perverts, for slave traders and liars and perjurers--and for whatever else is contrary to the sound doctrine",
    "that conforms to the glorious gospel of the blessed God, which he entrusted to me.",
    "I thank Christ Jesus our Lord, who has given me strength, that he considered me faithful, appointing me to his service.",
    "Even though I was once a blasphemer and a persecutor and a violent man, I was shown mercy because I acted in ignorance and unbelief.",
    "The grace of our Lord was poured out on me abundantly, along with the faith and love that are in Christ Jesus.",
    "Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners--of whom I am the worst.",
    "But for that very reason I was shown mercy so that in me, the worst of sinners, Christ Jesus might display his unlimited patience as an example for those who would believe on him and receive eternal life.",
    "Now to the King eternal, immortal, invisible, the only God, be honor and glory for ever and ever. Amen.",
    "Timothy, my son, I give you this instruction in keeping with the prophecies once made about you, so that by following them you may fight the good fight,",
    "holding on to faith and a good conscience. Some have rejected these and so have shipwrecked their faith.",
    "Among them are Hymenaeus and Alexander, whom I have handed over to Satan to be taught not to blaspheme."
  ],
  "Timothy1-2": [
    "I urge, then, first of all, that requests, prayers, intercession and thanksgiving be made for everyone--",
    "for kings and all those in authority, that we may live peaceful and quiet lives in all godliness and holiness.",
    "This is good, and pleases God our Savior,",
    "who wants all men to be saved and to come to a knowledge of the truth.",
    "For there is one God and one mediator between God and men, the man Christ Jesus,",
    "who gave himself as a ransom for all men--the testimony given in its proper time.",
    "And for this purpose I was appointed a herald and an apostle--I am telling the truth, I am not lying--and a teacher of the true faith to the Gentiles.",
    "I want men everywhere to lift up holy hands in prayer, without anger or disputing.",
    "I also want women to dress modestly, with decency and propriety, not with braided hair or gold or pearls or expensive clothes,",
    "but with good deeds, appropriate for women who profess to worship God.",
    "A woman should learn in quietness and full submission.",
    "I do not permit a woman to teach or to have authority over a man; she must be silent.",
    "For Adam was formed first, then Eve.",
    "And Adam was not the one deceived; it was the woman who was deceived and became a sinner.",
    "But women will be saved through childbearing--if they continue in faith, love and holiness with propriety."
  ],
  "Timothy1-3": [
    "Here is a trustworthy saying: If anyone sets his heart on being an overseer, he desires a noble task.",
    "Now the overseer must be above reproach, the husband of but one wife, temperate, self-controlled, respectable, hospitable, able to teach,",
    "not given to drunkenness, not violent but gentle, not quarrelsome, not a lover of money.",
    "He must manage his own family well and see that his children obey him with proper respect.",
    "(If anyone does not know how to manage his own family, how can he take care of God's church?)",
    "He must not be a recent convert, or he may become conceited and fall under the same judgment as the devil.",
    "He must also have a good reputation with outsiders, so that he will not fall into disgrace and into the devil's trap.",
    "Deacons, likewise, are to be men worthy of respect, sincere, not indulging in much wine, and not pursuing dishonest gain.",
    "They must keep hold of the deep truths of the faith with a clear conscience.",
    "They must first be tested; and then if there is nothing against them, let them serve as deacons.",
    "In the same way, their wives are to be women worthy of respect, not malicious talkers but temperate and trustworthy in everything.",
    "A deacon must be the husband of but one wife and must manage his children and his household well.",
    "Those who have served well gain an excellent standing and great assurance in their faith in Christ Jesus.",
    "Although I hope to come to you soon, I am writing you these instructions so that,",
    "if I am delayed, you will know how people ought to conduct themselves in God's household, which is the church of the living God, the pillar and foundation of the truth.",
    "Beyond all question, the mystery of godliness is great: He appeared in a body, was vindicated by the Spirit, was seen by angels, was preached among the nations, was believed on in the world, was taken up in glory."
  ],
  "Timothy1-4": [
    "The Spirit clearly says that in later times some will abandon the faith and follow deceiving spirits and things taught by demons.",
    "Such teachings come through hypocritical liars, whose consciences have been seared as with a hot iron.",
    "They forbid people to marry and order them to abstain from certain foods, which God created to be received with thanksgiving by those who believe and who know the truth.",
    "For everything God created is good, and nothing is to be rejected if it is received with thanksgiving,",
    "because it is consecrated by the word of God and prayer.",
    "If you point these things out to the brothers, you will be a good minister of Christ Jesus, brought up in the truths of the faith and of the good teaching that you have followed.",
    "Have nothing to do with godless myths and old wives' tales; rather, train yourself to be godly.",
    "For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come.",
    "This is a trustworthy saying that deserves full acceptance",
    "(and for this we labor and strive), that we have put our hope in the living God, who is the Savior of all men, and especially of those who believe.",
    "Command and teach these things.",
    "Don't let anyone look down on you because you are young, but set an example for the believers in speech, in life, in love, in faith and in purity.",
    "Until I come, devote yourself to the public reading of Scripture, to preaching and to teaching.",
    "Do not neglect your gift, which was given you through a prophetic message when the body of elders laid their hands on you.",
    "Be diligent in these matters; give yourself wholly to them, so that everyone may see your progress.",
    "Watch your life and doctrine closely. Persevere in them, because if you do, you will save both yourself and your hearers."
  ],
  "Timothy1-5": [
    "Do not rebuke an older man harshly, but exhort him as if he were your father. Treat younger men as brothers,",
    "older women as mothers, and younger women as sisters, with absolute purity.",
    "Give proper recognition to those widows who are really in need.",
    "But if a widow has children or grandchildren, these should learn first of all to put their religion into practice by caring for their own family and so repaying their parents and grandparents, for this is pleasing to God.",
    "The widow who is really in need and left all alone puts her hope in God and continues night and day to pray and to ask God for help.",
    "But the widow who lives for pleasure is dead even while she lives.",
    "Give the people these instructions, too, so that no one may be open to blame.",
    "If anyone does not provide for his relatives, and especially for his immediate family, he has denied the faith and is worse than an unbeliever.",
    "No widow may be put on the list of widows unless she is over sixty, has been faithful to her husband,",
    "and is well known for her good deeds, such as bringing up children, showing hospitality, washing the feet of the saints, helping those in trouble and devoting herself to all kinds of good deeds.",
    "As for younger widows, do not put them on such a list. For when their sensual desires overcome their dedication to Christ, they want to marry.",
    "Thus they bring judgment on themselves, because they have broken their first pledge.",
    "Besides, they get into the habit of being idle and going about from house to house. And not only do they become idlers, but also gossips and busybodies, saying things they ought not to.",
    "So I counsel younger widows to marry, to have children, to manage their homes and to give the enemy no opportunity for slander.",
    "Some have in fact already turned away to follow Satan.",
    "If any woman who is a believer has widows in her family, she should help them and not let the church be burdened with them, so that the church can help those widows who are really in need.",
    "The elders who direct the affairs of the church well are worthy of double honor, especially those whose work is preaching and teaching.",
    "For the Scripture says, \"Do not muzzle the ox while it is treading out the grain,\" and \"The worker deserves his wages.\"",
    "Do not entertain an accusation against an elder unless it is brought by two or three witnesses.",
    "Those who sin are to be rebuked publicly, so that the others may take warning.",
    "I charge you, in the sight of God and Christ Jesus and the elect angels, to keep these instructions without partiality, and to do nothing out of favoritism.",
    "Do not be hasty in the laying on of hands, and do not share in the sins of others. Keep yourself pure.",
    "Stop drinking only water, and use a little wine because of your stomach and your frequent illnesses.",
    "The sins of some men are obvious, reaching the place of judgment ahead of them; the sins of others trail behind them.",
    "In the same way, good deeds are obvious, and even those that are not cannot be hidden."
  ],
  "Timothy1-6": [
    "All who are under the yoke of slavery should consider their masters worthy of full respect, so that God's name and our teaching may not be slandered.",
    "Those who have believing masters are not to show less respect for them because they are brothers. Instead, they are to serve them even better, because those who benefit from their service are believers, and dear to them. These are the things you are to teach and urge on them.",
    "If anyone teaches false doctrines and does not agree to the sound instruction of our Lord Jesus Christ and to godly teaching,",
    "he is conceited and understands nothing. He has an unhealthy interest in controversies and quarrels about words that result in envy, strife, malicious talk, evil suspicions",
    "and constant friction between men of corrupt mind, who have been robbed of the truth and who think that godliness is a means to financial gain.",
    "But godliness with contentment is great gain.",
    "For we brought nothing into the world, and we can take nothing out of it.",
    "But if we have food and clothing, we will be content with that.",
    "People who want to get rich fall into temptation and a trap and into many foolish and harmful desires that plunge men into ruin and destruction.",
    "For the love of money is a root of all kinds of evil. Some people, eager for money, have wandered from the faith and pierced themselves with many griefs.",
    "But you, man of God, flee from all this, and pursue righteousness, godliness, faith, love, endurance and gentleness.",
    "Fight the good fight of the faith. Take hold of the eternal life to which you were called when you made your good confession in the presence of many witnesses.",
    "In the sight of God, who gives life to everything, and of Christ Jesus, who while testifying before Pontius Pilate made the good confession, I charge you",
    "to keep this command without spot or blame until the appearing of our Lord Jesus Christ,",
    "which God will bring about in his own time--God, the blessed and only Ruler, the King of kings and Lord of lords,",
    "who alone is immortal and who lives in unapproachable light, whom no one has seen or can see. To him be honor and might forever. Amen.",
    "Command those who are rich in this present world not to be arrogant nor to put their hope in wealth, which is so uncertain, but to put their hope in God, who richly provides us with everything for our enjoyment.",
    "Command them to do good, to be rich in good deeds, and to be generous and willing to share.",
    "In this way they will lay up treasure for themselves as a firm foundation for the coming age, so that they may take hold of the life that is truly life.",
    "Timothy, guard what has been entrusted to your care. Turn away from godless chatter and the opposing ideas of what is falsely called knowledge,",
    "which some have professed and in so doing have wandered from the faith. Grace be with you."
  ]
}