{
  "Titus-1": [
    "Paul, a servant of God and an apostle of Jesus Christ for the faith of God's elect and the knowledge of the truth that leads to godliness--",
    "a faith and knowledge resting on the hope of eternal life, which God, who does not lie, promised before the beginning of time,",
    "and at his appointed season he brought his word to light through the preaching entrusted to me by the command of God our Savior,",
    "To Titus, my true son in our common faith: Grace and peace from God the Father and Christ Jesus our Savior.",
    "The reason I left you in Crete was that you might straighten out what was left unfinished and appoint elders in every town, as I directed you.",
    "An elder must be blameless, the husband of but one wife, a man whose children believe and are not open to the charge of being wild and disobedient.",
    "Since an overseer is entrusted with God's work, he must be blameless--not overbearing, not quick-tempered, not given to drunkenness, not violent, not pursuing dishonest gain.",
    "Rather he must be hospitable, one who loves what is good, who is self-controlled, upright, holy and disciplined.",
    "He must hold firmly to the trustworthy message as it has been taught, so that he can encourage others by sound doctrine and refute those who oppose it.",
    "For there are many rebellious people, mere talkers and deceivers, especially those of the circumcision group.",
    "They must be silenced, because they are ruining whole households by teaching things they ought not to teach--and that for the sake of dishonest gain.",
    "Even one of their own prophets has said, \"Cretans are always liars, evil brutes, lazy gluttons.\"",
    "This testimony is true. Therefore, rebuke them sharply, so that they will be sound in the faith",
    "and will pay no attention to Jewish myths or to the commands of those who reject the truth.",
    "To the pure, all things are pure, but to those who are corrupted and do not believe, nothing is pure. In fact, both their minds and consciences are corrupted.",
    "They claim to know God, but by their actions they deny him. They are detestable, disobedient and unfit for doing anything good."
  ],
  "Titus-2": [
    "You must teach what is in accord with sound doctrine.",
    "Teach the older men to be temperate, worthy of respect, self-controlled, and sound in faith, in love and in endurance.",
    "Likewise, teach the older women to be reverent in the way they live, not to be slanderers or addicted to much wine, but to teach what is good.",
    "Then they can train the younger women to love their husbands and children,",
    "to be self-controlled and pure, to be busy at home, to be kind, and to be subject to their husbands, so that no one will malign the word of God.",
    "Similarly, encourage the young men to be self-controlled.",
    "In everything set them an example by doing what is good. In your teaching show integrity, seriousness",
    "and soundness of speech that cannot be condemned, so that those who oppose you may be ashamed because they have nothing bad to say about us.",
    "Teach slaves to be subject to their masters in everything, to try to please them, not to talk back to them,",
    "and not to steal from them, but to show that they can be fully trusted, so that in every way they will make the teaching about God our Savior attractive.",
    "For the grace of God that brings salvation has appeared to all men.",
    "It teaches us to say \"No\" to ungodliness and worldly passions, and to live self-controlled, upright and godly lives in this present age,",
    "while we wait for the blessed hope--the glorious appearing of our great God and Savior, Jesus Christ,",
    "who gave himself for us to redeem us from all wickedness and to purify for himself a people that are his very own, eager to do what is good.",
    "These, then, are the things you should teach. Encourage and rebuke with all authority. Do not let anyone despise you."
  ],
  "Titus-3": [
    "Remind the people to be subject to rulers and authorities, to be obedient, to be ready to do whatever is good,",
    "to slander no one, to be peaceable and considerate, and to show true humility toward all men.",
    "At one time we too were foolish, disobedient, deceived and enslaved by all kinds of passions and pleasures. We lived in malice and envy, being hated and hating one another.",
    "But when the kindness and love of God our Savior appeared,",
    "he saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit,",
    "whom he poured out on us generously through Jesus Christ our Savior,",
    "so that, having been justified by his grace, we might become heirs having the hope of eternal life.",
    "This is a trustworthy saying. And I want you to stress these things, so that those who have trusted in God may be careful to devote themselves to doing what is good. These things are excellent and profitable for everyone.",
    "But avoid foolish controversies and genealogies and arguments and quarrels about the law, because these are unprofitable and useless.",
    "Warn a divisive person once, and then warn him a second time. After that, have nothing to do with him.",
    "You may be sure that such a man is warped and sinful; he is self-condemned.",
    "As soon as I send Artemas or Tychicus to you, do your best to come to me at Nicopolis, because I have decided to winter there.",
    "Do everything you can to help Zenas the lawyer and Apollos on their way and see that they have everything they need.",
    "Our people must learn to devote themselves to doing what is good, in order that they may provide for daily necessities and not live unproductive lives.",
    "Everyone with me sends you greetings. Greet those who love us in the faith. Grace be with you all."
  ]
}