const Joshua = {
  "Joshua-0": [
    "After the death of Moses the servant of the LORD, the LORD said to Joshua son of Nun, Moses' aide:",
    "\"Moses my servant is dead. Now then, you and all these people, get ready to cross the Jordan River into the land I am about to give to them--to the Israelites.",
    "I will give you every place where you set your foot, as I promised Moses.",
    "Your territory will extend from the desert to Lebanon, and from the great river, the Euphrates--all the Hittite country--to the Great Sea on the west.",
    "No one will be able to stand up against you all the days of your life. As I was with Moses, so I will be with you; I will never leave you nor forsake you.",
    "\"Be strong and courageous, because you will lead these people to inherit the land I swore to their forefathers to give them.",
    "Be strong and very courageous. Be careful to obey all the law my servant Moses gave you; do not turn from it to the right or to the left, that you may be successful wherever you go.",
    "Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful.",
    "Have I not commanded you? Be strong and courageous. Do not be terrified; do not be discouraged, for the LORD your God will be with you wherever you go.\"",
    "So Joshua ordered the officers of the people:",
    "\"Go through the camp and tell the people, 'Get your supplies ready. Three days from now you will cross the Jordan here to go in and take possession of the land the LORD your God is giving you for your own.'\"",
    "But to the Reubenites, the Gadites and the half-tribe of Manasseh, Joshua said,",
    "\"Remember the command that Moses the servant of the LORD gave you: 'The LORD your God is giving you rest and has granted you this land.'",
    "Your wives, your children and your livestock may stay in the land that Moses gave you east of the Jordan, but all your fighting men, fully armed, must cross over ahead of your brothers. You are to help your brothers",
    "until the LORD gives them rest, as he has done for you, and until they too have taken possession of the land that the LORD your God is giving them. After that, you may go back and occupy your own land, which Moses the servant of the LORD gave you east of the Jordan toward the sunrise.\"",
    "Then they answered Joshua, \"Whatever you have commanded us we will do, and wherever you send us we will go.",
    "Just as we fully obeyed Moses, so we will obey you. Only may the LORD your God be with you as he was with Moses.",
    "Whoever rebels against your word and does not obey your words, whatever you may command them, will be put to death. Only be strong and courageous!\""
  ],
  "Joshua-1": [
    "Then Joshua son of Nun secretly sent two spies from Shittim. \"Go, look over the land,\" he said, \"especially Jericho.\" So they went and entered the house of a prostitute named Rahab and stayed there.",
    "The king of Jericho was told, \"Look! Some of the Israelites have come here tonight to spy out the land.\"",
    "So the king of Jericho sent this message to Rahab: \"Bring out the men who came to you and entered your house, because they have come to spy out the whole land.\"",
    "But the woman had taken the two men and hidden them. She said, \"Yes, the men came to me, but I did not know where they had come from.",
    "At dusk, when it was time to close the city gate, the men left. I don't know which way they went. Go after them quickly. You may catch up with them.\"",
    "(But she had taken them up to the roof and hidden them under the stalks of flax she had laid out on the roof.)",
    "So the men set out in pursuit of the spies on the road that leads to the fords of the Jordan, and as soon as the pursuers had gone out, the gate was shut.",
    "Before the spies lay down for the night, she went up on the roof",
    "and said to them, \"I know that the LORD has given this land to you and that a great fear of you has fallen on us, so that all who live in this country are melting in fear because of you.",
    "We have heard how the LORD dried up the water of the Red Sea for you when you came out of Egypt, and what you did to Sihon and Og, the two kings of the Amorites east of the Jordan, whom you completely destroyed.",
    "When we heard of it, our hearts melted and everyone's courage failed because of you, for the LORD your God is God in heaven above and on the earth below.",
    "Now then, please swear to me by the LORD that you will show kindness to my family, because I have shown kindness to you. Give me a sure sign",
    "that you will spare the lives of my father and mother, my brothers and sisters, and all who belong to them, and that you will save us from death.\"",
    "\"Our lives for your lives!\" the men assured her. \"If you don't tell what we are doing, we will treat you kindly and faithfully when the LORD gives us the land.\"",
    "So she let them down by a rope through the window, for the house she lived in was part of the city wall.",
    "Now she had said to them, \"Go to the hills so the pursuers will not find you. Hide yourselves there three days until they return, and then go on your way.\"",
    "The men said to her, \"This oath you made us swear will not be binding on us",
    "unless, when we enter the land, you have tied this scarlet cord in the window through which you let us down, and unless you have brought your father and mother, your brothers and all your family into your house.",
    "If anyone goes outside your house into the street, his blood will be on his own head; we will not be responsible. As for anyone who is in the house with you, his blood will be on our head if a hand is laid on him.",
    "But if you tell what we are doing, we will be released from the oath you made us swear.\"",
    "\"Agreed,\" she replied. \"Let it be as you say.\" So she sent them away and they departed. And she tied the scarlet cord in the window.",
    "When they left, they went into the hills and stayed there three days, until the pursuers had searched all along the road and returned without finding them.",
    "Then the two men started back. They went down out of the hills, forded the river and came to Joshua son of Nun and told him everything that had happened to them.",
    "They said to Joshua, \"The LORD has surely given the whole land into our hands; all the people are melting in fear because of us.\""
  ],
  "Joshua-2": [
    "Early in the morning Joshua and all the Israelites set out from Shittim and went to the Jordan, where they camped before crossing over.",
    "After three days the officers went throughout the camp,",
    "giving orders to the people: \"When you see the ark of the covenant of the LORD your God, and the priests, who are Levites, carrying it, you are to move out from your positions and follow it.",
    "Then you will know which way to go, since you have never been this way before. But keep a distance of about a thousand yards between you and the ark; do not go near it.\"",
    "Joshua told the people, \"Consecrate yourselves, for tomorrow the LORD will do amazing things among you.\"",
    "Joshua said to the priests, \"Take up the ark of the covenant and pass on ahead of the people.\" So they took it up and went ahead of them.",
    "And the LORD said to Joshua, \"Today I will begin to exalt you in the eyes of all Israel, so they may know that I am with you as I was with Moses.",
    "Tell the priests who carry the ark of the covenant: 'When you reach the edge of the Jordan's waters, go and stand in the river.'\"",
    "Joshua said to the Israelites, \"Come here and listen to the words of the LORD your God.",
    "This is how you will know that the living God is among you and that he will certainly drive out before you the Canaanites, Hittites, Hivites, Perizzites, Girgashites, Amorites and Jebusites.",
    "See, the ark of the covenant of the Lord of all the earth will go into the Jordan ahead of you.",
    "Now then, choose twelve men from the tribes of Israel, one from each tribe.",
    "And as soon as the priests who carry the ark of the LORD--the Lord of all the earth--set foot in the Jordan, its waters flowing downstream will be cut off and stand up in a heap.\"",
    "So when the people broke camp to cross the Jordan, the priests carrying the ark of the covenant went ahead of them.",
    "Now the Jordan is at flood stage all during harvest. Yet as soon as the priests who carried the ark reached the Jordan and their feet touched the water's edge,",
    "the water from upstream stopped flowing. It piled up in a heap a great distance away, at a town called Adam in the vicinity of Zarethan, while the water flowing down to the Sea of the Arabah (the Salt Sea) was completely cut off. So the people crossed over opposite Jericho.",
    "The priests who carried the ark of the covenant of the LORD stood firm on dry ground in the middle of the Jordan, while all Israel passed by until the whole nation had completed the crossing on dry ground."
  ],
  "Joshua-3": [
    "When the whole nation had finished crossing the Jordan, the LORD said to Joshua,",
    "\"Choose twelve men from among the people, one from each tribe,",
    "and tell them to take up twelve stones from the middle of the Jordan from right where the priests stood and to carry them over with you and put them down at the place where you stay tonight.\"",
    "So Joshua called together the twelve men he had appointed from the Israelites, one from each tribe,",
    "and said to them, \"Go over before the ark of the LORD your God into the middle of the Jordan. Each of you is to take up a stone on his shoulder, according to the number of the tribes of the Israelites,",
    "to serve as a sign among you. In the future, when your children ask you, 'What do these stones mean?'",
    "tell them that the flow of the Jordan was cut off before the ark of the covenant of the LORD. When it crossed the Jordan, the waters of the Jordan were cut off. These stones are to be a memorial to the people of Israel forever.\"",
    "So the Israelites did as Joshua commanded them. They took twelve stones from the middle of the Jordan, according to the number of the tribes of the Israelites, as the LORD had told Joshua; and they carried them over with them to their camp, where they put them down.",
    "Joshua set up the twelve stones that had been in the middle of the Jordan at the spot where the priests who carried the ark of the covenant had stood. And they are there to this day.",
    "Now the priests who carried the ark remained standing in the middle of the Jordan until everything the LORD had commanded Joshua was done by the people, just as Moses had directed Joshua. The people hurried over,",
    "and as soon as all of them had crossed, the ark of the LORD and the priests came to the other side while the people watched.",
    "The men of Reuben, Gad and the half-tribe of Manasseh crossed over, armed, in front of the Israelites, as Moses had directed them.",
    "About forty thousand armed for battle crossed over before the LORD to the plains of Jericho for war.",
    "That day the LORD exalted Joshua in the sight of all Israel; and they revered him all the days of his life, just as they had revered Moses.",
    "Then the LORD said to Joshua,",
    "\"Command the priests carrying the ark of the Testimony to come up out of the Jordan.\"",
    "So Joshua commanded the priests, \"Come up out of the Jordan.\"",
    "And the priests came up out of the river carrying the ark of the covenant of the LORD. No sooner had they set their feet on the dry ground than the waters of the Jordan returned to their place and ran at flood stage as before.",
    "On the tenth day of the first month the people went up from the Jordan and camped at Gilgal on the eastern border of Jericho.",
    "And Joshua set up at Gilgal the twelve stones they had taken out of the Jordan.",
    "He said to the Israelites, \"In the future when your descendants ask their fathers, 'What do these stones mean?'",
    "tell them, 'Israel crossed the Jordan on dry ground.'",
    "For the LORD your God dried up the Jordan before you until you had crossed over. The LORD your God did to the Jordan just what he had done to the Red Sea when he dried it up before us until we had crossed over.",
    "He did this so that all the peoples of the earth might know that the hand of the LORD is powerful and so that you might always fear the LORD your God.\""
  ],
  "Joshua-4": [
    "Now when all the Amorite kings west of the Jordan and all the Canaanite kings along the coast heard how the LORD had dried up the Jordan before the Israelites until we had crossed over, their hearts melted and they no longer had the courage to face the Israelites.",
    "At that time the LORD said to Joshua, \"Make flint knives and circumcise the Israelites again.\"",
    "So Joshua made flint knives and circumcised the Israelites at Gibeath Haaraloth.",
    "Now this is why he did so: All those who came out of Egypt--all the men of military age--died in the desert on the way after leaving Egypt.",
    "All the people that came out had been circumcised, but all the people born in the desert during the journey from Egypt had not.",
    "The Israelites had moved about in the desert forty years until all the men who were of military age when they left Egypt had died, since they had not obeyed the LORD. For the LORD had sworn to them that they would not see the land that he had solemnly promised their fathers to give us, a land flowing with milk and honey.",
    "So he raised up their sons in their place, and these were the ones Joshua circumcised. They were still uncircumcised because they had not been circumcised on the way.",
    "And after the whole nation had been circumcised, they remained where they were in camp until they were healed.",
    "Then the LORD said to Joshua, \"Today I have rolled away the reproach of Egypt from you.\" So the place has been called Gilgal to this day.",
    "On the evening of the fourteenth day of the month, while camped at Gilgal on the plains of Jericho, the Israelites celebrated the Passover.",
    "The day after the Passover, that very day, they ate some of the produce of the land: unleavened bread and roasted grain.",
    "The manna stopped the day after they ate this food from the land; there was no longer any manna for the Israelites, but that year they ate of the produce of Canaan.",
    "Now when Joshua was near Jericho, he looked up and saw a man standing in front of him with a drawn sword in his hand. Joshua went up to him and asked, \"Are you for us or for our enemies?\"",
    "\"Neither,\" he replied, \"but as commander of the army of the LORD I have now come.\" Then Joshua fell facedown to the ground in reverence, and asked him, \"What message does my Lord have for his servant?\"",
    "The commander of the LORD'S army replied, \"Take off your sandals, for the place where you are standing is holy.\" And Joshua did so."
  ],
  "Joshua-5": [
    "Now Jericho was tightly shut up because of the Israelites. No one went out and no one came in.",
    "Then the LORD said to Joshua, \"See, I have delivered Jericho into your hands, along with its king and its fighting men.",
    "March around the city once with all the armed men. Do this for six days.",
    "Have seven priests carry trumpets of rams' horns in front of the ark. On the seventh day, march around the city seven times, with the priests blowing the trumpets.",
    "When you hear them sound a long blast on the trumpets, have all the people give a loud shout; then the wall of the city will collapse and the people will go up, every man straight in.\"",
    "So Joshua son of Nun called the priests and said to them, \"Take up the ark of the covenant of the LORD and have seven priests carry trumpets in front of it.\"",
    "And he ordered the people, \"Advance! March around the city, with the armed guard going ahead of the ark of the LORD.\"",
    "When Joshua had spoken to the people, the seven priests carrying the seven trumpets before the LORD went forward, blowing their trumpets, and the ark of the LORD'S covenant followed them.",
    "The armed guard marched ahead of the priests who blew the trumpets, and the rear guard followed the ark. All this time the trumpets were sounding.",
    "But Joshua had commanded the people, \"Do not give a war cry, do not raise your voices, do not say a word until the day I tell you to shout. Then shout!\"",
    "So he had the ark of the LORD carried around the city, circling it once. Then the people returned to camp and spent the night there.",
    "Joshua got up early the next morning and the priests took up the ark of the LORD.",
    "The seven priests carrying the seven trumpets went forward, marching before the ark of the LORD and blowing the trumpets. The armed men went ahead of them and the rear guard followed the ark of the LORD, while the trumpets kept sounding.",
    "So on the second day they marched around the city once and returned to the camp. They did this for six days.",
    "On the seventh day, they got up at daybreak and marched around the city seven times in the same manner, except that on that day they circled the city seven times.",
    "The seventh time around, when the priests sounded the trumpet blast, Joshua commanded the people, \"Shout! For the LORD has given you the city!",
    "The city and all that is in it are to be devoted to the LORD. Only Rahab the prostitute and all who are with her in her house shall be spared, because she hid the spies we sent.",
    "But keep away from the devoted things, so that you will not bring about your own destruction by taking any of them. Otherwise you will make the camp of Israel liable to destruction and bring trouble on it.",
    "All the silver and gold and the articles of bronze and iron are sacred to the LORD and must go into his treasury.\"",
    "When the trumpets sounded, the people shouted, and at the sound of the trumpet, when the people gave a loud shout, the wall collapsed; so every man charged straight in, and they took the city.",
    "They devoted the city to the LORD and destroyed with the sword every living thing in it--men and women, young and old, cattle, sheep and donkeys.",
    "Joshua said to the two men who had spied out the land, \"Go into the prostitute's house and bring her out and all who belong to her, in accordance with your oath to her.\"",
    "So the young men who had done the spying went in and brought out Rahab, her father and mother and brothers and all who belonged to her. They brought out her entire family and put them in a place outside the camp of Israel.",
    "Then they burned the whole city and everything in it, but they put the silver and gold and the articles of bronze and iron into the treasury of the LORD'S house.",
    "But Joshua spared Rahab the prostitute, with her family and all who belonged to her, because she hid the men Joshua had sent as spies to Jericho--and she lives among the Israelites to this day.",
    "At that time Joshua pronounced this solemn oath: \"Cursed before the LORD is the man who undertakes to rebuild this city, Jericho: \"At the cost of his firstborn son will he lay its foundations; at the cost of his youngest will he set up its gates.\"",
    "So the LORD was with Joshua, and his fame spread throughout the land."
  ],
  "Joshua-6": [
    "But the Israelites acted unfaithfully in regard to the devoted things; Achan son of Carmi, the son of Zimri, the son of Zerah, of the tribe of Judah, took some of them. So the LORD'S anger burned against Israel.",
    "Now Joshua sent men from Jericho to Ai, which is near Beth Aven to the east of Bethel, and told them, \"Go up and spy out the region.\" So the men went up and spied out Ai.",
    "When they returned to Joshua, they said, \"Not all the people will have to go up against Ai. Send two or three thousand men to take it and do not weary all the people, for only a few men are there.\"",
    "So about three thousand men went up; but they were routed by the men of Ai,",
    "who killed about thirty-six of them. They chased the Israelites from the city gate as far as the stone quarries and struck them down on the slopes. At this the hearts of the people melted and became like water.",
    "Then Joshua tore his clothes and fell facedown to the ground before the ark of the LORD, remaining there till evening. The elders of Israel did the same, and sprinkled dust on their heads.",
    "And Joshua said, \"Ah, Sovereign LORD, why did you ever bring this people across the Jordan to deliver us into the hands of the Amorites to destroy us? If only we had been content to stay on the other side of the Jordan!",
    "O Lord, what can I say, now that Israel has been routed by its enemies?",
    "The Canaanites and the other people of the country will hear about this and they will surround us and wipe out our name from the earth. What then will you do for your own great name?\"",
    "The LORD said to Joshua, \"Stand up! What are you doing down on your face?",
    "Israel has sinned; they have violated my covenant, which I commanded them to keep. They have taken some of the devoted things; they have stolen, they have lied, they have put them with their own possessions.",
    "That is why the Israelites cannot stand against their enemies; they turn their backs and run because they have been made liable to destruction. I will not be with you anymore unless you destroy whatever among you is devoted to destruction.",
    "\"Go, consecrate the people. Tell them, 'Consecrate yourselves in preparation for tomorrow; for this is what the LORD, the God of Israel, says: That which is devoted is among you, O Israel. You cannot stand against your enemies until you remove it.",
    "\"'In the morning, present yourselves tribe by tribe. The tribe that the LORD takes shall come forward clan by clan; the clan that the LORD takes shall come forward family by family; and the family that the LORD takes shall come forward man by man.",
    "He who is caught with the devoted things shall be destroyed by fire, along with all that belongs to him. He has violated the covenant of the LORD and has done a disgraceful thing in Israel!'\"",
    "Early the next morning Joshua had Israel come forward by tribes, and Judah was taken.",
    "The clans of Judah came forward, and he took the Zerahites. He had the clan of the Zerahites come forward by families, and Zimri was taken.",
    "Joshua had his family come forward man by man, and Achan son of Carmi, the son of Zimri, the son of Zerah, of the tribe of Judah, was taken.",
    "Then Joshua said to Achan, \"My son, give glory to the LORD, the God of Israel, and give him the praise. Tell me what you have done; do not hide it from me.\"",
    "Achan replied, \"It is true! I have sinned against the LORD, the God of Israel. This is what I have done:",
    "When I saw in the plunder a beautiful robe from Babylonia, two hundred shekels of silver and a wedge of gold weighing fifty shekels, I coveted them and took them. They are hidden in the ground inside my tent, with the silver underneath.\"",
    "So Joshua sent messengers, and they ran to the tent, and there it was, hidden in his tent, with the silver underneath.",
    "They took the things from the tent, brought them to Joshua and all the Israelites and spread them out before the LORD.",
    "Then Joshua, together with all Israel, took Achan son of Zerah, the silver, the robe, the gold wedge, his sons and daughters, his cattle, donkeys and sheep, his tent and all that he had, to the Valley of Achor.",
    "Joshua said, \"Why have you brought this trouble on us? The LORD will bring trouble on you today.\" Then all Israel stoned him, and after they had stoned the rest, they burned them.",
    "Over Achan they heaped up a large pile of rocks, which remains to this day. Then the LORD turned from his fierce anger. Therefore that place has been called the Valley of Achor ever since."
  ],
  "Joshua-7": [
    "Then the LORD said to Joshua, \"Do not be afraid; do not be discouraged. Take the whole army with you, and go up and attack Ai. For I have delivered into your hands the king of Ai, his people, his city and his land.",
    "You shall do to Ai and its king as you did to Jericho and its king, except that you may carry off their plunder and livestock for yourselves. Set an ambush behind the city.\"",
    "So Joshua and the whole army moved out to attack Ai. He chose thirty thousand of his best fighting men and sent them out at night",
    "with these orders: \"Listen carefully. You are to set an ambush behind the city. Don't go very far from it. All of you be on the alert.",
    "I and all those with me will advance on the city, and when the men come out against us, as they did before, we will flee from them.",
    "They will pursue us until we have lured them away from the city, for they will say, 'They are running away from us as they did before.' So when we flee from them,",
    "you are to rise up from ambush and take the city. The LORD your God will give it into your hand.",
    "When you have taken the city, set it on fire. Do what the LORD has commanded. See to it; you have my orders.\"",
    "Then Joshua sent them off, and they went to the place of ambush and lay in wait between Bethel and Ai, to the west of Ai--but Joshua spent that night with the people.",
    "Early the next morning Joshua mustered his men, and he and the leaders of Israel marched before them to Ai.",
    "The entire force that was with him marched up and approached the city and arrived in front of it. They set up camp north of Ai, with the valley between them and the city.",
    "Joshua had taken about five thousand men and set them in ambush between Bethel and Ai, to the west of the city.",
    "They had the soldiers take up their positions--all those in the camp to the north of the city and the ambush to the west of it. That night Joshua went into the valley.",
    "When the king of Ai saw this, he and all the men of the city hurried out early in the morning to meet Israel in battle at a certain place overlooking the Arabah. But he did not know that an ambush had been set against him behind the city.",
    "Joshua and all Israel let themselves be driven back before them, and they fled toward the desert.",
    "All the men of Ai were called to pursue them, and they pursued Joshua and were lured away from the city.",
    "Not a man remained in Ai or Bethel who did not go after Israel. They left the city open and went in pursuit of Israel.",
    "Then the LORD said to Joshua, \"Hold out toward Ai the javelin that is in your hand, for into your hand I will deliver the city.\" So Joshua held out his javelin toward Ai.",
    "As soon as he did this, the men in the ambush rose quickly from their position and rushed forward. They entered the city and captured it and quickly set it on fire.",
    "The men of Ai looked back and saw the smoke of the city rising against the sky, but they had no chance to escape in any direction, for the Israelites who had been fleeing toward the desert had turned back against their pursuers.",
    "For when Joshua and all Israel saw that the ambush had taken the city and that smoke was going up from the city, they turned around and attacked the men of Ai.",
    "The men of the ambush also came out of the city against them, so that they were caught in the middle, with Israelites on both sides. Israel cut them down, leaving them neither survivors nor fugitives.",
    "But they took the king of Ai alive and brought him to Joshua.",
    "When Israel had finished killing all the men of Ai in the fields and in the desert where they had chased them, and when every one of them had been put to the sword, all the Israelites returned to Ai and killed those who were in it.",
    "Twelve thousand men and women fell that day--all the people of Ai.",
    "For Joshua did not draw back the hand that held out his javelin until he had destroyed all who lived in Ai.",
    "But Israel did carry off for themselves the livestock and plunder of this city, as the LORD had instructed Joshua.",
    "So Joshua burned Ai and made it a permanent heap of ruins, a desolate place to this day.",
    "He hung the king of Ai on a tree and left him there until evening. At sunset, Joshua ordered them to take his body from the tree and throw it down at the entrance of the city gate. And they raised a large pile of rocks over it, which remains to this day.",
    "Then Joshua built on Mount Ebal an altar to the LORD, the God of Israel,",
    "as Moses the servant of the LORD had commanded the Israelites. He built it according to what is written in the Book of the Law of Moses--an altar of uncut stones, on which no iron tool had been used. On it they offered to the LORD burnt offerings and sacrificed fellowship offerings.",
    "There, in the presence of the Israelites, Joshua copied on stones the law of Moses, which he had written.",
    "All Israel, aliens and citizens alike, with their elders, officials and judges, were standing on both sides of the ark of the covenant of the LORD, facing those who carried it--the priests, who were Levites. Half of the people stood in front of Mount Gerizim and half of them in front of Mount Ebal, as Moses the servant of the LORD had formerly commanded when he gave instructions to bless the people of Israel.",
    "Afterward, Joshua read all the words of the law--the blessings and the curses--just as it is written in the Book of the Law.",
    "There was not a word of all that Moses had commanded that Joshua did not read to the whole assembly of Israel, including the women and children, and the aliens who lived among them."
  ],
  "Joshua-8": [
    "Now when all the kings west of the Jordan heard about these things--those in the hill country, in the western foothills, and along the entire coast of the Great Sea as far as Lebanon (the kings of the Hittites, Amorites, Canaanites, Perizzites, Hivites and Jebusites)--",
    "they came together to make war against Joshua and Israel.",
    "However, when the people of Gibeon heard what Joshua had done to Jericho and Ai,",
    "they resorted to a ruse: They went as a delegation whose donkeys were loaded with worn-out sacks and old wineskins, cracked and mended.",
    "The men put worn and patched sandals on their feet and wore old clothes. All the bread of their food supply was dry and moldy.",
    "Then they went to Joshua in the camp at Gilgal and said to him and the men of Israel, \"We have come from a distant country; make a treaty with us.\"",
    "The men of Israel said to the Hivites, \"But perhaps you live near us. How then can we make a treaty with you?\"",
    "\"We are your servants,\" they said to Joshua. But Joshua asked, \"Who are you and where do you come from?\"",
    "They answered: \"Your servants have come from a very distant country because of the fame of the LORD your God. For we have heard reports of him: all that he did in Egypt,",
    "and all that he did to the two kings of the Amorites east of the Jordan--Sihon king of Heshbon, and Og king of Bashan, who reigned in Ashtaroth.",
    "And our elders and all those living in our country said to us, 'Take provisions for your journey; go and meet them and say to them, \"We are your servants; make a treaty with us.\" '",
    "This bread of ours was warm when we packed it at home on the day we left to come to you. But now see how dry and moldy it is.",
    "And these wineskins that we filled were new, but see how cracked they are. And our clothes and sandals are worn out by the very long journey.\"",
    "The men of Israel sampled their provisions but did not inquire of the LORD.",
    "Then Joshua made a treaty of peace with them to let them live, and the leaders of the assembly ratified it by oath.",
    "Three days after they made the treaty with the Gibeonites, the Israelites heard that they were neighbors, living near them.",
    "So the Israelites set out and on the third day came to their cities: Gibeon, Kephirah, Beeroth and Kiriath Jearim.",
    "But the Israelites did not attack them, because the leaders of the assembly had sworn an oath to them by the LORD, the God of Israel. The whole assembly grumbled against the leaders,",
    "but all the leaders answered, \"We have given them our oath by the LORD, the God of Israel, and we cannot touch them now.",
    "This is what we will do to them: We will let them live, so that wrath will not fall on us for breaking the oath we swore to them.\"",
    "They continued, \"Let them live, but let them be woodcutters and water carriers for the entire community.\" So the leaders' promise to them was kept.",
    "Then Joshua summoned the Gibeonites and said, \"Why did you deceive us by saying, 'We live a long way from you,' while actually you live near us?",
    "You are now under a curse: You will never cease to serve as woodcutters and water carriers for the house of my God.\"",
    "They answered Joshua, \"Your servants were clearly told how the LORD your God had commanded his servant Moses to give you the whole land and to wipe out all its inhabitants from before you. So we feared for our lives because of you, and that is why we did this.",
    "We are now in your hands. Do to us whatever seems good and right to you.\"",
    "So Joshua saved them from the Israelites, and they did not kill them.",
    "That day he made the Gibeonites woodcutters and water carriers for the community and for the altar of the LORD at the place the LORD would choose. And that is what they are to this day."
  ],
  "Joshua-9": [
    "Now Adoni-Zedek king of Jerusalem heard that Joshua had taken Ai and totally destroyed it, doing to Ai and its king as he had done to Jericho and its king, and that the people of Gibeon had made a treaty of peace with Israel and were living near them.",
    "He and his people were very much alarmed at this, because Gibeon was an important city, like one of the royal cities; it was larger than Ai, and all its men were good fighters.",
    "So Adoni-Zedek king of Jerusalem appealed to Hoham king of Hebron, Piram king of Jarmuth, Japhia king of Lachish and Debir king of Eglon.",
    "\"Come up and help me attack Gibeon,\" he said, \"because it has made peace with Joshua and the Israelites.\"",
    "Then the five kings of the Amorites--the kings of Jerusalem, Hebron, Jarmuth, Lachish and Eglon--joined forces. They moved up with all their troops and took up positions against Gibeon and attacked it.",
    "The Gibeonites then sent word to Joshua in the camp at Gilgal: \"Do not abandon your servants. Come up to us quickly and save us! Help us, because all the Amorite kings from the hill country have joined forces against us.\"",
    "So Joshua marched up from Gilgal with his entire army, including all the best fighting men.",
    "The LORD said to Joshua, \"Do not be afraid of them; I have given them into your hand. Not one of them will be able to withstand you.\"",
    "After an all-night march from Gilgal, Joshua took them by surprise.",
    "The LORD threw them into confusion before Israel, who defeated them in a great victory at Gibeon. Israel pursued them along the road going up to Beth Horon and cut them down all the way to Azekah and Makkedah.",
    "As they fled before Israel on the road down from Beth Horon to Azekah, the LORD hurled large hailstones down on them from the sky, and more of them died from the hailstones than were killed by the swords of the Israelites.",
    "On the day the LORD gave the Amorites over to Israel, Joshua said to the LORD in the presence of Israel: \"O sun, stand still over Gibeon, O moon, over the Valley of Aijalon.\"",
    "So the sun stood still, and the moon stopped, till the nation avenged itself on its enemies, as it is written in the Book of Jashar. The sun stopped in the middle of the sky and delayed going down about a full day.",
    "There has never been a day like it before or since, a day when the LORD listened to a man. Surely the LORD was fighting for Israel!",
    "Then Joshua returned with all Israel to the camp at Gilgal.",
    "Now the five kings had fled and hidden in the cave at Makkedah.",
    "When Joshua was told that the five kings had been found hiding in the cave at Makkedah,",
    "he said, \"Roll large rocks up to the mouth of the cave, and post some men there to guard it.",
    "But don't stop! Pursue your enemies, attack them from the rear and don't let them reach their cities, for the LORD your God has given them into your hand.\"",
    "So Joshua and the Israelites destroyed them completely--almost to a man--but the few who were left reached their fortified cities.",
    "The whole army then returned safely to Joshua in the camp at Makkedah, and no one uttered a word against the Israelites.",
    "Joshua said, \"Open the mouth of the cave and bring those five kings out to me.\"",
    "So they brought the five kings out of the cave--the kings of Jerusalem, Hebron, Jarmuth, Lachish and Eglon.",
    "When they had brought these kings to Joshua, he summoned all the men of Israel and said to the army commanders who had come with him, \"Come here and put your feet on the necks of these kings.\" So they came forward and placed their feet on their necks.",
    "Joshua said to them, \"Do not be afraid; do not be discouraged. Be strong and courageous. This is what the LORD will do to all the enemies you are going to fight.\"",
    "Then Joshua struck and killed the kings and hung them on five trees, and they were left hanging on the trees until evening.",
    "At sunset Joshua gave the order and they took them down from the trees and threw them into the cave where they had been hiding. At the mouth of the cave they placed large rocks, which are there to this day.",
    "That day Joshua took Makkedah. He put the city and its king to the sword and totally destroyed everyone in it. He left no survivors. And he did to the king of Makkedah as he had done to the king of Jericho.",
    "Then Joshua and all Israel with him moved on from Makkedah to Libnah and attacked it.",
    "The LORD also gave that city and its king into Israel's hand. The city and everyone in it Joshua put to the sword. He left no survivors there. And he did to its king as he had done to the king of Jericho.",
    "Then Joshua and all Israel with him moved on from Libnah to Lachish; he took up positions against it and attacked it.",
    "The LORD handed Lachish over to Israel, and Joshua took it on the second day. The city and everyone in it he put to the sword, just as he had done to Libnah.",
    "Meanwhile, Horam king of Gezer had come up to help Lachish, but Joshua defeated him and his army--until no survivors were left.",
    "Then Joshua and all Israel with him moved on from Lachish to Eglon; they took up positions against it and attacked it.",
    "They captured it that same day and put it to the sword and totally destroyed everyone in it, just as they had done to Lachish.",
    "Then Joshua and all Israel with him went up from Eglon to Hebron and attacked it.",
    "They took the city and put it to the sword, together with its king, its villages and everyone in it. They left no survivors. Just as at Eglon, they totally destroyed it and everyone in it.",
    "Then Joshua and all Israel with him turned around and attacked Debir.",
    "They took the city, its king and its villages, and put them to the sword. Everyone in it they totally destroyed. They left no survivors. They did to Debir and its king as they had done to Libnah and its king and to Hebron.",
    "So Joshua subdued the whole region, including the hill country, the Negev, the western foothills and the mountain slopes, together with all their kings. He left no survivors. He totally destroyed all who breathed, just as the LORD, the God of Israel, had commanded.",
    "Joshua subdued them from Kadesh Barnea to Gaza and from the whole region of Goshen to Gibeon.",
    "All these kings and their lands Joshua conquered in one campaign, because the LORD, the God of Israel, fought for Israel.",
    "Then Joshua returned with all Israel to the camp at Gilgal."
  ],
  "Joshua-10": [
    "When Jabin king of Hazor heard of this, he sent word to Jobab king of Madon, to the kings of Shimron and Acshaph,",
    "and to the northern kings who were in the mountains, in the Arabah south of Kinnereth, in the western foothills and in Naphoth Dor on the west;",
    "to the Canaanites in the east and west; to the Amorites, Hittites, Perizzites and Jebusites in the hill country; and to the Hivites below Hermon in the region of Mizpah.",
    "They came out with all their troops and a large number of horses and chariots--a huge army, as numerous as the sand on the seashore.",
    "All these kings joined forces and made camp together at the Waters of Merom, to fight against Israel.",
    "The LORD said to Joshua, \"Do not be afraid of them, because by this time tomorrow I will hand all of them over to Israel, slain. You are to hamstring their horses and burn their chariots.\"",
    "So Joshua and his whole army came against them suddenly at the Waters of Merom and attacked them,",
    "and the LORD gave them into the hand of Israel. They defeated them and pursued them all the way to Greater Sidon, to Misrephoth Maim, and to the Valley of Mizpah on the east, until no survivors were left.",
    "Joshua did to them as the LORD had directed: He hamstrung their horses and burned their chariots.",
    "At that time Joshua turned back and captured Hazor and put its king to the sword. (Hazor had been the head of all these kingdoms.)",
    "Everyone in it they put to the sword. They totally destroyed them, not sparing anything that breathed, and he burned up Hazor itself.",
    "Joshua took all these royal cities and their kings and put them to the sword. He totally destroyed them, as Moses the servant of the LORD had commanded.",
    "Yet Israel did not burn any of the cities built on their mounds--except Hazor, which Joshua burned.",
    "The Israelites carried off for themselves all the plunder and livestock of these cities, but all the people they put to the sword until they completely destroyed them, not sparing anyone that breathed.",
    "As the LORD commanded his servant Moses, so Moses commanded Joshua, and Joshua did it; he left nothing undone of all that the LORD commanded Moses.",
    "So Joshua took this entire land: the hill country, all the Negev, the whole region of Goshen, the western foothills, the Arabah and the mountains of Israel with their foothills,",
    "from Mount Halak, which rises toward Seir, to Baal Gad in the Valley of Lebanon below Mount Hermon. He captured all their kings and struck them down, putting them to death.",
    "Joshua waged war against all these kings for a long time.",
    "Except for the Hivites living in Gibeon, not one city made a treaty of peace with the Israelites, who took them all in battle.",
    "For it was the LORD himself who hardened their hearts to wage war against Israel, so that he might destroy them totally, exterminating them without mercy, as the LORD had commanded Moses.",
    "At that time Joshua went and destroyed the Anakites from the hill country: from Hebron, Debir and Anab, from all the hill country of Judah, and from all the hill country of Israel. Joshua totally destroyed them and their towns.",
    "No Anakites were left in Israelite territory; only in Gaza, Gath and Ashdod did any survive.",
    "So Joshua took the entire land, just as the LORD had directed Moses, and he gave it as an inheritance to Israel according to their tribal divisions. Then the land had rest from war."
  ],
  "Joshua-11": [
    "These are the kings of the land whom the Israelites had defeated and whose territory they took over east of the Jordan, from the Arnon Gorge to Mount Hermon, including all the eastern side of the Arabah:",
    "Sihon king of the Amorites, who reigned in Heshbon. He ruled from Aroer on the rim of the Arnon Gorge--from the middle of the gorge--to the Jabbok River, which is the border of the Ammonites. This included half of Gilead.",
    "He also ruled over the eastern Arabah from the Sea of Kinnereth to the Sea of the Arabah (the Salt Sea), to Beth Jeshimoth, and then southward below the slopes of Pisgah.",
    "And the territory of Og king of Bashan, one of the last of the Rephaites, who reigned in Ashtaroth and Edrei.",
    "He ruled over Mount Hermon, Salecah, all of Bashan to the border of the people of Geshur and Maacah, and half of Gilead to the border of Sihon king of Heshbon.",
    "Moses, the servant of the LORD, and the Israelites conquered them. And Moses the servant of the LORD gave their land to the Reubenites, the Gadites and the half-tribe of Manasseh to be their possession.",
    "These are the kings of the land that Joshua and the Israelites conquered on the west side of the Jordan, from Baal Gad in the Valley of Lebanon to Mount Halak, which rises toward Seir (their lands Joshua gave as an inheritance to the tribes of Israel according to their tribal divisions--",
    "the hill country, the western foothills, the Arabah, the mountain slopes, the desert and the Negev--the lands of the Hittites, Amorites, Canaanites, Perizzites, Hivites and Jebusites):",
    "the king of Jericho one the king of Ai (near Bethel) one",
    "the king of Jerusalem one the king of Hebron one",
    "the king of Jarmuth one the king of Lachish one",
    "the king of Eglon one the king of Gezer one",
    "the king of Debir one the king of Geder one",
    "the king of Hormah one the king of Arad one",
    "the king of Libnah one the king of Adullam one",
    "the king of Makkedah one the king of Bethel one",
    "the king of Tappuah one the king of Hepher one",
    "the king of Aphek one the king of Lasharon one",
    "the king of Madon one the king of Hazor one",
    "the king of Shimron Meron one the king of Acshaph one",
    "the king of Taanach one the king of Megiddo one",
    "the king of Kedesh one the king of Jokneam in Carmel one",
    "the king of Dor (in Naphoth Dor) one the king of Goyim in Gilgal one",
    "the king of Tirzah one thirty-one kings in all."
  ],
  "Joshua-12": [
    "When Joshua was old and well advanced in years, the LORD said to him, \"You are very old, and there are still very large areas of land to be taken over.",
    "\"This is the land that remains: all the regions of the Philistines and Geshurites:",
    "from the Shihor River on the east of Egypt to the territory of Ekron on the north, all of it counted as Canaanite (the territory of the five Philistine rulers in Gaza, Ashdod, Ashkelon, Gath and Ekron--that of the Avvites);",
    "from the south, all the land of the Canaanites, from Arah of the Sidonians as far as Aphek, the region of the Amorites,",
    "the area of the Gebalites; and all Lebanon to the east, from Baal Gad below Mount Hermon to Lebo Hamath.",
    "\"As for all the inhabitants of the mountain regions from Lebanon to Misrephoth Maim, that is, all the Sidonians, I myself will drive them out before the Israelites. Be sure to allocate this land to Israel for an inheritance, as I have instructed you,",
    "and divide it as an inheritance among the nine tribes and half of the tribe of Manasseh.\"",
    "The other half of Manasseh, the Reubenites and the Gadites had received the inheritance that Moses had given them east of the Jordan, as he, the servant of the LORD, had assigned it to them.",
    "It extended from Aroer on the rim of the Arnon Gorge, and from the town in the middle of the gorge, and included the whole plateau of Medeba as far as Dibon,",
    "and all the towns of Sihon king of the Amorites, who ruled in Heshbon, out to the border of the Ammonites.",
    "It also included Gilead, the territory of the people of Geshur and Maacah, all of Mount Hermon and all Bashan as far as Salecah--",
    "that is, the whole kingdom of Og in Bashan, who had reigned in Ashtaroth and Edrei and had survived as one of the last of the Rephaites. Moses had defeated them and taken over their land.",
    "But the Israelites did not drive out the people of Geshur and Maacah, so they continue to live among the Israelites to this day.",
    "But to the tribe of Levi he gave no inheritance, since the offerings made by fire to the LORD, the God of Israel, are their inheritance, as he promised them.",
    "This is what Moses had given to the tribe of Reuben, clan by clan:",
    "The territory from Aroer on the rim of the Arnon Gorge, and from the town in the middle of the gorge, and the whole plateau past Medeba",
    "to Heshbon and all its towns on the plateau, including Dibon, Bamoth Baal, Beth Baal Meon,",
    "Jahaz, Kedemoth, Mephaath,",
    "Kiriathaim, Sibmah, Zereth Shahar on the hill in the valley,",
    "Beth Peor, the slopes of Pisgah, and Beth Jeshimoth",
    "#NAME?",
    "In addition to those slain in battle, the Israelites had put to the sword Balaam son of Beor, who practiced divination.",
    "The boundary of the Reubenites was the bank of the Jordan. These towns and their villages were the inheritance of the Reubenites, clan by clan.",
    "This is what Moses had given to the tribe of Gad, clan by clan:",
    "The territory of Jazer, all the towns of Gilead and half the Ammonite country as far as Aroer, near Rabbah;",
    "and from Heshbon to Ramath Mizpah and Betonim, and from Mahanaim to the territory of Debir;",
    "and in the valley, Beth Haram, Beth Nimrah, Succoth and Zaphon with the rest of the realm of Sihon king of Heshbon (the east side of the Jordan, the territory up to the end of the Sea of Kinnereth).",
    "These towns and their villages were the inheritance of the Gadites, clan by clan.",
    "This is what Moses had given to the half-tribe of Manasseh, that is, to half the family of the descendants of Manasseh, clan by clan:",
    "The territory extending from Mahanaim and including all of Bashan, the entire realm of Og king of Bashan--all the settlements of Jair in Bashan, sixty towns,",
    "half of Gilead, and Ashtaroth and Edrei (the royal cities of Og in Bashan). This was for the descendants of Makir son of Manasseh--for half of the sons of Makir, clan by clan.",
    "This is the inheritance Moses had given when he was in the plains of Moab across the Jordan east of Jericho.",
    "But to the tribe of Levi, Moses had given no inheritance; the LORD, the God of Israel, is their inheritance, as he promised them."
  ],
  "Joshua-13": [
    "Now these are the areas the Israelites received as an inheritance in the land of Canaan, which Eleazar the priest, Joshua son of Nun and the heads of the tribal clans of Israel allotted to them.",
    "Their inheritances were assigned by lot to the nine-and-a-half tribes, as the LORD had commanded through Moses.",
    "Moses had granted the two-and-a-half tribes their inheritance east of the Jordan but had not granted the Levites an inheritance among the rest,",
    "for the sons of Joseph had become two tribes--Manasseh and Ephraim. The Levites received no share of the land but only towns to live in, with pasturelands for their flocks and herds.",
    "So the Israelites divided the land, just as the LORD had commanded Moses.",
    "Now the men of Judah approached Joshua at Gilgal, and Caleb son of Jephunneh the Kenizzite said to him, \"You know what the LORD said to Moses the man of God at Kadesh Barnea about you and me.",
    "I was forty years old when Moses the servant of the LORD sent me from Kadesh Barnea to explore the land. And I brought him back a report according to my convictions,",
    "but my brothers who went up with me made the hearts of the people melt with fear. I, however, followed the LORD my God wholeheartedly.",
    "So on that day Moses swore to me, 'The land on which your feet have walked will be your inheritance and that of your children forever, because you have followed the LORD my God wholeheartedly.'",
    "\"Now then, just as the LORD promised, he has kept me alive for forty-five years since the time he said this to Moses, while Israel moved about in the desert. So here I am today, eighty-five years old!",
    "I am still as strong today as the day Moses sent me out; I'm just as vigorous to go out to battle now as I was then.",
    "Now give me this hill country that the LORD promised me that day. You yourself heard then that the Anakites were there and their cities were large and fortified, but, the LORD helping me, I will drive them out just as he said.\"",
    "Then Joshua blessed Caleb son of Jephunneh and gave him Hebron as his inheritance.",
    "So Hebron has belonged to Caleb son of Jephunneh the Kenizzite ever since, because he followed the LORD, the God of Israel, wholeheartedly.",
    "(Hebron used to be called Kiriath Arba after Arba, who was the greatest man among the Anakites.) Then the land had rest from war."
  ],
  "Joshua-14": [
    "The allotment for the tribe of Judah, clan by clan, extended down to the territory of Edom, to the Desert of Zin in the extreme south.",
    "Their southern boundary started from the bay at the southern end of the Salt Sea,",
    "crossed south of Scorpion Pass, continued on to Zin and went over to the south of Kadesh Barnea. Then it ran past Hezron up to Addar and curved around to Karka.",
    "It then passed along to Azmon and joined the Wadi of Egypt, ending at the sea. This is their southern boundary.",
    "The eastern boundary is the Salt Sea as far as the mouth of the Jordan. The northern boundary started from the bay of the sea at the mouth of the Jordan,",
    "went up to Beth Hoglah and continued north of Beth Arabah to the Stone of Bohan son of Reuben.",
    "The boundary then went up to Debir from the Valley of Achor and turned north to Gilgal, which faces the Pass of Adummim south of the gorge. It continued along to the waters of En Shemesh and came out at En Rogel.",
    "Then it ran up the Valley of Ben Hinnom along the southern slope of the Jebusite city (that is, Jerusalem). From there it climbed to the top of the hill west of the Hinnom Valley at the northern end of the Valley of Rephaim.",
    "From the hilltop the boundary headed toward the spring of the waters of Nephtoah, came out at the towns of Mount Ephron and went down toward Baalah (that is, Kiriath Jearim).",
    "Then it curved westward from Baalah to Mount Seir, ran along the northern slope of Mount Jearim (that is, Kesalon), continued down to Beth Shemesh and crossed to Timnah.",
    "It went to the northern slope of Ekron, turned toward Shikkeron, passed along to Mount Baalah and reached Jabneel. The boundary ended at the sea.",
    "The western boundary is the coastline of the Great Sea. These are the boundaries around the people of Judah by their clans.",
    "In accordance with the LORD'S command to him, Joshua gave to Caleb son of Jephunneh a portion in Judah--Kiriath Arba, that is, Hebron. (Arba was the forefather of Anak.)",
    "From Hebron Caleb drove out the three Anakites--Sheshai, Ahiman and Talmai--descendants of Anak.",
    "From there he marched against the people living in Debir (formerly called Kiriath Sepher).",
    "And Caleb said, \"I will give my daughter Acsah in marriage to the man who attacks and captures Kiriath Sepher.\"",
    "Othniel son of Kenaz, Caleb's brother, took it; so Caleb gave his daughter Acsah to him in marriage.",
    "One day when she came to Othniel, she urged him to ask her father for a field. When she got off her donkey, Caleb asked her, \"What can I do for you?\"",
    "She replied, \"Do me a special favor. Since you have given me land in the Negev, give me also springs of water.\" So Caleb gave her the upper and lower springs.",
    "This is the inheritance of the tribe of Judah, clan by clan:",
    "The southernmost towns of the tribe of Judah in the Negev toward the boundary of Edom were: Kabzeel, Eder, Jagur,",
    "Kinah, Dimonah, Adadah,",
    "Kedesh, Hazor, Ithnan,",
    "Ziph, Telem, Bealoth,",
    "Hazor Hadattah, Kerioth Hezron (that is, Hazor),",
    "Amam, Shema, Moladah,",
    "Hazar Gaddah, Heshmon, Beth Pelet,",
    "Hazar Shual, Beersheba, Biziothiah,",
    "Baalah, Iim, Ezem,",
    "Eltolad, Kesil, Hormah,",
    "Ziklag, Madmannah, Sansannah,",
    "Lebaoth, Shilhim, Ain and Rimmon--a total of twenty-nine towns and their villages.",
    "In the western foothills: Eshtaol, Zorah, Ashnah,",
    "Zanoah, En Gannim, Tappuah, Enam,",
    "Jarmuth, Adullam, Socoh, Azekah,",
    "Shaaraim, Adithaim and Gederah (or Gederothaim)--fourteen towns and their villages.",
    "Zenan, Hadashah, Migdal Gad,",
    "Dilean, Mizpah, Joktheel,",
    "Lachish, Bozkath, Eglon,",
    "Cabbon, Lahmas, Kitlish,",
    "Gederoth, Beth Dagon, Naamah and Makkedah--sixteen towns and their villages.",
    "Libnah, Ether, Ashan,",
    "Iphtah, Ashnah, Nezib,",
    "Keilah, Aczib and Mareshah--nine towns and their villages.",
    "Ekron, with its surrounding settlements and villages;",
    "west of Ekron, all that were in the vicinity of Ashdod, together with their villages;",
    "Ashdod, its surrounding settlements and villages; and Gaza, its settlements and villages, as far as the Wadi of Egypt and the coastline of the Great Sea.",
    "In the hill country: Shamir, Jattir, Socoh,",
    "Dannah, Kiriath Sannah (that is, Debir),",
    "Anab, Eshtemoh, Anim,",
    "Goshen, Holon and Giloh--eleven towns and their villages.",
    "Arab, Dumah, Eshan,",
    "Janim, Beth Tappuah, Aphekah,",
    "Humtah, Kiriath Arba (that is, Hebron) and Zior--nine towns and their villages.",
    "Maon, Carmel, Ziph, Juttah,",
    "Jezreel, Jokdeam, Zanoah,",
    "Kain, Gibeah and Timnah--ten towns and their villages.",
    "Halhul, Beth Zur, Gedor,",
    "Maarath, Beth Anoth and Eltekon--six towns and their villages.",
    "Kiriath Baal (that is, Kiriath Jearim) and Rabbah--two towns and their villages.",
    "In the desert: Beth Arabah, Middin, Secacah,",
    "Nibshan, the City of Salt and En Gedi--six towns and their villages.",
    "Judah could not dislodge the Jebusites, who were living in Jerusalem; to this day the Jebusites live there with the people of Judah."
  ],
  "Joshua-15": [
    "The allotment for Joseph began at the Jordan of Jericho, east of the waters of Jericho, and went up from there through the desert into the hill country of Bethel.",
    "It went on from Bethel (that is, Luz), crossed over to the territory of the Arkites in Ataroth,",
    "descended westward to the territory of the Japhletites as far as the region of Lower Beth Horon and on to Gezer, ending at the sea.",
    "So Manasseh and Ephraim, the descendants of Joseph, received their inheritance.",
    "This was the territory of Ephraim, clan by clan: The boundary of their inheritance went from Ataroth Addar in the east to Upper Beth Horon",
    "and continued to the sea. From Micmethath on the north it curved eastward to Taanath Shiloh, passing by it to Janoah on the east.",
    "Then it went down from Janoah to Ataroth and Naarah, touched Jericho and came out at the Jordan.",
    "From Tappuah the border went west to the Kanah Ravine and ended at the sea. This was the inheritance of the tribe of the Ephraimites, clan by clan.",
    "It also included all the towns and their villages that were set aside for the Ephraimites within the inheritance of the Manassites.",
    "They did not dislodge the Canaanites living in Gezer; to this day the Canaanites live among the people of Ephraim but are required to do forced labor."
  ],
  "Joshua-16": [
    "This was the allotment for the tribe of Manasseh as Joseph's firstborn, that is, for Makir, Manasseh's firstborn. Makir was the ancestor of the Gileadites, who had received Gilead and Bashan because the Makirites were great soldiers.",
    "So this allotment was for the rest of the people of Manasseh--the clans of Abiezer, Helek, Asriel, Shechem, Hepher and Shemida. These are the other male descendants of Manasseh son of Joseph by their clans.",
    "Now Zelophehad son of Hepher, the son of Gilead, the son of Makir, the son of Manasseh, had no sons but only daughters, whose names were Mahlah, Noah, Hoglah, Milcah and Tirzah.",
    "They went to Eleazar the priest, Joshua son of Nun, and the leaders and said, \"The LORD commanded Moses to give us an inheritance among our brothers.\" So Joshua gave them an inheritance along with the brothers of their father, according to the LORD'S command.",
    "Manasseh's share consisted of ten tracts of land besides Gilead and Bashan east of the Jordan,",
    "because the daughters of the tribe of Manasseh received an inheritance among the sons. The land of Gilead belonged to the rest of the descendants of Manasseh.",
    "The territory of Manasseh extended from Asher to Micmethath east of Shechem. The boundary ran southward from there to include the people living at En Tappuah.",
    "(Manasseh had the land of Tappuah, but Tappuah itself, on the boundary of Manasseh, belonged to the Ephraimites.)",
    "Then the boundary continued south to the Kanah Ravine. There were towns belonging to Ephraim lying among the towns of Manasseh, but the boundary of Manasseh was the northern side of the ravine and ended at the sea.",
    "On the south the land belonged to Ephraim, on the north to Manasseh. The territory of Manasseh reached the sea and bordered Asher on the north and Issachar on the east.",
    "Within Issachar and Asher, Manasseh also had Beth Shan, Ibleam and the people of Dor, Endor, Taanach and Megiddo, together with their surrounding settlements (the third in the list is Naphoth).",
    "Yet the Manassites were not able to occupy these towns, for the Canaanites were determined to live in that region.",
    "However, when the Israelites grew stronger, they subjected the Canaanites to forced labor but did not drive them out completely.",
    "The people of Joseph said to Joshua, \"Why have you given us only one allotment and one portion for an inheritance? We are a numerous people and the LORD has blessed us abundantly.\"",
    "\"If you are so numerous,\" Joshua answered, \"and if the hill country of Ephraim is too small for you, go up into the forest and clear land for yourselves there in the land of the Perizzites and Rephaites.\"",
    "The people of Joseph replied, \"The hill country is not enough for us, and all the Canaanites who live in the plain have iron chariots, both those in Beth Shan and its settlements and those in the Valley of Jezreel.\"",
    "But Joshua said to the house of Joseph--to Ephraim and Manasseh--\"You are numerous and very powerful. You will have not only one allotment",
    "but the forested hill country as well. Clear it, and its farthest limits will be yours; though the Canaanites have iron chariots and though they are strong, you can drive them out.\""
  ],
  "Joshua-17": [
    "The whole assembly of the Israelites gathered at Shiloh and set up the Tent of Meeting there. The country was brought under their control,",
    "but there were still seven Israelite tribes who had not yet received their inheritance.",
    "So Joshua said to the Israelites: \"How long will you wait before you begin to take possession of the land that the LORD, the God of your fathers, has given you?",
    "Appoint three men from each tribe. I will send them out to make a survey of the land and to write a description of it, according to the inheritance of each. Then they will return to me.",
    "You are to divide the land into seven parts. Judah is to remain in its territory on the south and the house of Joseph in its territory on the north.",
    "After you have written descriptions of the seven parts of the land, bring them here to me and I will cast lots for you in the presence of the LORD our God.",
    "The Levites, however, do not get a portion among you, because the priestly service of the LORD is their inheritance. And Gad, Reuben and the half-tribe of Manasseh have already received their inheritance on the east side of the Jordan. Moses the servant of the LORD gave it to them.\"",
    "As the men started on their way to map out the land, Joshua instructed them, \"Go and make a survey of the land and write a description of it. Then return to me, and I will cast lots for you here at Shiloh in the presence of the LORD.\"",
    "So the men left and went through the land. They wrote its description on a scroll, town by town, in seven parts, and returned to Joshua in the camp at Shiloh.",
    "Joshua then cast lots for them in Shiloh in the presence of the LORD, and there he distributed the land to the Israelites according to their tribal divisions.",
    "The lot came up for the tribe of Benjamin, clan by clan. Their allotted territory lay between the tribes of Judah and Joseph:",
    "On the north side their boundary began at the Jordan, passed the northern slope of Jericho and headed west into the hill country, coming out at the desert of Beth Aven.",
    "From there it crossed to the south slope of Luz (that is, Bethel) and went down to Ataroth Addar on the hill south of Lower Beth Horon.",
    "From the hill facing Beth Horon on the south the boundary turned south along the western side and came out at Kiriath Baal (that is, Kiriath Jearim), a town of the people of Judah. This was the western side.",
    "The southern side began at the outskirts of Kiriath Jearim on the west, and the boundary came out at the spring of the waters of Nephtoah.",
    "The boundary went down to the foot of the hill facing the Valley of Ben Hinnom, north of the Valley of Rephaim. It continued down the Hinnom Valley along the southern slope of the Jebusite city and so to En Rogel.",
    "It then curved north, went to En Shemesh, continued to Geliloth, which faces the Pass of Adummim, and ran down to the Stone of Bohan son of Reuben.",
    "It continued to the northern slope of Beth Arabah and on down into the Arabah.",
    "It then went to the northern slope of Beth Hoglah and came out at the northern bay of the Salt Sea, at the mouth of the Jordan in the south. This was the southern boundary.",
    "The Jordan formed the boundary on the eastern side. These were the boundaries that marked out the inheritance of the clans of Benjamin on all sides.",
    "The tribe of Benjamin, clan by clan, had the following cities: Jericho, Beth Hoglah, Emek Keziz,",
    "Beth Arabah, Zemaraim, Bethel,",
    "Avvim, Parah, Ophrah,",
    "Kephar Ammoni, Ophni and Geba--twelve towns and their villages.",
    "Gibeon, Ramah, Beeroth,",
    "Mizpah, Kephirah, Mozah,",
    "Rekem, Irpeel, Taralah,",
    "Zelah, Haeleph, the Jebusite city (that is, Jerusalem), Gibeah and Kiriath--fourteen towns and their villages. This was the inheritance of Benjamin for its clans."
  ],
  "Joshua-18": [
    "The second lot came out for the tribe of Simeon, clan by clan. Their inheritance lay within the territory of Judah.",
    "It included: Beersheba (or Sheba), Moladah,",
    "Hazar Shual, Balah, Ezem,",
    "Eltolad, Bethul, Hormah,",
    "Ziklag, Beth Marcaboth, Hazar Susah,",
    "Beth Lebaoth and Sharuhen--thirteen towns and their villages;",
    "Ain, Rimmon, Ether and Ashan--four towns and their villages--",
    "and all the villages around these towns as far as Baalath Beer (Ramah in the Negev). This was the inheritance of the tribe of the Simeonites, clan by clan.",
    "The inheritance of the Simeonites was taken from the share of Judah, because Judah's portion was more than they needed. So the Simeonites received their inheritance within the territory of Judah.",
    "The third lot came up for Zebulun, clan by clan: The boundary of their inheritance went as far as Sarid.",
    "Going west it ran to Maralah, touched Dabbesheth, and extended to the ravine near Jokneam.",
    "It turned east from Sarid toward the sunrise to the territory of Kisloth Tabor and went on to Daberath and up to Japhia.",
    "Then it continued eastward to Gath Hepher and Eth Kazin; it came out at Rimmon and turned toward Neah.",
    "There the boundary went around on the north to Hannathon and ended at the Valley of Iphtah El.",
    "Included were Kattath, Nahalal, Shimron, Idalah and Bethlehem. There were twelve towns and their villages.",
    "These towns and their villages were the inheritance of Zebulun, clan by clan.",
    "The fourth lot came out for Issachar, clan by clan.",
    "Their territory included: Jezreel, Kesulloth, Shunem,",
    "Hapharaim, Shion, Anaharath,",
    "Rabbith, Kishion, Ebez,",
    "Remeth, En Gannim, En Haddah and Beth Pazzez.",
    "The boundary touched Tabor, Shahazumah and Beth Shemesh, and ended at the Jordan. There were sixteen towns and their villages.",
    "These towns and their villages were the inheritance of the tribe of Issachar, clan by clan.",
    "The fifth lot came out for the tribe of Asher, clan by clan.",
    "Their territory included: Helkath, Hali, Beten, Acshaph,",
    "Allammelech, Amad and Mishal. On the west the boundary touched Carmel and Shihor Libnath.",
    "It then turned east toward Beth Dagon, touched Zebulun and the Valley of Iphtah El, and went north to Beth Emek and Neiel, passing Cabul on the left.",
    "It went to Abdon, Rehob, Hammon and Kanah, as far as Greater Sidon.",
    "The boundary then turned back toward Ramah and went to the fortified city of Tyre, turned toward Hosah and came out at the sea in the region of Aczib,",
    "Ummah, Aphek and Rehob. There were twenty-two towns and their villages.",
    "These towns and their villages were the inheritance of the tribe of Asher, clan by clan.",
    "The sixth lot came out for Naphtali, clan by clan:",
    "Their boundary went from Heleph and the large tree in Zaanannim, passing Adami Nekeb and Jabneel to Lakkum and ending at the Jordan.",
    "The boundary ran west through Aznoth Tabor and came out at Hukkok. It touched Zebulun on the south, Asher on the west and the Jordan on the east.",
    "The fortified cities were Ziddim, Zer, Hammath, Rakkath, Kinnereth,",
    "Adamah, Ramah, Hazor,",
    "Kedesh, Edrei, En Hazor,",
    "Iron, Migdal El, Horem, Beth Anath and Beth Shemesh. There were nineteen towns and their villages.",
    "These towns and their villages were the inheritance of the tribe of Naphtali, clan by clan.",
    "The seventh lot came out for the tribe of Dan, clan by clan.",
    "The territory of their inheritance included: Zorah, Eshtaol, Ir Shemesh,",
    "Shaalabbin, Aijalon, Ithlah,",
    "Elon, Timnah, Ekron,",
    "Eltekeh, Gibbethon, Baalath,",
    "Jehud, Bene Berak, Gath Rimmon,",
    "Me Jarkon and Rakkon, with the area facing Joppa.",
    "(But the Danites had difficulty taking possession of their territory, so they went up and attacked Leshem, took it, put it to the sword and occupied it. They settled in Leshem and named it Dan after their forefather.)",
    "These towns and their villages were the inheritance of the tribe of Dan, clan by clan.",
    "When they had finished dividing the land into its allotted portions, the Israelites gave Joshua son of Nun an inheritance among them,",
    "as the LORD had commanded. They gave him the town he asked for--Timnath Serah in the hill country of Ephraim. And he built up the town and settled there.",
    "These are the territories that Eleazar the priest, Joshua son of Nun and the heads of the tribal clans of Israel assigned by lot at Shiloh in the presence of the LORD at the entrance to the Tent of Meeting. And so they finished dividing the land."
  ],
  "Joshua-19": [
    "Then the LORD said to Joshua:",
    "\"Tell the Israelites to designate the cities of refuge, as I instructed you through Moses,",
    "so that anyone who kills a person accidentally and unintentionally may flee there and find protection from the avenger of blood.",
    "\"When he flees to one of these cities, he is to stand in the entrance of the city gate and state his case before the elders of that city. Then they are to admit him into their city and give him a place to live with them.",
    "If the avenger of blood pursues him, they must not surrender the one accused, because he killed his neighbor unintentionally and without malice aforethought.",
    "He is to stay in that city until he has stood trial before the assembly and until the death of the high priest who is serving at that time. Then he may go back to his own home in the town from which he fled.\"",
    "So they set apart Kedesh in Galilee in the hill country of Naphtali, Shechem in the hill country of Ephraim, and Kiriath Arba (that is, Hebron) in the hill country of Judah.",
    "On the east side of the Jordan of Jericho they designated Bezer in the desert on the plateau in the tribe of Reuben, Ramoth in Gilead in the tribe of Gad, and Golan in Bashan in the tribe of Manasseh.",
    "Any of the Israelites or any alien living among them who killed someone accidentally could flee to these designated cities and not be killed by the avenger of blood prior to standing trial before the assembly."
  ],
  "Joshua-20": [
    "Now the family heads of the Levites approached Eleazar the priest, Joshua son of Nun, and the heads of the other tribal families of Israel",
    "at Shiloh in Canaan and said to them, \"The LORD commanded through Moses that you give us towns to live in, with pasturelands for our livestock.\"",
    "So, as the LORD had commanded, the Israelites gave the Levites the following towns and pasturelands out of their own inheritance:",
    "The first lot came out for the Kohathites, clan by clan. The Levites who were descendants of Aaron the priest were allotted thirteen towns from the tribes of Judah, Simeon and Benjamin.",
    "The rest of Kohath's descendants were allotted ten towns from the clans of the tribes of Ephraim, Dan and half of Manasseh.",
    "The descendants of Gershon were allotted thirteen towns from the clans of the tribes of Issachar, Asher, Naphtali and the half-tribe of Manasseh in Bashan.",
    "The descendants of Merari, clan by clan, received twelve towns from the tribes of Reuben, Gad and Zebulun.",
    "So the Israelites allotted to the Levites these towns and their pasturelands, as the LORD had commanded through Moses.",
    "From the tribes of Judah and Simeon they allotted the following towns by name",
    "(these towns were assigned to the descendants of Aaron who were from the Kohathite clans of the Levites, because the first lot fell to them):",
    "They gave them Kiriath Arba (that is, Hebron), with its surrounding pastureland, in the hill country of Judah. (Arba was the forefather of Anak.)",
    "But the fields and villages around the city they had given to Caleb son of Jephunneh as his possession.",
    "So to the descendants of Aaron the priest they gave Hebron (a city of refuge for one accused of murder), Libnah,",
    "Jattir, Eshtemoa,",
    "Holon, Debir,",
    "Ain, Juttah and Beth Shemesh, together with their pasturelands--nine towns from these two tribes.",
    "And from the tribe of Benjamin they gave them Gibeon, Geba,",
    "Anathoth and Almon, together with their pasturelands--four towns.",
    "All the towns for the priests, the descendants of Aaron, were thirteen, together with their pasturelands.",
    "The rest of the Kohathite clans of the Levites were allotted towns from the tribe of Ephraim:",
    "In the hill country of Ephraim they were given Shechem (a city of refuge for one accused of murder) and Gezer,",
    "Kibzaim and Beth Horon, together with their pasturelands--four towns.",
    "Also from the tribe of Dan they received Eltekeh, Gibbethon,",
    "Aijalon and Gath Rimmon, together with their pasturelands--four towns.",
    "From half the tribe of Manasseh they received Taanach and Gath Rimmon, together with their pasturelands--two towns.",
    "All these ten towns and their pasturelands were given to the rest of the Kohathite clans.",
    "The Levite clans of the Gershonites were given: from the half-tribe of Manasseh, Golan in Bashan (a city of refuge for one accused of murder) and Be Eshtarah, together with their pasturelands--two towns;",
    "from the tribe of Issachar, Kishion, Daberath,",
    "Jarmuth and En Gannim, together with their pasturelands--four towns;",
    "from the tribe of Asher, Mishal, Abdon,",
    "Helkath and Rehob, together with their pasturelands--four towns;",
    "from the tribe of Naphtali, Kedesh in Galilee (a city of refuge for one accused of murder), Hammoth Dor and Kartan, together with their pasturelands--three towns.",
    "All the towns of the Gershonite clans were thirteen, together with their pasturelands.",
    "The Merarite clans (the rest of the Levites) were given: from the tribe of Zebulun, Jokneam, Kartah,",
    "Dimnah and Nahalal, together with their pasturelands--four towns;",
    "from the tribe of Reuben, Bezer, Jahaz,",
    "Kedemoth and Mephaath, together with their pasturelands--four towns;",
    "from the tribe of Gad, Ramoth in Gilead (a city of refuge for one accused of murder), Mahanaim,",
    "Heshbon and Jazer, together with their pasturelands--four towns in all.",
    "All the towns allotted to the Merarite clans, who were the rest of the Levites, were twelve.",
    "The towns of the Levites in the territory held by the Israelites were forty-eight in all, together with their pasturelands.",
    "Each of these towns had pasturelands surrounding it; this was true for all these towns.",
    "So the LORD gave Israel all the land he had sworn to give their forefathers, and they took possession of it and settled there.",
    "The LORD gave them rest on every side, just as he had sworn to their forefathers. Not one of their enemies withstood them; the LORD handed all their enemies over to them.",
    "Not one of all the LORD'S good promises to the house of Israel failed; every one was fulfilled."
  ],
  "Joshua-21": [
    "Then Joshua summoned the Reubenites, the Gadites and the half-tribe of Manasseh",
    "and said to them, \"You have done all that Moses the servant of the LORD commanded, and you have obeyed me in everything I commanded.",
    "For a long time now--to this very day--you have not deserted your brothers but have carried out the mission the LORD your God gave you.",
    "Now that the LORD your God has given your brothers rest as he promised, return to your homes in the land that Moses the servant of the LORD gave you on the other side of the Jordan.",
    "But be very careful to keep the commandment and the law that Moses the servant of the LORD gave you: to love the LORD your God, to walk in all his ways, to obey his commands, to hold fast to him and to serve him with all your heart and all your soul.\"",
    "Then Joshua blessed them and sent them away, and they went to their homes.",
    "(To the half-tribe of Manasseh Moses had given land in Bashan, and to the other half of the tribe Joshua gave land on the west side of the Jordan with their brothers.) When Joshua sent them home, he blessed them,",
    "saying, \"Return to your homes with your great wealth--with large herds of livestock, with silver, gold, bronze and iron, and a great quantity of clothing--and divide with your brothers the plunder from your enemies.\"",
    "So the Reubenites, the Gadites and the half-tribe of Manasseh left the Israelites at Shiloh in Canaan to return to Gilead, their own land, which they had acquired in accordance with the command of the LORD through Moses.",
    "When they came to Geliloth near the Jordan in the land of Canaan, the Reubenites, the Gadites and the half-tribe of Manasseh built an imposing altar there by the Jordan.",
    "And when the Israelites heard that they had built the altar on the border of Canaan at Geliloth near the Jordan on the Israelite side,",
    "the whole assembly of Israel gathered at Shiloh to go to war against them.",
    "So the Israelites sent Phinehas son of Eleazar, the priest, to the land of Gilead--to Reuben, Gad and the half-tribe of Manasseh.",
    "With him they sent ten of the chief men, one for each of the tribes of Israel, each the head of a family division among the Israelite clans.",
    "When they went to Gilead--to Reuben, Gad and the half-tribe of Manasseh--they said to them:",
    "\"The whole assembly of the LORD says: 'How could you break faith with the God of Israel like this? How could you turn away from the LORD and build yourselves an altar in rebellion against him now?",
    "Was not the sin of Peor enough for us? Up to this very day we have not cleansed ourselves from that sin, even though a plague fell on the community of the LORD!",
    "And are you now turning away from the LORD? \"'If you rebel against the LORD today, tomorrow he will be angry with the whole community of Israel.",
    "If the land you possess is defiled, come over to the LORD'S land, where the LORD'S tabernacle stands, and share the land with us. But do not rebel against the LORD or against us by building an altar for yourselves, other than the altar of the LORD our God.",
    "When Achan son of Zerah acted unfaithfully regarding the devoted things, did not wrath come upon the whole community of Israel? He was not the only one who died for his sin.'\"",
    "Then Reuben, Gad and the half-tribe of Manasseh replied to the heads of the clans of Israel:",
    "\"The Mighty One, God, the LORD! The Mighty One, God, the LORD! He knows! And let Israel know! If this has been in rebellion or disobedience to the LORD, do not spare us this day.",
    "If we have built our own altar to turn away from the LORD and to offer burnt offerings and grain offerings, or to sacrifice fellowship offerings on it, may the LORD himself call us to account.",
    "\"No! We did it for fear that some day your descendants might say to ours, 'What do you have to do with the LORD, the God of Israel?",
    "The LORD has made the Jordan a boundary between us and you--you Reubenites and Gadites! You have no share in the LORD.' So your descendants might cause ours to stop fearing the LORD.",
    "\"That is why we said, 'Let us get ready and build an altar--but not for burnt offerings or sacrifices.'",
    "On the contrary, it is to be a witness between us and you and the generations that follow, that we will worship the LORD at his sanctuary with our burnt offerings, sacrifices and fellowship offerings. Then in the future your descendants will not be able to say to ours, 'You have no share in the LORD.'",
    "\"And we said, 'If they ever say this to us, or to our descendants, we will answer: Look at the replica of the LORD'S altar, which our fathers built, not for burnt offerings and sacrifices, but as a witness between us and you.'",
    "\"Far be it from us to rebel against the LORD and turn away from him today by building an altar for burnt offerings, grain offerings and sacrifices, other than the altar of the LORD our God that stands before his tabernacle.\"",
    "When Phinehas the priest and the leaders of the community--the heads of the clans of the Israelites--heard what Reuben, Gad and Manasseh had to say, they were pleased.",
    "And Phinehas son of Eleazar, the priest, said to Reuben, Gad and Manasseh, \"Today we know that the LORD is with us, because you have not acted unfaithfully toward the LORD in this matter. Now you have rescued the Israelites from the LORD'S hand.\"",
    "Then Phinehas son of Eleazar, the priest, and the leaders returned to Canaan from their meeting with the Reubenites and Gadites in Gilead and reported to the Israelites.",
    "They were glad to hear the report and praised God. And they talked no more about going to war against them to devastate the country where the Reubenites and the Gadites lived.",
    "And the Reubenites and the Gadites gave the altar this name: A Witness Between Us that the LORD is God."
  ],
  "Joshua-22": [
    "After a long time had passed and the LORD had given Israel rest from all their enemies around them, Joshua, by then old and well advanced in years,",
    "summoned all Israel--their elders, leaders, judges and officials--and said to them: \"I am old and well advanced in years.",
    "You yourselves have seen everything the LORD your God has done to all these nations for your sake; it was the LORD your God who fought for you.",
    "Remember how I have allotted as an inheritance for your tribes all the land of the nations that remain--the nations I conquered--between the Jordan and the Great Sea in the west.",
    "The LORD your God himself will drive them out of your way. He will push them out before you, and you will take possession of their land, as the LORD your God promised you.",
    "\"Be very strong; be careful to obey all that is written in the Book of the Law of Moses, without turning aside to the right or to the left.",
    "Do not associate with these nations that remain among you; do not invoke the names of their gods or swear by them. You must not serve them or bow down to them.",
    "But you are to hold fast to the LORD your God, as you have until now.",
    "\"The LORD has driven out before you great and powerful nations; to this day no one has been able to withstand you.",
    "One of you routs a thousand, because the LORD your God fights for you, just as he promised.",
    "So be very careful to love the LORD your God.",
    "\"But if you turn away and ally yourselves with the survivors of these nations that remain among you and if you intermarry with them and associate with them,",
    "then you may be sure that the LORD your God will no longer drive out these nations before you. Instead, they will become snares and traps for you, whips on your backs and thorns in your eyes, until you perish from this good land, which the LORD your God has given you.",
    "\"Now I am about to go the way of all the earth. You know with all your heart and soul that not one of all the good promises the LORD your God gave you has failed. Every promise has been fulfilled; not one has failed.",
    "But just as every good promise of the LORD your God has come true, so the LORD will bring on you all the evil he has threatened, until he has destroyed you from this good land he has given you.",
    "If you violate the covenant of the LORD your God, which he commanded you, and go and serve other gods and bow down to them, the LORD'S anger will burn against you, and you will quickly perish from the good land he has given you.\""
  ],
  "Joshua-23": [
    "Then Joshua assembled all the tribes of Israel at Shechem. He summoned the elders, leaders, judges and officials of Israel, and they presented themselves before God.",
    "Joshua said to all the people, \"This is what the LORD, the God of Israel, says: 'Long ago your forefathers, including Terah the father of Abraham and Nahor, lived beyond the River and worshiped other gods.",
    "But I took your father Abraham from the land beyond the River and led him throughout Canaan and gave him many descendants. I gave him Isaac,",
    "and to Isaac I gave Jacob and Esau. I assigned the hill country of Seir to Esau, but Jacob and his sons went down to Egypt.",
    "\"'Then I sent Moses and Aaron, and I afflicted the Egyptians by what I did there, and I brought you out.",
    "When I brought your fathers out of Egypt, you came to the sea, and the Egyptians pursued them with chariots and horsemen as far as the Red Sea.",
    "But they cried to the LORD for help, and he put darkness between you and the Egyptians; he brought the sea over them and covered them. You saw with your own eyes what I did to the Egyptians. Then you lived in the desert for a long time.",
    "\"'I brought you to the land of the Amorites who lived east of the Jordan. They fought against you, but I gave them into your hands. I destroyed them from before you, and you took possession of their land.",
    "When Balak son of Zippor, the king of Moab, prepared to fight against Israel, he sent for Balaam son of Beor to put a curse on you.",
    "But I would not listen to Balaam, so he blessed you again and again, and I delivered you out of his hand.",
    "\"'Then you crossed the Jordan and came to Jericho. The citizens of Jericho fought against you, as did also the Amorites, Perizzites, Canaanites, Hittites, Girgashites, Hivites and Jebusites, but I gave them into your hands.",
    "I sent the hornet ahead of you, which drove them out before you--also the two Amorite kings. You did not do it with your own sword and bow.",
    "So I gave you a land on which you did not toil and cities you did not build; and you live in them and eat from vineyards and olive groves that you did not plant.'",
    "\"Now fear the LORD and serve him with all faithfulness. Throw away the gods your forefathers worshiped beyond the River and in Egypt, and serve the LORD.",
    "But if serving the LORD seems undesirable to you, then choose for yourselves this day whom you will serve, whether the gods your forefathers served beyond the River, or the gods of the Amorites, in whose land you are living. But as for me and my household, we will serve the LORD.\"",
    "Then the people answered, \"Far be it from us to forsake the LORD to serve other gods!",
    "It was the LORD our God himself who brought us and our fathers up out of Egypt, from that land of slavery, and performed those great signs before our eyes. He protected us on our entire journey and among all the nations through which we traveled.",
    "And the LORD drove out before us all the nations, including the Amorites, who lived in the land. We too will serve the LORD, because he is our God.\"",
    "Joshua said to the people, \"You are not able to serve the LORD. He is a holy God; he is a jealous God. He will not forgive your rebellion and your sins.",
    "If you forsake the LORD and serve foreign gods, he will turn and bring disaster on you and make an end of you, after he has been good to you.\"",
    "But the people said to Joshua, \"No! We will serve the LORD.\"",
    "Then Joshua said, \"You are witnesses against yourselves that you have chosen to serve the LORD.\" \"Yes, we are witnesses,\" they replied.",
    "\"Now then,\" said Joshua, \"throw away the foreign gods that are among you and yield your hearts to the LORD, the God of Israel.\"",
    "And the people said to Joshua, \"We will serve the LORD our God and obey him.\"",
    "On that day Joshua made a covenant for the people, and there at Shechem he drew up for them decrees and laws.",
    "And Joshua recorded these things in the Book of the Law of God. Then he took a large stone and set it up there under the oak near the holy place of the LORD.",
    "\"See!\" he said to all the people. \"This stone will be a witness against us. It has heard all the words the LORD has said to us. It will be a witness against you if you are untrue to your God.\"",
    "Then Joshua sent the people away, each to his own inheritance.",
    "After these things, Joshua son of Nun, the servant of the LORD, died at the age of a hundred and ten.",
    "And they buried him in the land of his inheritance, at Timnath Serah in the hill country of Ephraim, north of Mount Gaash.",
    "Israel served the LORD throughout the lifetime of Joshua and of the elders who outlived him and who had experienced everything the LORD had done for Israel.",
    "And Joseph's bones, which the Israelites had brought up from Egypt, were buried at Shechem in the tract of land that Jacob bought for a hundred pieces of silver from the sons of Hamor, the father of Shechem. This became the inheritance of Joseph's descendants.",
    "And Eleazar son of Aaron died and was buried at Gibeah, which had been allotted to his son Phinehas in the hill country of Ephraim."
  ]
};