const Mark = {
  "Mark-0": [
    "The beginning of the gospel about Jesus Christ, the Son of God.",
    "It is written in Isaiah the prophet: \"I will send my messenger ahead of you, who will prepare your way\"--",
    "\"a voice of one calling in the desert, 'Prepare the way for the Lord, make straight paths for him.'\"",
    "And so John came, baptizing in the desert region and preaching a baptism of repentance for the forgiveness of sins.",
    "The whole Judean countryside and all the people of Jerusalem went out to him. Confessing their sins, they were baptized by him in the Jordan River.",
    "John wore clothing made of camel's hair, with a leather belt around his waist, and he ate locusts and wild honey.",
    "And this was his message: \"After me will come one more powerful than I, the thongs of whose sandals I am not worthy to stoop down and untie.",
    "I baptize you with water, but he will baptize you with the Holy Spirit.\"",
    "At that time Jesus came from Nazareth in Galilee and was baptized by John in the Jordan.",
    "As Jesus was coming up out of the water, he saw heaven being torn open and the Spirit descending on him like a dove.",
    "And a voice came from heaven: \"You are my Son, whom I love; with you I am well pleased.\"",
    "At once the Spirit sent him out into the desert,",
    "and he was in the desert forty days, being tempted by Satan. He was with the wild animals, and angels attended him.",
    "After John was put in prison, Jesus went into Galilee, proclaiming the good news of God.",
    "\"The time has come,\" he said. \"The kingdom of God is near. Repent and believe the good news!\"",
    "As Jesus walked beside the Sea of Galilee, he saw Simon and his brother Andrew casting a net into the lake, for they were fishermen.",
    "\"Come, follow me,\" Jesus said, \"and I will make you fishers of men.\"",
    "At once they left their nets and followed him.",
    "When he had gone a little farther, he saw James son of Zebedee and his brother John in a boat, preparing their nets.",
    "Without delay he called them, and they left their father Zebedee in the boat with the hired men and followed him.",
    "They went to Capernaum, and when the Sabbath came, Jesus went into the synagogue and began to teach.",
    "The people were amazed at his teaching, because he taught them as one who had authority, not as the teachers of the law.",
    "Just then a man in their synagogue who was possessed by an evil spirit cried out,",
    "\"What do you want with us, Jesus of Nazareth? Have you come to destroy us? I know who you are--the Holy One of God!\"",
    "\"Be quiet!\" said Jesus sternly. \"Come out of him!\"",
    "The evil spirit shook the man violently and came out of him with a shriek.",
    "The people were all so amazed that they asked each other, \"What is this? A new teaching--and with authority! He even gives orders to evil spirits and they obey him.\"",
    "News about him spread quickly over the whole region of Galilee.",
    "As soon as they left the synagogue, they went with James and John to the home of Simon and Andrew.",
    "Simon's mother-in-law was in bed with a fever, and they told Jesus about her.",
    "So he went to her, took her hand and helped her up. The fever left her and she began to wait on them.",
    "That evening after sunset the people brought to Jesus all the sick and demon-possessed.",
    "The whole town gathered at the door,",
    "and Jesus healed many who had various diseases. He also drove out many demons, but he would not let the demons speak because they knew who he was.",
    "Very early in the morning, while it was still dark, Jesus got up, left the house and went off to a solitary place, where he prayed.",
    "Simon and his companions went to look for him,",
    "and when they found him, they exclaimed: \"Everyone is looking for you!\"",
    "Jesus replied, \"Let us go somewhere else--to the nearby villages--so I can preach there also. That is why I have come.\"",
    "So he traveled throughout Galilee, preaching in their synagogues and driving out demons.",
    "A man with leprosy came to him and begged him on his knees, \"If you are willing, you can make me clean.\"",
    "Filled with compassion, Jesus reached out his hand and touched the man. \"I am willing,\" he said. \"Be clean!\"",
    "Immediately the leprosy left him and he was cured.",
    "Jesus sent him away at once with a strong warning:",
    "\"See that you don't tell this to anyone. But go, show yourself to the priest and offer the sacrifices that Moses commanded for your cleansing, as a testimony to them.\"",
    "Instead he went out and began to talk freely, spreading the news. As a result, Jesus could no longer enter a town openly but stayed outside in lonely places. Yet the people still came to him from everywhere."
  ],
  "Mark-1": [
    "A few days later, when Jesus again entered Capernaum, the people heard that he had come home.",
    "So many gathered that there was no room left, not even outside the door, and he preached the word to them.",
    "Some men came, bringing to him a paralytic, carried by four of them.",
    "Since they could not get him to Jesus because of the crowd, they made an opening in the roof above Jesus and, after digging through it, lowered the mat the paralyzed man was lying on.",
    "When Jesus saw their faith, he said to the paralytic, \"Son, your sins are forgiven.\"",
    "Now some teachers of the law were sitting there, thinking to themselves,",
    "\"Why does this fellow talk like that? He's blaspheming! Who can forgive sins but God alone?\"",
    "Immediately Jesus knew in his spirit that this was what they were thinking in their hearts, and he said to them, \"Why are you thinking these things?",
    "Which is easier: to say to the paralytic, 'Your sins are forgiven,' or to say, 'Get up, take your mat and walk'?",
    "But that you may know that the Son of Man has authority on earth to forgive sins. . . .\" He said to the paralytic,",
    "\"I tell you, get up, take your mat and go home.\"",
    "He got up, took his mat and walked out in full view of them all. This amazed everyone and they praised God, saying, \"We have never seen anything like this!\"",
    "Once again Jesus went out beside the lake. A large crowd came to him, and he began to teach them.",
    "As he walked along, he saw Levi son of Alphaeus sitting at the tax collector's booth. \"Follow me,\" Jesus told him, and Levi got up and followed him.",
    "While Jesus was having dinner at Levi's house, many tax collectors and \"sinners\" were eating with him and his disciples, for there were many who followed him.",
    "When the teachers of the law who were Pharisees saw him eating with the \"sinners\" and tax collectors, they asked his disciples: \"Why does he eat with tax collectors and 'sinners'?\"",
    "On hearing this, Jesus said to them, \"It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners.\"",
    "Now John's disciples and the Pharisees were fasting. Some people came and asked Jesus, \"How is it that John's disciples and the disciples of the Pharisees are fasting, but yours are not?\"",
    "Jesus answered, \"How can the guests of the bridegroom fast while he is with them? They cannot, so long as they have him with them.",
    "But the time will come when the bridegroom will be taken from them, and on that day they will fast.",
    "\"No one sews a patch of unshrunk cloth on an old garment. If he does, the new piece will pull away from the old, making the tear worse.",
    "And no one pours new wine into old wineskins. If he does, the wine will burst the skins, and both the wine and the wineskins will be ruined. No, he pours new wine into new wineskins.\"",
    "One Sabbath Jesus was going through the grainfields, and as his disciples walked along, they began to pick some heads of grain.",
    "The Pharisees said to him, \"Look, why are they doing what is unlawful on the Sabbath?\"",
    "He answered, \"Have you never read what David did when he and his companions were hungry and in need?",
    "In the days of Abiathar the high priest, he entered the house of God and ate the consecrated bread, which is lawful only for priests to eat. And he also gave some to his companions.\"",
    "Then he said to them, \"The Sabbath was made for man, not man for the Sabbath.",
    "So the Son of Man is Lord even of the Sabbath.\""
  ],
  "Mark-2": [
    "Another time he went into the synagogue, and a man with a shriveled hand was there.",
    "Some of them were looking for a reason to accuse Jesus, so they watched him closely to see if he would heal him on the Sabbath.",
    "Jesus said to the man with the shriveled hand, \"Stand up in front of everyone.\"",
    "Then Jesus asked them, \"Which is lawful on the Sabbath: to do good or to do evil, to save life or to kill?\" But they remained silent.",
    "He looked around at them in anger and, deeply distressed at their stubborn hearts, said to the man, \"Stretch out your hand.\" He stretched it out, and his hand was completely restored.",
    "Then the Pharisees went out and began to plot with the Herodians how they might kill Jesus.",
    "Jesus withdrew with his disciples to the lake, and a large crowd from Galilee followed.",
    "When they heard all he was doing, many people came to him from Judea, Jerusalem, Idumea, and the regions across the Jordan and around Tyre and Sidon.",
    "Because of the crowd he told his disciples to have a small boat ready for him, to keep the people from crowding him.",
    "For he had healed many, so that those with diseases were pushing forward to touch him.",
    "Whenever the evil spirits saw him, they fell down before him and cried out, \"You are the Son of God.\"",
    "But he gave them strict orders not to tell who he was.",
    "Jesus went up on a mountainside and called to him those he wanted, and they came to him.",
    "He appointed twelve--designating them apostles--that they might be with him and that he might send them out to preach",
    "and to have authority to drive out demons.",
    "These are the twelve he appointed: Simon (to whom he gave the name Peter);",
    "James son of Zebedee and his brother John (to them he gave the name Boanerges, which means Sons of Thunder);",
    "Andrew, Philip, Bartholomew, Matthew, Thomas, James son of Alphaeus, Thaddaeus, Simon the Zealot",
    "and Judas Iscariot, who betrayed him.",
    "Then Jesus entered a house, and again a crowd gathered, so that he and his disciples were not even able to eat.",
    "When his family heard about this, they went to take charge of him, for they said, \"He is out of his mind.\"",
    "And the teachers of the law who came down from Jerusalem said, \"He is possessed by Beelzebub! By the prince of demons he is driving out demons.\"",
    "So Jesus called them and spoke to them in parables: \"How can Satan drive out Satan?",
    "If a kingdom is divided against itself, that kingdom cannot stand.",
    "If a house is divided against itself, that house cannot stand.",
    "And if Satan opposes himself and is divided, he cannot stand; his end has come.",
    "In fact, no one can enter a strong man's house and carry off his possessions unless he first ties up the strong man. Then he can rob his house.",
    "I tell you the truth, all the sins and blasphemies of men will be forgiven them.",
    "But whoever blasphemes against the Holy Spirit will never be forgiven; he is guilty of an eternal sin.\"",
    "He said this because they were saying, \"He has an evil spirit.\"",
    "Then Jesus' mother and brothers arrived. Standing outside, they sent someone in to call him.",
    "A crowd was sitting around him, and they told him, \"Your mother and brothers are outside looking for you.\"",
    "\"Who are my mother and my brothers?\" he asked.",
    "Then he looked at those seated in a circle around him and said, \"Here are my mother and my brothers!",
    "Whoever does God's will is my brother and sister and mother.\""
  ],
  "Mark-3": [
    "Again Jesus began to teach by the lake. The crowd that gathered around him was so large that he got into a boat and sat in it out on the lake, while all the people were along the shore at the water's edge.",
    "He taught them many things by parables, and in his teaching said:",
    "\"Listen! A farmer went out to sow his seed.",
    "As he was scattering the seed, some fell along the path, and the birds came and ate it up.",
    "Some fell on rocky places, where it did not have much soil. It sprang up quickly, because the soil was shallow.",
    "But when the sun came up, the plants were scorched, and they withered because they had no root.",
    "Other seed fell among thorns, which grew up and choked the plants, so that they did not bear grain.",
    "Still other seed fell on good soil. It came up, grew and produced a crop, multiplying thirty, sixty, or even a hundred times.\"",
    "Then Jesus said, \"He who has ears to hear, let him hear.\"",
    "When he was alone, the Twelve and the others around him asked him about the parables.",
    "He told them, \"The secret of the kingdom of God has been given to you. But to those on the outside everything is said in parables",
    "so that, \"'they may be ever seeing but never perceiving, and ever hearing but never understanding; otherwise they might turn and be forgiven!'\"",
    "Then Jesus said to them, \"Don't you understand this parable? How then will you understand any parable?",
    "The farmer sows the word.",
    "Some people are like seed along the path, where the word is sown. As soon as they hear it, Satan comes and takes away the word that was sown in them.",
    "Others, like seed sown on rocky places, hear the word and at once receive it with joy.",
    "But since they have no root, they last only a short time. When trouble or persecution comes because of the word, they quickly fall away.",
    "Still others, like seed sown among thorns, hear the word;",
    "but the worries of this life, the deceitfulness of wealth and the desires for other things come in and choke the word, making it unfruitful.",
    "Others, like seed sown on good soil, hear the word, accept it, and produce a crop--thirty, sixty or even a hundred times what was sown.\"",
    "He said to them, \"Do you bring in a lamp to put it under a bowl or a bed? Instead, don't you put it on its stand?",
    "For whatever is hidden is meant to be disclosed, and whatever is concealed is meant to be brought out into the open.",
    "If anyone has ears to hear, let him hear.\"",
    "\"Consider carefully what you hear,\" he continued. \"With the measure you use, it will be measured to you--and even more.",
    "Whoever has will be given more; whoever does not have, even what he has will be taken from him.\"",
    "He also said, \"This is what the kingdom of God is like. A man scatters seed on the ground.",
    "Night and day, whether he sleeps or gets up, the seed sprouts and grows, though he does not know how.",
    "All by itself the soil produces grain--first the stalk, then the head, then the full kernel in the head.",
    "As soon as the grain is ripe, he puts the sickle to it, because the harvest has come.\"",
    "Again he said, \"What shall we say the kingdom of God is like, or what parable shall we use to describe it?",
    "It is like a mustard seed, which is the smallest seed you plant in the ground.",
    "Yet when planted, it grows and becomes the largest of all garden plants, with such big branches that the birds of the air can perch in its shade.\"",
    "With many similar parables Jesus spoke the word to them, as much as they could understand.",
    "He did not say anything to them without using a parable. But when he was alone with his own disciples, he explained everything.",
    "That day when evening came, he said to his disciples, \"Let us go over to the other side.\"",
    "Leaving the crowd behind, they took him along, just as he was, in the boat. There were also other boats with him.",
    "A furious squall came up, and the waves broke over the boat, so that it was nearly swamped.",
    "Jesus was in the stern, sleeping on a cushion. The disciples woke him and said to him, \"Teacher, don't you care if we drown?\"",
    "He got up, rebuked the wind and said to the waves, \"Quiet! Be still!\" Then the wind died down and it was completely calm.",
    "He said to his disciples, \"Why are you so afraid? Do you still have no faith?\"",
    "They were terrified and asked each other, \"Who is this? Even the wind and the waves obey him!\""
  ],
  "Mark-4": [
    "They went across the lake to the region of the Gerasenes.",
    "When Jesus got out of the boat, a man with an evil spirit came from the tombs to meet him.",
    "This man lived in the tombs, and no one could bind him any more, not even with a chain.",
    "For he had often been chained hand and foot, but he tore the chains apart and broke the irons on his feet. No one was strong enough to subdue him.",
    "Night and day among the tombs and in the hills he would cry out and cut himself with stones.",
    "When he saw Jesus from a distance, he ran and fell on his knees in front of him.",
    "He shouted at the top of his voice, \"What do you want with me, Jesus, Son of the Most High God? Swear to God that you won't torture me!\"",
    "For Jesus had said to him, \"Come out of this man, you evil spirit!\"",
    "Then Jesus asked him, \"What is your name?\" \"My name is Legion,\" he replied, \"for we are many.\"",
    "And he begged Jesus again and again not to send them out of the area.",
    "A large herd of pigs was feeding on the nearby hillside.",
    "The demons begged Jesus, \"Send us among the pigs; allow us to go into them.\"",
    "He gave them permission, and the evil spirits came out and went into the pigs. The herd, about two thousand in number, rushed down the steep bank into the lake and were drowned.",
    "Those tending the pigs ran off and reported this in the town and countryside, and the people went out to see what had happened.",
    "When they came to Jesus, they saw the man who had been possessed by the legion of demons, sitting there, dressed and in his right mind; and they were afraid.",
    "Those who had seen it told the people what had happened to the demon-possessed man--and told about the pigs as well.",
    "Then the people began to plead with Jesus to leave their region.",
    "As Jesus was getting into the boat, the man who had been demon-possessed begged to go with him.",
    "Jesus did not let him, but said, \"Go home to your family and tell them how much the Lord has done for you, and how he has had mercy on you.\"",
    "So the man went away and began to tell in the Decapolis how much Jesus had done for him. And all the people were amazed.",
    "When Jesus had again crossed over by boat to the other side of the lake, a large crowd gathered around him while he was by the lake.",
    "Then one of the synagogue rulers, named Jairus, came there. Seeing Jesus, he fell at his feet",
    "and pleaded earnestly with him, \"My little daughter is dying. Please come and put your hands on her so that she will be healed and live.\"",
    "So Jesus went with him. A large crowd followed and pressed around him.",
    "And a woman was there who had been subject to bleeding for twelve years.",
    "She had suffered a great deal under the care of many doctors and had spent all she had, yet instead of getting better she grew worse.",
    "When she heard about Jesus, she came up behind him in the crowd and touched his cloak,",
    "because she thought, \"If I just touch his clothes, I will be healed.\"",
    "Immediately her bleeding stopped and she felt in her body that she was freed from her suffering.",
    "At once Jesus realized that power had gone out from him. He turned around in the crowd and asked, \"Who touched my clothes?\"",
    "\"You see the people crowding against you,\" his disciples answered, \"and yet you can ask, 'Who touched me?'\"",
    "But Jesus kept looking around to see who had done it.",
    "Then the woman, knowing what had happened to her, came and fell at his feet and, trembling with fear, told him the whole truth.",
    "He said to her, \"Daughter, your faith has healed you. Go in peace and be freed from your suffering.\"",
    "While Jesus was still speaking, some men came from the house of Jairus, the synagogue ruler. \"Your daughter is dead,\" they said. \"Why bother the teacher any more?\"",
    "Ignoring what they said, Jesus told the synagogue ruler, \"Don't be afraid; just believe.\"",
    "He did not let anyone follow him except Peter, James and John the brother of James.",
    "When they came to the home of the synagogue ruler, Jesus saw a commotion, with people crying and wailing loudly.",
    "He went in and said to them, \"Why all this commotion and wailing? The child is not dead but asleep.\"",
    "But they laughed at him. After he put them all out, he took the child's father and mother and the disciples who were with him, and went in where the child was.",
    "He took her by the hand and said to her, \"Talitha koum!\" (which means, \"Little girl, I say to you, get up!\").",
    "Immediately the girl stood up and walked around (she was twelve years old). At this they were completely astonished.",
    "He gave strict orders not to let anyone know about this, and told them to give her something to eat."
  ],
  "Mark-5": [
    "Jesus left there and went to his hometown, accompanied by his disciples.",
    "When the Sabbath came, he began to teach in the synagogue, and many who heard him were amazed. \"Where did this man get these things?\" they asked. \"What's this wisdom that has been given him, that he even does miracles!",
    "Isn't this the carpenter? Isn't this Mary's son and the brother of James, Joseph, Judas and Simon? Aren't his sisters here with us?\" And they took offense at him.",
    "Jesus said to them, \"Only in his hometown, among his relatives and in his own house is a prophet without honor.\"",
    "He could not do any miracles there, except lay his hands on a few sick people and heal them.",
    "And he was amazed at their lack of faith. Then Jesus went around teaching from village to village.",
    "Calling the Twelve to him, he sent them out two by two and gave them authority over evil spirits.",
    "These were his instructions: \"Take nothing for the journey except a staff--no bread, no bag, no money in your belts.",
    "Wear sandals but not an extra tunic.",
    "Whenever you enter a house, stay there until you leave that town.",
    "And if any place will not welcome you or listen to you, shake the dust off your feet when you leave, as a testimony against them.\"",
    "They went out and preached that people should repent.",
    "They drove out many demons and anointed many sick people with oil and healed them.",
    "King Herod heard about this, for Jesus' name had become well known. Some were saying, \"John the Baptist has been raised from the dead, and that is why miraculous powers are at work in him.\"",
    "Others said, \"He is Elijah.\" And still others claimed, \"He is a prophet, like one of the prophets of long ago.\"",
    "But when Herod heard this, he said, \"John, the man I beheaded, has been raised from the dead!\"",
    "For Herod himself had given orders to have John arrested, and he had him bound and put in prison. He did this because of Herodias, his brother Philip's wife, whom he had married.",
    "For John had been saying to Herod, \"It is not lawful for you to have your brother's wife.\"",
    "So Herodias nursed a grudge against John and wanted to kill him. But she was not able to,",
    "because Herod feared John and protected him, knowing him to be a righteous and holy man. When Herod heard John, he was greatly puzzled; yet he liked to listen to him.",
    "Finally the opportune time came. On his birthday Herod gave a banquet for his high officials and military commanders and the leading men of Galilee.",
    "When the daughter of Herodias came in and danced, she pleased Herod and his dinner guests. The king said to the girl, \"Ask me for anything you want, and I'll give it to you.\"",
    "And he promised her with an oath, \"Whatever you ask I will give you, up to half my kingdom.\"",
    "She went out and said to her mother, \"What shall I ask for?\" \"The head of John the Baptist,\" she answered.",
    "At once the girl hurried in to the king with the request: \"I want you to give me right now the head of John the Baptist on a platter.\"",
    "The king was greatly distressed, but because of his oaths and his dinner guests, he did not want to refuse her.",
    "So he immediately sent an executioner with orders to bring John's head. The man went, beheaded John in the prison,",
    "and brought back his head on a platter. He presented it to the girl, and she gave it to her mother.",
    "On hearing of this, John's disciples came and took his body and laid it in a tomb.",
    "The apostles gathered around Jesus and reported to him all they had done and taught.",
    "Then, because so many people were coming and going that they did not even have a chance to eat, he said to them, \"Come with me by yourselves to a quiet place and get some rest.\"",
    "So they went away by themselves in a boat to a solitary place.",
    "But many who saw them leaving recognized them and ran on foot from all the towns and got there ahead of them.",
    "When Jesus landed and saw a large crowd, he had compassion on them, because they were like sheep without a shepherd. So he began teaching them many things.",
    "By this time it was late in the day, so his disciples came to him. \"This is a remote place,\" they said, \"and it's already very late.",
    "Send the people away so they can go to the surrounding countryside and villages and buy themselves something to eat.\"",
    "But he answered, \"You give them something to eat.\" They said to him, \"That would take eight months of a man's wages! Are we to go and spend that much on bread and give it to them to eat?\"",
    "\"How many loaves do you have?\" he asked. \"Go and see.\" When they found out, they said, \"Five--and two fish.\"",
    "Then Jesus directed them to have all the people sit down in groups on the green grass.",
    "So they sat down in groups of hundreds and fifties.",
    "Taking the five loaves and the two fish and looking up to heaven, he gave thanks and broke the loaves. Then he gave them to his disciples to set before the people. He also divided the two fish among them all.",
    "They all ate and were satisfied,",
    "and the disciples picked up twelve basketfuls of broken pieces of bread and fish.",
    "The number of the men who had eaten was five thousand.",
    "Immediately Jesus made his disciples get into the boat and go on ahead of him to Bethsaida, while he dismissed the crowd.",
    "After leaving them, he went up on a mountainside to pray.",
    "When evening came, the boat was in the middle of the lake, and he was alone on land.",
    "He saw the disciples straining at the oars, because the wind was against them. About the fourth watch of the night he went out to them, walking on the lake. He was about to pass by them,",
    "but when they saw him walking on the lake, they thought he was a ghost. They cried out,",
    "because they all saw him and were terrified. Immediately he spoke to them and said, \"Take courage! It is I. Don't be afraid.\"",
    "Then he climbed into the boat with them, and the wind died down. They were completely amazed,",
    "for they had not understood about the loaves; their hearts were hardened.",
    "When they had crossed over, they landed at Gennesaret and anchored there.",
    "As soon as they got out of the boat, people recognized Jesus.",
    "They ran throughout that whole region and carried the sick on mats to wherever they heard he was.",
    "And wherever he went--into villages, towns or countryside--they placed the sick in the marketplaces. They begged him to let them touch even the edge of his cloak, and all who touched him were healed."
  ],
  "Mark-6": [
    "The Pharisees and some of the teachers of the law who had come from Jerusalem gathered around Jesus and",
    "saw some of his disciples eating food with hands that were \"unclean,\" that is, unwashed.",
    "(The Pharisees and all the Jews do not eat unless they give their hands a ceremonial washing, holding to the tradition of the elders.",
    "When they come from the marketplace they do not eat unless they wash. And they observe many other traditions, such as the washing of cups, pitchers and kettles.)",
    "So the Pharisees and teachers of the law asked Jesus, \"Why don't your disciples live according to the tradition of the elders instead of eating their food with 'unclean' hands?\"",
    "He replied, \"Isaiah was right when he prophesied about you hypocrites; as it is written: \"'These people honor me with their lips, but their hearts are far from me.",
    "They worship me in vain; their teachings are but rules taught by men.'",
    "You have let go of the commands of God and are holding on to the traditions of men.\"",
    "And he said to them: \"You have a fine way of setting aside the commands of God in order to observe your own traditions!",
    "For Moses said, 'Honor your father and your mother,' and, 'Anyone who curses his father or mother must be put to death.'",
    "But you say that if a man says to his father or mother: 'Whatever help you might otherwise have received from me is Corban' (that is, a gift devoted to God),",
    "then you no longer let him do anything for his father or mother.",
    "Thus you nullify the word of God by your tradition that you have handed down. And you do many things like that.\"",
    "Again Jesus called the crowd to him and said, \"Listen to me, everyone, and understand this.",
    "Nothing outside a man can make him 'unclean' by going into him. Rather, it is what comes out of a man that makes him 'unclean.'\"",
    "[If anyone has ears to hear, let him hear.]",
    "After he had left the crowd and entered the house, his disciples asked him about this parable.",
    "\"Are you so dull?\" he asked. \"Don't you see that nothing that enters a man from the outside can make him 'unclean'?",
    "For it doesn't go into his heart but into his stomach, and then out of his body.\" (In saying this, Jesus declared all foods \"clean.\")",
    "He went on: \"What comes out of a man is what makes him 'unclean.'",
    "For from within, out of men's hearts, come evil thoughts, sexual immorality, theft, murder, adultery,",
    "greed, malice, deceit, lewdness, envy, slander, arrogance and folly.",
    "All these evils come from inside and make a man 'unclean.'\"",
    "Jesus left that place and went to the vicinity of Tyre. He entered a house and did not want anyone to know it; yet he could not keep his presence secret.",
    "In fact, as soon as she heard about him, a woman whose little daughter was possessed by an evil spirit came and fell at his feet.",
    "The woman was a Greek, born in Syrian Phoenicia. She begged Jesus to drive the demon out of her daughter.",
    "\"First let the children eat all they want,\" he told her, \"for it is not right to take the children's bread and toss it to their dogs.\"",
    "\"Yes, Lord,\" she replied, \"but even the dogs under the table eat the children's crumbs.\"",
    "Then he told her, \"For such a reply, you may go; the demon has left your daughter.\"",
    "She went home and found her child lying on the bed, and the demon gone.",
    "Then Jesus left the vicinity of Tyre and went through Sidon, down to the Sea of Galilee and into the region of the Decapolis.",
    "There some people brought to him a man who was deaf and could hardly talk, and they begged him to place his hand on the man.",
    "After he took him aside, away from the crowd, Jesus put his fingers into the man's ears. Then he spit and touched the man's tongue.",
    "He looked up to heaven and with a deep sigh said to him, \"Ephphatha!\" (which means, \"Be opened!\").",
    "At this, the man's ears were opened, his tongue was loosened and he began to speak plainly.",
    "Jesus commanded them not to tell anyone. But the more he did so, the more they kept talking about it.",
    "People were overwhelmed with amazement. \"He has done everything well,\" they said. \"He even makes the deaf hear and the mute speak.\""
  ],
  "Mark-7": [
    "During those days another large crowd gathered. Since they had nothing to eat, Jesus called his disciples to him and said,",
    "\"I have compassion for these people; they have already been with me three days and have nothing to eat.",
    "If I send them home hungry, they will collapse on the way, because some of them have come a long distance.\"",
    "His disciples answered, \"But where in this remote place can anyone get enough bread to feed them?\"",
    "\"How many loaves do you have?\" Jesus asked. \"Seven,\" they replied.",
    "He told the crowd to sit down on the ground. When he had taken the seven loaves and given thanks, he broke them and gave them to his disciples to set before the people, and they did so.",
    "They had a few small fish as well; he gave thanks for them also and told the disciples to distribute them.",
    "The people ate and were satisfied. Afterward the disciples picked up seven basketfuls of broken pieces that were left over.",
    "About four thousand men were present. And having sent them away,",
    "he got into the boat with his disciples and went to the region of Dalmanutha.",
    "The Pharisees came and began to question Jesus. To test him, they asked him for a sign from heaven.",
    "He sighed deeply and said, \"Why does this generation ask for a miraculous sign? I tell you the truth, no sign will be given to it.\"",
    "Then he left them, got back into the boat and crossed to the other side.",
    "The disciples had forgotten to bring bread, except for one loaf they had with them in the boat.",
    "\"Be careful,\" Jesus warned them. \"Watch out for the yeast of the Pharisees and that of Herod.\"",
    "They discussed this with one another and said, \"It is because we have no bread.\"",
    "Aware of their discussion, Jesus asked them: \"Why are you talking about having no bread? Do you still not see or understand? Are your hearts hardened?",
    "Do you have eyes but fail to see, and ears but fail to hear? And don't you remember?",
    "When I broke the five loaves for the five thousand, how many basketfuls of pieces did you pick up?\" \"Twelve,\" they replied.",
    "\"And when I broke the seven loaves for the four thousand, how many basketfuls of pieces did you pick up?\" They answered, \"Seven.\"",
    "He said to them, \"Do you still not understand?\"",
    "They came to Bethsaida, and some people brought a blind man and begged Jesus to touch him.",
    "He took the blind man by the hand and led him outside the village. When he had spit on the man's eyes and put his hands on him, Jesus asked, \"Do you see anything?\"",
    "He looked up and said, \"I see people; they look like trees walking around.\"",
    "Once more Jesus put his hands on the man's eyes. Then his eyes were opened, his sight was restored, and he saw everything clearly.",
    "Jesus sent him home, saying, \"Don't go into the village.\"",
    "Jesus and his disciples went on to the villages around Caesarea Philippi. On the way he asked them, \"Who do people say I am?\"",
    "They replied, \"Some say John the Baptist; others say Elijah; and still others, one of the prophets.\"",
    "\"But what about you?\" he asked. \"Who do you say I am?\" Peter answered, \"You are the Christ.\"",
    "Jesus warned them not to tell anyone about him.",
    "He then began to teach them that the Son of Man must suffer many things and be rejected by the elders, chief priests and teachers of the law, and that he must be killed and after three days rise again.",
    "He spoke plainly about this, and Peter took him aside and began to rebuke him.",
    "But when Jesus turned and looked at his disciples, he rebuked Peter. \"Get behind me, Satan!\" he said. \"You do not have in mind the things of God, but the things of men.\"",
    "Then he called the crowd to him along with his disciples and said: \"If anyone would come after me, he must deny himself and take up his cross and follow me.",
    "For whoever wants to save his life will lose it, but whoever loses his life for me and for the gospel will save it.",
    "What good is it for a man to gain the whole world, yet forfeit his soul?",
    "Or what can a man give in exchange for his soul?",
    "If anyone is ashamed of me and my words in this adulterous and sinful generation, the Son of Man will be ashamed of him when he comes in his Father's glory with the holy angels.\""
  ],
  "Mark-8": [
    "And he said to them, \"I tell you the truth, some who are standing here will not taste death before they see the kingdom of God come with power.\"",
    "After six days Jesus took Peter, James and John with him and led them up a high mountain, where they were all alone. There he was transfigured before them.",
    "His clothes became dazzling white, whiter than anyone in the world could bleach them.",
    "And there appeared before them Elijah and Moses, who were talking with Jesus.",
    "Peter said to Jesus, \"Rabbi, it is good for us to be here. Let us put up three shelters--one for you, one for Moses and one for Elijah.\"",
    "(He did not know what to say, they were so frightened.)",
    "Then a cloud appeared and enveloped them, and a voice came from the cloud: \"This is my Son, whom I love. Listen to him!\"",
    "Suddenly, when they looked around, they no longer saw anyone with them except Jesus.",
    "As they were coming down the mountain, Jesus gave them orders not to tell anyone what they had seen until the Son of Man had risen from the dead.",
    "They kept the matter to themselves, discussing what \"rising from the dead\" meant.",
    "And they asked him, \"Why do the teachers of the law say that Elijah must come first?\"",
    "Jesus replied, \"To be sure, Elijah does come first, and restores all things. Why then is it written that the Son of Man must suffer much and be rejected?",
    "But I tell you, Elijah has come, and they have done to him everything they wished, just as it is written about him.\"",
    "When they came to the other disciples, they saw a large crowd around them and the teachers of the law arguing with them.",
    "As soon as all the people saw Jesus, they were overwhelmed with wonder and ran to greet him.",
    "\"What are you arguing with them about?\" he asked.",
    "A man in the crowd answered, \"Teacher, I brought you my son, who is possessed by a spirit that has robbed him of speech.",
    "Whenever it seizes him, it throws him to the ground. He foams at the mouth, gnashes his teeth and becomes rigid. I asked your disciples to drive out the spirit, but they could not.\"",
    "\"O unbelieving generation,\" Jesus replied, \"how long shall I stay with you? How long shall I put up with you? Bring the boy to me.\"",
    "So they brought him. When the spirit saw Jesus, it immediately threw the boy into a convulsion. He fell to the ground and rolled around, foaming at the mouth.",
    "Jesus asked the boy's father, \"How long has he been like this?\" \"From childhood,\" he answered.",
    "\"It has often thrown him into fire or water to kill him. But if you can do anything, take pity on us and help us.\"",
    "\"'If you can'?\" said Jesus. \"Everything is possible for him who believes.\"",
    "Immediately the boy's father exclaimed, \"I do believe; help me overcome my unbelief!\"",
    "When Jesus saw that a crowd was running to the scene, he rebuked the evil spirit. \"You deaf and mute spirit,\" he said, \"I command you, come out of him and never enter him again.\"",
    "The spirit shrieked, convulsed him violently and came out. The boy looked so much like a corpse that many said, \"He's dead.\"",
    "But Jesus took him by the hand and lifted him to his feet, and he stood up.",
    "After Jesus had gone indoors, his disciples asked him privately, \"Why couldn't we drive it out?\"",
    "He replied, \"This kind can come out only by prayer.\"",
    "They left that place and passed through Galilee. Jesus did not want anyone to know where they were,",
    "because he was teaching his disciples. He said to them, \"The Son of Man is going to be betrayed into the hands of men. They will kill him, and after three days he will rise.\"",
    "But they did not understand what he meant and were afraid to ask him about it.",
    "They came to Capernaum. When he was in the house, he asked them, \"What were you arguing about on the road?\"",
    "But they kept quiet because on the way they had argued about who was the greatest.",
    "Sitting down, Jesus called the Twelve and said, \"If anyone wants to be first, he must be the very last, and the servant of all.\"",
    "He took a little child and had him stand among them. Taking him in his arms, he said to them,",
    "\"Whoever welcomes one of these little children in my name welcomes me; and whoever welcomes me does not welcome me but the one who sent me.\"",
    "\"Teacher,\" said John, \"we saw a man driving out demons in your name and we told him to stop, because he was not one of us.\"",
    "\"Do not stop him,\" Jesus said. \"No one who does a miracle in my name can in the next moment say anything bad about me,",
    "for whoever is not against us is for us.",
    "I tell you the truth, anyone who gives you a cup of water in my name because you belong to Christ will certainly not lose his reward.",
    "\"And if anyone causes one of these little ones who believe in me to sin, it would be better for him to be thrown into the sea with a large millstone tied around his neck.",
    "If your hand causes you to sin, cut it off. It is better for you to enter life maimed than with two hands to go into hell, where the fire never goes out.",
    "[Where their worm does not die, and the fire is not quenched.]",
    "And if your foot causes you to sin, cut it off. It is better for you to enter life crippled than to have two feet and be thrown into hell.",
    "[Where their worm does not die, and the fire is not quenched.]",
    "And if your eye causes you to sin, pluck it out. It is better for you to enter the kingdom of God with one eye than to have two eyes and be thrown into hell,",
    "where \"'their worm does not die, and the fire is not quenched.'",
    "Everyone will be salted with fire.",
    "\"Salt is good, but if it loses its saltiness, how can you make it salty again? Have salt in yourselves, and be at peace with each other.\""
  ],
  "Mark-9": [
    "Jesus then left that place and went into the region of Judea and across the Jordan. Again crowds of people came to him, and as was his custom, he taught them.",
    "Some Pharisees came and tested him by asking, \"Is it lawful for a man to divorce his wife?\"",
    "\"What did Moses command you?\" he replied.",
    "They said, \"Moses permitted a man to write a certificate of divorce and send her away.\"",
    "\"It was because your hearts were hard that Moses wrote you this law,\" Jesus replied.",
    "\"But at the beginning of creation God 'made them male and female.'",
    "'For this reason a man will leave his father and mother and be united to his wife,",
    "and the two will become one flesh.' So they are no longer two, but one.",
    "Therefore what God has joined together, let man not separate.\"",
    "When they were in the house again, the disciples asked Jesus about this.",
    "He answered, \"Anyone who divorces his wife and marries another woman commits adultery against her.",
    "And if she divorces her husband and marries another man, she commits adultery.\"",
    "People were bringing little children to Jesus to have him touch them, but the disciples rebuked them.",
    "When Jesus saw this, he was indignant. He said to them, \"Let the little children come to me, and do not hinder them, for the kingdom of God belongs to such as these.",
    "I tell you the truth, anyone who will not receive the kingdom of God like a little child will never enter it.\"",
    "And he took the children in his arms, put his hands on them and blessed them.",
    "As Jesus started on his way, a man ran up to him and fell on his knees before him. \"Good teacher,\" he asked, \"what must I do to inherit eternal life?\"",
    "\"Why do you call me good?\" Jesus answered. \"No one is good--except God alone.",
    "You know the commandments: 'Do not murder, do not commit adultery, do not steal, do not give false testimony, do not defraud, honor your father and mother.'\"",
    "\"Teacher,\" he declared, \"all these I have kept since I was a boy.\"",
    "Jesus looked at him and loved him. \"One thing you lack,\" he said. \"Go, sell everything you have and give to the poor, and you will have treasure in heaven. Then come, follow me.\"",
    "At this the man's face fell. He went away sad, because he had great wealth.",
    "Jesus looked around and said to his disciples, \"How hard it is for the rich to enter the kingdom of God!\"",
    "The disciples were amazed at his words. But Jesus said again, \"Children, how hard it is to enter the kingdom of God!",
    "It is easier for a camel to go through the eye of a needle than for a rich man to enter the kingdom of God.\"",
    "The disciples were even more amazed, and said to each other, \"Who then can be saved?\"",
    "Jesus looked at them and said, \"With man this is impossible, but not with God; all things are possible with God.\"",
    "Peter said to him, \"We have left everything to follow you!\"",
    "\"I tell you the truth,\" Jesus replied, \"no one who has left home or brothers or sisters or mother or father or children or fields for me and the gospel",
    "will fail to receive a hundred times as much in this present age (homes, brothers, sisters, mothers, children and fields--and with them, persecutions) and in the age to come, eternal life.",
    "But many who are first will be last, and the last first.\"",
    "They were on their way up to Jerusalem, with Jesus leading the way, and the disciples were astonished, while those who followed were afraid. Again he took the Twelve aside and told them what was going to happen to him.",
    "\"We are going up to Jerusalem,\" he said, \"and the Son of Man will be betrayed to the chief priests and teachers of the law. They will condemn him to death and will hand him over to the Gentiles,",
    "who will mock him and spit on him, flog him and kill him. Three days later he will rise.\"",
    "Then James and John, the sons of Zebedee, came to him. \"Teacher,\" they said, \"we want you to do for us whatever we ask.\"",
    "\"What do you want me to do for you?\" he asked.",
    "They replied, \"Let one of us sit at your right and the other at your left in your glory.\"",
    "\"You don't know what you are asking,\" Jesus said. \"Can you drink the cup I drink or be baptized with the baptism I am baptized with?\"",
    "\"We can,\" they answered. Jesus said to them, \"You will drink the cup I drink and be baptized with the baptism I am baptized with,",
    "but to sit at my right or left is not for me to grant. These places belong to those for whom they have been prepared.\"",
    "When the ten heard about this, they became indignant with James and John.",
    "Jesus called them together and said, \"You know that those who are regarded as rulers of the Gentiles lord it over them, and their high officials exercise authority over them.",
    "Not so with you. Instead, whoever wants to become great among you must be your servant,",
    "and whoever wants to be first must be slave of all.",
    "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.\"",
    "Then they came to Jericho. As Jesus and his disciples, together with a large crowd, were leaving the city, a blind man, Bartimaeus (that is, the Son of Timaeus), was sitting by the roadside begging.",
    "When he heard that it was Jesus of Nazareth, he began to shout, \"Jesus, Son of David, have mercy on me!\"",
    "Many rebuked him and told him to be quiet, but he shouted all the more, \"Son of David, have mercy on me!\"",
    "Jesus stopped and said, \"Call him.\" So they called to the blind man, \"Cheer up! On your feet! He's calling you.\"",
    "Throwing his cloak aside, he jumped to his feet and came to Jesus.",
    "\"What do you want me to do for you?\" Jesus asked him. The blind man said, \"Rabbi, I want to see.\"",
    "\"Go,\" said Jesus, \"your faith has healed you.\" Immediately he received his sight and followed Jesus along the road."
  ],
  "Mark-10": [
    "As they approached Jerusalem and came to Bethphage and Bethany at the Mount of Olives, Jesus sent two of his disciples,",
    "saying to them, \"Go to the village ahead of you, and just as you enter it, you will find a colt tied there, which no one has ever ridden. Untie it and bring it here.",
    "If anyone asks you, 'Why are you doing this?' tell him, 'The Lord needs it and will send it back here shortly.'\"",
    "They went and found a colt outside in the street, tied at a doorway. As they untied it,",
    "some people standing there asked, \"What are you doing, untying that colt?\"",
    "They answered as Jesus had told them to, and the people let them go.",
    "When they brought the colt to Jesus and threw their cloaks over it, he sat on it.",
    "Many people spread their cloaks on the road, while others spread branches they had cut in the fields.",
    "Those who went ahead and those who followed shouted, \"Hosanna!\" \"Blessed is he who comes in the name of the Lord!\"",
    "\"Blessed is the coming kingdom of our father David!\" \"Hosanna in the highest!\"",
    "Jesus entered Jerusalem and went to the temple. He looked around at everything, but since it was already late, he went out to Bethany with the Twelve.",
    "The next day as they were leaving Bethany, Jesus was hungry.",
    "Seeing in the distance a fig tree in leaf, he went to find out if it had any fruit. When he reached it, he found nothing but leaves, because it was not the season for figs.",
    "Then he said to the tree, \"May no one ever eat fruit from you again.\" And his disciples heard him say it.",
    "On reaching Jerusalem, Jesus entered the temple area and began driving out those who were buying and selling there. He overturned the tables of the money changers and the benches of those selling doves,",
    "and would not allow anyone to carry merchandise through the temple courts.",
    "And as he taught them, he said, \"Is it not written: \"'My house will be called a house of prayer for all nations'? But you have made it 'a den of robbers.'\"",
    "The chief priests and the teachers of the law heard this and began looking for a way to kill him, for they feared him, because the whole crowd was amazed at his teaching.",
    "When evening came, they went out of the city.",
    "In the morning, as they went along, they saw the fig tree withered from the roots.",
    "Peter remembered and said to Jesus, \"Rabbi, look! The fig tree you cursed has withered!\"",
    "\"Have faith in God,\" Jesus answered.",
    "\"I tell you the truth, if anyone says to this mountain, 'Go, throw yourself into the sea,' and does not doubt in his heart but believes that what he says will happen, it will be done for him.",
    "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.",
    "And when you stand praying, if you hold anything against anyone, forgive him, so that your Father in heaven may forgive you your sins.\"",
    "[But if you do not forgive, neither will your Father who is in heaven forgive your sins.]",
    "They arrived again in Jerusalem, and while Jesus was walking in the temple courts, the chief priests, the teachers of the law and the elders came to him.",
    "\"By what authority are you doing these things?\" they asked. \"And who gave you authority to do this?\"",
    "Jesus replied, \"I will ask you one question. Answer me, and I will tell you by what authority I am doing these things.",
    "John's baptism--was it from heaven, or from men? Tell me!\"",
    "They discussed it among themselves and said, \"If we say, 'From heaven,' he will ask, 'Then why didn't you believe him?'",
    "But if we say, 'From men' . . . .\" (They feared the people, for everyone held that John really was a prophet.)",
    "So they answered Jesus, \"We don't know.\" Jesus said, \"Neither will I tell you by what authority I am doing these things.\""
  ],
  "Mark-11": [
    "He then began to speak to them in parables: \"A man planted a vineyard. He put a wall around it, dug a pit for the winepress and built a watchtower. Then he rented the vineyard to some farmers and went away on a journey.",
    "At harvest time he sent a servant to the tenants to collect from them some of the fruit of the vineyard.",
    "But they seized him, beat him and sent him away empty-handed.",
    "Then he sent another servant to them; they struck this man on the head and treated him shamefully.",
    "He sent still another, and that one they killed. He sent many others; some of them they beat, others they killed.",
    "\"He had one left to send, a son, whom he loved. He sent him last of all, saying, 'They will respect my son.'",
    "\"But the tenants said to one another, 'This is the heir. Come, let's kill him, and the inheritance will be ours.'",
    "So they took him and killed him, and threw him out of the vineyard.",
    "\"What then will the owner of the vineyard do? He will come and kill those tenants and give the vineyard to others.",
    "Haven't you read this scripture: \"'The stone the builders rejected has become the capstone;",
    "the Lord has done this, and it is marvelous in our eyes'?\"",
    "Then they looked for a way to arrest him because they knew he had spoken the parable against them. But they were afraid of the crowd; so they left him and went away.",
    "Later they sent some of the Pharisees and Herodians to Jesus to catch him in his words.",
    "They came to him and said, \"Teacher, we know you are a man of integrity. You aren't swayed by men, because you pay no attention to who they are; but you teach the way of God in accordance with the truth. Is it right to pay taxes to Caesar or not?",
    "Should we pay or shouldn't we?\" But Jesus knew their hypocrisy. \"Why are you trying to trap me?\" he asked. \"Bring me a denarius and let me look at it.\"",
    "They brought the coin, and he asked them, \"Whose portrait is this? And whose inscription?\" \"Caesar's,\" they replied.",
    "Then Jesus said to them, \"Give to Caesar what is Caesar's and to God what is God's.\" And they were amazed at him.",
    "Then the Sadducees, who say there is no resurrection, came to him with a question.",
    "\"Teacher,\" they said, \"Moses wrote for us that if a man's brother dies and leaves a wife but no children, the man must marry the widow and have children for his brother.",
    "Now there were seven brothers. The first one married and died without leaving any children.",
    "The second one married the widow, but he also died, leaving no child. It was the same with the third.",
    "In fact, none of the seven left any children. Last of all, the woman died too.",
    "At the resurrection whose wife will she be, since the seven were married to her?\"",
    "Jesus replied, \"Are you not in error because you do not know the Scriptures or the power of God?",
    "When the dead rise, they will neither marry nor be given in marriage; they will be like the angels in heaven.",
    "Now about the dead rising--have you not read in the book of Moses, in the account of the bush, how God said to him, 'I am the God of Abraham, the God of Isaac, and the God of Jacob'?",
    "He is not the God of the dead, but of the living. You are badly mistaken!\"",
    "One of the teachers of the law came and heard them debating. Noticing that Jesus had given them a good answer, he asked him, \"Of all the commandments, which is the most important?\"",
    "\"The most important one,\" answered Jesus, \"is this: 'Hear, O Israel, the Lord our God, the Lord is one.",
    "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.'",
    "The second is this: 'Love your neighbor as yourself.' There is no commandment greater than these.\"",
    "\"Well said, teacher,\" the man replied. \"You are right in saying that God is one and there is no other but him.",
    "To love him with all your heart, with all your understanding and with all your strength, and to love your neighbor as yourself is more important than all burnt offerings and sacrifices.\"",
    "When Jesus saw that he had answered wisely, he said to him, \"You are not far from the kingdom of God.\" And from then on no one dared ask him any more questions.",
    "While Jesus was teaching in the temple courts, he asked, \"How is it that the teachers of the law say that the Christ is the son of David?",
    "David himself, speaking by the Holy Spirit, declared: \"'The Lord said to my Lord: \"Sit at my right hand until I put your enemies under your feet.\" '",
    "David himself calls him 'Lord.' How then can he be his son?\" The large crowd listened to him with delight.",
    "As he taught, Jesus said, \"Watch out for the teachers of the law. They like to walk around in flowing robes and be greeted in the marketplaces,",
    "and have the most important seats in the synagogues and the places of honor at banquets.",
    "They devour widows' houses and for a show make lengthy prayers. Such men will be punished most severely.\"",
    "Jesus sat down opposite the place where the offerings were put and watched the crowd putting their money into the temple treasury. Many rich people threw in large amounts.",
    "But a poor widow came and put in two very small copper coins, worth only a fraction of a penny.",
    "Calling his disciples to him, Jesus said, \"I tell you the truth, this poor widow has put more into the treasury than all the others.",
    "They all gave out of their wealth; but she, out of her poverty, put in everything--all she had to live on.\""
  ],
  "Mark-12": [
    "As he was leaving the temple, one of his disciples said to him, \"Look, Teacher! What massive stones! What magnificent buildings!\"",
    "\"Do you see all these great buildings?\" replied Jesus. \"Not one stone here will be left on another; every one will be thrown down.\"",
    "As Jesus was sitting on the Mount of Olives opposite the temple, Peter, James, John and Andrew asked him privately,",
    "\"Tell us, when will these things happen? And what will be the sign that they are all about to be fulfilled?\"",
    "Jesus said to them: \"Watch out that no one deceives you.",
    "Many will come in my name, claiming, 'I am he,' and will deceive many.",
    "When you hear of wars and rumors of wars, do not be alarmed. Such things must happen, but the end is still to come.",
    "Nation will rise against nation, and kingdom against kingdom. There will be earthquakes in various places, and famines. These are the beginning of birth pains.",
    "\"You must be on your guard. You will be handed over to the local councils and flogged in the synagogues. On account of me you will stand before governors and kings as witnesses to them.",
    "And the gospel must first be preached to all nations.",
    "Whenever you are arrested and brought to trial, do not worry beforehand about what to say. Just say whatever is given you at the time, for it is not you speaking, but the Holy Spirit.",
    "\"Brother will betray brother to death, and a father his child. Children will rebel against their parents and have them put to death.",
    "All men will hate you because of me, but he who stands firm to the end will be saved.",
    "\"When you see 'the abomination that causes desolation' standing where it does not belong--let the reader understand--then let those who are in Judea flee to the mountains.",
    "Let no one on the roof of his house go down or enter the house to take anything out.",
    "Let no one in the field go back to get his cloak.",
    "How dreadful it will be in those days for pregnant women and nursing mothers!",
    "Pray that this will not take place in winter,",
    "because those will be days of distress unequaled from the beginning, when God created the world, until now--and never to be equaled again.",
    "If the Lord had not cut short those days, no one would survive. But for the sake of the elect, whom he has chosen, he has shortened them.",
    "At that time if anyone says to you, 'Look, here is the Christ!' or, 'Look, there he is!' do not believe it.",
    "For false Christs and false prophets will appear and perform signs and miracles to deceive the elect--if that were possible.",
    "So be on your guard; I have told you everything ahead of time.",
    "\"But in those days, following that distress, \"'the sun will be darkened, and the moon will not give its light;",
    "the stars will fall from the sky, and the heavenly bodies will be shaken.'",
    "\"At that time men will see the Son of Man coming in clouds with great power and glory.",
    "And he will send his angels and gather his elect from the four winds, from the ends of the earth to the ends of the heavens.",
    "\"Now learn this lesson from the fig tree: As soon as its twigs get tender and its leaves come out, you know that summer is near.",
    "Even so, when you see these things happening, you know that it is near, right at the door.",
    "I tell you the truth, this generation will certainly not pass away until all these things have happened.",
    "Heaven and earth will pass away, but my words will never pass away.",
    "\"No one knows about that day or hour, not even the angels in heaven, nor the Son, but only the Father.",
    "Be on guard! Be alert! You do not know when that time will come.",
    "It's like a man going away: He leaves his house and puts his servants in charge, each with his assigned task, and tells the one at the door to keep watch.",
    "\"Therefore keep watch because you do not know when the owner of the house will come back--whether in the evening, or at midnight, or when the rooster crows, or at dawn.",
    "If he comes suddenly, do not let him find you sleeping.",
    "What I say to you, I say to everyone: 'Watch!'\""
  ],
  "Mark-13": [
    "Now the Passover and the Feast of Unleavened Bread were only two days away, and the chief priests and the teachers of the law were looking for some sly way to arrest Jesus and kill him.",
    "\"But not during the Feast,\" they said, \"or the people may riot.\"",
    "While he was in Bethany, reclining at the table in the home of a man known as Simon the Leper, a woman came with an alabaster jar of very expensive perfume, made of pure nard. She broke the jar and poured the perfume on his head.",
    "Some of those present were saying indignantly to one another, \"Why this waste of perfume?",
    "It could have been sold for more than a year's wages and the money given to the poor.\" And they rebuked her harshly.",
    "\"Leave her alone,\" said Jesus. \"Why are you bothering her? She has done a beautiful thing to me.",
    "The poor you will always have with you, and you can help them any time you want. But you will not always have me.",
    "She did what she could. She poured perfume on my body beforehand to prepare for my burial.",
    "I tell you the truth, wherever the gospel is preached throughout the world, what she has done will also be told, in memory of her.\"",
    "Then Judas Iscariot, one of the Twelve, went to the chief priests to betray Jesus to them.",
    "They were delighted to hear this and promised to give him money. So he watched for an opportunity to hand him over.",
    "On the first day of the Feast of Unleavened Bread, when it was customary to sacrifice the Passover lamb, Jesus' disciples asked him, \"Where do you want us to go and make preparations for you to eat the Passover?\"",
    "So he sent two of his disciples, telling them, \"Go into the city, and a man carrying a jar of water will meet you. Follow him.",
    "Say to the owner of the house he enters, 'The Teacher asks: Where is my guest room, where I may eat the Passover with my disciples?'",
    "He will show you a large upper room, furnished and ready. Make preparations for us there.\"",
    "The disciples left, went into the city and found things just as Jesus had told them. So they prepared the Passover.",
    "When evening came, Jesus arrived with the Twelve.",
    "While they were reclining at the table eating, he said, \"I tell you the truth, one of you will betray me--one who is eating with me.\"",
    "They were saddened, and one by one they said to him, \"Surely not I?\"",
    "\"It is one of the Twelve,\" he replied, \"one who dips bread into the bowl with me.",
    "The Son of Man will go just as it is written about him. But woe to that man who betrays the Son of Man! It would be better for him if he had not been born.\"",
    "While they were eating, Jesus took bread, gave thanks and broke it, and gave it to his disciples, saying, \"Take it; this is my body.\"",
    "Then he took the cup, gave thanks and offered it to them, and they all drank from it.",
    "\"This is my blood of the covenant, which is poured out for many,\" he said to them.",
    "\"I tell you the truth, I will not drink again of the fruit of the vine until that day when I drink it anew in the kingdom of God.\"",
    "When they had sung a hymn, they went out to the Mount of Olives.",
    "\"You will all fall away,\" Jesus told them, \"for it is written: \"'I will strike the shepherd, and the sheep will be scattered.'",
    "But after I have risen, I will go ahead of you into Galilee.\"",
    "Peter declared, \"Even if all fall away, I will not.\"",
    "\"I tell you the truth,\" Jesus answered, \"today--yes, tonight--before the rooster crows twice you yourself will disown me three times.\"",
    "But Peter insisted emphatically, \"Even if I have to die with you, I will never disown you.\" And all the others said the same.",
    "They went to a place called Gethsemane, and Jesus said to his disciples, \"Sit here while I pray.\"",
    "He took Peter, James and John along with him, and he began to be deeply distressed and troubled.",
    "\"My soul is overwhelmed with sorrow to the point of death,\" he said to them. \"Stay here and keep watch.\"",
    "Going a little farther, he fell to the ground and prayed that if possible the hour might pass from him.",
    "\"Abba, Father,\" he said, \"everything is possible for you. Take this cup from me. Yet not what I will, but what you will.\"",
    "Then he returned to his disciples and found them sleeping. \"Simon,\" he said to Peter, \"are you asleep? Could you not keep watch for one hour?",
    "Watch and pray so that you will not fall into temptation. The spirit is willing, but the body is weak.\"",
    "Once more he went away and prayed the same thing.",
    "When he came back, he again found them sleeping, because their eyes were heavy. They did not know what to say to him.",
    "Returning the third time, he said to them, \"Are you still sleeping and resting? Enough! The hour has come. Look, the Son of Man is betrayed into the hands of sinners.",
    "Rise! Let us go! Here comes my betrayer!\"",
    "Just as he was speaking, Judas, one of the Twelve, appeared. With him was a crowd armed with swords and clubs, sent from the chief priests, the teachers of the law, and the elders.",
    "Now the betrayer had arranged a signal with them: \"The one I kiss is the man; arrest him and lead him away under guard.\"",
    "Going at once to Jesus, Judas said, \"Rabbi!\" and kissed him.",
    "The men seized Jesus and arrested him.",
    "Then one of those standing near drew his sword and struck the servant of the high priest, cutting off his ear.",
    "\"Am I leading a rebellion,\" said Jesus, \"that you have come out with swords and clubs to capture me?",
    "Every day I was with you, teaching in the temple courts, and you did not arrest me. But the Scriptures must be fulfilled.\"",
    "Then everyone deserted him and fled.",
    "A young man, wearing nothing but a linen garment, was following Jesus. When they seized him,",
    "he fled naked, leaving his garment behind.",
    "They took Jesus to the high priest, and all the chief priests, elders and teachers of the law came together.",
    "Peter followed him at a distance, right into the courtyard of the high priest. There he sat with the guards and warmed himself at the fire.",
    "The chief priests and the whole Sanhedrin were looking for evidence against Jesus so that they could put him to death, but they did not find any.",
    "Many testified falsely against him, but their statements did not agree.",
    "Then some stood up and gave this false testimony against him:",
    "\"We heard him say, 'I will destroy this man-made temple and in three days will build another, not made by man.'\"",
    "Yet even then their testimony did not agree.",
    "Then the high priest stood up before them and asked Jesus, \"Are you not going to answer? What is this testimony that these men are bringing against you?\"",
    "But Jesus remained silent and gave no answer. Again the high priest asked him, \"Are you the Christ, the Son of the Blessed One?\"",
    "\"I am,\" said Jesus. \"And you will see the Son of Man sitting at the right hand of the Mighty One and coming on the clouds of heaven.\"",
    "The high priest tore his clothes. \"Why do we need any more witnesses?\" he asked.",
    "\"You have heard the blasphemy. What do you think?\" They all condemned him as worthy of death.",
    "Then some began to spit at him; they blindfolded him, struck him with their fists, and said, \"Prophesy!\" And the guards took him and beat him.",
    "While Peter was below in the courtyard, one of the servant girls of the high priest came by.",
    "When she saw Peter warming himself, she looked closely at him. \"You also were with that Nazarene, Jesus,\" she said.",
    "But he denied it. \"I don't know or understand what you're talking about,\" he said, and went out into the entryway.",
    "When the servant girl saw him there, she said again to those standing around, \"This fellow is one of them.\"",
    "Again he denied it. After a little while, those standing near said to Peter, \"Surely you are one of them, for you are a Galilean.\"",
    "He began to call down curses on himself, and he swore to them, \"I don't know this man you're talking about.\"",
    "Immediately the rooster crowed the second time. Then Peter remembered the word Jesus had spoken to him: \"Before the rooster crows twice you will disown me three times.\" And he broke down and wept."
  ],
  "Mark-14": [
    "Very early in the morning, the chief priests, with the elders, the teachers of the law and the whole Sanhedrin, reached a decision. They bound Jesus, led him away and handed him over to Pilate.",
    "\"Are you the king of the Jews?\" asked Pilate. \"Yes, it is as you say,\" Jesus replied.",
    "The chief priests accused him of many things.",
    "So again Pilate asked him, \"Aren't you going to answer? See how many things they are accusing you of.\"",
    "But Jesus still made no reply, and Pilate was amazed.",
    "Now it was the custom at the Feast to release a prisoner whom the people requested.",
    "A man called Barabbas was in prison with the insurrectionists who had committed murder in the uprising.",
    "The crowd came up and asked Pilate to do for them what he usually did.",
    "\"Do you want me to release to you the king of the Jews?\" asked Pilate,",
    "knowing it was out of envy that the chief priests had handed Jesus over to him.",
    "But the chief priests stirred up the crowd to have Pilate release Barabbas instead.",
    "\"What shall I do, then, with the one you call the king of the Jews?\" Pilate asked them.",
    "\"Crucify him!\" they shouted.",
    "\"Why? What crime has he committed?\" asked Pilate. But they shouted all the louder, \"Crucify him!\"",
    "Wanting to satisfy the crowd, Pilate released Barabbas to them. He had Jesus flogged, and handed him over to be crucified.",
    "The soldiers led Jesus away into the palace (that is, the Praetorium) and called together the whole company of soldiers.",
    "They put a purple robe on him, then twisted together a crown of thorns and set it on him.",
    "And they began to call out to him, \"Hail, king of the Jews!\"",
    "Again and again they struck him on the head with a staff and spit on him. Falling on their knees, they paid homage to him.",
    "And when they had mocked him, they took off the purple robe and put his own clothes on him. Then they led him out to crucify him.",
    "A certain man from Cyrene, Simon, the father of Alexander and Rufus, was passing by on his way in from the country, and they forced him to carry the cross.",
    "They brought Jesus to the place called Golgotha (which means The Place of the Skull).",
    "Then they offered him wine mixed with myrrh, but he did not take it.",
    "And they crucified him. Dividing up his clothes, they cast lots to see what each would get.",
    "It was the third hour when they crucified him.",
    "The written notice of the charge against him read: THE KING OF THE JEWS.",
    "They crucified two robbers with him, one on his right and one on his left.",
    "[and the scripture was fulfilled which says, \"He was counted with the lawless ones\" (Isa 53:12)]",
    "Those who passed by hurled insults at him, shaking their heads and saying, \"So! You who are going to destroy the temple and build it in three days,",
    "come down from the cross and save yourself!\"",
    "In the same way the chief priests and the teachers of the law mocked him among themselves. \"He saved others,\" they said, \"but he can't save himself!",
    "Let this Christ, this King of Israel, come down now from the cross, that we may see and believe.\" Those crucified with him also heaped insults on him.",
    "At the sixth hour darkness came over the whole land until the ninth hour.",
    "And at the ninth hour Jesus cried out in a loud voice, \"Eloi, Eloi, lama sabachthani?\"--which means, \"My God, my God, why have you forsaken me?\"",
    "When some of those standing near heard this, they said, \"Listen, he's calling Elijah.\"",
    "One man ran, filled a sponge with wine vinegar, put it on a stick, and offered it to Jesus to drink. \"Now leave him alone. Let's see if Elijah comes to take him down,\" he said.",
    "With a loud cry, Jesus breathed his last.",
    "The curtain of the temple was torn in two from top to bottom.",
    "And when the centurion, who stood there in front of Jesus, heard his cry and saw how he died, he said, \"Surely this man was the Son of God!\"",
    "Some women were watching from a distance. Among them were Mary Magdalene, Mary the mother of James the younger and of Joses, and Salome.",
    "In Galilee these women had followed him and cared for his needs. Many other women who had come up with him to Jerusalem were also there.",
    "It was Preparation Day (that is, the day before the Sabbath). So as evening approached,",
    "Joseph of Arimathea, a prominent member of the Council, who was himself waiting for the kingdom of God, went boldly to Pilate and asked for Jesus' body.",
    "Pilate was surprised to hear that he was already dead. Summoning the centurion, he asked him if Jesus had already died.",
    "When he learned from the centurion that it was so, he gave the body to Joseph.",
    "So Joseph bought some linen cloth, took down the body, wrapped it in the linen, and placed it in a tomb cut out of rock. Then he rolled a stone against the entrance of the tomb.",
    "Mary Magdalene and Mary the mother of Joses saw where he was laid."
  ],
  "Mark-15": [
    "When the Sabbath was over, Mary Magdalene, Mary the mother of James, and Salome bought spices so that they might go to anoint Jesus' body.",
    "Very early on the first day of the week, just after sunrise, they were on their way to the tomb",
    "and they asked each other, \"Who will roll the stone away from the entrance of the tomb?\"",
    "But when they looked up, they saw that the stone, which was very large, had been rolled away.",
    "As they entered the tomb, they saw a young man dressed in a white robe sitting on the right side, and they were alarmed.",
    "\"Don't be alarmed,\" he said. \"You are looking for Jesus the Nazarene, who was crucified. He has risen! He is not here. See the place where they laid him.",
    "But go, tell his disciples and Peter, 'He is going ahead of you into Galilee. There you will see him, just as he told you.'\"",
    "Trembling and bewildered, the women went out and fled from the tomb. They said nothing to anyone, because they were afraid.",
    "The most reliable early manuscripts and other ancient witnesses do not have Mark 16:9-20. When Jesus rose early on the first day of the week, he appeared first to Mary Magdalene, out of whom he had driven seven demons.",
    "She went and told those who had been with him and who were mourning and weeping.",
    "When they heard that Jesus was alive and that she had seen him, they did not believe it.",
    "Afterward Jesus appeared in a different form to two of them while they were walking in the country.",
    "These returned and reported it to the rest; but they did not believe them either.",
    "Later Jesus appeared to the Eleven as they were eating; he rebuked them for their lack of faith and their stubborn refusal to believe those who had seen him after he had risen.",
    "He said to them, \"Go into all the world and preach the good news to all creation.",
    "Whoever believes and is baptized will be saved, but whoever does not believe will be condemned.",
    "And these signs will accompany those who believe: In my name they will drive out demons; they will speak in new tongues;",
    "they will pick up snakes with their hands; and when they drink deadly poison, it will not hurt them at all; they will place their hands on sick people, and they will get well.\"",
    "After the Lord Jesus had spoken to them, he was taken up into heaven and he sat at the right hand of God.",
    "Then the disciples went out and preached everywhere, and the Lord worked with them and confirmed his word by the signs that accompanied it."
  ]
};