const Nehemiah = {
  "Nehemiah-0": [
    "The words of Neemiah son of Hacaliah: In the month of Kislev in the twentieth year, while I was in the citadel of Susa,",
    "Hanani, one of my brothers, came from Judah with some other men, and I questioned them about the Jewish remnant that survived the exile, and also about Jerusalem.",
    "They said to me, \"Those who survived the exile and are back in the province are in great trouble and disgrace. The wall of Jerusalem is broken down, and its gates have been burned with fire.\"",
    "When I heard these things, I sat down and wept. For some days I mourned and fasted and prayed before the God of heaven.",
    "Then I said: \"O LORD, God of heaven, the great and awesome God, who keeps his covenant of love with those who love him and obey his commands,",
    "let your ear be attentive and your eyes open to hear the prayer your servant is praying before you day and night for your servants, the people of Israel. I confess the sins we Israelites, including myself and my father's house, have committed against you.",
    "We have acted very wickedly toward you. We have not obeyed the commands, decrees and laws you gave your servant Moses.",
    "\"Remember the instruction you gave your servant Moses, saying, 'If you are unfaithful, I will scatter you among the nations,",
    "but if you return to me and obey my commands, then even if your exiled people are at the farthest horizon, I will gather them from there and bring them to the place I have chosen as a dwelling for my Name.'",
    "\"They are your servants and your people, whom you redeemed by your great strength and your mighty hand.",
    "O Lord, let your ear be attentive to the prayer of this your servant and to the prayer of your servants who delight in revering your name. Give your servant success today by granting him favor in the presence of this man.\" I was cupbearer to the king."
  ],
  "Nehemiah-1": [
    "In the month of Nisan in the twentieth year of King Artaxerxes, when wine was brought for him, I took the wine and gave it to the king. I had not been sad in his presence before;",
    "so the king asked me, \"Why does your face look so sad when you are not ill? This can be nothing but sadness of heart.\" I was very much afraid,",
    "but I said to the king, \"May the king live forever! Why should my face not look sad when the city where my fathers are buried lies in ruins, and its gates have been destroyed by fire?\"",
    "The king said to me, \"What is it you want?\" Then I prayed to the God of heaven,",
    "and I answered the king, \"If it pleases the king and if your servant has found favor in his sight, let him send me to the city in Judah where my fathers are buried so that I can rebuild it.\"",
    "Then the king, with the queen sitting beside him, asked me, \"How long will your journey take, and when will you get back?\" It pleased the king to send me; so I set a time.",
    "I also said to him, \"If it pleases the king, may I have letters to the governors of Trans-Euphrates, so that they will provide me safe-conduct until I arrive in Judah?",
    "And may I have a letter to Asaph, keeper of the king's forest, so he will give me timber to make beams for the gates of the citadel by the temple and for the city wall and for the residence I will occupy?\" And because the gracious hand of my God was upon me, the king granted my requests.",
    "So I went to the governors of Trans-Euphrates and gave them the king's letters. The king had also sent army officers and cavalry with me.",
    "When Sanballat the Horonite and Tobiah the Ammonite official heard about this, they were very much disturbed that someone had come to promote the welfare of the Israelites.",
    "I went to Jerusalem, and after staying there three days",
    "I set out during the night with a few men. I had not told anyone what my God had put in my heart to do for Jerusalem. There were no mounts with me except the one I was riding on.",
    "By night I went out through the Valley Gate toward the Jackal Well and the Dung Gate, examining the walls of Jerusalem, which had been broken down, and its gates, which had been destroyed by fire.",
    "Then I moved on toward the Fountain Gate and the King's Pool, but there was not enough room for my mount to get through;",
    "so I went up the valley by night, examining the wall. Finally, I turned back and reentered through the Valley Gate.",
    "The officials did not know where I had gone or what I was doing, because as yet I had said nothing to the Jews or the priests or nobles or officials or any others who would be doing the work.",
    "Then I said to them, \"You see the trouble we are in: Jerusalem lies in ruins, and its gates have been burned with fire. Come, let us rebuild the wall of Jerusalem, and we will no longer be in disgrace.\"",
    "I also told them about the gracious hand of my God upon me and what the king had said to me. They replied, \"Let us start rebuilding.\" So they began this good work.",
    "But when Sanballat the Horonite, Tobiah the Ammonite official and Geshem the Arab heard about it, they mocked and ridiculed us. \"What is this you are doing?\" they asked. \"Are you rebelling against the king?\"",
    "I answered them by saying, \"The God of heaven will give us success. We his servants will start rebuilding, but as for you, you have no share in Jerusalem or any claim or historic right to it.\""
  ],
  "Nehemiah-2": [
    "Eliashib the high priest and his fellow priests went to work and rebuilt the Sheep Gate. They dedicated it and set its doors in place, building as far as the Tower of the Hundred, which they dedicated, and as far as the Tower of Hananel.",
    "The men of Jericho built the adjoining section, and Zaccur son of Imri built next to them.",
    "The Fish Gate was rebuilt by the sons of Hassenaah. They laid its beams and put its doors and bolts and bars in place.",
    "Meremoth son of Uriah, the son of Hakkoz, repaired the next section. Next to him Meshullam son of Berekiah, the son of Meshezabel, made repairs, and next to him Zadok son of Baana also made repairs.",
    "The next section was repaired by the men of Tekoa, but their nobles would not put their shoulders to the work under their supervisors.",
    "The Jeshanah Gate was repaired by Joiada son of Paseah and Meshullam son of Besodeiah. They laid its beams and put its doors and bolts and bars in place.",
    "Next to them, repairs were made by men from Gibeon and Mizpah--Melatiah of Gibeon and Jadon of Meronoth--places under the authority of the governor of Trans-Euphrates.",
    "Uzziel son of Harhaiah, one of the goldsmiths, repaired the next section; and Hananiah, one of the perfume-makers, made repairs next to that. They restored Jerusalem as far as the Broad Wall.",
    "Rephaiah son of Hur, ruler of a half-district of Jerusalem, repaired the next section.",
    "Adjoining this, Jedaiah son of Harumaph made repairs opposite his house, and Hattush son of Hashabneiah made repairs next to him.",
    "Malkijah son of Harim and Hasshub son of Pahath-Moab repaired another section and the Tower of the Ovens.",
    "Shallum son of Hallohesh, ruler of a half-district of Jerusalem, repaired the next section with the help of his daughters.",
    "The Valley Gate was repaired by Hanun and the residents of Zanoah. They rebuilt it and put its doors and bolts and bars in place. They also repaired five hundred yards of the wall as far as the Dung Gate.",
    "The Dung Gate was repaired by Malkijah son of Recab, ruler of the district of Beth Hakkerem. He rebuilt it and put its doors and bolts and bars in place.",
    "The Fountain Gate was repaired by Shallun son of Col-Hozeh, ruler of the district of Mizpah. He rebuilt it, roofing it over and putting its doors and bolts and bars in place. He also repaired the wall of the Pool of Siloam, by the King's Garden, as far as the steps going down from the City of David.",
    "Beyond him, Neemiah son of Azbuk, ruler of a half-district of Beth Zur, made repairs up to a point opposite the tombs of David, as far as the artificial pool and the House of the Heroes.",
    "Next to him, the repairs were made by the Levites under Rehum son of Bani. Beside him, Hashabiah, ruler of half the district of Keilah, carried out repairs for his district.",
    "Next to him, the repairs were made by their countrymen under Binnui son of Henadad, ruler of the other half-district of Keilah.",
    "Next to him, Ezer son of Jeshua, ruler of Mizpah, repaired another section, from a point facing the ascent to the armory as far as the angle.",
    "Next to him, Baruch son of Zabbai zealously repaired another section, from the angle to the entrance of the house of Eliashib the high priest.",
    "Next to him, Meremoth son of Uriah, the son of Hakkoz, repaired another section, from the entrance of Eliashib's house to the end of it.",
    "The repairs next to him were made by the priests from the surrounding region.",
    "Beyond them, Benjamin and Hasshub made repairs in front of their house; and next to them, Azariah son of Maaseiah, the son of Ananiah, made repairs beside his house.",
    "Next to him, Binnui son of Henadad repaired another section, from Azariah's house to the angle and the corner,",
    "and Palal son of Uzai worked opposite the angle and the tower projecting from the upper palace near the court of the guard. Next to him, Pedaiah son of Parosh",
    "and the temple servants living on the hill of Ophel made repairs up to a point opposite the Water Gate toward the east and the projecting tower.",
    "Next to them, the men of Tekoa repaired another section, from the great projecting tower to the wall of Ophel.",
    "Above the Horse Gate, the priests made repairs, each in front of his own house.",
    "Next to them, Zadok son of Immer made repairs opposite his house. Next to him, Shemaiah son of Shecaniah, the guard at the East Gate, made repairs.",
    "Next to him, Hananiah son of Shelemiah, and Hanun, the sixth son of Zalaph, repaired another section. Next to them, Meshullam son of Berekiah made repairs opposite his living quarters.",
    "Next to him, Malkijah, one of the goldsmiths, made repairs as far as the house of the temple servants and the merchants, opposite the Inspection Gate, and as far as the room above the corner;",
    "and between the room above the corner and the Sheep Gate the goldsmiths and merchants made repairs."
  ],
  "Nehemiah-3": [
    "When Sanballat heard that we were rebuilding the wall, he became angry and was greatly incensed. He ridiculed the Jews,",
    "and in the presence of his associates and the army of Samaria, he said, \"What are those feeble Jews doing? Will they restore their wall? Will they offer sacrifices? Will they finish in a day? Can they bring the stones back to life from those heaps of rubble--burned as they are?\"",
    "Tobiah the Ammonite, who was at his side, said, \"What they are building--if even a fox climbed up on it, he would break down their wall of stones!\"",
    "Hear us, O our God, for we are despised. Turn their insults back on their own heads. Give them over as plunder in a land of captivity.",
    "Do not cover up their guilt or blot out their sins from your sight, for they have thrown insults in the face of the builders.",
    "So we rebuilt the wall till all of it reached half its height, for the people worked with all their heart.",
    "But when Sanballat, Tobiah, the Arabs, the Ammonites and the men of Ashdod heard that the repairs to Jerusalem's walls had gone ahead and that the gaps were being closed, they were very angry.",
    "They all plotted together to come and fight against Jerusalem and stir up trouble against it.",
    "But we prayed to our God and posted a guard day and night to meet this threat.",
    "Meanwhile, the people in Judah said, \"The strength of the laborers is giving out, and there is so much rubble that we cannot rebuild the wall.\"",
    "Also our enemies said, \"Before they know it or see us, we will be right there among them and will kill them and put an end to the work.\"",
    "Then the Jews who lived near them came and told us ten times over, \"Wherever you turn, they will attack us.\"",
    "Therefore I stationed some of the people behind the lowest points of the wall at the exposed places, posting them by families, with their swords, spears and bows.",
    "After I looked things over, I stood up and said to the nobles, the officials and the rest of the people, \"Don't be afraid of them. Remember the Lord, who is great and awesome, and fight for your brothers, your sons and your daughters, your wives and your homes.\"",
    "When our enemies heard that we were aware of their plot and that God had frustrated it, we all returned to the wall, each to his own work.",
    "From that day on, half of my men did the work, while the other half were equipped with spears, shields, bows and armor. The officers posted themselves behind all the people of Judah",
    "who were building the wall. Those who carried materials did their work with one hand and held a weapon in the other,",
    "and each of the builders wore his sword at his side as he worked. But the man who sounded the trumpet stayed with me.",
    "Then I said to the nobles, the officials and the rest of the people, \"The work is extensive and spread out, and we are widely separated from each other along the wall.",
    "Wherever you hear the sound of the trumpet, join us there. Our God will fight for us!\"",
    "So we continued the work with half the men holding spears, from the first light of dawn till the stars came out.",
    "At that time I also said to the people, \"Have every man and his helper stay inside Jerusalem at night, so they can serve us as guards by night and workmen by day.\"",
    "Neither I nor my brothers nor my men nor the guards with me took off our clothes; each had his weapon, even when he went for water."
  ],
  "Nehemiah-4": [
    "Now the men and their wives raised a great outcry against their Jewish brothers.",
    "Some were saying, \"We and our sons and daughters are numerous; in order for us to eat and stay alive, we must get grain.\"",
    "Others were saying, \"We are mortgaging our fields, our vineyards and our homes to get grain during the famine.\"",
    "Still others were saying, \"We have had to borrow money to pay the king's tax on our fields and vineyards.",
    "Although we are of the same flesh and blood as our countrymen and though our sons are as good as theirs, yet we have to subject our sons and daughters to slavery. Some of our daughters have already been enslaved, but we are powerless, because our fields and our vineyards belong to others.\"",
    "When I heard their outcry and these charges, I was very angry.",
    "I pondered them in my mind and then accused the nobles and officials. I told them, \"You are exacting usury from your own countrymen!\" So I called together a large meeting to deal with them",
    "and said: \"As far as possible, we have bought back our Jewish brothers who were sold to the Gentiles. Now you are selling your brothers, only for them to be sold back to us!\" They kept quiet, because they could find nothing to say.",
    "So I continued, \"What you are doing is not right. Shouldn't you walk in the fear of our God to avoid the reproach of our Gentile enemies?",
    "I and my brothers and my men are also lending the people money and grain. But let the exacting of usury stop!",
    "Give back to them immediately their fields, vineyards, olive groves and houses, and also the usury you are charging them--the hundredth part of the money, grain, new wine and oil.\"",
    "\"We will give it back,\" they said. \"And we will not demand anything more from them. We will do as you say.\" Then I summoned the priests and made the nobles and officials take an oath to do what they had promised.",
    "I also shook out the folds of my robe and said, \"In this way may God shake out of his house and possessions every man who does not keep this promise. So may such a man be shaken out and emptied!\" At this the whole assembly said, \"Amen,\" and praised the LORD. And the people did as they had promised.",
    "Moreover, from the twentieth year of King Artaxerxes, when I was appointed to be their governor in the land of Judah, until his thirty-second year--twelve years--neither I nor my brothers ate the food allotted to the governor.",
    "But the earlier governors--those preceding me--placed a heavy burden on the people and took forty shekels of silver from them in addition to food and wine. Their assistants also lorded it over the people. But out of reverence for God I did not act like that.",
    "Instead, I devoted myself to the work on this wall. All my men were assembled there for the work; we did not acquire any land.",
    "Furthermore, a hundred and fifty Jews and officials ate at my table, as well as those who came to us from the surrounding nations.",
    "Each day one ox, six choice sheep and some poultry were prepared for me, and every ten days an abundant supply of wine of all kinds. In spite of all this, I never demanded the food allotted to the governor, because the demands were heavy on these people.",
    "Remember me with favor, O my God, for all I have done for these people."
  ],
  "Nehemiah-5": [
    "When word came to Sanballat, Tobiah, Geshem the Arab and the rest of our enemies that I had rebuilt the wall and not a gap was left in it--though up to that time I had not set the doors in the gates--",
    "Sanballat and Geshem sent me this message: \"Come, let us meet together in one of the villages on the plain of Ono.\" But they were scheming to harm me;",
    "so I sent messengers to them with this reply: \"I am carrying on a great project and cannot go down. Why should the work stop while I leave it and go down to you?\"",
    "Four times they sent me the same message, and each time I gave them the same answer.",
    "Then, the fifth time, Sanballat sent his aide to me with the same message, and in his hand was an unsealed letter",
    "in which was written: \"It is reported among the nations--and Geshem says it is true--that you and the Jews are plotting to revolt, and therefore you are building the wall. Moreover, according to these reports you are about to become their king",
    "and have even appointed prophets to make this proclamation about you in Jerusalem: 'There is a king in Judah!' Now this report will get back to the king; so come, let us confer together.\"",
    "I sent him this reply: \"Nothing like what you are saying is happening; you are just making it up out of your head.\"",
    "They were all trying to frighten us, thinking, \"Their hands will get too weak for the work, and it will not be completed.\" But I prayed,\"Now strengthen my hands.\"",
    "One day I went to the house of Shemaiah son of Delaiah, the son of Mehetabel, who was shut in at his home. He said, \"Let us meet in the house of God, inside the temple, and let us close the temple doors, because men are coming to kill you--by night they are coming to kill you.\"",
    "But I said, \"Should a man like me run away? Or should one like me go into the temple to save his life? I will not go!\"",
    "I realized that God had not sent him, but that he had prophesied against me because Tobiah and Sanballat had hired him.",
    "He had been hired to intimidate me so that I would commit a sin by doing this, and then they would give me a bad name to discredit me.",
    "Remember Tobiah and Sanballat, O my God, because of what they have done; remember also the prophetess Noadiah and the rest of the prophets who have been trying to intimidate me.",
    "So the wall was completed on the twenty-fifth of Elul, in fifty-two days.",
    "When all our enemies heard about this, all the surrounding nations were afraid and lost their self-confidence, because they realized that this work had been done with the help of our God.",
    "Also, in those days the nobles of Judah were sending many letters to Tobiah, and replies from Tobiah kept coming to them.",
    "For many in Judah were under oath to him, since he was son-in-law to Shecaniah son of Arah, and his son Jehohanan had married the daughter of Meshullam son of Berekiah.",
    "Moreover, they kept reporting to me his good deeds and then telling him what I said. And Tobiah sent letters to intimidate me."
  ],
  "Nehemiah-6": [
    "After the wall had been rebuilt and I had set the doors in place, the gatekeepers and the singers and the Levites were appointed.",
    "I put in charge of Jerusalem my brother Hanani, along with Hananiah the commander of the citadel, because he was a man of integrity and feared God more than most men do.",
    "I said to them, \"The gates of Jerusalem are not to be opened until the sun is hot. While the gatekeepers are still on duty, have them shut the doors and bar them. Also appoint residents of Jerusalem as guards, some at their posts and some near their own houses.\"",
    "Now the city was large and spacious, but there were few people in it, and the houses had not yet been rebuilt.",
    "So my God put it into my heart to assemble the nobles, the officials and the common people for registration by families. I found the genealogical record of those who had been the first to return. This is what I found written there:",
    "These are the people of the province who came up from the captivity of the exiles whom Nebuchadnezzar king of Babylon had taken captive (they returned to Jerusalem and Judah, each to his own town,",
    "in company with Zerubbabel, Jeshua, Neemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Neum and Baanah): The list of the men of Israel:",
    "the descendants of Parosh 2,172",
    "of Shephatiah 372",
    "of Arah 652",
    "of Pahath-Moab (through the line of Jeshua and Joab) 2,818",
    "of Elam 1,254",
    "of Zattu 845",
    "of Zaccai 760",
    "of Binnui 648",
    "of Bebai 628",
    "of Azgad 2,322",
    "of Adonikam 667",
    "of Bigvai 2,067",
    "of Adin 655",
    "of Ater (through Hezekiah) 98",
    "of Hashum 328",
    "of Bezai 324",
    "of Hariph 112",
    "of Gibeon 95",
    "the men of Bethlehem and Netophah 188",
    "of Anathoth 128",
    "of Beth Azmaveth 42",
    "of Kiriath Jearim, Kephirah and Beeroth 743",
    "of Ramah and Geba 621",
    "of Micmash 122",
    "of Bethel and Ai 123",
    "of the other Nebo 52",
    "of the other Elam 1,254",
    "of Harim 320",
    "of Jericho 345",
    "of Lod, Hadid and Ono 721",
    "of Senaah 3,0930",
    "The priests: the descendants of Jedaiah (through the family of Jeshua) 973",
    "of Immer 1,052",
    "of Pashhur 1,247",
    "of Harim 1,017",
    "The Levites: the descendants of Jeshua (through Kadmiel through the line of Hodaviah) 74",
    "The singers: the descendants of Asaph 148",
    "The gatekeepers: the descendants of Shallum, Ater, Talmon, Akkub, Hatita and Shobai 138",
    "The temple servants: the descendants of Ziha, Hasupha, Tabbaoth,",
    "Keros, Sia, Padon,",
    "Lebana, Hagaba, Shalmai,",
    "Hanan, Giddel, Gahar,",
    "Reaiah, Rezin, Nekoda,",
    "Gazzam, Uzza, Paseah,",
    "Besai, Meunim, Nephussim,",
    "Bakbuk, Hakupha, Harhur,",
    "Bazluth, Mehida, Harsha,",
    "Barkos, Sisera, Temah,",
    "Neziah and Hatipha",
    "The descendants of the servants of Solomon: the descendants of Sotai, Sophereth, Perida,",
    "Jaala, Darkon, Giddel,",
    "Shephatiah, Hattil, Pokereth-Hazzebaim and Amon",
    "The temple servants and the descendants of the servants of Solomon 392",
    "The following came up from the towns of Tel Melah, Tel Harsha, Kerub, Addon and Immer, but they could not show that their families were descended from Israel:",
    "the descendants of Delaiah, Tobiah and Nekoda 642",
    "And from among the priests: the descendants of Hobaiah, Hakkoz and Barzillai (a man who had married a daughter of Barzillai the Gileadite and was called by that name).",
    "These searched for their family records, but they could not find them and so were excluded from the priesthood as unclean.",
    "The governor, therefore, ordered them not to eat any of the most sacred food until there should be a priest ministering with the Urim and Thummim.",
    "The whole company numbered 42,360,",
    "besides their 7,337 menservants and maidservants; and they also had 245 men and women singers.",
    "There were 736 horses, 245 mules,",
    "435 camels and 6,720 donkeys.",
    "Some of the heads of the families contributed to the work. The governor gave to the treasury 1,000 drachmas of gold, 50 bowls and 530 garments for priests.",
    "Some of the heads of the families gave to the treasury for the work 20,000 drachmas of gold and 2,200 minas of silver.",
    "The total given by the rest of the people was 20,000 drachmas of gold, 2,000 minas of silver and 67 garments for priests.",
    "The priests, the Levites, the gatekeepers, the singers and the temple servants, along with certain of the people and the rest of the Israelites, settled in their own towns. When the seventh month came and the Israelites had settled in their towns,"
  ],
  "Nehemiah-7": [
    "all the people assembled as one man in the square before the Water Gate. They told Ezra the scribe to bring out the Book of the Law of Moses, which the LORD had commanded for Israel.",
    "So on the first day of the seventh month Ezra the priest brought the Law before the assembly, which was made up of men and women and all who were able to understand.",
    "He read it aloud from daybreak till noon as he faced the square before the Water Gate in the presence of the men, women and others who could understand. And all the people listened attentively to the Book of the Law.",
    "Ezra the scribe stood on a high wooden platform built for the occasion. Beside him on his right stood Mattithiah, Shema, Anaiah, Uriah, Hilkiah and Maaseiah; and on his left were Pedaiah, Mishael, Malkijah, Hashum, Hashbaddanah, Zechariah and Meshullam.",
    "Ezra opened the book. All the people could see him because he was standing above them; and as he opened it, the people all stood up.",
    "Ezra praised the LORD, the great God; and all the people lifted their hands and responded, \"Amen! Amen!\" Then they bowed down and worshiped the LORD with their faces to the ground.",
    "The Levites--Jeshua, Bani, Sherebiah, Jamin, Akkub, Shabbethai, Hodiah, Maaseiah, Kelita, Azariah, Jozabad, Hanan and Pelaiah--instructed the people in the Law while the people were standing there.",
    "They read from the Book of the Law of God, making it clear and giving the meaning so that the people could understand what was being read.",
    "Then Neemiah the governor, Ezra the priest and scribe, and the Levites who were instructing the people said to them all, \"This day is sacred to the LORD your God. Do not mourn or weep.\" For all the people had been weeping as they listened to the words of the Law.",
    "Neemiah said, \"Go and enjoy choice food and sweet drinks, and send some to those who have nothing prepared. This day is sacred to our Lord. Do not grieve, for the joy of the LORD is your strength.\"",
    "The Levites calmed all the people, saying, \"Be still, for this is a sacred day. Do not grieve.\"",
    "Then all the people went away to eat and drink, to send portions of food and to celebrate with great joy, because they now understood the words that had been made known to them.",
    "On the second day of the month, the heads of all the families, along with the priests and the Levites, gathered around Ezra the scribe to give attention to the words of the Law.",
    "They found written in the Law, which the LORD had commanded through Moses, that the Israelites were to live in booths during the feast of the seventh month",
    "and that they should proclaim this word and spread it throughout their towns and in Jerusalem: \"Go out into the hill country and bring back branches from olive and wild olive trees, and from myrtles, palms and shade trees, to make booths\"--as it is written.",
    "So the people went out and brought back branches and built themselves booths on their own roofs, in their courtyards, in the courts of the house of God and in the square by the Water Gate and the one by the Gate of Ephraim.",
    "The whole company that had returned from exile built booths and lived in them. From the days of Joshua son of Nun until that day, the Israelites had not celebrated it like this. And their joy was very great.",
    "Day after day, from the first day to the last, Ezra read from the Book of the Law of God. They celebrated the feast for seven days, and on the eighth day, in accordance with the regulation, there was an assembly."
  ],
  "Nehemiah-8": [
    "On the twenty-fourth day of the same month, the Israelites gathered together, fasting and wearing sackcloth and having dust on their heads.",
    "Those of Israelite descent had separated themselves from all foreigners. They stood in their places and confessed their sins and the wickedness of their fathers.",
    "They stood where they were and read from the Book of the Law of the LORD their God for a quarter of the day, and spent another quarter in confession and in worshiping the LORD their God.",
    "Standing on the stairs were the Levites--Jeshua, Bani, Kadmiel, Shebaniah, Bunni, Sherebiah, Bani and Kenani--who called with loud voices to the LORD their God.",
    "And the Levites--Jeshua, Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah and Pethahiah--said: \"Stand up and praise the LORD your God, who is from everlasting to everlasting.\" \"Blessed be your glorious name, and may it be exalted above all blessing and praise.",
    "You alone are the LORD. You made the heavens, even the highest heavens, and all their starry host, the earth and all that is on it, the seas and all that is in them. You give life to everything, and the multitudes of heaven worship you.",
    "\"You are the LORD God, who chose Abram and brought him out of Ur of the Chaldeans and named him Abraham.",
    "You found his heart faithful to you, and you made a covenant with him to give to his descendants the land of the Canaanites, Hittites, Amorites, Perizzites, Jebusites and Girgashites. You have kept your promise because you are righteous.",
    "\"You saw the suffering of our forefathers in Egypt; you heard their cry at the Red Sea.",
    "You sent miraculous signs and wonders against Pharaoh, against all his officials and all the people of his land, for you knew how arrogantly the Egyptians treated them. You made a name for yourself, which remains to this day.",
    "You divided the sea before them, so that they passed through it on dry ground, but you hurled their pursuers into the depths, like a stone into mighty waters.",
    "By day you led them with a pillar of cloud, and by night with a pillar of fire to give them light on the way they were to take.",
    "\"You came down on Mount Sinai; you spoke to them from heaven. You gave them regulations and laws that are just and right, and decrees and commands that are good.",
    "You made known to them your holy Sabbath and gave them commands, decrees and laws through your servant Moses.",
    "In their hunger you gave them bread from heaven and in their thirst you brought them water from the rock; you told them to go in and take possession of the land you had sworn with uplifted hand to give them.",
    "\"But they, our forefathers, became arrogant and stiff-necked, and did not obey your commands.",
    "They refused to listen and failed to remember the miracles you performed among them. They became stiff-necked and in their rebellion appointed a leader in order to return to their slavery. But you are a forgiving God, gracious and compassionate, slow to anger and abounding in love. Therefore you did not desert them,",
    "even when they cast for themselves an image of a calf and said, 'This is your god, who brought you up out of Egypt,' or when they committed awful blasphemies.",
    "\"Because of your great compassion you did not abandon them in the desert. By day the pillar of cloud did not cease to guide them on their path, nor the pillar of fire by night to shine on the way they were to take.",
    "You gave your good Spirit to instruct them. You did not withhold your manna from their mouths, and you gave them water for their thirst.",
    "For forty years you sustained them in the desert; they lacked nothing, their clothes did not wear out nor did their feet become swollen.",
    "\"You gave them kingdoms and nations, allotting to them even the remotest frontiers. They took over the country of Sihon king of Heshbon and the country of Og king of Bashan.",
    "You made their sons as numerous as the stars in the sky, and you brought them into the land that you told their fathers to enter and possess.",
    "Their sons went in and took possession of the land. You subdued before them the Canaanites, who lived in the land; you handed the Canaanites over to them, along with their kings and the peoples of the land, to deal with them as they pleased.",
    "They captured fortified cities and fertile land; they took possession of houses filled with all kinds of good things, wells already dug, vineyards, olive groves and fruit trees in abundance. They ate to the full and were well-nourished; they reveled in your great goodness.",
    "\"But they were disobedient and rebelled against you; they put your law behind their backs. They killed your prophets, who had admonished them in order to turn them back to you; they committed awful blasphemies.",
    "So you handed them over to their enemies, who oppressed them. But when they were oppressed they cried out to you. From heaven you heard them, and in your great compassion you gave them deliverers, who rescued them from the hand of their enemies.",
    "\"But as soon as they were at rest, they again did what was evil in your sight. Then you abandoned them to the hand of their enemies so that they ruled over them. And when they cried out to you again, you heard from heaven, and in your compassion you delivered them time after time.",
    "\"You warned them to return to your law, but they became arrogant and disobeyed your commands. They sinned against your ordinances, by which a man will live if he obeys them. Stubbornly they turned their backs on you, became stiff-necked and refused to listen.",
    "For many years you were patient with them. By your Spirit you admonished them through your prophets. Yet they paid no attention, so you handed them over to the neighboring peoples.",
    "But in your great mercy you did not put an end to them or abandon them, for you are a gracious and merciful God.",
    "\"Now therefore, O our God, the great, mighty and awesome God, who keeps his covenant of love, do not let all this hardship seem trifling in your eyes--the hardship that has come upon us, upon our kings and leaders, upon our priests and prophets, upon our fathers and all your people, from the days of the kings of Assyria until today.",
    "In all that has happened to us, you have been just; you have acted faithfully, while we did wrong.",
    "Our kings, our leaders, our priests and our fathers did not follow your law; they did not pay attention to your commands or the warnings you gave them.",
    "Even while they were in their kingdom, enjoying your great goodness to them in the spacious and fertile land you gave them, they did not serve you or turn from their evil ways.",
    "\"But see, we are slaves today, slaves in the land you gave our forefathers so they could eat its fruit and the other good things it produces.",
    "Because of our sins, its abundant harvest goes to the kings you have placed over us. They rule over our bodies and our cattle as they please. We are in great distress.",
    "\"In view of all this, we are making a binding agreement, putting it in writing, and our leaders, our Levites and our priests are affixing their seals to it.\""
  ],
  "Nehemiah-9": [
    "Those who sealed it were: Neemiah the governor, the son of Hacaliah. Zedekiah,",
    "Seraiah, Azariah, Jeremiah,",
    "Pashhur, Amariah, Malkijah,",
    "Hattush, Shebaniah, Malluch,",
    "Harim, Meremoth, Obadiah,",
    "Daniel, Ginnethon, Baruch,",
    "Meshullam, Abijah, Mijamin,",
    "Maaziah, Bilgai and Shemaiah. These were the priests.",
    "The Levites: Jeshua son of Azaniah, Binnui of the sons of Henadad, Kadmiel,",
    "and their associates: Shebaniah, Hodiah, Kelita, Pelaiah, Hanan,",
    "Mica, Rehob, Hashabiah,",
    "Zaccur, Sherebiah, Shebaniah,",
    "Hodiah, Bani and Beninu.",
    "The leaders of the people: Parosh, Pahath-Moab, Elam, Zattu, Bani,",
    "Bunni, Azgad, Bebai,",
    "Adonijah, Bigvai, Adin,",
    "Ater, Hezekiah, Azzur,",
    "Hodiah, Hashum, Bezai,",
    "Hariph, Anathoth, Nebai,",
    "Magpiash, Meshullam, Hezir,",
    "Meshezabel, Zadok, Jaddua,",
    "Pelatiah, Hanan, Anaiah,",
    "Hoshea, Hananiah, Hasshub,",
    "Hallohesh, Pilha, Shobek,",
    "Rehum, Hashabnah, Maaseiah,",
    "Ahiah, Hanan, Anan,",
    "Malluch, Harim and Baanah.",
    "\"The rest of the people--priests, Levites, gatekeepers, singers, temple servants and all who separated themselves from the neighboring peoples for the sake of the Law of God, together with their wives and all their sons and daughters who are able to understand--",
    "all these now join their brothers the nobles, and bind themselves with a curse and an oath to follow the Law of God given through Moses the servant of God and to obey carefully all the commands, regulations and decrees of the LORD our Lord.",
    "\"We promise not to give our daughters in marriage to the peoples around us or take their daughters for our sons.",
    "\"When the neighboring peoples bring merchandise or grain to sell on the Sabbath, we will not buy from them on the Sabbath or on any holy day. Every seventh year we will forgo working the land and will cancel all debts.",
    "\"We assume the responsibility for carrying out the commands to give a third of a shekel each year for the service of the house of our God:",
    "for the bread set out on the table; for the regular grain offerings and burnt offerings; for the offerings on the Sabbaths, New Moon festivals and appointed feasts; for the holy offerings; for sin offerings to make atonement for Israel; and for all the duties of the house of our God.",
    "\"We--the priests, the Levites and the people--have cast lots to determine when each of our families is to bring to the house of our God at set times each year a contribution of wood to burn on the altar of the LORD our God, as it is written in the Law.",
    "\"We also assume responsibility for bringing to the house of the LORD each year the firstfruits of our crops and of every fruit tree.",
    "\"As it is also written in the Law, we will bring the firstborn of our sons and of our cattle, of our herds and of our flocks to the house of our God, to the priests ministering there.",
    "\"Moreover, we will bring to the storerooms of the house of our God, to the priests, the first of our ground meal, of our grain offerings, of the fruit of all our trees and of our new wine and oil. And we will bring a tithe of our crops to the Levites, for it is the Levites who collect the tithes in all the towns where we work.",
    "A priest descended from Aaron is to accompany the Levites when they receive the tithes, and the Levites are to bring a tenth of the tithes up to the house of our God, to the storerooms of the treasury.",
    "The people of Israel, including the Levites, are to bring their contributions of grain, new wine and oil to the storerooms where the articles for the sanctuary are kept and where the ministering priests, the gatekeepers and the singers stay. \"We will not neglect the house of our God.\""
  ],
  "Nehemiah-10": [
    "Now the leaders of the people settled in Jerusalem, and the rest of the people cast lots to bring one out of every ten to live in Jerusalem, the holy city, while the remaining nine were to stay in their own towns.",
    "The people commended all the men who volunteered to live in Jerusalem.",
    "These are the provincial leaders who settled in Jerusalem (now some Israelites, priests, Levites, temple servants and descendants of Solomon's servants lived in the towns of Judah, each on his own property in the various towns,",
    "while other people from both Judah and Benjamin lived in Jerusalem): From the descendants of Judah: Athaiah son of Uzziah, the son of Zechariah, the son of Amariah, the son of Shephatiah, the son of Mahalalel, a descendant of Perez;",
    "and Maaseiah son of Baruch, the son of Col-Hozeh, the son of Hazaiah, the son of Adaiah, the son of Joiarib, the son of Zechariah, a descendant of Shelah.",
    "The descendants of Perez who lived in Jerusalem totaled 468 able men.",
    "From the descendants of Benjamin: Sallu son of Meshullam, the son of Joed, the son of Pedaiah, the son of Kolaiah, the son of Maaseiah, the son of Ithiel, the son of Jeshaiah,",
    "and his followers, Gabbai and Sallai--928 men.",
    "Joel son of Zicri was their chief officer, and Judah son of Hassenuah was over the Second District of the city.",
    "From the priests: Jedaiah; the son of Joiarib; Jakin;",
    "Seraiah son of Hilkiah, the son of Meshullam, the son of Zadok, the son of Meraioth, the son of Ahitub, supervisor in the house of God,",
    "and their associates, who carried on work for the temple--822 men; Adaiah son of Jeroham, the son of Pelaliah, the son of Amzi, the son of Zechariah, the son of Pashhur, the son of Malkijah,",
    "and his associates, who were heads of families--242 men; Amashsai son of Azarel, the son of Ahzai, the son of Meshillemoth, the son of Immer,",
    "and his associates, who were able men--128. Their chief officer was Zabdiel son of Haggedolim.",
    "From the Levites: Shemaiah son of Hasshub, the son of Azrikam, the son of Hashabiah, the son of Bunni;",
    "Shabbethai and Jozabad, two of the heads of the Levites, who had charge of the outside work of the house of God;",
    "Mattaniah son of Mica, the son of Zabdi, the son of Asaph, the director who led in thanksgiving and prayer; Bakbukiah, second among his associates; and Abda son of Shammua, the son of Galal, the son of Jeduthun.",
    "The Levites in the holy city totaled 284.",
    "The gatekeepers: Akkub, Talmon and their associates, who kept watch at the gates--172 men.",
    "The rest of the Israelites, with the priests and Levites, were in all the towns of Judah, each on his ancestral property.",
    "The temple servants lived on the hill of Ophel, and Ziha and Gishpa were in charge of them.",
    "The chief officer of the Levites in Jerusalem was Uzzi son of Bani, the son of Hashabiah, the son of Mattaniah, the son of Mica. Uzzi was one of Asaph's descendants, who were the singers responsible for the service of the house of God.",
    "The singers were under the king's orders, which regulated their daily activity.",
    "Pethahiah son of Meshezabel, one of the descendants of Zerah son of Judah, was the king's agent in all affairs relating to the people.",
    "As for the villages with their fields, some of the people of Judah lived in Kiriath Arba and its surrounding settlements, in Dibon and its settlements, in Jekabzeel and its villages,",
    "in Jeshua, in Moladah, in Beth Pelet,",
    "in Hazar Shual, in Beersheba and its settlements,",
    "in Ziklag, in Meconah and its settlements,",
    "in En Rimmon, in Zorah, in Jarmuth,",
    "Zanoah, Adullam and their villages, in Lachish and its fields, and in Azekah and its settlements. So they were living all the way from Beersheba to the Valley of Hinnom.",
    "The descendants of the Benjamites from Geba lived in Micmash, Aija, Bethel and its settlements,",
    "in Anathoth, Nob and Ananiah,",
    "in Hazor, Ramah and Gittaim,",
    "in Hadid, Zeboim and Neballat,",
    "in Lod and Ono, and in the Valley of the Craftsmen.",
    "Some of the divisions of the Levites of Judah settled in Benjamin."
  ],
  "Nehemiah-11": [
    "These were the priests and Levites who returned with Zerubbabel son of Shealtiel and with Jeshua: Seraiah, Jeremiah, Ezra,",
    "Amariah, Malluch, Hattush,",
    "Shecaniah, Rehum, Meremoth,",
    "Iddo, Ginnethon, Abijah,",
    "Mijamin, Moadiah, Bilgah,",
    "Shemaiah, Joiarib, Jedaiah,",
    "Sallu, Amok, Hilkiah and Jedaiah. These were the leaders of the priests and their associates in the days of Jeshua.",
    "The Levites were Jeshua, Binnui, Kadmiel, Sherebiah, Judah, and also Mattaniah, who, together with his associates, was in charge of the songs of thanksgiving.",
    "Bakbukiah and Unni, their associates, stood opposite them in the services.",
    "Jeshua was the father of Joiakim, Joiakim the father of Eliashib, Eliashib the father of Joiada,",
    "Joiada the father of Jonathan, and Jonathan the father of Jaddua.",
    "In the days of Joiakim, these were the heads of the priestly families: of Seraiah's family, Meraiah; of Jeremiah's, Hananiah;",
    "of Ezra's, Meshullam; of Amariah's, Jehohanan;",
    "of Malluch's, Jonathan; of Shecaniah's, Joseph;",
    "of Harim's, Adna; of Meremoth's, Helkai;",
    "of Iddo's, Zechariah; of Ginnethon's, Meshullam;",
    "of Abijah's, Zicri; of Miniamin's and of Moadiah's, Piltai;",
    "of Bilgah's, Shammua; of Shemaiah's, Jehonathan;",
    "of Joiarib's, Mattenai; of Jedaiah's, Uzzi;",
    "of Sallu's, Kallai; of Amok's, Eber;",
    "of Hilkiah's, Hashabiah; of Jedaiah's, Nethanel.",
    "The family heads of the Levites in the days of Eliashib, Joiada, Johanan and Jaddua, as well as those of the priests, were recorded in the reign of Darius the Persian.",
    "The family heads among the descendants of Levi up to the time of Johanan son of Eliashib were recorded in the book of the annals.",
    "And the leaders of the Levites were Hashabiah, Sherebiah, Jeshua son of Kadmiel, and their associates, who stood opposite them to give praise and thanksgiving, one section responding to the other, as prescribed by David the man of God.",
    "Mattaniah, Bakbukiah, Obadiah, Meshullam, Talmon and Akkub were gatekeepers who guarded the storerooms at the gates.",
    "They served in the days of Joiakim son of Jeshua, the son of Jozadak, and in the days of Neemiah the governor and of Ezra the priest and scribe.",
    "At the dedication of the wall of Jerusalem, the Levites were sought out from where they lived and were brought to Jerusalem to celebrate joyfully the dedication with songs of thanksgiving and with the music of cymbals, harps and lyres.",
    "The singers also were brought together from the region around Jerusalem--from the villages of the Netophathites,",
    "from Beth Gilgal, and from the area of Geba and Azmaveth, for the singers had built villages for themselves around Jerusalem.",
    "When the priests and Levites had purified themselves ceremonially, they purified the people, the gates and the wall.",
    "I had the leaders of Judah go up on top of the wall. I also assigned two large choirs to give thanks. One was to proceed on top of the wall to the right, toward the Dung Gate.",
    "Hoshaiah and half the leaders of Judah followed them,",
    "along with Azariah, Ezra, Meshullam,",
    "Judah, Benjamin, Shemaiah, Jeremiah,",
    "as well as some priests with trumpets, and also Zechariah son of Jonathan, the son of Shemaiah, the son of Mattaniah, the son of Micaiah, the son of Zaccur, the son of Asaph,",
    "and his associates--Shemaiah, Azarel, Milalai, Gilalai, Maai, Nethanel, Judah and Hanani--with musical instruments prescribed by David the man of God. Ezra the scribe led the procession.",
    "At the Fountain Gate they continued directly up the steps of the City of David on the ascent to the wall and passed above the house of David to the Water Gate on the east.",
    "The second choir proceeded in the opposite direction. I followed them on top of the wall, together with half the people--past the Tower of the Ovens to the Broad Wall,",
    "over the Gate of Ephraim, the Jeshanah Gate, the Fish Gate, the Tower of Hananel and the Tower of the Hundred, as far as the Sheep Gate. At the Gate of the Guard they stopped.",
    "The two choirs that gave thanks then took their places in the house of God; so did I, together with half the officials,",
    "as well as the priests--Eliakim, Maaseiah, Miniamin, Micaiah, Elioenai, Zechariah and Hananiah with their trumpets--",
    "and also Maaseiah, Shemaiah, Eleazar, Uzzi, Jehohanan, Malkijah, Elam and Ezer. The choirs sang under the direction of Jezrahiah.",
    "And on that day they offered great sacrifices, rejoicing because God had given them great joy. The women and children also rejoiced. The sound of rejoicing in Jerusalem could be heard far away.",
    "At that time men were appointed to be in charge of the storerooms for the contributions, firstfruits and tithes. From the fields around the towns they were to bring into the storerooms the portions required by the Law for the priests and the Levites, for Judah was pleased with the ministering priests and Levites.",
    "They performed the service of their God and the service of purification, as did also the singers and gatekeepers, according to the commands of David and his son Solomon.",
    "For long ago, in the days of David and Asaph, there had been directors for the singers and for the songs of praise and thanksgiving to God.",
    "So in the days of Zerubbabel and of Neemiah, all Israel contributed the daily portions for the singers and gatekeepers. They also set aside the portion for the other Levites, and the Levites set aside the portion for the descendants of Aaron."
  ],
  "Nehemiah-12": [
    "On that day the Book of Moses was read aloud in the hearing of the people and there it was found written that no Ammonite or Moabite should ever be admitted into the assembly of God,",
    "because they had not met the Israelites with food and water but had hired Balaam to call a curse down on them. (Our God, however, turned the curse into a blessing.)",
    "When the people heard this law, they excluded from Israel all who were of foreign descent.",
    "Before this, Eliashib the priest had been put in charge of the storerooms of the house of our God. He was closely associated with Tobiah,",
    "and he had provided him with a large room formerly used to store the grain offerings and incense and temple articles, and also the tithes of grain, new wine and oil prescribed for the Levites, singers and gatekeepers, as well as the contributions for the priests.",
    "But while all this was going on, I was not in Jerusalem, for in the thirty-second year of Artaxerxes king of Babylon I had returned to the king. Some time later I asked his permission",
    "and came back to Jerusalem. Here I learned about the evil thing Eliashib had done in providing Tobiah a room in the courts of the house of God.",
    "I was greatly displeased and threw all Tobiah's household goods out of the room.",
    "I gave orders to purify the rooms, and then I put back into them the equipment of the house of God, with the grain offerings and the incense.",
    "I also learned that the portions assigned to the Levites had not been given to them, and that all the Levites and singers responsible for the service had gone back to their own fields.",
    "So I rebuked the officials and asked them, \"Why is the house of God neglected?\" Then I called them together and stationed them at their posts.",
    "All Judah brought the tithes of grain, new wine and oil into the storerooms.",
    "I put Shelemiah the priest, Zadok the scribe, and a Levite named Pedaiah in charge of the storerooms and made Hanan son of Zaccur, the son of Mattaniah, their assistant, because these men were considered trustworthy. They were made responsible for distributing the supplies to their brothers.",
    "Remember me for this, O my God, and do not blot out what I have so faithfully done for the house of my God and its services.",
    "In those days I saw men in Judah treading winepresses on the Sabbath and bringing in grain and loading it on donkeys, together with wine, grapes, figs and all other kinds of loads. And they were bringing all this into Jerusalem on the Sabbath. Therefore I warned them against selling food on that day.",
    "Men from Tyre who lived in Jerusalem were bringing in fish and all kinds of merchandise and selling them in Jerusalem on the Sabbath to the people of Judah.",
    "I rebuked the nobles of Judah and said to them, \"What is this wicked thing you are doing--desecrating the Sabbath day?",
    "Didn't your forefathers do the same things, so that our God brought all this calamity upon us and upon this city? Now you are stirring up more wrath against Israel by desecrating the Sabbath.\"",
    "When evening shadows fell on the gates of Jerusalem before the Sabbath, I ordered the doors to be shut and not opened until the Sabbath was over. I stationed some of my own men at the gates so that no load could be brought in on the Sabbath day.",
    "Once or twice the merchants and sellers of all kinds of goods spent the night outside Jerusalem.",
    "But I warned them and said, \"Why do you spend the night by the wall? If you do this again, I will lay hands on you.\" From that time on they no longer came on the Sabbath.",
    "Then I commanded the Levites to purify themselves and go and guard the gates in order to keep the Sabbath day holy. Remember me for this also, O my God, and show mercy to me according to your great love.",
    "Moreover, in those days I saw men of Judah who had married women from Ashdod, Ammon and Moab.",
    "Half of their children spoke the language of Ashdod or the language of one of the other peoples, and did not know how to speak the language of Judah.",
    "I rebuked them and called curses down on them. I beat some of the men and pulled out their hair. I made them take an oath in God's name and said: \"You are not to give your daughters in marriage to their sons, nor are you to take their daughters in marriage for your sons or for yourselves.",
    "Was it not because of marriages like these that Solomon king of Israel sinned? Among the many nations there was no king like him. He was loved by his God, and God made him king over all Israel, but even he was led into sin by foreign women.",
    "Must we hear now that you too are doing all this terrible wickedness and are being unfaithful to our God by marrying foreign women?\"",
    "One of the sons of Joiada son of Eliashib the high priest was son-in-law to Sanballat the Horonite. And I drove him away from me.",
    "Remember them, O my God, because they defiled the priestly office and the covenant of the priesthood and of the Levites.",
    "So I purified the priests and the Levites of everything foreign, and assigned them duties, each to his own task.",
    "I also made provision for contributions of wood at designated times, and for the firstfruits. Remember me with favor, O my God."
  ]
};