const Proverbs = {
  "Proverbs-0": [
    "The proverbs of Solomon son of David, king of Israel:",
    "for attaining wisdom and discipline; for understanding words of insight;",
    "for acquiring a disciplined and prudent life, doing what is right and just and fair;",
    "for giving prudence to the simple, knowledge and discretion to the young--",
    "let the wise listen and add to their learning, and let the discerning get guidance--",
    "for understanding proverbs and parables, the sayings and riddles of the wise.",
    "The fear of the LORD is the beginning of knowledge, but fools despise wisdom and discipline.",
    "Listen, my son, to your father's instruction and do not forsake your mother's teaching.",
    "They will be a garland to grace your head and a chain to adorn your neck.",
    "My son, if sinners entice you, do not give in to them.",
    "If they say, \"Come along with us; let's lie in wait for someone's blood, let's waylay some harmless soul;",
    "let's swallow them alive, like the grave, and whole, like those who go down to the pit;",
    "we will get all sorts of valuable things and fill our houses with plunder;",
    "throw in your lot with us, and we will share a common purse\"--",
    "my son, do not go along with them, do not set foot on their paths;",
    "for their feet rush into sin, they are swift to shed blood.",
    "How useless to spread a net in full view of all the birds!",
    "These men lie in wait for their own blood; they waylay only themselves!",
    "Such is the end of all who go after ill-gotten gain; it takes away the lives of those who get it.",
    "Wisdom calls aloud in the street, she raises her voice in the public squares;",
    "at the head of the noisy streets she cries out, in the gateways of the city she makes her speech:",
    "\"How long will you simple ones love your simple ways? How long will mockers delight in mockery and fools hate knowledge?",
    "If you had responded to my rebuke, I would have poured out my heart to you and made my thoughts known to you.",
    "But since you rejected me when I called and no one gave heed when I stretched out my hand,",
    "since you ignored all my advice and would not accept my rebuke,",
    "I in turn will laugh at your disaster; I will mock when calamity overtakes you--",
    "when calamity overtakes you like a storm, when disaster sweeps over you like a whirlwind, when distress and trouble overwhelm you.",
    "\"Then they will call to me but I will not answer; they will look for me but will not find me.",
    "Since they hated knowledge and did not choose to fear the LORD,",
    "since they would not accept my advice and spurned my rebuke,",
    "they will eat the fruit of their ways and be filled with the fruit of their schemes.",
    "For the waywardness of the simple will kill them, and the complacency of fools will destroy them;",
    "but whoever listens to me will live in safety and be at ease, without fear of harm.\""
  ],
  "Proverbs-1": [
    "My son, if you accept my words and store up my commands within you,",
    "turning your ear to wisdom and applying your heart to understanding,",
    "and if you call out for insight and cry aloud for understanding,",
    "and if you look for it as for silver and search for it as for hidden treasure,",
    "then you will understand the fear of the LORD and find the knowledge of God.",
    "For the LORD gives wisdom, and from his mouth come knowledge and understanding.",
    "He holds victory in store for the upright, he is a shield to those whose walk is blameless,",
    "for he guards the course of the just and protects the way of his faithful ones.",
    "Then you will understand what is right and just and fair--every good path.",
    "For wisdom will enter your heart, and knowledge will be pleasant to your soul.",
    "Discretion will protect you, and understanding will guard you.",
    "Wisdom will save you from the ways of wicked men, from men whose words are perverse,",
    "who leave the straight paths to walk in dark ways,",
    "who delight in doing wrong and rejoice in the perverseness of evil,",
    "whose paths are crooked and who are devious in their ways.",
    "It will save you also from the adulteress, from the wayward wife with her seductive words,",
    "who has left the partner of her youth and ignored the covenant she made before God.",
    "For her house leads down to death and her paths to the spirits of the dead.",
    "None who go to her return or attain the paths of life.",
    "Thus you will walk in the ways of good men and keep to the paths of the righteous.",
    "For the upright will live in the land, and the blameless will remain in it;",
    "but the wicked will be cut off from the land, and the unfaithful will be torn from it."
  ],
  "Proverbs-2": [
    "My son, do not forget my teaching, but keep my commands in your heart,",
    "for they will prolong your life many years and bring you prosperity.",
    "Let love and faithfulness never leave you; bind them around your neck, write them on the tablet of your heart.",
    "Then you will win favor and a good name in the sight of God and man.",
    "Trust in the LORD with all your heart and lean not on your own understanding;",
    "in all your ways acknowledge him, and he will make your paths straight.",
    "Do not be wise in your own eyes; fear the LORD and shun evil.",
    "This will bring health to your body and nourishment to your bones.",
    "Honor the LORD with your wealth, with the firstfruits of all your crops;",
    "then your barns will be filled to overflowing, and your vats will brim over with new wine.",
    "My son, do not despise the LORD'S discipline and do not resent his rebuke,",
    "because the LORD disciplines those he loves, as a father the son he delights in.",
    "Blessed is the man who finds wisdom, the man who gains understanding,",
    "for she is more profitable than silver and yields better returns than gold.",
    "She is more precious than rubies; nothing you desire can compare with her.",
    "Long life is in her right hand; in her left hand are riches and honor.",
    "Her ways are pleasant ways, and all her paths are peace.",
    "She is a tree of life to those who embrace her; those who lay hold of her will be blessed.",
    "By wisdom the LORD laid the earth's foundations, by understanding he set the heavens in place;",
    "by his knowledge the deeps were divided, and the clouds let drop the dew.",
    "My son, preserve sound judgment and discernment, do not let them out of your sight;",
    "they will be life for you, an ornament to grace your neck.",
    "Then you will go on your way in safety, and your foot will not stumble;",
    "when you lie down, you will not be afraid; when you lie down, your sleep will be sweet.",
    "Have no fear of sudden disaster or of the ruin that overtakes the wicked,",
    "for the LORD will be your confidence and will keep your foot from being snared.",
    "Do not withhold good from those who deserve it, when it is in your power to act.",
    "Do not say to your neighbor, \"Come back later; I'll give it tomorrow\"--when you now have it with you.",
    "Do not plot harm against your neighbor, who lives trustfully near you.",
    "Do not accuse a man for no reason--when he has done you no harm.",
    "Do not envy a violent man or choose any of his ways,",
    "for the LORD detests a perverse man but takes the upright into his confidence.",
    "The LORD'S curse is on the house of the wicked, but he blesses the home of the righteous.",
    "He mocks proud mockers but gives grace to the humble.",
    "The wise inherit honor, but fools he holds up to shame."
  ],
  "Proverbs-3": [
    "Listen, my sons, to a father's instruction; pay attention and gain understanding.",
    "I give you sound learning, so do not forsake my teaching.",
    "When I was a boy in my father's house, still tender, and an only child of my mother,",
    "he taught me and said, \"Lay hold of my words with all your heart; keep my commands and you will live.",
    "Get wisdom, get understanding; do not forget my words or swerve from them.",
    "Do not forsake wisdom, and she will protect you; love her, and she will watch over you.",
    "Wisdom is supreme; therefore get wisdom. Though it cost all you have, get understanding.",
    "Esteem her, and she will exalt you; embrace her, and she will honor you.",
    "She will set a garland of grace on your head and present you with a crown of splendor.\"",
    "Listen, my son, accept what I say, and the years of your life will be many.",
    "I guide you in the way of wisdom and lead you along straight paths.",
    "When you walk, your steps will not be hampered; when you run, you will not stumble.",
    "Hold on to instruction, do not let it go; guard it well, for it is your life.",
    "Do not set foot on the path of the wicked or walk in the way of evil men.",
    "Avoid it, do not travel on it; turn from it and go on your way.",
    "For they cannot sleep till they do evil; they are robbed of slumber till they make someone fall.",
    "They eat the bread of wickedness and drink the wine of violence.",
    "The path of the righteous is like the first gleam of dawn, shining ever brighter till the full light of day.",
    "But the way of the wicked is like deep darkness; they do not know what makes them stumble.",
    "My son, pay attention to what I say; listen closely to my words.",
    "Do not let them out of your sight, keep them within your heart;",
    "for they are life to those who find them and health to a man's whole body.",
    "Above all else, guard your heart, for it is the wellspring of life.",
    "Put away perversity from your mouth; keep corrupt talk far from your lips.",
    "Let your eyes look straight ahead, fix your gaze directly before you.",
    "Make level paths for your feet and take only ways that are firm.",
    "Do not swerve to the right or the left; keep your foot from evil."
  ],
  "Proverbs-4": [
    "My son, pay attention to my wisdom, listen well to my words of insight,",
    "that you may maintain discretion and your lips may preserve knowledge.",
    "For the lips of an adulteress drip honey, and her speech is smoother than oil;",
    "but in the end she is bitter as gall, sharp as a double-edged sword.",
    "Her feet go down to death; her steps lead straight to the grave.",
    "She gives no thought to the way of life; her paths are crooked, but she knows it not.",
    "Now then, my sons, listen to me; do not turn aside from what I say.",
    "Keep to a path far from her, do not go near the door of her house,",
    "lest you give your best strength to others and your years to one who is cruel,",
    "lest strangers feast on your wealth and your toil enrich another man's house.",
    "At the end of your life you will groan, when your flesh and body are spent.",
    "You will say, \"How I hated discipline! How my heart spurned correction!",
    "I would not obey my teachers or listen to my instructors.",
    "I have come to the brink of utter ruin in the midst of the whole assembly.\"",
    "Drink water from your own cistern, running water from your own well.",
    "Should your springs overflow in the streets, your streams of water in the public squares?",
    "Let them be yours alone, never to be shared with strangers.",
    "May your fountain be blessed, and may you rejoice in the wife of your youth.",
    "A loving doe, a graceful deer--may her breasts satisfy you always, may you ever be captivated by her love.",
    "Why be captivated, my son, by an adulteress? Why embrace the bosom of another man's wife?",
    "For a man's ways are in full view of the LORD, and he examines all his paths.",
    "The evil deeds of a wicked man ensnare him; the cords of his sin hold him fast.",
    "He will die for lack of discipline, led astray by his own great folly."
  ],
  "Proverbs-5": [
    "My son, if you have put up security for your neighbor, if you have struck hands in pledge for another,",
    "if you have been trapped by what you said, ensnared by the words of your mouth,",
    "then do this, my son, to free yourself, since you have fallen into your neighbor's hands: Go and humble yourself; press your plea with your neighbor!",
    "Allow no sleep to your eyes, no slumber to your eyelids.",
    "Free yourself, like a gazelle from the hand of the hunter, like a bird from the snare of the fowler.",
    "Go to the ant, you sluggard; consider its ways and be wise!",
    "It has no commander, no overseer or ruler,",
    "yet it stores its provisions in summer and gathers its food at harvest.",
    "How long will you lie there, you sluggard? When will you get up from your sleep?",
    "A little sleep, a little slumber, a little folding of the hands to rest--",
    "and poverty will come on you like a bandit and scarcity like an armed man.",
    "A scoundrel and villain, who goes about with a corrupt mouth,",
    "who winks with his eye, signals with his feet and motions with his fingers,",
    "who plots evil with deceit in his heart--he always stirs up dissension.",
    "Therefore disaster will overtake him in an instant; he will suddenly be destroyed--without remedy.",
    "There are six things the LORD hates, seven that are detestable to him:",
    "haughty eyes, a lying tongue, hands that shed innocent blood,",
    "a heart that devises wicked schemes, feet that are quick to rush into evil,",
    "a false witness who pours out lies and a man who stirs up dissension among brothers.",
    "My son, keep your father's commands and do not forsake your mother's teaching.",
    "Bind them upon your heart forever; fasten them around your neck.",
    "When you walk, they will guide you; when you sleep, they will watch over you; when you awake, they will speak to you.",
    "For these commands are a lamp, this teaching is a light, and the corrections of discipline are the way to life,",
    "keeping you from the immoral woman, from the smooth tongue of the wayward wife.",
    "Do not lust in your heart after her beauty or let her captivate you with her eyes,",
    "for the prostitute reduces you to a loaf of bread, and the adulteress preys upon your very life.",
    "Can a man scoop fire into his lap without his clothes being burned?",
    "Can a man walk on hot coals without his feet being scorched?",
    "So is he who sleeps with another man's wife; no one who touches her will go unpunished.",
    "Men do not despise a thief if he steals to satisfy his hunger when he is starving.",
    "Yet if he is caught, he must pay sevenfold, though it costs him all the wealth of his house.",
    "But a man who commits adultery lacks judgment; whoever does so destroys himself.",
    "Blows and disgrace are his lot, and his shame will never be wiped away;",
    "for jealousy arouses a husband's fury, and he will show no mercy when he takes revenge.",
    "He will not accept any compensation; he will refuse the bribe, however great it is."
  ],
  "Proverbs-6": [
    "My son, keep my words and store up my commands within you.",
    "Keep my commands and you will live; guard my teachings as the apple of your eye.",
    "Bind them on your fingers; write them on the tablet of your heart.",
    "Say to wisdom, \"You are my sister,\" and call understanding your kinsman;",
    "they will keep you from the adulteress, from the wayward wife with her seductive words.",
    "At the window of my house I looked out through the lattice.",
    "I saw among the simple, I noticed among the young men, a youth who lacked judgment.",
    "He was going down the street near her corner, walking along in the direction of her house",
    "at twilight, as the day was fading, as the dark of night set in.",
    "Then out came a woman to meet him, dressed like a prostitute and with crafty intent.",
    "(She is loud and defiant, her feet never stay at home;",
    "now in the street, now in the squares, at every corner she lurks.)",
    "She took hold of him and kissed him and with a brazen face she said:",
    "\"I have fellowship offerings at home; today I fulfilled my vows.",
    "So I came out to meet you; I looked for you and have found you!",
    "I have covered my bed with colored linens from Egypt.",
    "I have perfumed my bed with myrrh, aloes and cinnamon.",
    "Come, let's drink deep of love till morning; let's enjoy ourselves with love!",
    "My husband is not at home; he has gone on a long journey.",
    "He took his purse filled with money and will not be home till full moon.\"",
    "With persuasive words she led him astray; she seduced him with her smooth talk.",
    "All at once he followed her like an ox going to the slaughter, like a deer stepping into a noose",
    "till an arrow pierces his liver, like a bird darting into a snare, little knowing it will cost him his life.",
    "Now then, my sons, listen to me; pay attention to what I say.",
    "Do not let your heart turn to her ways or stray into her paths.",
    "Many are the victims she has brought down; her slain are a mighty throng.",
    "Her house is a highway to the grave, leading down to the chambers of death."
  ],
  "Proverbs-7": [
    "Does not wisdom call out? Does not understanding raise her voice?",
    "On the heights along the way, where the paths meet, she takes her stand;",
    "beside the gates leading into the city, at the entrances, she cries aloud:",
    "\"To you, O men, I call out; I raise my voice to all mankind.",
    "You who are simple, gain prudence; you who are foolish, gain understanding.",
    "Listen, for I have worthy things to say; I open my lips to speak what is right.",
    "My mouth speaks what is true, for my lips detest wickedness.",
    "All the words of my mouth are just; none of them is crooked or perverse.",
    "To the discerning all of them are right; they are faultless to those who have knowledge.",
    "Choose my instruction instead of silver, knowledge rather than choice gold,",
    "for wisdom is more precious than rubies, and nothing you desire can compare with her.",
    "\"I, wisdom, dwell together with prudence; I possess knowledge and discretion.",
    "To fear the LORD is to hate evil; I hate pride and arrogance, evil behavior and perverse speech.",
    "Counsel and sound judgment are mine; I have understanding and power.",
    "By me kings reign and rulers make laws that are just;",
    "by me princes govern, and all nobles who rule on earth.",
    "I love those who love me, and those who seek me find me.",
    "With me are riches and honor, enduring wealth and prosperity.",
    "My fruit is better than fine gold; what I yield surpasses choice silver.",
    "I walk in the way of righteousness, along the paths of justice,",
    "bestowing wealth on those who love me and making their treasuries full.",
    "\"The LORD brought me forth as the first of his works, before his deeds of old;",
    "I was appointed from eternity, from the beginning, before the world began.",
    "When there were no oceans, I was given birth, when there were no springs abounding with water;",
    "before the mountains were settled in place, before the hills, I was given birth,",
    "before he made the earth or its fields or any of the dust of the world.",
    "I was there when he set the heavens in place, when he marked out the horizon on the face of the deep,",
    "when he established the clouds above and fixed securely the fountains of the deep,",
    "when he gave the sea its boundary so the waters would not overstep his command, and when he marked out the foundations of the earth.",
    "Then I was the craftsman at his side. I was filled with delight day after day, rejoicing always in his presence,",
    "rejoicing in his whole world and delighting in mankind.",
    "\"Now then, my sons, listen to me; blessed are those who keep my ways.",
    "Listen to my instruction and be wise; do not ignore it.",
    "Blessed is the man who listens to me, watching daily at my doors, waiting at my doorway.",
    "For whoever finds me finds life and receives favor from the LORD.",
    "But whoever fails to find me harms himself; all who hate me love death.\""
  ],
  "Proverbs-8": [
    "Wisdom has built her house; she has hewn out its seven pillars.",
    "She has prepared her meat and mixed her wine; she has also set her table.",
    "She has sent out her maids, and she calls from the highest point of the city.",
    "\"Let all who are simple come in here!\" she says to those who lack judgment.",
    "\"Come, eat my food and drink the wine I have mixed.",
    "Leave your simple ways and you will live; walk in the way of understanding.",
    "\"Whoever corrects a mocker invites insult; whoever rebukes a wicked man incurs abuse.",
    "Do not rebuke a mocker or he will hate you; rebuke a wise man and he will love you.",
    "Instruct a wise man and he will be wiser still; teach a righteous man and he will add to his learning.",
    "\"The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.",
    "For through me your days will be many, and years will be added to your life.",
    "If you are wise, your wisdom will reward you; if you are a mocker, you alone will suffer.\"",
    "The woman Folly is loud; she is undisciplined and without knowledge.",
    "She sits at the door of her house, on a seat at the highest point of the city,",
    "calling out to those who pass by, who go straight on their way.",
    "\"Let all who are simple come in here!\" she says to those who lack judgment.",
    "\"Stolen water is sweet; food eaten in secret is delicious!\"",
    "But little do they know that the dead are there, that her guests are in the depths of the grave."
  ],
  "Proverbs-9": [
    "The proverbs of Solomon: A wise son brings joy to his father, but a foolish son grief to his mother.",
    "Ill-gotten treasures are of no value, but righteousness delivers from death.",
    "The LORD does not let the righteous go hungry but he thwarts the craving of the wicked.",
    "Lazy hands make a man poor, but diligent hands bring wealth.",
    "He who gathers crops in summer is a wise son, but he who sleeps during harvest is a disgraceful son.",
    "Blessings crown the head of the righteous, but violence overwhelms the mouth of the wicked.",
    "The memory of the righteous will be a blessing, but the name of the wicked will rot.",
    "The wise in heart accept commands, but a chattering fool comes to ruin.",
    "The man of integrity walks securely, but he who takes crooked paths will be found out.",
    "He who winks maliciously causes grief, and a chattering fool comes to ruin.",
    "The mouth of the righteous is a fountain of life, but violence overwhelms the mouth of the wicked.",
    "Hatred stirs up dissension, but love covers over all wrongs.",
    "Wisdom is found on the lips of the discerning, but a rod is for the back of him who lacks judgment.",
    "Wise men store up knowledge, but the mouth of a fool invites ruin.",
    "The wealth of the rich is their fortified city, but poverty is the ruin of the poor.",
    "The wages of the righteous bring them life, but the income of the wicked brings them punishment.",
    "He who heeds discipline shows the way to life, but whoever ignores correction leads others astray.",
    "He who conceals his hatred has lying lips, and whoever spreads slander is a fool.",
    "When words are many, sin is not absent, but he who holds his tongue is wise.",
    "The tongue of the righteous is choice silver, but the heart of the wicked is of little value.",
    "The lips of the righteous nourish many, but fools die for lack of judgment.",
    "The blessing of the LORD brings wealth, and he adds no trouble to it.",
    "A fool finds pleasure in evil conduct, but a man of understanding delights in wisdom.",
    "What the wicked dreads will overtake him; what the righteous desire will be granted.",
    "When the storm has swept by, the wicked are gone, but the righteous stand firm forever.",
    "As vinegar to the teeth and smoke to the eyes, so is a sluggard to those who send him.",
    "The fear of the LORD adds length to life, but the years of the wicked are cut short.",
    "The prospect of the righteous is joy, but the hopes of the wicked come to nothing.",
    "The way of the LORD is a refuge for the righteous, but it is the ruin of those who do evil.",
    "The righteous will never be uprooted, but the wicked will not remain in the land.",
    "The mouth of the righteous brings forth wisdom, but a perverse tongue will be cut out.",
    "The lips of the righteous know what is fitting, but the mouth of the wicked only what is perverse."
  ],
  "Proverbs-10": [
    "The LORD abhors dishonest scales, but accurate weights are his delight.",
    "When pride comes, then comes disgrace, but with humility comes wisdom.",
    "The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity.",
    "Wealth is worthless in the day of wrath, but righteousness delivers from death.",
    "The righteousness of the blameless makes a straight way for them, but the wicked are brought down by their own wickedness.",
    "The righteousness of the upright delivers them, but the unfaithful are trapped by evil desires.",
    "When a wicked man dies, his hope perishes; all he expected from his power comes to nothing.",
    "The righteous man is rescued from trouble, and it comes on the wicked instead.",
    "With his mouth the godless destroys his neighbor, but through knowledge the righteous escape.",
    "When the righteous prosper, the city rejoices; when the wicked perish, there are shouts of joy.",
    "Through the blessing of the upright a city is exalted, but by the mouth of the wicked it is destroyed.",
    "A man who lacks judgment derides his neighbor, but a man of understanding holds his tongue.",
    "A gossip betrays a confidence, but a trustworthy man keeps a secret.",
    "For lack of guidance a nation falls, but many advisers make victory sure.",
    "He who puts up security for another will surely suffer, but whoever refuses to strike hands in pledge is safe.",
    "A kindhearted woman gains respect, but ruthless men gain only wealth.",
    "A kind man benefits himself, but a cruel man brings trouble on himself.",
    "The wicked man earns deceptive wages, but he who sows righteousness reaps a sure reward.",
    "The truly righteous man attains life, but he who pursues evil goes to his death.",
    "The LORD detests men of perverse heart but he delights in those whose ways are blameless.",
    "Be sure of this: The wicked will not go unpunished, but those who are righteous will go free.",
    "Like a gold ring in a pig's snout is a beautiful woman who shows no discretion.",
    "The desire of the righteous ends only in good, but the hope of the wicked only in wrath.",
    "One man gives freely, yet gains even more; another withholds unduly, but comes to poverty.",
    "A generous man will prosper; he who refreshes others will himself be refreshed.",
    "People curse the man who hoards grain, but blessing crowns him who is willing to sell.",
    "He who seeks good finds goodwill, but evil comes to him who searches for it.",
    "Whoever trusts in his riches will fall, but the righteous will thrive like a green leaf.",
    "He who brings trouble on his family will inherit only wind, and the fool will be servant to the wise.",
    "The fruit of the righteous is a tree of life, and he who wins souls is wise.",
    "If the righteous receive their due on earth, how much more the ungodly and the sinner!"
  ],
  "Proverbs-11": [
    "Whoever loves discipline loves knowledge, but he who hates correction is stupid.",
    "A good man obtains favor from the LORD, but the LORD condemns a crafty man.",
    "A man cannot be established through wickedness, but the righteous cannot be uprooted.",
    "A wife of noble character is her husband's crown, but a disgraceful wife is like decay in his bones.",
    "The plans of the righteous are just, but the advice of the wicked is deceitful.",
    "The words of the wicked lie in wait for blood, but the speech of the upright rescues them.",
    "Wicked men are overthrown and are no more, but the house of the righteous stands firm.",
    "A man is praised according to his wisdom, but men with warped minds are despised.",
    "Better to be a nobody and yet have a servant than pretend to be somebody and have no food.",
    "A righteous man cares for the needs of his animal, but the kindest acts of the wicked are cruel.",
    "He who works his land will have abundant food, but he who chases fantasies lacks judgment.",
    "The wicked desire the plunder of evil men, but the root of the righteous flourishes.",
    "An evil man is trapped by his sinful talk, but a righteous man escapes trouble.",
    "From the fruit of his lips a man is filled with good things as surely as the work of his hands rewards him.",
    "The way of a fool seems right to him, but a wise man listens to advice.",
    "A fool shows his annoyance at once, but a prudent man overlooks an insult.",
    "A truthful witness gives honest testimony, but a false witness tells lies.",
    "Reckless words pierce like a sword, but the tongue of the wise brings healing.",
    "Truthful lips endure forever, but a lying tongue lasts only a moment.",
    "There is deceit in the hearts of those who plot evil, but joy for those who promote peace.",
    "No harm befalls the righteous, but the wicked have their fill of trouble.",
    "The LORD detests lying lips, but he delights in men who are truthful.",
    "A prudent man keeps his knowledge to himself, but the heart of fools blurts out folly.",
    "Diligent hands will rule, but laziness ends in slave labor.",
    "An anxious heart weighs a man down, but a kind word cheers him up.",
    "A righteous man is cautious in friendship, but the way of the wicked leads them astray.",
    "The lazy man does not roast his game, but the diligent man prizes his possessions.",
    "In the way of righteousness there is life; along that path is immortality."
  ],
  "Proverbs-12": [
    "A wise son heeds his father's instruction, but a mocker does not listen to rebuke.",
    "From the fruit of his lips a man enjoys good things, but the unfaithful have a craving for violence.",
    "He who guards his lips guards his life, but he who speaks rashly will come to ruin.",
    "The sluggard craves and gets nothing, but the desires of the diligent are fully satisfied.",
    "The righteous hate what is false, but the wicked bring shame and disgrace.",
    "Righteousness guards the man of integrity, but wickedness overthrows the sinner.",
    "One man pretends to be rich, yet has nothing; another pretends to be poor, yet has great wealth.",
    "A man's riches may ransom his life, but a poor man hears no threat.",
    "The light of the righteous shines brightly, but the lamp of the wicked is snuffed out.",
    "Pride only breeds quarrels, but wisdom is found in those who take advice.",
    "Dishonest money dwindles away, but he who gathers money little by little makes it grow.",
    "Hope deferred makes the heart sick, but a longing fulfilled is a tree of life.",
    "He who scorns instruction will pay for it, but he who respects a command is rewarded.",
    "The teaching of the wise is a fountain of life, turning a man from the snares of death.",
    "Good understanding wins favor, but the way of the unfaithful is hard.",
    "Every prudent man acts out of knowledge, but a fool exposes his folly.",
    "A wicked messenger falls into trouble, but a trustworthy envoy brings healing.",
    "He who ignores discipline comes to poverty and shame, but whoever heeds correction is honored.",
    "A longing fulfilled is sweet to the soul, but fools detest turning from evil.",
    "He who walks with the wise grows wise, but a companion of fools suffers harm.",
    "Misfortune pursues the sinner, but prosperity is the reward of the righteous.",
    "A good man leaves an inheritance for his children's children, but a sinner's wealth is stored up for the righteous.",
    "A poor man's field may produce abundant food, but injustice sweeps it away.",
    "He who spares the rod hates his son, but he who loves him is careful to discipline him.",
    "The righteous eat to their hearts' content, but the stomach of the wicked goes hungry."
  ],
  "Proverbs-13": [
    "The wise woman builds her house, but with her own hands the foolish one tears hers down.",
    "He whose walk is upright fears the LORD, but he whose ways are devious despises him.",
    "A fool's talk brings a rod to his back, but the lips of the wise protect them.",
    "Where there are no oxen, the manger is empty, but from the strength of an ox comes an abundant harvest.",
    "A truthful witness does not deceive, but a false witness pours out lies.",
    "The mocker seeks wisdom and finds none, but knowledge comes easily to the discerning.",
    "Stay away from a foolish man, for you will not find knowledge on his lips.",
    "The wisdom of the prudent is to give thought to their ways, but the folly of fools is deception.",
    "Fools mock at making amends for sin, but goodwill is found among the upright.",
    "Each heart knows its own bitterness, and no one else can share its joy.",
    "The house of the wicked will be destroyed, but the tent of the upright will flourish.",
    "There is a way that seems right to a man, but in the end it leads to death.",
    "Even in laughter the heart may ache, and joy may end in grief.",
    "The faithless will be fully repaid for their ways, and the good man rewarded for his.",
    "A simple man believes anything, but a prudent man gives thought to his steps.",
    "A wise man fears the LORD and shuns evil, but a fool is hotheaded and reckless.",
    "A quick-tempered man does foolish things, and a crafty man is hated.",
    "The simple inherit folly, but the prudent are crowned with knowledge.",
    "Evil men will bow down in the presence of the good, and the wicked at the gates of the righteous.",
    "The poor are shunned even by their neighbors, but the rich have many friends.",
    "He who despises his neighbor sins, but blessed is he who is kind to the needy.",
    "Do not those who plot evil go astray? But those who plan what is good find love and faithfulness.",
    "All hard work brings a profit, but mere talk leads only to poverty.",
    "The wealth of the wise is their crown, but the folly of fools yields folly.",
    "A truthful witness saves lives, but a false witness is deceitful.",
    "He who fears the LORD has a secure fortress, and for his children it will be a refuge.",
    "The fear of the LORD is a fountain of life, turning a man from the snares of death.",
    "A large population is a king's glory, but without subjects a prince is ruined.",
    "A patient man has great understanding, but a quick-tempered man displays folly.",
    "A heart at peace gives life to the body, but envy rots the bones.",
    "He who oppresses the poor shows contempt for their Maker, but whoever is kind to the needy honors God.",
    "When calamity comes, the wicked are brought down, but even in death the righteous have a refuge.",
    "Wisdom reposes in the heart of the discerning and even among fools she lets herself be known.",
    "Righteousness exalts a nation, but sin is a disgrace to any people.",
    "A king delights in a wise servant, but a shameful servant incurs his wrath."
  ],
  "Proverbs-14": [
    "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    "The tongue of the wise commends knowledge, but the mouth of the fool gushes folly.",
    "The eyes of the LORD are everywhere, keeping watch on the wicked and the good.",
    "The tongue that brings healing is a tree of life, but a deceitful tongue crushes the spirit.",
    "A fool spurns his father's discipline, but whoever heeds correction shows prudence.",
    "The house of the righteous contains great treasure, but the income of the wicked brings them trouble.",
    "The lips of the wise spread knowledge; not so the hearts of fools.",
    "The LORD detests the sacrifice of the wicked, but the prayer of the upright pleases him.",
    "The LORD detests the way of the wicked but he loves those who pursue righteousness.",
    "Stern discipline awaits him who leaves the path; he who hates correction will die.",
    "Death and Destruction lie open before the LORD--how much more the hearts of men!",
    "A mocker resents correction; he will not consult the wise.",
    "A happy heart makes the face cheerful, but heartache crushes the spirit.",
    "The discerning heart seeks knowledge, but the mouth of a fool feeds on folly.",
    "All the days of the oppressed are wretched, but the cheerful heart has a continual feast.",
    "Better a little with the fear of the LORD than great wealth with turmoil.",
    "Better a meal of vegetables where there is love than a fattened calf with hatred.",
    "A hot-tempered man stirs up dissension, but a patient man calms a quarrel.",
    "The way of the sluggard is blocked with thorns, but the path of the upright is a highway.",
    "A wise son brings joy to his father, but a foolish man despises his mother.",
    "Folly delights a man who lacks judgment, but a man of understanding keeps a straight course.",
    "Plans fail for lack of counsel, but with many advisers they succeed.",
    "A man finds joy in giving an apt reply--and how good is a timely word!",
    "The path of life leads upward for the wise to keep him from going down to the grave.",
    "The LORD tears down the proud man's house but he keeps the widow's boundaries intact.",
    "The LORD detests the thoughts of the wicked, but those of the pure are pleasing to him.",
    "A greedy man brings trouble to his family, but he who hates bribes will live.",
    "The heart of the righteous weighs its answers, but the mouth of the wicked gushes evil.",
    "The LORD is far from the wicked but he hears the prayer of the righteous.",
    "A cheerful look brings joy to the heart, and good news gives health to the bones.",
    "He who listens to a life-giving rebuke will be at home among the wise.",
    "He who ignores discipline despises himself, but whoever heeds correction gains understanding.",
    "The fear of the LORD teaches a man wisdom, and humility comes before honor."
  ],
  "Proverbs-15": [
    "To man belong the plans of the heart, but from the LORD comes the reply of the tongue.",
    "All a man's ways seem innocent to him, but motives are weighed by the LORD.",
    "Commit to the LORD whatever you do, and your plans will succeed.",
    "The LORD works out everything for his own ends--even the wicked for a day of disaster.",
    "The LORD detests all the proud of heart. Be sure of this: They will not go unpunished.",
    "Through love and faithfulness sin is atoned for; through the fear of the LORD a man avoids evil.",
    "When a man's ways are pleasing to the LORD, he makes even his enemies live at peace with him.",
    "Better a little with righteousness than much gain with injustice.",
    "In his heart a man plans his course, but the LORD determines his steps.",
    "The lips of a king speak as an oracle, and his mouth should not betray justice.",
    "Honest scales and balances are from the LORD; all the weights in the bag are of his making.",
    "Kings detest wrongdoing, for a throne is established through righteousness.",
    "Kings take pleasure in honest lips; they value a man who speaks the truth.",
    "A king's wrath is a messenger of death, but a wise man will appease it.",
    "When a king's face brightens, it means life; his favor is like a rain cloud in spring.",
    "How much better to get wisdom than gold, to choose understanding rather than silver!",
    "The highway of the upright avoids evil; he who guards his way guards his life.",
    "Pride goes before destruction, a haughty spirit before a fall.",
    "Better to be lowly in spirit and among the oppressed than to share plunder with the proud.",
    "Whoever gives heed to instruction prospers, and blessed is he who trusts in the LORD.",
    "The wise in heart are called discerning, and pleasant words promote instruction.",
    "Understanding is a fountain of life to those who have it, but folly brings punishment to fools.",
    "A wise man's heart guides his mouth, and his lips promote instruction.",
    "Pleasant words are a honeycomb, sweet to the soul and healing to the bones.",
    "There is a way that seems right to a man, but in the end it leads to death.",
    "The laborer's appetite works for him; his hunger drives him on.",
    "A scoundrel plots evil, and his speech is like a scorching fire.",
    "A perverse man stirs up dissension, and a gossip separates close friends.",
    "A violent man entices his neighbor and leads him down a path that is not good.",
    "He who winks with his eye is plotting perversity; he who purses his lips is bent on evil.",
    "Gray hair is a crown of splendor; it is attained by a righteous life.",
    "Better a patient man than a warrior, a man who controls his temper than one who takes a city.",
    "The lot is cast into the lap, but its every decision is from the LORD."
  ],
  "Proverbs-16": [
    "Better a dry crust with peace and quiet than a house full of feasting, with strife.",
    "A wise servant will rule over a disgraceful son, and will share the inheritance as one of the brothers.",
    "The crucible for silver and the furnace for gold, but the LORD tests the heart.",
    "A wicked man listens to evil lips; a liar pays attention to a malicious tongue.",
    "He who mocks the poor shows contempt for their Maker; whoever gloats over disaster will not go unpunished.",
    "Children's children are a crown to the aged, and parents are the pride of their children.",
    "Arrogant lips are unsuited to a fool--how much worse lying lips to a ruler!",
    "A bribe is a charm to the one who gives it; wherever he turns, he succeeds.",
    "He who covers over an offense promotes love, but whoever repeats the matter separates close friends.",
    "A rebuke impresses a man of discernment more than a hundred lashes a fool.",
    "An evil man is bent only on rebellion; a merciless official will be sent against him.",
    "Better to meet a bear robbed of her cubs than a fool in his folly.",
    "If a man pays back evil for good, evil will never leave his house.",
    "Starting a quarrel is like breaching a dam; so drop the matter before a dispute breaks out.",
    "Acquitting the guilty and condemning the innocent--the LORD detests them both.",
    "Of what use is money in the hand of a fool, since he has no desire to get wisdom?",
    "A friend loves at all times, and a brother is born for adversity.",
    "A man lacking in judgment strikes hands in pledge and puts up security for his neighbor.",
    "He who loves a quarrel loves sin; he who builds a high gate invites destruction.",
    "A man of perverse heart does not prosper; he whose tongue is deceitful falls into trouble.",
    "To have a fool for a son brings grief; there is no joy for the father of a fool.",
    "A cheerful heart is good medicine, but a crushed spirit dries up the bones.",
    "A wicked man accepts a bribe in secret to pervert the course of justice.",
    "A discerning man keeps wisdom in view, but a fool's eyes wander to the ends of the earth.",
    "A foolish son brings grief to his father and bitterness to the one who bore him.",
    "It is not good to punish an innocent man, or to flog officials for their integrity.",
    "A man of knowledge uses words with restraint, and a man of understanding is even-tempered.",
    "Even a fool is thought wise if he keeps silent, and discerning if he holds his tongue."
  ],
  "Proverbs-17": [
    "An unfriendly man pursues selfish ends; he defies all sound judgment.",
    "A fool finds no pleasure in understanding but delights in airing his own opinions.",
    "When wickedness comes, so does contempt, and with shame comes disgrace.",
    "The words of a man's mouth are deep waters, but the fountain of wisdom is a bubbling brook.",
    "It is not good to be partial to the wicked or to deprive the innocent of justice.",
    "A fool's lips bring him strife, and his mouth invites a beating.",
    "A fool's mouth is his undoing, and his lips are a snare to his soul.",
    "The words of a gossip are like choice morsels; they go down to a man's inmost parts.",
    "One who is slack in his work is brother to one who destroys.",
    "The name of the LORD is a strong tower; the righteous run to it and are safe.",
    "The wealth of the rich is their fortified city; they imagine it an unscalable wall.",
    "Before his downfall a man's heart is proud, but humility comes before honor.",
    "He who answers before listening--that is his folly and his shame.",
    "A man's spirit sustains him in sickness, but a crushed spirit who can bear?",
    "The heart of the discerning acquires knowledge; the ears of the wise seek it out.",
    "A gift opens the way for the giver and ushers him into the presence of the great.",
    "The first to present his case seems right, till another comes forward and questions him.",
    "Casting the lot settles disputes and keeps strong opponents apart.",
    "An offended brother is more unyielding than a fortified city, and disputes are like the barred gates of a citadel.",
    "From the fruit of his mouth a man's stomach is filled; with the harvest from his lips he is satisfied.",
    "The tongue has the power of life and death, and those who love it will eat its fruit.",
    "He who finds a wife finds what is good and receives favor from the LORD.",
    "A poor man pleads for mercy, but a rich man answers harshly.",
    "A man of many companions may come to ruin, but there is a friend who sticks closer than a brother."
  ],
  "Proverbs-18": [
    "Better a poor man whose walk is blameless than a fool whose lips are perverse.",
    "It is not good to have zeal without knowledge, nor to be hasty and miss the way.",
    "A man's own folly ruins his life, yet his heart rages against the LORD.",
    "Wealth brings many friends, but a poor man's friend deserts him.",
    "A false witness will not go unpunished, and he who pours out lies will not go free.",
    "Many curry favor with a ruler, and everyone is the friend of a man who gives gifts.",
    "A poor man is shunned by all his relatives--how much more do his friends avoid him! Though he pursues them with pleading, they are nowhere to be found.",
    "He who gets wisdom loves his own soul; he who cherishes understanding prospers.",
    "A false witness will not go unpunished, and he who pours out lies will perish.",
    "It is not fitting for a fool to live in luxury--how much worse for a slave to rule over princes!",
    "A man's wisdom gives him patience; it is to his glory to overlook an offense.",
    "A king's rage is like the roar of a lion, but his favor is like dew on the grass.",
    "A foolish son is his father's ruin, and a quarrelsome wife is like a constant dripping.",
    "Houses and wealth are inherited from parents, but a prudent wife is from the LORD.",
    "Laziness brings on deep sleep, and the shiftless man goes hungry.",
    "He who obeys instructions guards his life, but he who is contemptuous of his ways will die.",
    "He who is kind to the poor lends to the LORD, and he will reward him for what he has done.",
    "Discipline your son, for in that there is hope; do not be a willing party to his death.",
    "A hot-tempered man must pay the penalty; if you rescue him, you will have to do it again.",
    "Listen to advice and accept instruction, and in the end you will be wise.",
    "Many are the plans in a man's heart, but it is the LORD'S purpose that prevails.",
    "What a man desires is unfailing love; better to be poor than a liar.",
    "The fear of the LORD leads to life: Then one rests content, untouched by trouble.",
    "The sluggard buries his hand in the dish; he will not even bring it back to his mouth!",
    "Flog a mocker, and the simple will learn prudence; rebuke a discerning man, and he will gain knowledge.",
    "He who robs his father and drives out his mother is a son who brings shame and disgrace.",
    "Stop listening to instruction, my son, and you will stray from the words of knowledge.",
    "A corrupt witness mocks at justice, and the mouth of the wicked gulps down evil.",
    "Penalties are prepared for mockers, and beatings for the backs of fools."
  ],
  "Proverbs-19": [
    "Wine is a mocker and beer a brawler; whoever is led astray by them is not wise.",
    "A king's wrath is like the roar of a lion; he who angers him forfeits his life.",
    "It is to a man's honor to avoid strife, but every fool is quick to quarrel.",
    "A sluggard does not plow in season; so at harvest time he looks but finds nothing.",
    "The purposes of a man's heart are deep waters, but a man of understanding draws them out.",
    "Many a man claims to have unfailing love, but a faithful man who can find?",
    "The righteous man leads a blameless life; blessed are his children after him.",
    "When a king sits on his throne to judge, he winnows out all evil with his eyes.",
    "Who can say, \"I have kept my heart pure; I am clean and without sin\"?",
    "Differing weights and differing measures--the LORD detests them both.",
    "Even a child is known by his actions, by whether his conduct is pure and right.",
    "Ears that hear and eyes that see--the LORD has made them both.",
    "Do not love sleep or you will grow poor; stay awake and you will have food to spare.",
    "\"It's no good, it's no good!\" says the buyer; then off he goes and boasts about his purchase.",
    "Gold there is, and rubies in abundance, but lips that speak knowledge are a rare jewel.",
    "Take the garment of one who puts up security for a stranger; hold it in pledge if he does it for a wayward woman.",
    "Food gained by fraud tastes sweet to a man, but he ends up with a mouth full of gravel.",
    "Make plans by seeking advice; if you wage war, obtain guidance.",
    "A gossip betrays a confidence; so avoid a man who talks too much.",
    "If a man curses his father or mother, his lamp will be snuffed out in pitch darkness.",
    "An inheritance quickly gained at the beginning will not be blessed at the end.",
    "Do not say, \"I'll pay you back for this wrong!\" Wait for the LORD, and he will deliver you.",
    "The LORD detests differing weights, and dishonest scales do not please him.",
    "A man's steps are directed by the LORD. How then can anyone understand his own way?",
    "It is a trap for a man to dedicate something rashly and only later to consider his vows.",
    "A wise king winnows out the wicked; he drives the threshing wheel over them.",
    "The lamp of the LORD searches the spirit of a man; it searches out his inmost being.",
    "Love and faithfulness keep a king safe; through love his throne is made secure.",
    "The glory of young men is their strength, gray hair the splendor of the old.",
    "Blows and wounds cleanse away evil, and beatings purge the inmost being."
  ],
  "Proverbs-20": [
    "The king's heart is in the hand of the LORD; he directs it like a watercourse wherever he pleases.",
    "All a man's ways seem right to him, but the LORD weighs the heart.",
    "To do what is right and just is more acceptable to the LORD than sacrifice.",
    "Haughty eyes and a proud heart, the lamp of the wicked, are sin!",
    "The plans of the diligent lead to profit as surely as haste leads to poverty.",
    "A fortune made by a lying tongue is a fleeting vapor and a deadly snare.",
    "The violence of the wicked will drag them away, for they refuse to do what is right.",
    "The way of the guilty is devious, but the conduct of the innocent is upright.",
    "Better to live on a corner of the roof than share a house with a quarrelsome wife.",
    "The wicked man craves evil; his neighbor gets no mercy from him.",
    "When a mocker is punished, the simple gain wisdom; when a wise man is instructed, he gets knowledge.",
    "The Righteous One takes note of the house of the wicked and brings the wicked to ruin.",
    "If a man shuts his ears to the cry of the poor, he too will cry out and not be answered.",
    "A gift given in secret soothes anger, and a bribe concealed in the cloak pacifies great wrath.",
    "When justice is done, it brings joy to the righteous but terror to evildoers.",
    "A man who strays from the path of understanding comes to rest in the company of the dead.",
    "He who loves pleasure will become poor; whoever loves wine and oil will never be rich.",
    "The wicked become a ransom for the righteous, and the unfaithful for the upright.",
    "Better to live in a desert than with a quarrelsome and ill-tempered wife.",
    "In the house of the wise are stores of choice food and oil, but a foolish man devours all he has.",
    "He who pursues righteousness and love finds life, prosperity and honor.",
    "A wise man attacks the city of the mighty and pulls down the stronghold in which they trust.",
    "He who guards his mouth and his tongue keeps himself from calamity.",
    "The proud and arrogant man--\"Mocker\" is his name; he behaves with overweening pride.",
    "The sluggard's craving will be the death of him, because his hands refuse to work.",
    "All day long he craves for more, but the righteous give without sparing.",
    "The sacrifice of the wicked is detestable--how much more so when brought with evil intent!",
    "A false witness will perish, and whoever listens to him will be destroyed forever.",
    "A wicked man puts up a bold front, but an upright man gives thought to his ways.",
    "There is no wisdom, no insight, no plan that can succeed against the LORD.",
    "The horse is made ready for the day of battle, but victory rests with the LORD."
  ],
  "Proverbs-21": [
    "A good name is more desirable than great riches; to be esteemed is better than silver or gold.",
    "Rich and poor have this in common: The LORD is the Maker of them all.",
    "A prudent man sees danger and takes refuge, but the simple keep going and suffer for it.",
    "Humility and the fear of the LORD bring wealth and honor and life.",
    "In the paths of the wicked lie thorns and snares, but he who guards his soul stays far from them.",
    "Train a child in the way he should go, and when he is old he will not turn from it.",
    "The rich rule over the poor, and the borrower is servant to the lender.",
    "He who sows wickedness reaps trouble, and the rod of his fury will be destroyed.",
    "A generous man will himself be blessed, for he shares his food with the poor.",
    "Drive out the mocker, and out goes strife; quarrels and insults are ended.",
    "He who loves a pure heart and whose speech is gracious will have the king for his friend.",
    "The eyes of the LORD keep watch over knowledge, but he frustrates the words of the unfaithful.",
    "The sluggard says, \"There is a lion outside!\" or, \"I will be murdered in the streets!\"",
    "The mouth of an adulteress is a deep pit; he who is under the LORD'S wrath will fall into it.",
    "Folly is bound up in the heart of a child, but the rod of discipline will drive it far from him.",
    "He who oppresses the poor to increase his wealth and he who gives gifts to the rich--both come to poverty.",
    "Pay attention and listen to the sayings of the wise; apply your heart to what I teach,",
    "for it is pleasing when you keep them in your heart and have all of them ready on your lips.",
    "So that your trust may be in the LORD, I teach you today, even you.",
    "Have I not written thirty sayings for you, sayings of counsel and knowledge,",
    "teaching you true and reliable words, so that you can give sound answers to him who sent you?",
    "Do not exploit the poor because they are poor and do not crush the needy in court,",
    "for the LORD will take up their case and will plunder those who plunder them.",
    "Do not make friends with a hot-tempered man, do not associate with one easily angered,",
    "or you may learn his ways and get yourself ensnared.",
    "Do not be a man who strikes hands in pledge or puts up security for debts;",
    "if you lack the means to pay, your very bed will be snatched from under you.",
    "Do not move an ancient boundary stone set up by your forefathers.",
    "Do you see a man skilled in his work? He will serve before kings; he will not serve before obscure men."
  ],
  "Proverbs-22": [
    "When you sit to dine with a ruler, note well what is before you,",
    "and put a knife to your throat if you are given to gluttony.",
    "Do not crave his delicacies, for that food is deceptive.",
    "Do not wear yourself out to get rich; have the wisdom to show restraint.",
    "Cast but a glance at riches, and they are gone, for they will surely sprout wings and fly off to the sky like an eagle.",
    "Do not eat the food of a stingy man, do not crave his delicacies;",
    "for he is the kind of man who is always thinking about the cost. \"Eat and drink,\" he says to you, but his heart is not with you.",
    "You will vomit up the little you have eaten and will have wasted your compliments.",
    "Do not speak to a fool, for he will scorn the wisdom of your words.",
    "Do not move an ancient boundary stone or encroach on the fields of the fatherless,",
    "for their Defender is strong; he will take up their case against you.",
    "Apply your heart to instruction and your ears to words of knowledge.",
    "Do not withhold discipline from a child; if you punish him with the rod, he will not die.",
    "Punish him with the rod and save his soul from death.",
    "My son, if your heart is wise, then my heart will be glad;",
    "my inmost being will rejoice when your lips speak what is right.",
    "Do not let your heart envy sinners, but always be zealous for the fear of the LORD.",
    "There is surely a future hope for you, and your hope will not be cut off.",
    "Listen, my son, and be wise, and keep your heart on the right path.",
    "Do not join those who drink too much wine or gorge themselves on meat,",
    "for drunkards and gluttons become poor, and drowsiness clothes them in rags.",
    "Listen to your father, who gave you life, and do not despise your mother when she is old.",
    "Buy the truth and do not sell it; get wisdom, discipline and understanding.",
    "The father of a righteous man has great joy; he who has a wise son delights in him.",
    "May your father and mother be glad; may she who gave you birth rejoice!",
    "My son, give me your heart and let your eyes keep to my ways,",
    "for a prostitute is a deep pit and a wayward wife is a narrow well.",
    "Like a bandit she lies in wait, and multiplies the unfaithful among men.",
    "Who has woe? Who has sorrow? Who has strife? Who has complaints? Who has needless bruises? Who has bloodshot eyes?",
    "Those who linger over wine, who go to sample bowls of mixed wine.",
    "Do not gaze at wine when it is red, when it sparkles in the cup, when it goes down smoothly!",
    "In the end it bites like a snake and poisons like a viper.",
    "Your eyes will see strange sights and your mind imagine confusing things.",
    "You will be like one sleeping on the high seas, lying on top of the rigging.",
    "\"They hit me,\" you will say, \"but I'm not hurt! They beat me, but I don't feel it! When will I wake up so I can find another drink?\""
  ],
  "Proverbs-23": [
    "Do not envy wicked men, do not desire their company;",
    "for their hearts plot violence, and their lips talk about making trouble.",
    "By wisdom a house is built, and through understanding it is established;",
    "through knowledge its rooms are filled with rare and beautiful treasures.",
    "A wise man has great power, and a man of knowledge increases strength;",
    "for waging war you need guidance, and for victory many advisers.",
    "Wisdom is too high for a fool; in the assembly at the gate he has nothing to say.",
    "He who plots evil will be known as a schemer.",
    "The schemes of folly are sin, and men detest a mocker.",
    "If you falter in times of trouble, how small is your strength!",
    "Rescue those being led away to death; hold back those staggering toward slaughter.",
    "If you say, \"But we knew nothing about this,\" does not he who weighs the heart perceive it? Does not he who guards your life know it? Will he not repay each person according to what he has done?",
    "Eat honey, my son, for it is good; honey from the comb is sweet to your taste.",
    "Know also that wisdom is sweet to your soul; if you find it, there is a future hope for you, and your hope will not be cut off.",
    "Do not lie in wait like an outlaw against a righteous man's house, do not raid his dwelling place;",
    "for though a righteous man falls seven times, he rises again, but the wicked are brought down by calamity.",
    "Do not gloat when your enemy falls; when he stumbles, do not let your heart rejoice,",
    "or the LORD will see and disapprove and turn his wrath away from him.",
    "Do not fret because of evil men or be envious of the wicked,",
    "for the evil man has no future hope, and the lamp of the wicked will be snuffed out.",
    "Fear the LORD and the king, my son, and do not join with the rebellious,",
    "for those two will send sudden destruction upon them, and who knows what calamities they can bring?",
    "These also are sayings of the wise: To show partiality in judging is not good:",
    "Whoever says to the guilty, \"You are innocent\"--peoples will curse him and nations denounce him.",
    "But it will go well with those who convict the guilty, and rich blessing will come upon them.",
    "An honest answer is like a kiss on the lips.",
    "Finish your outdoor work and get your fields ready; after that, build your house.",
    "Do not testify against your neighbor without cause, or use your lips to deceive.",
    "Do not say, \"I'll do to him as he has done to me; I'll pay that man back for what he did.\"",
    "I went past the field of the sluggard, past the vineyard of the man who lacks judgment;",
    "thorns had come up everywhere, the ground was covered with weeds, and the stone wall was in ruins.",
    "I applied my heart to what I observed and learned a lesson from what I saw:",
    "A little sleep, a little slumber, a little folding of the hands to rest--",
    "and poverty will come on you like a bandit and scarcity like an armed man."
  ],
  "Proverbs-24": [
    "These are more proverbs of Solomon, copied by the men of Hezekiah king of Judah:",
    "It is the glory of God to conceal a matter; to search out a matter is the glory of kings.",
    "As the heavens are high and the earth is deep, so the hearts of kings are unsearchable.",
    "Remove the dross from the silver, and out comes material for the silversmith;",
    "remove the wicked from the king's presence, and his throne will be established through righteousness.",
    "Do not exalt yourself in the king's presence, and do not claim a place among great men;",
    "it is better for him to say to you, \"Come up here,\" than for him to humiliate you before a nobleman. What you have seen with your eyes",
    "do not bring hastily to court, for what will you do in the end if your neighbor puts you to shame?",
    "If you argue your case with a neighbor, do not betray another man's confidence,",
    "or he who hears it may shame you and you will never lose your bad reputation.",
    "A word aptly spoken is like apples of gold in settings of silver.",
    "Like an earring of gold or an ornament of fine gold is a wise man's rebuke to a listening ear.",
    "Like the coolness of snow at harvest time is a trustworthy messenger to those who send him; he refreshes the spirit of his masters.",
    "Like clouds and wind without rain is a man who boasts of gifts he does not give.",
    "Through patience a ruler can be persuaded, and a gentle tongue can break a bone.",
    "If you find honey, eat just enough--too much of it, and you will vomit.",
    "Seldom set foot in your neighbor's house--too much of you, and he will hate you.",
    "Like a club or a sword or a sharp arrow is the man who gives false testimony against his neighbor.",
    "Like a bad tooth or a lame foot is reliance on the unfaithful in times of trouble.",
    "Like one who takes away a garment on a cold day, or like vinegar poured on soda, is one who sings songs to a heavy heart.",
    "If your enemy is hungry, give him food to eat; if he is thirsty, give him water to drink.",
    "In doing this, you will heap burning coals on his head, and the LORD will reward you.",
    "As a north wind brings rain, so a sly tongue brings angry looks.",
    "Better to live on a corner of the roof than share a house with a quarrelsome wife.",
    "Like cold water to a weary soul is good news from a distant land.",
    "Like a muddied spring or a polluted well is a righteous man who gives way to the wicked.",
    "It is not good to eat too much honey, nor is it honorable to seek one's own honor.",
    "Like a city whose walls are broken down is a man who lacks self-control."
  ],
  "Proverbs-25": [
    "Like snow in summer or rain in harvest, honor is not fitting for a fool.",
    "Like a fluttering sparrow or a darting swallow, an undeserved curse does not come to rest.",
    "A whip for the horse, a halter for the donkey, and a rod for the backs of fools!",
    "Do not answer a fool according to his folly, or you will be like him yourself.",
    "Answer a fool according to his folly, or he will be wise in his own eyes.",
    "Like cutting off one's feet or drinking violence is the sending of a message by the hand of a fool.",
    "Like a lame man's legs that hang limp is a proverb in the mouth of a fool.",
    "Like tying a stone in a sling is the giving of honor to a fool.",
    "Like a thornbush in a drunkard's hand is a proverb in the mouth of a fool.",
    "Like an archer who wounds at random is he who hires a fool or any passer-by.",
    "As a dog returns to its vomit, so a fool repeats his folly.",
    "Do you see a man wise in his own eyes? There is more hope for a fool than for him.",
    "The sluggard says, \"There is a lion in the road, a fierce lion roaming the streets!\"",
    "As a door turns on its hinges, so a sluggard turns on his bed.",
    "The sluggard buries his hand in the dish; he is too lazy to bring it back to his mouth.",
    "The sluggard is wiser in his own eyes than seven men who answer discreetly.",
    "Like one who seizes a dog by the ears is a passer-by who meddles in a quarrel not his own.",
    "Like a madman shooting firebrands or deadly arrows",
    "is a man who deceives his neighbor and says, \"I was only joking!\"",
    "Without wood a fire goes out; without gossip a quarrel dies down.",
    "As charcoal to embers and as wood to fire, so is a quarrelsome man for kindling strife.",
    "The words of a gossip are like choice morsels; they go down to a man's inmost parts.",
    "Like a coating of glaze over earthenware are fervent lips with an evil heart.",
    "A malicious man disguises himself with his lips, but in his heart he harbors deceit.",
    "Though his speech is charming, do not believe him, for seven abominations fill his heart.",
    "His malice may be concealed by deception, but his wickedness will be exposed in the assembly.",
    "If a man digs a pit, he will fall into it; if a man rolls a stone, it will roll back on him.",
    "A lying tongue hates those it hurts, and a flattering mouth works ruin."
  ],
  "Proverbs-26": [
    "Do not boast about tomorrow, for you do not know what a day may bring forth.",
    "Let another praise you, and not your own mouth; someone else, and not your own lips.",
    "Stone is heavy and sand a burden, but provocation by a fool is heavier than both.",
    "Anger is cruel and fury overwhelming, but who can stand before jealousy?",
    "Better is open rebuke than hidden love.",
    "Wounds from a friend can be trusted, but an enemy multiplies kisses.",
    "He who is full loathes honey, but to the hungry even what is bitter tastes sweet.",
    "Like a bird that strays from its nest is a man who strays from his home.",
    "Perfume and incense bring joy to the heart, and the pleasantness of one's friend springs from his earnest counsel.",
    "Do not forsake your friend and the friend of your father, and do not go to your brother's house when disaster strikes you--better a neighbor nearby than a brother far away.",
    "Be wise, my son, and bring joy to my heart; then I can answer anyone who treats me with contempt.",
    "The prudent see danger and take refuge, but the simple keep going and suffer for it.",
    "Take the garment of one who puts up security for a stranger; hold it in pledge if he does it for a wayward woman.",
    "If a man loudly blesses his neighbor early in the morning, it will be taken as a curse.",
    "A quarrelsome wife is like a constant dripping on a rainy day;",
    "restraining her is like restraining the wind or grasping oil with the hand.",
    "As iron sharpens iron, so one man sharpens another.",
    "He who tends a fig tree will eat its fruit, and he who looks after his master will be honored.",
    "As water reflects a face, so a man's heart reflects the man.",
    "Death and Destruction are never satisfied, and neither are the eyes of man.",
    "The crucible for silver and the furnace for gold, but man is tested by the praise he receives.",
    "Though you grind a fool in a mortar, grinding him like grain with a pestle, you will not remove his folly from him.",
    "Be sure you know the condition of your flocks, give careful attention to your herds;",
    "for riches do not endure forever, and a crown is not secure for all generations.",
    "When the hay is removed and new growth appears and the grass from the hills is gathered in,",
    "the lambs will provide you with clothing, and the goats with the price of a field.",
    "You will have plenty of goats' milk to feed you and your family and to nourish your servant girls."
  ],
  "Proverbs-27": [
    "The wicked man flees though no one pursues, but the righteous are as bold as a lion.",
    "When a country is rebellious, it has many rulers, but a man of understanding and knowledge maintains order.",
    "A ruler who oppresses the poor is like a driving rain that leaves no crops.",
    "Those who forsake the law praise the wicked, but those who keep the law resist them.",
    "Evil men do not understand justice, but those who seek the LORD understand it fully.",
    "Better a poor man whose walk is blameless than a rich man whose ways are perverse.",
    "He who keeps the law is a discerning son, but a companion of gluttons disgraces his father.",
    "He who increases his wealth by exorbitant interest amasses it for another, who will be kind to the poor.",
    "If anyone turns a deaf ear to the law, even his prayers are detestable.",
    "He who leads the upright along an evil path will fall into his own trap, but the blameless will receive a good inheritance.",
    "A rich man may be wise in his own eyes, but a poor man who has discernment sees through him.",
    "When the righteous triumph, there is great elation; but when the wicked rise to power, men go into hiding.",
    "He who conceals his sins does not prosper, but whoever confesses and renounces them finds mercy.",
    "Blessed is the man who always fears the LORD, but he who hardens his heart falls into trouble.",
    "Like a roaring lion or a charging bear is a wicked man ruling over a helpless people.",
    "A tyrannical ruler lacks judgment, but he who hates ill-gotten gain will enjoy a long life.",
    "A man tormented by the guilt of murder will be a fugitive till death; let no one support him.",
    "He whose walk is blameless is kept safe, but he whose ways are perverse will suddenly fall.",
    "He who works his land will have abundant food, but the one who chases fantasies will have his fill of poverty.",
    "A faithful man will be richly blessed, but one eager to get rich will not go unpunished.",
    "To show partiality is not good--yet a man will do wrong for a piece of bread.",
    "A stingy man is eager to get rich and is unaware that poverty awaits him.",
    "He who rebukes a man will in the end gain more favor than he who has a flattering tongue.",
    "He who robs his father or mother and says, \"It's not wrong\"--he is partner to him who destroys.",
    "A greedy man stirs up dissension, but he who trusts in the LORD will prosper.",
    "He who trusts in himself is a fool, but he who walks in wisdom is kept safe.",
    "He who gives to the poor will lack nothing, but he who closes his eyes to them receives many curses.",
    "When the wicked rise to power, people go into hiding; but when the wicked perish, the righteous thrive."
  ],
  "Proverbs-28": [
    "A man who remains stiff-necked after many rebukes will suddenly be destroyed--without remedy.",
    "When the righteous thrive, the people rejoice; when the wicked rule, the people groan.",
    "A man who loves wisdom brings joy to his father, but a companion of prostitutes squanders his wealth.",
    "By justice a king gives a country stability, but one who is greedy for bribes tears it down.",
    "Whoever flatters his neighbor is spreading a net for his feet.",
    "An evil man is snared by his own sin, but a righteous one can sing and be glad.",
    "The righteous care about justice for the poor, but the wicked have no such concern.",
    "Mockers stir up a city, but wise men turn away anger.",
    "If a wise man goes to court with a fool, the fool rages and scoffs, and there is no peace.",
    "Bloodthirsty men hate a man of integrity and seek to kill the upright.",
    "A fool gives full vent to his anger, but a wise man keeps himself under control.",
    "If a ruler listens to lies, all his officials become wicked.",
    "The poor man and the oppressor have this in common: The LORD gives sight to the eyes of both.",
    "If a king judges the poor with fairness, his throne will always be secure.",
    "The rod of correction imparts wisdom, but a child left to himself disgraces his mother.",
    "When the wicked thrive, so does sin, but the righteous will see their downfall.",
    "Discipline your son, and he will give you peace; he will bring delight to your soul.",
    "Where there is no revelation, the people cast off restraint; but blessed is he who keeps the law.",
    "A servant cannot be corrected by mere words; though he understands, he will not respond.",
    "Do you see a man who speaks in haste? There is more hope for a fool than for him.",
    "If a man pampers his servant from youth, he will bring grief in the end.",
    "An angry man stirs up dissension, and a hot-tempered one commits many sins.",
    "A man's pride brings him low, but a man of lowly spirit gains honor.",
    "The accomplice of a thief is his own enemy; he is put under oath and dare not testify.",
    "Fear of man will prove to be a snare, but whoever trusts in the LORD is kept safe.",
    "Many seek an audience with a ruler, but it is from the LORD that man gets justice.",
    "The righteous detest the dishonest; the wicked detest the upright."
  ],
  "Proverbs-29": [
    "The sayings of Agur son of Jakeh--an oracle: This man declared to Ithiel, to Ithiel and to Ucal:",
    "\"I am the most ignorant of men; I do not have a man's understanding.",
    "I have not learned wisdom, nor have I knowledge of the Holy One.",
    "Who has gone up to heaven and come down? Who has gathered up the wind in the hollow of his hands? Who has wrapped up the waters in his cloak? Who has established all the ends of the earth? What is his name, and the name of his son? Tell me if you know!",
    "\"Every word of God is flawless; he is a shield to those who take refuge in him.",
    "Do not add to his words, or he will rebuke you and prove you a liar.",
    "\"Two things I ask of you, O LORD; do not refuse me before I die:",
    "Keep falsehood and lies far from me; give me neither poverty nor riches, but give me only my daily bread.",
    "Otherwise, I may have too much and disown you and say, 'Who is the LORD?' Or I may become poor and steal, and so dishonor the name of my God.",
    "\"Do not slander a servant to his master, or he will curse you, and you will pay for it.",
    "\"There are those who curse their fathers and do not bless their mothers;",
    "those who are pure in their own eyes and yet are not cleansed of their filth;",
    "those whose eyes are ever so haughty, whose glances are so disdainful;",
    "those whose teeth are swords and whose jaws are set with knives to devour the poor from the earth, the needy from among mankind.",
    "\"The leech has two daughters. 'Give! Give!' they cry. \"There are three things that are never satisfied, four that never say, 'Enough!':",
    "the grave, the barren womb, land, which is never satisfied with water, and fire, which never says, 'Enough!'",
    "\"The eye that mocks a father, that scorns obedience to a mother, will be pecked out by the ravens of the valley, will be eaten by the vultures.",
    "\"There are three things that are too amazing for me, four that I do not understand:",
    "the way of an eagle in the sky, the way of a snake on a rock, the way of a ship on the high seas, and the way of a man with a maiden.",
    "\"This is the way of an adulteress: She eats and wipes her mouth and says, 'I've done nothing wrong.'",
    "\"Under three things the earth trembles, under four it cannot bear up:",
    "a servant who becomes king, a fool who is full of food,",
    "an unloved woman who is married, and a maidservant who displaces her mistress.",
    "\"Four things on earth are small, yet they are extremely wise:",
    "Ants are creatures of little strength, yet they store up their food in the summer;",
    "coneys are creatures of little power, yet they make their home in the crags;",
    "locusts have no king, yet they advance together in ranks;",
    "a lizard can be caught with the hand, yet it is found in kings' palaces.",
    "\"There are three things that are stately in their stride, four that move with stately bearing:",
    "a lion, mighty among beasts, who retreats before nothing;",
    "a strutting rooster, a he-goat, and a king with his army around him.",
    "\"If you have played the fool and exalted yourself, or if you have planned evil, clap your hand over your mouth!",
    "For as churning the milk produces butter, and as twisting the nose produces blood, so stirring up anger produces strife.\""
  ],
  "Proverbs-30": [
    "The sayings of King Lemuel--an oracle his mother taught him:",
    "\"O my son, O son of my womb, O son of my vows,",
    "do not spend your strength on women, your vigor on those who ruin kings.",
    "\"It is not for kings, O Lemuel--not for kings to drink wine, not for rulers to crave beer,",
    "lest they drink and forget what the law decrees, and deprive all the oppressed of their rights.",
    "Give beer to those who are perishing, wine to those who are in anguish;",
    "let them drink and forget their poverty and remember their misery no more.",
    "\"Speak up for those who cannot speak for themselves, for the rights of all who are destitute.",
    "Speak up and judge fairly; defend the rights of the poor and needy.\"",
    "A wife of noble character who can find? She is worth far more than rubies.",
    "Her husband has full confidence in her and lacks nothing of value.",
    "She brings him good, not harm, all the days of her life.",
    "She selects wool and flax and works with eager hands.",
    "She is like the merchant ships, bringing her food from afar.",
    "She gets up while it is still dark; she provides food for her family and portions for her servant girls.",
    "She considers a field and buys it; out of her earnings she plants a vineyard.",
    "She sets about her work vigorously; her arms are strong for her tasks.",
    "She sees that her trading is profitable, and her lamp does not go out at night.",
    "In her hand she holds the distaff and grasps the spindle with her fingers.",
    "She opens her arms to the poor and extends her hands to the needy.",
    "When it snows, she has no fear for her household; for all of them are clothed in scarlet.",
    "She makes coverings for her bed; she is clothed in fine linen and purple.",
    "Her husband is respected at the city gate, where he takes his seat among the elders of the land.",
    "She makes linen garments and sells them, and supplies the merchants with sashes.",
    "She is clothed with strength and dignity; she can laugh at the days to come.",
    "She speaks with wisdom, and faithful instruction is on her tongue.",
    "She watches over the affairs of her household and does not eat the bread of idleness.",
    "Her children arise and call her blessed; her husband also, and he praises her:",
    "\"Many women do noble things, but you surpass them all.\"",
    "Charm is deceptive, and beauty is fleeting; but a woman who fears the LORD is to be praised.",
    "Give her the reward she has earned, and let her works bring her praise at the city gate."
  ]
};