const Revelation = {
  "Revelation-0": [
    "The revelation of Jesus Christ, which God gave him to show his servants what must soon take place. He made it known by sending his angel to his servant John,",
    "who testifies to everything he saw--that is, the word of God and the testimony of Jesus Christ.",
    "Blessed is the one who reads the words of this prophecy, and blessed are those who hear it and take to heart what is written in it, because the time is near.",
    "John, To the seven churches in the province of Asia: Grace and peace to you from him who is, and who was, and who is to come, and from the seven spirits before his throne,",
    "and from Jesus Christ, who is the faithful witness, the firstborn from the dead, and the ruler of the kings of the earth. To him who loves us and has freed us from our sins by his blood,",
    "and has made us to be a kingdom and priests to serve his God and Father--to him be glory and power for ever and ever! Amen.",
    "Look, he is coming with the clouds, and every eye will see him, even those who pierced him; and all the peoples of the earth will mourn because of him. So shall it be! Amen.",
    "\"I am the Alpha and the Omega,\" says the Lord God, \"who is, and who was, and who is to come, the Almighty.\"",
    "I, John, your brother and companion in the suffering and kingdom and patient endurance that are ours in Jesus, was on the island of Patmos because of the word of God and the testimony of Jesus.",
    "On the Lord's Day I was in the Spirit, and I heard behind me a loud voice like a trumpet,",
    "which said: \"Write on a scroll what you see and send it to the seven churches: to Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia and Laodicea.\"",
    "I turned around to see the voice that was speaking to me. And when I turned I saw seven golden lampstands,",
    "and among the lampstands was someone \"like a son of man,\" dressed in a robe reaching down to his feet and with a golden sash around his chest.",
    "His head and hair were white like wool, as white as snow, and his eyes were like blazing fire.",
    "His feet were like bronze glowing in a furnace, and his voice was like the sound of rushing waters.",
    "In his right hand he held seven stars, and out of his mouth came a sharp double-edged sword. His face was like the sun shining in all its brilliance.",
    "When I saw him, I fell at his feet as though dead. Then he placed his right hand on me and said: \"Do not be afraid. I am the First and the Last.",
    "I am the Living One; I was dead, and behold I am alive for ever and ever! And I hold the keys of death and Hades.",
    "\"Write, therefore, what you have seen, what is now and what will take place later.",
    "The mystery of the seven stars that you saw in my right hand and of the seven golden lampstands is this: The seven stars are the angels of the seven churches, and the seven lampstands are the seven churches."
  ],
  "Revelation-1": [
    "\"To the angel of the church in Ephesus write: These are the words of him who holds the seven stars in his right hand and walks among the seven golden lampstands:",
    "I know your deeds, your hard work and your perseverance. I know that you cannot tolerate wicked men, that you have tested those who claim to be apostles but are not, and have found them false.",
    "You have persevered and have endured hardships for my name, and have not grown weary.",
    "Yet I hold this against you: You have forsaken your first love.",
    "Remember the height from which you have fallen! Repent and do the things you did at first. If you do not repent, I will come to you and remove your lampstand from its place.",
    "But you have this in your favor: You hate the practices of the Nicolaitans, which I also hate.",
    "He who has an ear, let him hear what the Spirit says to the churches. To him who overcomes, I will give the right to eat from the tree of life, which is in the paradise of God.",
    "\"To the angel of the church in Smyrna write: These are the words of him who is the First and the Last, who died and came to life again.",
    "I know your afflictions and your poverty--yet you are rich! I know the slander of those who say they are Jews and are not, but are a synagogue of Satan.",
    "Do not be afraid of what you are about to suffer. I tell you, the devil will put some of you in prison to test you, and you will suffer persecution for ten days. Be faithful, even to the point of death, and I will give you the crown of life.",
    "He who has an ear, let him hear what the Spirit says to the churches. He who overcomes will not be hurt at all by the second death.",
    "\"To the angel of the church in Pergamum write: These are the words of him who has the sharp, double-edged sword.",
    "I know where you live--where Satan has his throne. Yet you remain true to my name. You did not renounce your faith in me, even in the days of Antipas, my faithful witness, who was put to death in your city--where Satan lives.",
    "Nevertheless, I have a few things against you: You have people there who hold to the teaching of Balaam, who taught Balak to entice the Israelites to sin by eating food sacrificed to idols and by committing sexual immorality.",
    "Likewise you also have those who hold to the teaching of the Nicolaitans.",
    "Repent therefore! Otherwise, I will soon come to you and will fight against them with the sword of my mouth.",
    "He who has an ear, let him hear what the Spirit says to the churches. To him who overcomes, I will give some of the hidden manna. I will also give him a white stone with a new name written on it, known only to him who receives it.",
    "\"To the angel of the church in Thyatira write: These are the words of the Son of God, whose eyes are like blazing fire and whose feet are like burnished bronze.",
    "I know your deeds, your love and faith, your service and perseverance, and that you are now doing more than you did at first.",
    "Nevertheless, I have this against you: You tolerate that woman Jezebel, who calls herself a prophetess. By her teaching she misleads my servants into sexual immorality and the eating of food sacrificed to idols.",
    "I have given her time to repent of her immorality, but she is unwilling.",
    "So I will cast her on a bed of suffering, and I will make those who commit adultery with her suffer intensely, unless they repent of her ways.",
    "I will strike her children dead. Then all the churches will know that I am he who searches hearts and minds, and I will repay each of you according to your deeds.",
    "Now I say to the rest of you in Thyatira, to you who do not hold to her teaching and have not learned Satan's so-called deep secrets (I will not impose any other burden on you):",
    "Only hold on to what you have until I come.",
    "To him who overcomes and does my will to the end, I will give authority over the nations--",
    "'He will rule them with an iron scepter; he will dash them to pieces like pottery'--just as I have received authority from my Father.",
    "I will also give him the morning star.",
    "He who has an ear, let him hear what the Spirit says to the churches."
  ],
  "Revelation-2": [
    "\"To the angel of the church in Sardis write: These are the words of him who holds the seven spirits of God and the seven stars. I know your deeds; you have a reputation of being alive, but you are dead.",
    "Wake up! Strengthen what remains and is about to die, for I have not found your deeds complete in the sight of my God.",
    "Remember, therefore, what you have received and heard; obey it, and repent. But if you do not wake up, I will come like a thief, and you will not know at what time I will come to you.",
    "Yet you have a few people in Sardis who have not soiled their clothes. They will walk with me, dressed in white, for they are worthy.",
    "He who overcomes will, like them, be dressed in white. I will never blot out his name from the book of life, but will acknowledge his name before my Father and his angels.",
    "He who has an ear, let him hear what the Spirit says to the churches.",
    "\"To the angel of the church in Philadelphia write: These are the words of him who is holy and true, who holds the key of David. What he opens no one can shut, and what he shuts no one can open.",
    "I know your deeds. See, I have placed before you an open door that no one can shut. I know that you have little strength, yet you have kept my word and have not denied my name.",
    "I will make those who are of the synagogue of Satan, who claim to be Jews though they are not, but are liars--I will make them come and fall down at your feet and acknowledge that I have loved you.",
    "Since you have kept my command to endure patiently, I will also keep you from the hour of trial that is going to come upon the whole world to test those who live on the earth.",
    "I am coming soon. Hold on to what you have, so that no one will take your crown.",
    "Him who overcomes I will make a pillar in the temple of my God. Never again will he leave it. I will write on him the name of my God and the name of the city of my God, the new Jerusalem, which is coming down out of heaven from my God; and I will also write on him my new name.",
    "He who has an ear, let him hear what the Spirit says to the churches.",
    "\"To the angel of the church in Laodicea write: These are the words of the Amen, the faithful and true witness, the ruler of God's creation.",
    "I know your deeds, that you are neither cold nor hot. I wish you were either one or the other!",
    "So, because you are lukewarm--neither hot nor cold--I am about to spit you out of my mouth.",
    "You say, 'I am rich; I have acquired wealth and do not need a thing.' But you do not realize that you are wretched, pitiful, poor, blind and naked.",
    "I counsel you to buy from me gold refined in the fire, so you can become rich; and white clothes to wear, so you can cover your shameful nakedness; and salve to put on your eyes, so you can see.",
    "Those whom I love I rebuke and discipline. So be earnest, and repent.",
    "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with him, and he with me.",
    "To him who overcomes, I will give the right to sit with me on my throne, just as I overcame and sat down with my Father on his throne.",
    "He who has an ear, let him hear what the Spirit says to the churches.\""
  ],
  "Revelation-3": [
    "After this I looked, and there before me was a door standing open in heaven. And the voice I had first heard speaking to me like a trumpet said, \"Come up here, and I will show you what must take place after this.\"",
    "At once I was in the Spirit, and there before me was a throne in heaven with someone sitting on it.",
    "And the one who sat there had the appearance of jasper and carnelian. A rainbow, resembling an emerald, encircled the throne.",
    "Surrounding the throne were twenty-four other thrones, and seated on them were twenty-four elders. They were dressed in white and had crowns of gold on their heads.",
    "From the throne came flashes of lightning, rumblings and peals of thunder. Before the throne, seven lamps were blazing. These are the seven spirits of God.",
    "Also before the throne there was what looked like a sea of glass, clear as crystal. In the center, around the throne, were four living creatures, and they were covered with eyes, in front and in back.",
    "The first living creature was like a lion, the second was like an ox, the third had a face like a man, the fourth was like a flying eagle.",
    "Each of the four living creatures had six wings and was covered with eyes all around, even under his wings. Day and night they never stop saying: \"Holy, holy, holy is the Lord God Almighty, who was, and is, and is to come.\"",
    "Whenever the living creatures give glory, honor and thanks to him who sits on the throne and who lives for ever and ever,",
    "the twenty-four elders fall down before him who sits on the throne, and worship him who lives for ever and ever. They lay their crowns before the throne and say:",
    "\"You are worthy, our Lord and God, to receive glory and honor and power, for you created all things, and by your will they were created and have their being.\""
  ],
  "Revelation-4": [
    "Then I saw in the right hand of him who sat on the throne a scroll with writing on both sides and sealed with seven seals.",
    "And I saw a mighty angel proclaiming in a loud voice, \"Who is worthy to break the seals and open the scroll?\"",
    "But no one in heaven or on earth or under the earth could open the scroll or even look inside it.",
    "I wept and wept because no one was found who was worthy to open the scroll or look inside.",
    "Then one of the elders said to me, \"Do not weep! See, the Lion of the tribe of Judah, the Root of David, has triumphed. He is able to open the scroll and its seven seals.\"",
    "Then I saw a Lamb, looking as if it had been slain, standing in the center of the throne, encircled by the four living creatures and the elders. He had seven horns and seven eyes, which are the seven spirits of God sent out into all the earth.",
    "He came and took the scroll from the right hand of him who sat on the throne.",
    "And when he had taken it, the four living creatures and the twenty-four elders fell down before the Lamb. Each one had a harp and they were holding golden bowls full of incense, which are the prayers of the saints.",
    "And they sang a new song: \"You are worthy to take the scroll and to open its seals, because you were slain, and with your blood you purchased men for God from every tribe and language and people and nation.",
    "You have made them to be a kingdom and priests to serve our God, and they will reign on the earth.\"",
    "Then I looked and heard the voice of many angels, numbering thousands upon thousands, and ten thousand times ten thousand. They encircled the throne and the living creatures and the elders.",
    "In a loud voice they sang: \"Worthy is the Lamb, who was slain, to receive power and wealth and wisdom and strength and honor and glory and praise!\"",
    "Then I heard every creature in heaven and on earth and under the earth and on the sea, and all that is in them, singing: \"To him who sits on the throne and to the Lamb be praise and honor and glory and power, for ever and ever!\"",
    "The four living creatures said, \"Amen,\" and the elders fell down and worshiped."
  ],
  "Revelation-5": [
    "I watched as the Lamb opened the first of the seven seals. Then I heard one of the four living creatures say in a voice like thunder, \"Come!\"",
    "I looked, and there before me was a white horse! Its rider held a bow, and he was given a crown, and he rode out as a conqueror bent on conquest.",
    "When the Lamb opened the second seal, I heard the second living creature say, \"Come!\"",
    "Then another horse came out, a fiery red one. Its rider was given power to take peace from the earth and to make men slay each other. To him was given a large sword.",
    "When the Lamb opened the third seal, I heard the third living creature say, \"Come!\" I looked, and there before me was a black horse! Its rider was holding a pair of scales in his hand.",
    "Then I heard what sounded like a voice among the four living creatures, saying, \"A quart of wheat for a day's wages, and three quarts of barley for a day's wages, and do not damage the oil and the wine!\"",
    "When the Lamb opened the fourth seal, I heard the voice of the fourth living creature say, \"Come!\"",
    "I looked, and there before me was a pale horse! Its rider was named Death, and Hades was following close behind him. They were given power over a fourth of the earth to kill by sword, famine and plague, and by the wild beasts of the earth.",
    "When he opened the fifth seal, I saw under the altar the souls of those who had been slain because of the word of God and the testimony they had maintained.",
    "They called out in a loud voice, \"How long, Sovereign Lord, holy and true, until you judge the inhabitants of the earth and avenge our blood?\"",
    "Then each of them was given a white robe, and they were told to wait a little longer, until the number of their fellow servants and brothers who were to be killed as they had been was completed.",
    "I watched as he opened the sixth seal. There was a great earthquake. The sun turned black like sackcloth made of goat hair, the whole moon turned blood red,",
    "and the stars in the sky fell to earth, as late figs drop from a fig tree when shaken by a strong wind.",
    "The sky receded like a scroll, rolling up, and every mountain and island was removed from its place.",
    "Then the kings of the earth, the princes, the generals, the rich, the mighty, and every slave and every free man hid in caves and among the rocks of the mountains.",
    "They called to the mountains and the rocks, \"Fall on us and hide us from the face of him who sits on the throne and from the wrath of the Lamb!",
    "For the great day of their wrath has come, and who can stand?\""
  ],
  "Revelation-6": [
    "After this I saw four angels standing at the four corners of the earth, holding back the four winds of the earth to prevent any wind from blowing on the land or on the sea or on any tree.",
    "Then I saw another angel coming up from the east, having the seal of the living God. He called out in a loud voice to the four angels who had been given power to harm the land and the sea:",
    "\"Do not harm the land or the sea or the trees until we put a seal on the foreheads of the servants of our God.\"",
    "Then I heard the number of those who were sealed: 144,000 from all the tribes of Israel.",
    "From the tribe of Judah 12,000 were sealed, from the tribe of Reuben 12,000, from the tribe of Gad 12,000,",
    "from the tribe of Asher 12,000, from the tribe of Naphtali 12,000, from the tribe of Manasseh 12,000,",
    "from the tribe of Simeon 12,000, from the tribe of Levi 12,000, from the tribe of Issachar 12,000,",
    "from the tribe of Zebulun 12,000, from the tribe of Joseph 12,000, from the tribe of Benjamin 12,000.",
    "After this I looked and there before me was a great multitude that no one could count, from every nation, tribe, people and language, standing before the throne and in front of the Lamb. They were wearing white robes and were holding palm branches in their hands.",
    "And they cried out in a loud voice: \"Salvation belongs to our God, who sits on the throne, and to the Lamb.\"",
    "All the angels were standing around the throne and around the elders and the four living creatures. They fell down on their faces before the throne and worshiped God,",
    "saying: \"Amen! Praise and glory and wisdom and thanks and honor and power and strength be to our God for ever and ever. Amen!\"",
    "Then one of the elders asked me, \"These in white robes--who are they, and where did they come from?\"",
    "I answered, \"Sir, you know.\" And he said, \"These are they who have come out of the great tribulation; they have washed their robes and made them white in the blood of the Lamb.",
    "Therefore, \"they are before the throne of God and serve him day and night in his temple; and he who sits on the throne will spread his tent over them.",
    "Never again will they hunger; never again will they thirst. The sun will not beat upon them, nor any scorching heat.",
    "For the Lamb at the center of the throne will be their shepherd; he will lead them to springs of living water. And God will wipe away every tear from their eyes.\""
  ],
  "Revelation-7": [
    "When he opened the seventh seal, there was silence in heaven for about half an hour.",
    "And I saw the seven angels who stand before God, and to them were given seven trumpets.",
    "Another angel, who had a golden censer, came and stood at the altar. He was given much incense to offer, with the prayers of all the saints, on the golden altar before the throne.",
    "The smoke of the incense, together with the prayers of the saints, went up before God from the angel's hand.",
    "Then the angel took the censer, filled it with fire from the altar, and hurled it on the earth; and there came peals of thunder, rumblings, flashes of lightning and an earthquake.",
    "Then the seven angels who had the seven trumpets prepared to sound them.",
    "The first angel sounded his trumpet, and there came hail and fire mixed with blood, and it was hurled down upon the earth. A third of the earth was burned up, a third of the trees were burned up, and all the green grass was burned up.",
    "The second angel sounded his trumpet, and something like a huge mountain, all ablaze, was thrown into the sea. A third of the sea turned into blood,",
    "a third of the living creatures in the sea died, and a third of the ships were destroyed.",
    "The third angel sounded his trumpet, and a great star, blazing like a torch, fell from the sky on a third of the rivers and on the springs of water--",
    "the name of the star is Wormwood. A third of the waters turned bitter, and many people died from the waters that had become bitter.",
    "The fourth angel sounded his trumpet, and a third of the sun was struck, a third of the moon, and a third of the stars, so that a third of them turned dark. A third of the day was without light, and also a third of the night.",
    "As I watched, I heard an eagle that was flying in midair call out in a loud voice: \"Woe! Woe! Woe to the inhabitants of the earth, because of the trumpet blasts about to be sounded by the other three angels!\""
  ],
  "Revelation-8": [
    "The fifth angel sounded his trumpet, and I saw a star that had fallen from the sky to the earth. The star was given the key to the shaft of the Abyss.",
    "When he opened the Abyss, smoke rose from it like the smoke from a gigantic furnace. The sun and sky were darkened by the smoke from the Abyss.",
    "And out of the smoke locusts came down upon the earth and were given power like that of scorpions of the earth.",
    "They were told not to harm the grass of the earth or any plant or tree, but only those people who did not have the seal of God on their foreheads.",
    "They were not given power to kill them, but only to torture them for five months. And the agony they suffered was like that of the sting of a scorpion when it strikes a man.",
    "During those days men will seek death, but will not find it; they will long to die, but death will elude them.",
    "The locusts looked like horses prepared for battle. On their heads they wore something like crowns of gold, and their faces resembled human faces.",
    "Their hair was like women's hair, and their teeth were like lions' teeth.",
    "They had breastplates like breastplates of iron, and the sound of their wings was like the thundering of many horses and chariots rushing into battle.",
    "They had tails and stings like scorpions, and in their tails they had power to torment people for five months.",
    "They had as king over them the angel of the Abyss, whose name in Hebrew is Abaddon, and in Greek, Apollyon.",
    "The first woe is past; two other woes are yet to come.",
    "The sixth angel sounded his trumpet, and I heard a voice coming from the horns of the golden altar that is before God.",
    "It said to the sixth angel who had the trumpet, \"Release the four angels who are bound at the great river Euphrates.\"",
    "And the four angels who had been kept ready for this very hour and day and month and year were released to kill a third of mankind.",
    "The number of the mounted troops was two hundred million. I heard their number.",
    "The horses and riders I saw in my vision looked like this: Their breastplates were fiery red, dark blue, and yellow as sulfur. The heads of the horses resembled the heads of lions, and out of their mouths came fire, smoke and sulfur.",
    "A third of mankind was killed by the three plagues of fire, smoke and sulfur that came out of their mouths.",
    "The power of the horses was in their mouths and in their tails; for their tails were like snakes, having heads with which they inflict injury.",
    "The rest of mankind that were not killed by these plagues still did not repent of the work of their hands; they did not stop worshiping demons, and idols of gold, silver, bronze, stone and wood--idols that cannot see or hear or walk.",
    "Nor did they repent of their murders, their magic arts, their sexual immorality or their thefts."
  ],
  "Revelation-9": [
    "Then I saw another mighty angel coming down from heaven. He was robed in a cloud, with a rainbow above his head; his face was like the sun, and his legs were like fiery pillars.",
    "He was holding a little scroll, which lay open in his hand. He planted his right foot on the sea and his left foot on the land,",
    "and he gave a loud shout like the roar of a lion. When he shouted, the voices of the seven thunders spoke.",
    "And when the seven thunders spoke, I was about to write; but I heard a voice from heaven say, \"Seal up what the seven thunders have said and do not write it down.\"",
    "Then the angel I had seen standing on the sea and on the land raised his right hand to heaven.",
    "And he swore by him who lives for ever and ever, who created the heavens and all that is in them, the earth and all that is in it, and the sea and all that is in it, and said, \"There will be no more delay!",
    "But in the days when the seventh angel is about to sound his trumpet, the mystery of God will be accomplished, just as he announced to his servants the prophets.\"",
    "Then the voice that I had heard from heaven spoke to me once more: \"Go, take the scroll that lies open in the hand of the angel who is standing on the sea and on the land.\"",
    "So I went to the angel and asked him to give me the little scroll. He said to me, \"Take it and eat it. It will turn your stomach sour, but in your mouth it will be as sweet as honey.\"",
    "I took the little scroll from the angel's hand and ate it. It tasted as sweet as honey in my mouth, but when I had eaten it, my stomach turned sour.",
    "Then I was told, \"You must prophesy again about many peoples, nations, languages and kings.\""
  ],
  "Revelation-10": [
    "I was given a reed like a measuring rod and was told, \"Go and measure the temple of God and the altar, and count the worshipers there.",
    "But exclude the outer court; do not measure it, because it has been given to the Gentiles. They will trample on the holy city for 42 months.",
    "And I will give power to my two witnesses, and they will prophesy for 1,260 days, clothed in sackcloth.\"",
    "These are the two olive trees and the two lampstands that stand before the Lord of the earth.",
    "If anyone tries to harm them, fire comes from their mouths and devours their enemies. This is how anyone who wants to harm them must die.",
    "These men have power to shut up the sky so that it will not rain during the time they are prophesying; and they have power to turn the waters into blood and to strike the earth with every kind of plague as often as they want.",
    "Now when they have finished their testimony, the beast that comes up from the Abyss will attack them, and overpower and kill them.",
    "Their bodies will lie in the street of the great city, which is figuratively called Sodom and Egypt, where also their Lord was crucified.",
    "For three and a half days men from every people, tribe, language and nation will gaze on their bodies and refuse them burial.",
    "The inhabitants of the earth will gloat over them and will celebrate by sending each other gifts, because these two prophets had tormented those who live on the earth.",
    "But after the three and a half days a breath of life from God entered them, and they stood on their feet, and terror struck those who saw them.",
    "Then they heard a loud voice from heaven saying to them, \"Come up here.\" And they went up to heaven in a cloud, while their enemies looked on.",
    "At that very hour there was a severe earthquake and a tenth of the city collapsed. Seven thousand people were killed in the earthquake, and the survivors were terrified and gave glory to the God of heaven.",
    "The second woe has passed; the third woe is coming soon.",
    "The seventh angel sounded his trumpet, and there were loud voices in heaven, which said: \"The kingdom of the world has become the kingdom of our Lord and of his Christ, and he will reign for ever and ever.\"",
    "And the twenty-four elders, who were seated on their thrones before God, fell on their faces and worshiped God,",
    "saying: \"We give thanks to you, Lord God Almighty, the One who is and who was, because you have taken your great power and have begun to reign.",
    "The nations were angry; and your wrath has come. The time has come for judging the dead, and for rewarding your servants the prophets and your saints and those who reverence your name, both small and great--and for destroying those who destroy the earth.\"",
    "Then God's temple in heaven was opened, and within his temple was seen the ark of his covenant. And there came flashes of lightning, rumblings, peals of thunder, an earthquake and a great hailstorm."
  ],
  "Revelation-11": [
    "A great and wondrous sign appeared in heaven: a woman clothed with the sun, with the moon under her feet and a crown of twelve stars on her head.",
    "She was pregnant and cried out in pain as she was about to give birth.",
    "Then another sign appeared in heaven: an enormous red dragon with seven heads and ten horns and seven crowns on his heads.",
    "His tail swept a third of the stars out of the sky and flung them to the earth. The dragon stood in front of the woman who was about to give birth, so that he might devour her child the moment it was born.",
    "She gave birth to a son, a male child, who will rule all the nations with an iron scepter. And her child was snatched up to God and to his throne.",
    "The woman fled into the desert to a place prepared for her by God, where she might be taken care of for 1,260 days.",
    "And there was war in heaven. Michael and his angels fought against the dragon, and the dragon and his angels fought back.",
    "But he was not strong enough, and they lost their place in heaven.",
    "The great dragon was hurled down--that ancient serpent called the devil, or Satan, who leads the whole world astray. He was hurled to the earth, and his angels with him.",
    "Then I heard a loud voice in heaven say: \"Now have come the salvation and the power and the kingdom of our God, and the authority of his Christ. For the accuser of our brothers, who accuses them before our God day and night, has been hurled down.",
    "They overcame him by the blood of the Lamb and by the word of their testimony; they did not love their lives so much as to shrink from death.",
    "Therefore rejoice, you heavens and you who dwell in them! But woe to the earth and the sea, because the devil has gone down to you! He is filled with fury, because he knows that his time is short.\"",
    "When the dragon saw that he had been hurled to the earth, he pursued the woman who had given birth to the male child.",
    "The woman was given the two wings of a great eagle, so that she might fly to the place prepared for her in the desert, where she would be taken care of for a time, times and half a time, out of the serpent's reach.",
    "Then from his mouth the serpent spewed water like a river, to overtake the woman and sweep her away with the torrent.",
    "But the earth helped the woman by opening its mouth and swallowing the river that the dragon had spewed out of his mouth.",
    "Then the dragon was enraged at the woman and went off to make war against the rest of her offspring--those who obey God's commandments and hold to the testimony of Jesus."
  ],
  "Revelation-12": [
    "And the dragon stood on the shore of the sea. And I saw a beast coming out of the sea. He had ten horns and seven heads, with ten crowns on his horns, and on each head a blasphemous name.",
    "The beast I saw resembled a leopard, but had feet like those of a bear and a mouth like that of a lion. The dragon gave the beast his power and his throne and great authority.",
    "One of the heads of the beast seemed to have had a fatal wound, but the fatal wound had been healed. The whole world was astonished and followed the beast.",
    "Men worshiped the dragon because he had given authority to the beast, and they also worshiped the beast and asked, \"Who is like the beast? Who can make war against him?\"",
    "The beast was given a mouth to utter proud words and blasphemies and to exercise his authority for forty-two months.",
    "He opened his mouth to blaspheme God, and to slander his name and his dwelling place and those who live in heaven.",
    "He was given power to make war against the saints and to conquer them. And he was given authority over every tribe, people, language and nation.",
    "All inhabitants of the earth will worship the beast--all whose names have not been written in the book of life belonging to the Lamb that was slain from the creation of the world.",
    "He who has an ear, let him hear.",
    "If anyone is to go into captivity, into captivity he will go. If anyone is to be killed with the sword, with the sword he will be killed. This calls for patient endurance and faithfulness on the part of the saints.",
    "Then I saw another beast, coming out of the earth. He had two horns like a lamb, but he spoke like a dragon.",
    "He exercised all the authority of the first beast on his behalf, and made the earth and its inhabitants worship the first beast, whose fatal wound had been healed.",
    "And he performed great and miraculous signs, even causing fire to come down from heaven to earth in full view of men.",
    "Because of the signs he was given power to do on behalf of the first beast, he deceived the inhabitants of the earth. He ordered them to set up an image in honor of the beast who was wounded by the sword and yet lived.",
    "He was given power to give breath to the image of the first beast, so that it could speak and cause all who refused to worship the image to be killed.",
    "He also forced everyone, small and great, rich and poor, free and slave, to receive a mark on his right hand or on his forehead,",
    "so that no one could buy or sell unless he had the mark, which is the name of the beast or the number of his name.",
    "This calls for wisdom. If anyone has insight, let him calculate the number of the beast, for it is man's number. His number is 666."
  ],
  "Revelation-13": [
    "Then I looked, and there before me was the Lamb, standing on Mount Zion, and with him 144,000 who had his name and his Father's name written on their foreheads.",
    "And I heard a sound from heaven like the roar of rushing waters and like a loud peal of thunder. The sound I heard was like that of harpists playing their harps.",
    "And they sang a new song before the throne and before the four living creatures and the elders. No one could learn the song except the 144,000 who had been redeemed from the earth.",
    "These are those who did not defile themselves with women, for they kept themselves pure. They follow the Lamb wherever he goes. They were purchased from among men and offered as firstfruits to God and the Lamb.",
    "No lie was found in their mouths; they are blameless.",
    "Then I saw another angel flying in midair, and he had the eternal gospel to proclaim to those who live on the earth--to every nation, tribe, language and people.",
    "He said in a loud voice, \"Fear God and give him glory, because the hour of his judgment has come. Worship him who made the heavens, the earth, the sea and the springs of water.\"",
    "A second angel followed and said, \"Fallen! Fallen is Babylon the Great, which made all the nations drink the maddening wine of her adulteries.\"",
    "A third angel followed them and said in a loud voice: \"If anyone worships the beast and his image and receives his mark on the forehead or on the hand,",
    "he, too, will drink of the wine of God's fury, which has been poured full strength into the cup of his wrath. He will be tormented with burning sulfur in the presence of the holy angels and of the Lamb.",
    "And the smoke of their torment rises for ever and ever. There is no rest day or night for those who worship the beast and his image, or for anyone who receives the mark of his name.\"",
    "This calls for patient endurance on the part of the saints who obey God's commandments and remain faithful to Jesus.",
    "Then I heard a voice from heaven say, \"Write: Blessed are the dead who die in the Lord from now on.\" \"Yes,\" says the Spirit, \"they will rest from their labor, for their deeds will follow them.\"",
    "I looked, and there before me was a white cloud, and seated on the cloud was one \"like a son of man\" with a crown of gold on his head and a sharp sickle in his hand.",
    "Then another angel came out of the temple and called in a loud voice to him who was sitting on the cloud, \"Take your sickle and reap, because the time to reap has come, for the harvest of the earth is ripe.\"",
    "So he who was seated on the cloud swung his sickle over the earth, and the earth was harvested.",
    "Another angel came out of the temple in heaven, and he too had a sharp sickle.",
    "Still another angel, who had charge of the fire, came from the altar and called in a loud voice to him who had the sharp sickle, \"Take your sharp sickle and gather the clusters of grapes from the earth's vine, because its grapes are ripe.\"",
    "The angel swung his sickle on the earth, gathered its grapes and threw them into the great winepress of God's wrath.",
    "They were trampled in the winepress outside the city, and blood flowed out of the press, rising as high as the horses' bridles for a distance of 1,600 stadia."
  ],
  "Revelation-14": [
    "I saw in heaven another great and marvelous sign: seven angels with the seven last plagues--last, because with them God's wrath is completed.",
    "And I saw what looked like a sea of glass mixed with fire and, standing beside the sea, those who had been victorious over the beast and his image and over the number of his name. They held harps given them by God",
    "and sang the song of Moses the servant of God and the song of the Lamb: \"Great and marvelous are your deeds, Lord God Almighty. Just and true are your ways, King of the ages.",
    "Who will not fear you, O Lord, and bring glory to your name? For you alone are holy. All nations will come and worship before you, for your righteous acts have been revealed.\"",
    "After this I looked and in heaven the temple, that is, the tabernacle of the Testimony, was opened.",
    "Out of the temple came the seven angels with the seven plagues. They were dressed in clean, shining linen and wore golden sashes around their chests.",
    "Then one of the four living creatures gave to the seven angels seven golden bowls filled with the wrath of God, who lives for ever and ever.",
    "And the temple was filled with smoke from the glory of God and from his power, and no one could enter the temple until the seven plagues of the seven angels were completed."
  ],
  "Revelation-15": [
    "Then I heard a loud voice from the temple saying to the seven angels, \"Go, pour out the seven bowls of God's wrath on the earth.\"",
    "The first angel went and poured out his bowl on the land, and ugly and painful sores broke out on the people who had the mark of the beast and worshiped his image.",
    "The second angel poured out his bowl on the sea, and it turned into blood like that of a dead man, and every living thing in the sea died.",
    "The third angel poured out his bowl on the rivers and springs of water, and they became blood.",
    "Then I heard the angel in charge of the waters say: \"You are just in these judgments, you who are and who were, the Holy One, because you have so judged;",
    "for they have shed the blood of your saints and prophets, and you have given them blood to drink as they deserve.\"",
    "And I heard the altar respond: \"Yes, Lord God Almighty, true and just are your judgments.\"",
    "The fourth angel poured out his bowl on the sun, and the sun was given power to scorch people with fire.",
    "They were seared by the intense heat and they cursed the name of God, who had control over these plagues, but they refused to repent and glorify him.",
    "The fifth angel poured out his bowl on the throne of the beast, and his kingdom was plunged into darkness. Men gnawed their tongues in agony",
    "and cursed the God of heaven because of their pains and their sores, but they refused to repent of what they had done.",
    "The sixth angel poured out his bowl on the great river Euphrates, and its water was dried up to prepare the way for the kings from the East.",
    "Then I saw three evil spirits that looked like frogs; they came out of the mouth of the dragon, out of the mouth of the beast and out of the mouth of the false prophet.",
    "They are spirits of demons performing miraculous signs, and they go out to the kings of the whole world, to gather them for the battle on the great day of God Almighty.",
    "\"Behold, I come like a thief! Blessed is he who stays awake and keeps his clothes with him, so that he may not go naked and be shamefully exposed.\"",
    "Then they gathered the kings together to the place that in Hebrew is called Armageddon.",
    "The seventh angel poured out his bowl into the air, and out of the temple came a loud voice from the throne, saying, \"It is done!\"",
    "Then there came flashes of lightning, rumblings, peals of thunder and a severe earthquake. No earthquake like it has ever occurred since man has been on earth, so tremendous was the quake.",
    "The great city split into three parts, and the cities of the nations collapsed. God remembered Babylon the Great and gave her the cup filled with the wine of the fury of his wrath.",
    "Every island fled away and the mountains could not be found.",
    "From the sky huge hailstones of about a hundred pounds each fell upon men. And they cursed God on account of the plague of hail, because the plague was so terrible."
  ],
  "Revelation-16": [
    "One of the seven angels who had the seven bowls came and said to me, \"Come, I will show you the punishment of the great prostitute, who sits on many waters.",
    "With her the kings of the earth committed adultery and the inhabitants of the earth were intoxicated with the wine of her adulteries.\"",
    "Then the angel carried me away in the Spirit into a desert. There I saw a woman sitting on a scarlet beast that was covered with blasphemous names and had seven heads and ten horns.",
    "The woman was dressed in purple and scarlet, and was glittering with gold, precious stones and pearls. She held a golden cup in her hand, filled with abominable things and the filth of her adulteries.",
    "This title was written on her forehead: MYSTERY BABYLON THE GREAT THE MOTHER OF PROSTITUTES AND OF THE ABOMINATIONS OF THE EARTH.",
    "I saw that the woman was drunk with the blood of the saints, the blood of those who bore testimony to Jesus. When I saw her, I was greatly astonished.",
    "Then the angel said to me: \"Why are you astonished? I will explain to you the mystery of the woman and of the beast she rides, which has the seven heads and ten horns.",
    "The beast, which you saw, once was, now is not, and will come up out of the Abyss and go to his destruction. The inhabitants of the earth whose names have not been written in the book of life from the creation of the world will be astonished when they see the beast, because he once was, now is not, and yet will come.",
    "\"This calls for a mind with wisdom. The seven heads are seven hills on which the woman sits.",
    "They are also seven kings. Five have fallen, one is, the other has not yet come; but when he does come, he must remain for a little while.",
    "The beast who once was, and now is not, is an eighth king. He belongs to the seven and is going to his destruction.",
    "\"The ten horns you saw are ten kings who have not yet received a kingdom, but who for one hour will receive authority as kings along with the beast.",
    "They have one purpose and will give their power and authority to the beast.",
    "They will make war against the Lamb, but the Lamb will overcome them because he is Lord of lords and King of kings--and with him will be his called, chosen and faithful followers.\"",
    "Then the angel said to me, \"The waters you saw, where the prostitute sits, are peoples, multitudes, nations and languages.",
    "The beast and the ten horns you saw will hate the prostitute. They will bring her to ruin and leave her naked; they will eat her flesh and burn her with fire.",
    "For God has put it into their hearts to accomplish his purpose by agreeing to give the beast their power to rule, until God's words are fulfilled.",
    "The woman you saw is the great city that rules over the kings of the earth.\""
  ],
  "Revelation-17": [
    "After this I saw another angel coming down from heaven. He had great authority, and the earth was illuminated by his splendor.",
    "With a mighty voice he shouted: \"Fallen! Fallen is Babylon the Great! She has become a home for demons and a haunt for every evil spirit, a haunt for every unclean and detestable bird.",
    "For all the nations have drunk the maddening wine of her adulteries. The kings of the earth committed adultery with her, and the merchants of the earth grew rich from her excessive luxuries.\"",
    "Then I heard another voice from heaven say: \"Come out of her, my people, so that you will not share in her sins, so that you will not receive any of her plagues;",
    "for her sins are piled up to heaven, and God has remembered her crimes.",
    "Give back to her as she has given; pay her back double for what she has done. Mix her a double portion from her own cup.",
    "Give her as much torture and grief as the glory and luxury she gave herself. In her heart she boasts, 'I sit as queen; I am not a widow, and I will never mourn.'",
    "Therefore in one day her plagues will overtake her: death, mourning and famine. She will be consumed by fire, for mighty is the Lord God who judges her.",
    "\"When the kings of the earth who committed adultery with her and shared her luxury see the smoke of her burning, they will weep and mourn over her.",
    "Terrified at her torment, they will stand far off and cry: \"'Woe! Woe, O great city, O Babylon, city of power! In one hour your doom has come!'",
    "\"The merchants of the earth will weep and mourn over her because no one buys their cargoes any more--",
    "cargoes of gold, silver, precious stones and pearls; fine linen, purple, silk and scarlet cloth; every sort of citron wood, and articles of every kind made of ivory, costly wood, bronze, iron and marble;",
    "cargoes of cinnamon and spice, of incense, myrrh and frankincense, of wine and olive oil, of fine flour and wheat; cattle and sheep; horses and carriages; and bodies and souls of men.",
    "\"They will say, 'The fruit you longed for is gone from you. All your riches and splendor have vanished, never to be recovered.'",
    "The merchants who sold these things and gained their wealth from her will stand far off, terrified at her torment. They will weep and mourn",
    "and cry out: \"'Woe! Woe, O great city, dressed in fine linen, purple and scarlet, and glittering with gold, precious stones and pearls!",
    "In one hour such great wealth has been brought to ruin!' \"Every sea captain, and all who travel by ship, the sailors, and all who earn their living from the sea, will stand far off.",
    "When they see the smoke of her burning, they will exclaim, 'Was there ever a city like this great city?'",
    "They will throw dust on their heads, and with weeping and mourning cry out: \"'Woe! Woe, O great city, where all who had ships on the sea became rich through her wealth! In one hour she has been brought to ruin!",
    "Rejoice over her, O heaven! Rejoice, saints and apostles and prophets! God has judged her for the way she treated you.'\"",
    "Then a mighty angel picked up a boulder the size of a large millstone and threw it into the sea, and said: \"With such violence the great city of Babylon will be thrown down, never to be found again.",
    "The music of harpists and musicians, flute players and trumpeters, will never be heard in you again. No workman of any trade will ever be found in you again. The sound of a millstone will never be heard in you again.",
    "The light of a lamp will never shine in you again. The voice of bridegroom and bride will never be heard in you again. Your merchants were the world's great men. By your magic spell all the nations were led astray.",
    "In her was found the blood of prophets and of the saints, and of all who have been killed on the earth.\""
  ],
  "Revelation-18": [
    "After this I heard what sounded like the roar of a great multitude in heaven shouting: \"Hallelujah! Salvation and glory and power belong to our God,",
    "for true and just are his judgments. He has condemned the great prostitute who corrupted the earth by her adulteries. He has avenged on her the blood of his servants.\"",
    "And again they shouted: \"Hallelujah! The smoke from her goes up for ever and ever.\"",
    "The twenty-four elders and the four living creatures fell down and worshiped God, who was seated on the throne. And they cried: \"Amen, Hallelujah!\"",
    "Then a voice came from the throne, saying: \"Praise our God, all you his servants, you who fear him, both small and great!\"",
    "Then I heard what sounded like a great multitude, like the roar of rushing waters and like loud peals of thunder, shouting: \"Hallelujah! For our Lord God Almighty reigns.",
    "Let us rejoice and be glad and give him glory! For the wedding of the Lamb has come, and his bride has made herself ready.",
    "Fine linen, bright and clean, was given her to wear.\" (Fine linen stands for the righteous acts of the saints.)",
    "Then the angel said to me, \"Write: 'Blessed are those who are invited to the wedding supper of the Lamb!'\" And he added, \"These are the true words of God.\"",
    "At this I fell at his feet to worship him. But he said to me, \"Do not do it! I am a fellow servant with you and with your brothers who hold to the testimony of Jesus. Worship God! For the testimony of Jesus is the spirit of prophecy.\"",
    "I saw heaven standing open and there before me was a white horse, whose rider is called Faithful and True. With justice he judges and makes war.",
    "His eyes are like blazing fire, and on his head are many crowns. He has a name written on him that no one knows but he himself.",
    "He is dressed in a robe dipped in blood, and his name is the Word of God.",
    "The armies of heaven were following him, riding on white horses and dressed in fine linen, white and clean.",
    "Out of his mouth comes a sharp sword with which to strike down the nations. \"He will rule them with an iron scepter.\" He treads the winepress of the fury of the wrath of God Almighty.",
    "On his robe and on his thigh he has this name written: KING OF KINGS AND LORD OF LORDS.",
    "And I saw an angel standing in the sun, who cried in a loud voice to all the birds flying in midair, \"Come, gather together for the great supper of God,",
    "so that you may eat the flesh of kings, generals, and mighty men, of horses and their riders, and the flesh of all people, free and slave, small and great.\"",
    "Then I saw the beast and the kings of the earth and their armies gathered together to make war against the rider on the horse and his army.",
    "But the beast was captured, and with him the false prophet who had performed the miraculous signs on his behalf. With these signs he had deluded those who had received the mark of the beast and worshiped his image. The two of them were thrown alive into the fiery lake of burning sulfur.",
    "The rest of them were killed with the sword that came out of the mouth of the rider on the horse, and all the birds gorged themselves on their flesh."
  ],
  "Revelation-19": [
    "And I saw an angel coming down out of heaven, having the key to the Abyss and holding in his hand a great chain.",
    "He seized the dragon, that ancient serpent, who is the devil, or Satan, and bound him for a thousand years.",
    "He threw him into the Abyss, and locked and sealed it over him, to keep him from deceiving the nations anymore until the thousand years were ended. After that, he must be set free for a short time.",
    "I saw thrones on which were seated those who had been given authority to judge. And I saw the souls of those who had been beheaded because of their testimony for Jesus and because of the word of God. They had not worshiped the beast or his image and had not received his mark on their foreheads or their hands. They came to life and reigned with Christ a thousand years.",
    "(The rest of the dead did not come to life until the thousand years were ended.) This is the first resurrection.",
    "Blessed and holy are those who have part in the first resurrection. The second death has no power over them, but they will be priests of God and of Christ and will reign with him for a thousand years.",
    "When the thousand years are over, Satan will be released from his prison",
    "and will go out to deceive the nations in the four corners of the earth--Gog and Magog--to gather them for battle. In number they are like the sand on the seashore.",
    "They marched across the breadth of the earth and surrounded the camp of God's people, the city he loves. But fire came down from heaven and devoured them.",
    "And the devil, who deceived them, was thrown into the lake of burning sulfur, where the beast and the false prophet had been thrown. They will be tormented day and night for ever and ever.",
    "Then I saw a great white throne and him who was seated on it. Earth and sky fled from his presence, and there was no place for them.",
    "And I saw the dead, great and small, standing before the throne, and books were opened. Another book was opened, which is the book of life. The dead were judged according to what they had done as recorded in the books.",
    "The sea gave up the dead that were in it, and death and Hades gave up the dead that were in them, and each person was judged according to what he had done.",
    "Then death and Hades were thrown into the lake of fire. The lake of fire is the second death.",
    "If anyone's name was not found written in the book of life, he was thrown into the lake of fire."
  ],
  "Revelation-20": [
    "Then I saw a new heaven and a new earth, for the first heaven and the first earth had passed away, and there was no longer any sea.",
    "I saw the Holy City, the new Jerusalem, coming down out of heaven from God, prepared as a bride beautifully dressed for her husband.",
    "And I heard a loud voice from the throne saying, \"Now the dwelling of God is with men, and he will live with them. They will be his people, and God himself will be with them and be their God.",
    "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.\"",
    "He who was seated on the throne said, \"I am making everything new!\" Then he said, \"Write this down, for these words are trustworthy and true.\"",
    "He said to me: \"It is done. I am the Alpha and the Omega, the Beginning and the End. To him who is thirsty I will give to drink without cost from the spring of the water of life.",
    "He who overcomes will inherit all this, and I will be his God and he will be my son.",
    "But the cowardly, the unbelieving, the vile, the murderers, the sexually immoral, those who practice magic arts, the idolaters and all liars--their place will be in the fiery lake of burning sulfur. This is the second death.\"",
    "One of the seven angels who had the seven bowls full of the seven last plagues came and said to me, \"Come, I will show you the bride, the wife of the Lamb.\"",
    "And he carried me away in the Spirit to a mountain great and high, and showed me the Holy City, Jerusalem, coming down out of heaven from God.",
    "It shone with the glory of God, and its brilliance was like that of a very precious jewel, like a jasper, clear as crystal.",
    "It had a great, high wall with twelve gates, and with twelve angels at the gates. On the gates were written the names of the twelve tribes of Israel.",
    "There were three gates on the east, three on the north, three on the south and three on the west.",
    "The wall of the city had twelve foundations, and on them were the names of the twelve apostles of the Lamb.",
    "The angel who talked with me had a measuring rod of gold to measure the city, its gates and its walls.",
    "The city was laid out like a square, as long as it was wide. He measured the city with the rod and found it to be 12,000 stadia in length, and as wide and high as it is long.",
    "He measured its wall and it was 144 cubits thick, by man's measurement, which the angel was using.",
    "The wall was made of jasper, and the city of pure gold, as pure as glass.",
    "The foundations of the city walls were decorated with every kind of precious stone. The first foundation was jasper, the second sapphire, the third chalcedony, the fourth emerald,",
    "the fifth sardonyx, the sixth carnelian, the seventh chrysolite, the eighth beryl, the ninth topaz, the tenth chrysoprase, the eleventh jacinth, and the twelfth amethyst.",
    "The twelve gates were twelve pearls, each gate made of a single pearl. The great street of the city was of pure gold, like transparent glass.",
    "I did not see a temple in the city, because the Lord God Almighty and the Lamb are its temple.",
    "The city does not need the sun or the moon to shine on it, for the glory of God gives it light, and the Lamb is its lamp.",
    "The nations will walk by its light, and the kings of the earth will bring their splendor into it.",
    "On no day will its gates ever be shut, for there will be no night there.",
    "The glory and honor of the nations will be brought into it.",
    "Nothing impure will ever enter it, nor will anyone who does what is shameful or deceitful, but only those whose names are written in the Lamb's book of life."
  ],
  "Revelation-21": [
    "Then the angel showed me the river of the water of life, as clear as crystal, flowing from the throne of God and of the Lamb",
    "down the middle of the great street of the city. On each side of the river stood the tree of life, bearing twelve crops of fruit, yielding its fruit every month. And the leaves of the tree are for the healing of the nations.",
    "No longer will there be any curse. The throne of God and of the Lamb will be in the city, and his servants will serve him.",
    "They will see his face, and his name will be on their foreheads.",
    "There will be no more night. They will not need the light of a lamp or the light of the sun, for the Lord God will give them light. And they will reign for ever and ever.",
    "The angel said to me, \"These words are trustworthy and true. The Lord, the God of the spirits of the prophets, sent his angel to show his servants the things that must soon take place.\"",
    "\"Behold, I am coming soon! Blessed is he who keeps the words of the prophecy in this book.\"",
    "I, John, am the one who heard and saw these things. And when I had heard and seen them, I fell down to worship at the feet of the angel who had been showing them to me.",
    "But he said to me, \"Do not do it! I am a fellow servant with you and with your brothers the prophets and of all who keep the words of this book. Worship God!\"",
    "Then he told me, \"Do not seal up the words of the prophecy of this book, because the time is near.",
    "Let him who does wrong continue to do wrong; let him who is vile continue to be vile; let him who does right continue to do right; and let him who is holy continue to be holy.\"",
    "\"Behold, I am coming soon! My reward is with me, and I will give to everyone according to what he has done.",
    "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.",
    "\"Blessed are those who wash their robes, that they may have the right to the tree of life and may go through the gates into the city.",
    "Outside are the dogs, those who practice magic arts, the sexually immoral, the murderers, the idolaters and everyone who loves and practices falsehood.",
    "\"I, Jesus, have sent my angel to give you this testimony for the churches. I am the Root and the Offspring of David, and the bright Morning Star.\"",
    "The Spirit and the bride say, \"Come!\" And let him who hears say, \"Come!\" Whoever is thirsty, let him come; and whoever wishes, let him take the free gift of the water of life.",
    "I warn everyone who hears the words of the prophecy of this book: If anyone adds anything to them, God will add to him the plagues described in this book.",
    "And if anyone takes words away from this book of prophecy, God will take away from him his share in the tree of life and in the holy city, which are described in this book.",
    "He who testifies to these things says, \"Yes, I am coming soon.\" Amen. Come, Lord Jesus.",
    "The grace of the Lord Jesus be with God's people. Amen."
  ]
};