const Romans = {
  "Romans-0": [
    "Paul, a servant of Christ Jesus, called to be an apostle and set apart for the gospel of God--",
    "the gospel he promised beforehand through his prophets in the Holy Scriptures",
    "regarding his Son, who as to his human nature was a descendant of David,",
    "and who through the Spirit of holiness was declared with power to be the Son of God by his resurrection from the dead: Jesus Christ our Lord.",
    "Through him and for his name's sake, we received grace and apostleship to call people from among all the Gentiles to the obedience that comes from faith.",
    "And you also are among those who are called to belong to Jesus Christ.",
    "To all in Rome who are loved by God and called to be saints: Grace and peace to you from God our Father and from the Lord Jesus Christ.",
    "First, I thank my God through Jesus Christ for all of you, because your faith is being reported all over the world.",
    "God, whom I serve with my whole heart in preaching the gospel of his Son, is my witness how constantly I remember you",
    "in my prayers at all times; and I pray that now at last by God's will the way may be opened for me to come to you.",
    "I long to see you so that I may impart to you some spiritual gift to make you strong--",
    "that is, that you and I may be mutually encouraged by each other's faith.",
    "I do not want you to be unaware, brothers, that I planned many times to come to you (but have been prevented from doing so until now) in order that I might have a harvest among you, just as I have had among the other Gentiles.",
    "I am obligated both to Greeks and non-Greeks, both to the wise and the foolish.",
    "That is why I am so eager to preach the gospel also to you who are at Rome.",
    "I am not ashamed of the gospel, because it is the power of God for the salvation of everyone who believes: first for the Jew, then for the Gentile.",
    "For in the gospel a righteousness from God is revealed, a righteousness that is by faith from first to last, just as it is written: \"The righteous will live by faith.\"",
    "The wrath of God is being revealed from heaven against all the godlessness and wickedness of men who suppress the truth by their wickedness,",
    "since what may be known about God is plain to them, because God has made it plain to them.",
    "For since the creation of the world God's invisible qualities--his eternal power and divine nature--have been clearly seen, being understood from what has been made, so that men are without excuse.",
    "For although they knew God, they neither glorified him as God nor gave thanks to him, but their thinking became futile and their foolish hearts were darkened.",
    "Although they claimed to be wise, they became fools",
    "and exchanged the glory of the immortal God for images made to look like mortal man and birds and animals and reptiles.",
    "Therefore God gave them over in the sinful desires of their hearts to sexual impurity for the degrading of their bodies with one another.",
    "They exchanged the truth of God for a lie, and worshiped and served created things rather than the Creator--who is forever praised. Amen.",
    "Because of this, God gave them over to shameful lusts. Even their women exchanged natural relations for unnatural ones.",
    "In the same way the men also abandoned natural relations with women and were inflamed with lust for one another. Men committed indecent acts with other men, and received in themselves the due penalty for their perversion.",
    "Furthermore, since they did not think it worthwhile to retain the knowledge of God, he gave them over to a depraved mind, to do what ought not to be done.",
    "They have become filled with every kind of wickedness, evil, greed and depravity. They are full of envy, murder, strife, deceit and malice. They are gossips,",
    "slanderers, God-haters, insolent, arrogant and boastful; they invent ways of doing evil; they disobey their parents;",
    "they are senseless, faithless, heartless, ruthless.",
    "Although they know God's righteous decree that those who do such things deserve death, they not only continue to do these very things but also approve of those who practice them."
  ],
  "Romans-1": [
    "You, therefore, have no excuse, you who pass judgment on someone else, for at whatever point you judge the other, you are condemning yourself, because you who pass judgment do the same things.",
    "Now we know that God's judgment against those who do such things is based on truth.",
    "So when you, a mere man, pass judgment on them and yet do the same things, do you think you will escape God's judgment?",
    "Or do you show contempt for the riches of his kindness, tolerance and patience, not realizing that God's kindness leads you toward repentance?",
    "But because of your stubbornness and your unrepentant heart, you are storing up wrath against yourself for the day of God's wrath, when his righteous judgment will be revealed.",
    "God \"will give to each person according to what he has done.\"",
    "To those who by persistence in doing good seek glory, honor and immortality, he will give eternal life.",
    "But for those who are self-seeking and who reject the truth and follow evil, there will be wrath and anger.",
    "There will be trouble and distress for every human being who does evil: first for the Jew, then for the Gentile;",
    "but glory, honor and peace for everyone who does good: first for the Jew, then for the Gentile.",
    "For God does not show favoritism.",
    "All who sin apart from the law will also perish apart from the law, and all who sin under the law will be judged by the law.",
    "For it is not those who hear the law who are righteous in God's sight, but it is those who obey the law who will be declared righteous.",
    "(Indeed, when Gentiles, who do not have the law, do by nature things required by the law, they are a law for themselves, even though they do not have the law,",
    "since they show that the requirements of the law are written on their hearts, their consciences also bearing witness, and their thoughts now accusing, now even defending them.)",
    "This will take place on the day when God will judge men's secrets through Jesus Christ, as my gospel declares.",
    "Now you, if you call yourself a Jew; if you rely on the law and brag about your relationship to God;",
    "if you know his will and approve of what is superior because you are instructed by the law;",
    "if you are convinced that you are a guide for the blind, a light for those who are in the dark,",
    "an instructor of the foolish, a teacher of infants, because you have in the law the embodiment of knowledge and truth--",
    "you, then, who teach others, do you not teach yourself? You who preach against stealing, do you steal?",
    "You who say that people should not commit adultery, do you commit adultery? You who abhor idols, do you rob temples?",
    "You who brag about the law, do you dishonor God by breaking the law?",
    "As it is written: \"God's name is blasphemed among the Gentiles because of you.\"",
    "Circumcision has value if you observe the law, but if you break the law, you have become as though you had not been circumcised.",
    "If those who are not circumcised keep the law's requirements, will they not be regarded as though they were circumcised?",
    "The one who is not circumcised physically and yet obeys the law will condemn you who, even though you have the written code and circumcision, are a lawbreaker.",
    "A man is not a Jew if he is only one outwardly, nor is circumcision merely outward and physical.",
    "No, a man is a Jew if he is one inwardly; and circumcision is circumcision of the heart, by the Spirit, not by the written code. Such a man's praise is not from men, but from God."
  ],
  "Romans-2": [
    "What advantage, then, is there in being a Jew, or what value is there in circumcision?",
    "Much in every way! First of all, they have been entrusted with the very words of God.",
    "What if some did not have faith? Will their lack of faith nullify God's faithfulness?",
    "Not at all! Let God be true, and every man a liar. As it is written: \"So that you may be proved right when you speak and prevail when you judge.\"",
    "But if our unrighteousness brings out God's righteousness more clearly, what shall we say? That God is unjust in bringing his wrath on us? (I am using a human argument.)",
    "Certainly not! If that were so, how could God judge the world?",
    "Someone might argue, \"If my falsehood enhances God's truthfulness and so increases his glory, why am I still condemned as a sinner?\"",
    "Why not say--as we are being slanderously reported as saying and as some claim that we say--\"Let us do evil that good may result\"? Their condemnation is deserved.",
    "What shall we conclude then? Are we any better? Not at all! We have already made the charge that Jews and Gentiles alike are all under sin.",
    "As it is written: \"There is no one righteous, not even one;",
    "there is no one who understands, no one who seeks God.",
    "All have turned away, they have together become worthless; there is no one who does good, not even one.\"",
    "\"Their throats are open graves; their tongues practice deceit.\" \"The poison of vipers is on their lips.\"",
    "\"Their mouths are full of cursing and bitterness.\"",
    "\"Their feet are swift to shed blood;",
    "ruin and misery mark their ways,",
    "and the way of peace they do not know.\"",
    "\"There is no fear of God before their eyes.\"",
    "Now we know that whatever the law says, it says to those who are under the law, so that every mouth may be silenced and the whole world held accountable to God.",
    "Therefore no one will be declared righteous in his sight by observing the law; rather, through the law we become conscious of sin.",
    "But now a righteousness from God, apart from law, has been made known, to which the Law and the Prophets testify.",
    "This righteousness from God comes through faith in Jesus Christ to all who believe. There is no difference,",
    "for all have sinned and fall short of the glory of God,",
    "and are justified freely by his grace through the redemption that came by Christ Jesus.",
    "God presented him as a sacrifice of atonement, through faith in his blood. He did this to demonstrate his justice, because in his forbearance he had left the sins committed beforehand unpunished--",
    "he did it to demonstrate his justice at the present time, so as to be just and the one who justifies those who have faith in Jesus.",
    "Where, then, is boasting? It is excluded. On what principle? On that of observing the law? No, but on that of faith.",
    "For we maintain that a man is justified by faith apart from observing the law.",
    "Is God the God of Jews only? Is he not the God of Gentiles too? Yes, of Gentiles too,",
    "since there is only one God, who will justify the circumcised by faith and the uncircumcised through that same faith.",
    "Do we, then, nullify the law by this faith? Not at all! Rather, we uphold the law."
  ],
  "Romans-3": [
    "What then shall we say that Abraham, our forefather, discovered in this matter?",
    "If, in fact, Abraham was justified by works, he had something to boast about--but not before God.",
    "What does the Scripture say? \"Abraham believed God, and it was credited to him as righteousness.\"",
    "Now when a man works, his wages are not credited to him as a gift, but as an obligation.",
    "However, to the man who does not work but trusts God who justifies the wicked, his faith is credited as righteousness.",
    "David says the same thing when he speaks of the blessedness of the man to whom God credits righteousness apart from works:",
    "\"Blessed are they whose transgressions are forgiven, whose sins are covered.",
    "Blessed is the man whose sin the Lord will never count against him.\"",
    "Is this blessedness only for the circumcised, or also for the uncircumcised? We have been saying that Abraham's faith was credited to him as righteousness.",
    "Under what circumstances was it credited? Was it after he was circumcised, or before? It was not after, but before!",
    "And he received the sign of circumcision, a seal of the righteousness that he had by faith while he was still uncircumcised. So then, he is the father of all who believe but have not been circumcised, in order that righteousness might be credited to them.",
    "And he is also the father of the circumcised who not only are circumcised but who also walk in the footsteps of the faith that our father Abraham had before he was circumcised.",
    "It was not through law that Abraham and his offspring received the promise that he would be heir of the world, but through the righteousness that comes by faith.",
    "For if those who live by law are heirs, faith has no value and the promise is worthless,",
    "because law brings wrath. And where there is no law there is no transgression.",
    "Therefore, the promise comes by faith, so that it may be by grace and may be guaranteed to all Abraham's offspring--not only to those who are of the law but also to those who are of the faith of Abraham. He is the father of us all.",
    "As it is written: \"I have made you a father of many nations.\" He is our father in the sight of God, in whom he believed--the God who gives life to the dead and calls things that are not as though they were.",
    "Against all hope, Abraham in hope believed and so became the father of many nations, just as it had been said to him, \"So shall your offspring be.\"",
    "Without weakening in his faith, he faced the fact that his body was as good as dead--since he was about a hundred years old--and that Sarah's womb was also dead.",
    "Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God,",
    "being fully persuaded that God had power to do what he had promised.",
    "This is why \"it was credited to him as righteousness.\"",
    "The words \"it was credited to him\" were written not for him alone,",
    "but also for us, to whom God will credit righteousness--for us who believe in him who raised Jesus our Lord from the dead.",
    "He was delivered over to death for our sins and was raised to life for our justification."
  ],
  "Romans-4": [
    "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ,",
    "through whom we have gained access by faith into this grace in which we now stand. And we rejoice in the hope of the glory of God.",
    "Not only so, but we also rejoice in our sufferings, because we know that suffering produces perseverance;",
    "perseverance, character; and character, hope.",
    "And hope does not disappoint us, because God has poured out his love into our hearts by the Holy Spirit, whom he has given us.",
    "You see, at just the right time, when we were still powerless, Christ died for the ungodly.",
    "Very rarely will anyone die for a righteous man, though for a good man someone might possibly dare to die.",
    "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
    "Since we have now been justified by his blood, how much more shall we be saved from God's wrath through him!",
    "For if, when we were God's enemies, we were reconciled to him through the death of his Son, how much more, having been reconciled, shall we be saved through his life!",
    "Not only is this so, but we also rejoice in God through our Lord Jesus Christ, through whom we have now received reconciliation.",
    "Therefore, just as sin entered the world through one man, and death through sin, and in this way death came to all men, because all sinned--",
    "for before the law was given, sin was in the world. But sin is not taken into account when there is no law.",
    "Nevertheless, death reigned from the time of Adam to the time of Moses, even over those who did not sin by breaking a command, as did Adam, who was a pattern of the one to come.",
    "But the gift is not like the trespass. For if the many died by the trespass of the one man, how much more did God's grace and the gift that came by the grace of the one man, Jesus Christ, overflow to the many!",
    "Again, the gift of God is not like the result of the one man's sin: The judgment followed one sin and brought condemnation, but the gift followed many trespasses and brought justification.",
    "For if, by the trespass of the one man, death reigned through that one man, how much more will those who receive God's abundant provision of grace and of the gift of righteousness reign in life through the one man, Jesus Christ.",
    "Consequently, just as the result of one trespass was condemnation for all men, so also the result of one act of righteousness was justification that brings life for all men.",
    "For just as through the disobedience of the one man the many were made sinners, so also through the obedience of the one man the many will be made righteous.",
    "The law was added so that the trespass might increase. But where sin increased, grace increased all the more,",
    "so that, just as sin reigned in death, so also grace might reign through righteousness to bring eternal life through Jesus Christ our Lord."
  ],
  "Romans-5": [
    "What shall we say, then? Shall we go on sinning so that grace may increase?",
    "By no means! We died to sin; how can we live in it any longer?",
    "Or don't you know that all of us who were baptized into Christ Jesus were baptized into his death?",
    "We were therefore buried with him through baptism into death in order that, just as Christ was raised from the dead through the glory of the Father, we too may live a new life.",
    "If we have been united with him like this in his death, we will certainly also be united with him in his resurrection.",
    "For we know that our old self was crucified with him so that the body of sin might be done away with, that we should no longer be slaves to sin--",
    "because anyone who has died has been freed from sin.",
    "Now if we died with Christ, we believe that we will also live with him.",
    "For we know that since Christ was raised from the dead, he cannot die again; death no longer has mastery over him.",
    "The death he died, he died to sin once for all; but the life he lives, he lives to God.",
    "In the same way, count yourselves dead to sin but alive to God in Christ Jesus.",
    "Therefore do not let sin reign in your mortal body so that you obey its evil desires.",
    "Do not offer the parts of your body to sin, as instruments of wickedness, but rather offer yourselves to God, as those who have been brought from death to life; and offer the parts of your body to him as instruments of righteousness.",
    "For sin shall not be your master, because you are not under law, but under grace.",
    "What then? Shall we sin because we are not under law but under grace? By no means!",
    "Don't you know that when you offer yourselves to someone to obey him as slaves, you are slaves to the one whom you obey--whether you are slaves to sin, which leads to death, or to obedience, which leads to righteousness?",
    "But thanks be to God that, though you used to be slaves to sin, you wholeheartedly obeyed the form of teaching to which you were entrusted.",
    "You have been set free from sin and have become slaves to righteousness.",
    "I put this in human terms because you are weak in your natural selves. Just as you used to offer the parts of your body in slavery to impurity and to ever-increasing wickedness, so now offer them in slavery to righteousness leading to holiness.",
    "When you were slaves to sin, you were free from the control of righteousness.",
    "What benefit did you reap at that time from the things you are now ashamed of? Those things result in death!",
    "But now that you have been set free from sin and have become slaves to God, the benefit you reap leads to holiness, and the result is eternal life.",
    "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord."
  ],
  "Romans-6": [
    "Do you not know, brothers--for I am speaking to men who know the law--that the law has authority over a man only as long as he lives?",
    "For example, by law a married woman is bound to her husband as long as he is alive, but if her husband dies, she is released from the law of marriage.",
    "So then, if she marries another man while her husband is still alive, she is called an adulteress. But if her husband dies, she is released from that law and is not an adulteress, even though she marries another man.",
    "So, my brothers, you also died to the law through the body of Christ, that you might belong to another, to him who was raised from the dead, in order that we might bear fruit to God.",
    "For when we were controlled by the sinful nature, the sinful passions aroused by the law were at work in our bodies, so that we bore fruit for death.",
    "But now, by dying to what once bound us, we have been released from the law so that we serve in the new way of the Spirit, and not in the old way of the written code.",
    "What shall we say, then? Is the law sin? Certainly not! Indeed I would not have known what sin was except through the law. For I would not have known what coveting really was if the law had not said, \"Do not covet.\"",
    "But sin, seizing the opportunity afforded by the commandment, produced in me every kind of covetous desire. For apart from law, sin is dead.",
    "Once I was alive apart from law; but when the commandment came, sin sprang to life and I died.",
    "I found that the very commandment that was intended to bring life actually brought death.",
    "For sin, seizing the opportunity afforded by the commandment, deceived me, and through the commandment put me to death.",
    "So then, the law is holy, and the commandment is holy, righteous and good.",
    "Did that which is good, then, become death to me? By no means! But in order that sin might be recognized as sin, it produced death in me through what was good, so that through the commandment sin might become utterly sinful.",
    "We know that the law is spiritual; but I am unspiritual, sold as a slave to sin.",
    "I do not understand what I do. For what I want to do I do not do, but what I hate I do.",
    "And if I do what I do not want to do, I agree that the law is good.",
    "As it is, it is no longer I myself who do it, but it is sin living in me.",
    "I know that nothing good lives in me, that is, in my sinful nature. For I have the desire to do what is good, but I cannot carry it out.",
    "For what I do is not the good I want to do; no, the evil I do not want to do--this I keep on doing.",
    "Now if I do what I do not want to do, it is no longer I who do it, but it is sin living in me that does it.",
    "So I find this law at work: When I want to do good, evil is right there with me.",
    "For in my inner being I delight in God's law;",
    "but I see another law at work in the members of my body, waging war against the law of my mind and making me a prisoner of the law of sin at work within my members.",
    "What a wretched man I am! Who will rescue me from this body of death?",
    "Thanks be to God--through Jesus Christ our Lord! So then, I myself in my mind am a slave to God's law, but in the sinful nature a slave to the law of sin."
  ],
  "Romans-7": [
    "Therefore, there is now no condemnation for those who are in Christ Jesus,",
    "because through Christ Jesus the law of the Spirit of life set me free from the law of sin and death.",
    "For what the law was powerless to do in that it was weakened by the sinful nature, God did by sending his own Son in the likeness of sinful man to be a sin offering. And so he condemned sin in sinful man,",
    "in order that the righteous requirements of the law might be fully met in us, who do not live according to the sinful nature but according to the Spirit.",
    "Those who live according to the sinful nature have their minds set on what that nature desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires.",
    "The mind of sinful man is death, but the mind controlled by the Spirit is life and peace;",
    "the sinful mind is hostile to God. It does not submit to God's law, nor can it do so.",
    "Those controlled by the sinful nature cannot please God.",
    "You, however, are controlled not by the sinful nature but by the Spirit, if the Spirit of God lives in you. And if anyone does not have the Spirit of Christ, he does not belong to Christ.",
    "But if Christ is in you, your body is dead because of sin, yet your spirit is alive because of righteousness.",
    "And if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies through his Spirit, who lives in you.",
    "Therefore, brothers, we have an obligation--but it is not to the sinful nature, to live according to it.",
    "For if you live according to the sinful nature, you will die; but if by the Spirit you put to death the misdeeds of the body, you will live,",
    "because those who are led by the Spirit of God are sons of God.",
    "For you did not receive a spirit that makes you a slave again to fear, but you received the Spirit of sonship. And by him we cry, \"Abba, Father.\"",
    "The Spirit himself testifies with our spirit that we are God's children.",
    "Now if we are children, then we are heirs--heirs of God and co-heirs with Christ, if indeed we share in his sufferings in order that we may also share in his glory.",
    "I consider that our present sufferings are not worth comparing with the glory that will be revealed in us.",
    "The creation waits in eager expectation for the sons of God to be revealed.",
    "For the creation was subjected to frustration, not by its own choice, but by the will of the one who subjected it, in hope",
    "that the creation itself will be liberated from its bondage to decay and brought into the glorious freedom of the children of God.",
    "We know that the whole creation has been groaning as in the pains of childbirth right up to the present time.",
    "Not only so, but we ourselves, who have the firstfruits of the Spirit, groan inwardly as we wait eagerly for our adoption as sons, the redemption of our bodies.",
    "For in this hope we were saved. But hope that is seen is no hope at all. Who hopes for what he already has?",
    "But if we hope for what we do not yet have, we wait for it patiently.",
    "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us with groans that words cannot express.",
    "And he who searches our hearts knows the mind of the Spirit, because the Spirit intercedes for the saints in accordance with God's will.",
    "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    "For those God foreknew he also predestined to be conformed to the likeness of his Son, that he might be the firstborn among many brothers.",
    "And those he predestined, he also called; those he called, he also justified; those he justified, he also glorified.",
    "What, then, shall we say in response to this? If God is for us, who can be against us?",
    "He who did not spare his own Son, but gave him up for us all--how will he not also, along with him, graciously give us all things?",
    "Who will bring any charge against those whom God has chosen? It is God who justifies.",
    "Who is he that condemns? Christ Jesus, who died--more than that, who was raised to life--is at the right hand of God and is also interceding for us.",
    "Who shall separate us from the love of Christ? Shall trouble or hardship or persecution or famine or nakedness or danger or sword?",
    "As it is written: \"For your sake we face death all day long; we are considered as sheep to be slaughtered.\"",
    "No, in all these things we are more than conquerors through him who loved us.",
    "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers,",
    "neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord."
  ],
  "Romans-8": [
    "I speak the truth in Christ--I am not lying, my conscience confirms it in the Holy Spirit--",
    "I have great sorrow and unceasing anguish in my heart.",
    "For I could wish that I myself were cursed and cut off from Christ for the sake of my brothers, those of my own race,",
    "the people of Israel. Theirs is the adoption as sons; theirs the divine glory, the covenants, the receiving of the law, the temple worship and the promises.",
    "Theirs are the patriarchs, and from them is traced the human ancestry of Christ, who is God over all, forever praised! Amen.",
    "It is not as though God's word had failed. For not all who are descended from Israel are Israel.",
    "Nor because they are his descendants are they all Abraham's children. On the contrary, \"It is through Isaac that your offspring will be reckoned.\"",
    "In other words, it is not the natural children who are God's children, but it is the children of the promise who are regarded as Abraham's offspring.",
    "For this was how the promise was stated: \"At the appointed time I will return, and Sarah will have a son.\"",
    "Not only that, but Rebekah's children had one and the same father, our father Isaac.",
    "Yet, before the twins were born or had done anything good or bad--in order that God's purpose in election might stand:",
    "not by works but by him who calls--she was told, \"The older will serve the younger.\"",
    "Just as it is written: \"Jacob I loved, but Esau I hated.\"",
    "What then shall we say? Is God unjust? Not at all!",
    "For he says to Moses, \"I will have mercy on whom I have mercy, and I will have compassion on whom I have compassion.\"",
    "It does not, therefore, depend on man's desire or effort, but on God's mercy.",
    "For the Scripture says to Pharaoh: \"I raised you up for this very purpose, that I might display my power in you and that my name might be proclaimed in all the earth.\"",
    "Therefore God has mercy on whom he wants to have mercy, and he hardens whom he wants to harden.",
    "One of you will say to me: \"Then why does God still blame us? For who resists his will?\"",
    "But who are you, O man, to talk back to God? \"Shall what is formed say to him who formed it, 'Why did you make me like this?'\"",
    "Does not the potter have the right to make out of the same lump of clay some pottery for noble purposes and some for common use?",
    "What if God, choosing to show his wrath and make his power known, bore with great patience the objects of his wrath--prepared for destruction?",
    "What if he did this to make the riches of his glory known to the objects of his mercy, whom he prepared in advance for glory--",
    "even us, whom he also called, not only from the Jews but also from the Gentiles?",
    "As he says in Hosea: \"I will call them 'my people' who are not my people; and I will call her 'my loved one' who is not my loved one,\"",
    "and, \"It will happen that in the very place where it was said to them, 'You are not my people,' they will be called 'sons of the living God.'\"",
    "Isaiah cries out concerning Israel: \"Though the number of the Israelites be like the sand by the sea, only the remnant will be saved.",
    "For the Lord will carry out his sentence on earth with speed and finality.\"",
    "It is just as Isaiah said previously: \"Unless the Lord Almighty had left us descendants, we would have become like Sodom, we would have been like Gomorrah.\"",
    "What then shall we say? That the Gentiles, who did not pursue righteousness, have obtained it, a righteousness that is by faith;",
    "but Israel, who pursued a law of righteousness, has not attained it.",
    "Why not? Because they pursued it not by faith but as if it were by works. They stumbled over the \"stumbling stone.\"",
    "As it is written: \"See, I lay in Zion a stone that causes men to stumble and a rock that makes them fall, and the one who trusts in him will never be put to shame.\""
  ],
  "Romans-9": [
    "Brothers, my heart's desire and prayer to God for the Israelites is that they may be saved.",
    "For I can testify about them that they are zealous for God, but their zeal is not based on knowledge.",
    "Since they did not know the righteousness that comes from God and sought to establish their own, they did not submit to God's righteousness.",
    "Christ is the end of the law so that there may be righteousness for everyone who believes.",
    "Moses describes in this way the righteousness that is by the law: \"The man who does these things will live by them.\"",
    "But the righteousness that is by faith says: \"Do not say in your heart, 'Who will ascend into heaven?'\" (that is, to bring Christ down)",
    "\"or 'Who will descend into the deep?'\" (that is, to bring Christ up from the dead).",
    "But what does it say? \"The word is near you; it is in your mouth and in your heart,\" that is, the word of faith we are proclaiming:",
    "That if you confess with your mouth, \"Jesus is Lord,\" and believe in your heart that God raised him from the dead, you will be saved.",
    "For it is with your heart that you believe and are justified, and it is with your mouth that you confess and are saved.",
    "As the Scripture says, \"Anyone who trusts in him will never be put to shame.\"",
    "For there is no difference between Jew and Gentile--the same Lord is Lord of all and richly blesses all who call on him,",
    "for, \"Everyone who calls on the name of the Lord will be saved.\"",
    "How, then, can they call on the one they have not believed in? And how can they believe in the one of whom they have not heard? And how can they hear without someone preaching to them?",
    "And how can they preach unless they are sent? As it is written, \"How beautiful are the feet of those who bring good news!\"",
    "But not all the Israelites accepted the good news. For Isaiah says, \"Lord, who has believed our message?\"",
    "Consequently, faith comes from hearing the message, and the message is heard through the word of Christ.",
    "But I ask: Did they not hear? Of course they did: \"Their voice has gone out into all the earth, their words to the ends of the world.\"",
    "Again I ask: Did Israel not understand? First, Moses says, \"I will make you envious by those who are not a nation; I will make you angry by a nation that has no understanding.\"",
    "And Isaiah boldly says, \"I was found by those who did not seek me; I revealed myself to those who did not ask for me.\"",
    "But concerning Israel he says, \"All day long I have held out my hands to a disobedient and obstinate people.\""
  ],
  "Romans-10": [
    "I ask then: Did God reject his people? By no means! I am an Israelite myself, a descendant of Abraham, from the tribe of Benjamin.",
    "God did not reject his people, whom he foreknew. Don't you know what the Scripture says in the passage about Elijah--how he appealed to God against Israel:",
    "\"Lord, they have killed your prophets and torn down your altars; I am the only one left, and they are trying to kill me\"?",
    "And what was God's answer to him? \"I have reserved for myself seven thousand who have not bowed the knee to Baal.\"",
    "So too, at the present time there is a remnant chosen by grace.",
    "And if by grace, then it is no longer by works; if it were, grace would no longer be grace.",
    "What then? What Israel sought so earnestly it did not obtain, but the elect did. The others were hardened,",
    "as it is written: \"God gave them a spirit of stupor, eyes so that they could not see and ears so that they could not hear, to this very day.\"",
    "And David says: \"May their table become a snare and a trap, a stumbling block and a retribution for them.",
    "May their eyes be darkened so they cannot see, and their backs be bent forever.\"",
    "Again I ask: Did they stumble so as to fall beyond recovery? Not at all! Rather, because of their transgression, salvation has come to the Gentiles to make Israel envious.",
    "But if their transgression means riches for the world, and their loss means riches for the Gentiles, how much greater riches will their fullness bring!",
    "I am talking to you Gentiles. Inasmuch as I am the apostle to the Gentiles, I make much of my ministry",
    "in the hope that I may somehow arouse my own people to envy and save some of them.",
    "For if their rejection is the reconciliation of the world, what will their acceptance be but life from the dead?",
    "If the part of the dough offered as firstfruits is holy, then the whole batch is holy; if the root is holy, so are the branches.",
    "If some of the branches have been broken off, and you, though a wild olive shoot, have been grafted in among the others and now share in the nourishing sap from the olive root,",
    "do not boast over those branches. If you do, consider this: You do not support the root, but the root supports you.",
    "You will say then, \"Branches were broken off so that I could be grafted in.\"",
    "Granted. But they were broken off because of unbelief, and you stand by faith. Do not be arrogant, but be afraid.",
    "For if God did not spare the natural branches, he will not spare you either.",
    "Consider therefore the kindness and sternness of God: sternness to those who fell, but kindness to you, provided that you continue in his kindness. Otherwise, you also will be cut off.",
    "And if they do not persist in unbelief, they will be grafted in, for God is able to graft them in again.",
    "After all, if you were cut out of an olive tree that is wild by nature, and contrary to nature were grafted into a cultivated olive tree, how much more readily will these, the natural branches, be grafted into their own olive tree!",
    "I do not want you to be ignorant of this mystery, brothers, so that you may not be conceited: Israel has experienced a hardening in part until the full number of the Gentiles has come in.",
    "And so all Israel will be saved, as it is written: \"The deliverer will come from Zion; he will turn godlessness away from Jacob.",
    "And this is my covenant with them when I take away their sins.\"",
    "As far as the gospel is concerned, they are enemies on your account; but as far as election is concerned, they are loved on account of the patriarchs,",
    "for God's gifts and his call are irrevocable.",
    "Just as you who were at one time disobedient to God have now received mercy as a result of their disobedience,",
    "so they too have now become disobedient in order that they too may now receive mercy as a result of God's mercy to you.",
    "For God has bound all men over to disobedience so that he may have mercy on them all.",
    "Oh, the depth of the riches of the wisdom and knowledge of God! How unsearchable his judgments, and his paths beyond tracing out!",
    "\"Who has known the mind of the Lord? Or who has been his counselor?\"",
    "\"Who has ever given to God, that God should repay him?\"",
    "For from him and through him and to him are all things. To him be the glory forever! Amen."
  ],
  "Romans-11": [
    "Therefore, I urge you, brothers, in view of God's mercy, to offer your bodies as living sacrifices, holy and pleasing to God--this is your spiritual act of worship.",
    "Do not conform any longer to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God's will is--his good, pleasing and perfect will.",
    "For by the grace given me I say to every one of you: Do not think of yourself more highly than you ought, but rather think of yourself with sober judgment, in accordance with the measure of faith God has given you.",
    "Just as each of us has one body with many members, and these members do not all have the same function,",
    "so in Christ we who are many form one body, and each member belongs to all the others.",
    "We have different gifts, according to the grace given us. If a man's gift is prophesying, let him use it in proportion to his faith.",
    "If it is serving, let him serve; if it is teaching, let him teach;",
    "if it is encouraging, let him encourage; if it is contributing to the needs of others, let him give generously; if it is leadership, let him govern diligently; if it is showing mercy, let him do it cheerfully.",
    "Love must be sincere. Hate what is evil; cling to what is good.",
    "Be devoted to one another in brotherly love. Honor one another above yourselves.",
    "Never be lacking in zeal, but keep your spiritual fervor, serving the Lord.",
    "Be joyful in hope, patient in affliction, faithful in prayer.",
    "Share with God's people who are in need. Practice hospitality.",
    "Bless those who persecute you; bless and do not curse.",
    "Rejoice with those who rejoice; mourn with those who mourn.",
    "Live in harmony with one another. Do not be proud, but be willing to associate with people of low position. Do not be conceited.",
    "Do not repay anyone evil for evil. Be careful to do what is right in the eyes of everybody.",
    "If it is possible, as far as it depends on you, live at peace with everyone.",
    "Do not take revenge, my friends, but leave room for God's wrath, for it is written: \"It is mine to avenge; I will repay,\" says the Lord.",
    "On the contrary: \"If your enemy is hungry, feed him; if he is thirsty, give him something to drink. In doing this, you will heap burning coals on his head.\"",
    "Do not be overcome by evil, but overcome evil with good."
  ],
  "Romans-12": [
    "Everyone must submit himself to the governing authorities, for there is no authority except that which God has established. The authorities that exist have been established by God.",
    "Consequently, he who rebels against the authority is rebelling against what God has instituted, and those who do so will bring judgment on themselves.",
    "For rulers hold no terror for those who do right, but for those who do wrong. Do you want to be free from fear of the one in authority? Then do what is right and he will commend you.",
    "For he is God's servant to do you good. But if you do wrong, be afraid, for he does not bear the sword for nothing. He is God's servant, an agent of wrath to bring punishment on the wrongdoer.",
    "Therefore, it is necessary to submit to the authorities, not only because of possible punishment but also because of conscience.",
    "This is also why you pay taxes, for the authorities are God's servants, who give their full time to governing.",
    "Give everyone what you owe him: If you owe taxes, pay taxes; if revenue, then revenue; if respect, then respect; if honor, then honor.",
    "Let no debt remain outstanding, except the continuing debt to love one another, for he who loves his fellowman has fulfilled the law.",
    "The commandments, \"Do not commit adultery,\" \"Do not murder,\" \"Do not steal,\" \"Do not covet,\" and whatever other commandment there may be, are summed up in this one rule: \"Love your neighbor as yourself.\"",
    "Love does no harm to its neighbor. Therefore love is the fulfillment of the law.",
    "And do this, understanding the present time. The hour has come for you to wake up from your slumber, because our salvation is nearer now than when we first believed.",
    "The night is nearly over; the day is almost here. So let us put aside the deeds of darkness and put on the armor of light.",
    "Let us behave decently, as in the daytime, not in orgies and drunkenness, not in sexual immorality and debauchery, not in dissension and jealousy.",
    "Rather, clothe yourselves with the Lord Jesus Christ, and do not think about how to gratify the desires of the sinful nature."
  ],
  "Romans-13": [
    "Accept him whose faith is weak, without passing judgment on disputable matters.",
    "One man's faith allows him to eat everything, but another man, whose faith is weak, eats only vegetables.",
    "The man who eats everything must not look down on him who does not, and the man who does not eat everything must not condemn the man who does, for God has accepted him.",
    "Who are you to judge someone else's servant? To his own master he stands or falls. And he will stand, for the Lord is able to make him stand.",
    "One man considers one day more sacred than another; another man considers every day alike. Each one should be fully convinced in his own mind.",
    "He who regards one day as special, does so to the Lord. He who eats meat, eats to the Lord, for he gives thanks to God; and he who abstains, does so to the Lord and gives thanks to God.",
    "For none of us lives to himself alone and none of us dies to himself alone.",
    "If we live, we live to the Lord; and if we die, we die to the Lord. So, whether we live or die, we belong to the Lord.",
    "For this very reason, Christ died and returned to life so that he might be the Lord of both the dead and the living.",
    "You, then, why do you judge your brother? Or why do you look down on your brother? For we will all stand before God's judgment seat.",
    "It is written: \"'As surely as I live,' says the Lord, 'every knee will bow before me; every tongue will confess to God.'\"",
    "So then, each of us will give an account of himself to God.",
    "Therefore let us stop passing judgment on one another. Instead, make up your mind not to put any stumbling block or obstacle in your brother's way.",
    "As one who is in the Lord Jesus, I am fully convinced that no food is unclean in itself. But if anyone regards something as unclean, then for him it is unclean.",
    "If your brother is distressed because of what you eat, you are no longer acting in love. Do not by your eating destroy your brother for whom Christ died.",
    "Do not allow what you consider good to be spoken of as evil.",
    "For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit,",
    "because anyone who serves Christ in this way is pleasing to God and approved by men.",
    "Let us therefore make every effort to do what leads to peace and to mutual edification.",
    "Do not destroy the work of God for the sake of food. All food is clean, but it is wrong for a man to eat anything that causes someone else to stumble.",
    "It is better not to eat meat or drink wine or to do anything else that will cause your brother to fall.",
    "So whatever you believe about these things keep between yourself and God. Blessed is the man who does not condemn himself by what he approves.",
    "But the man who has doubts is condemned if he eats, because his eating is not from faith; and everything that does not come from faith is sin."
  ],
  "Romans-14": [
    "We who are strong ought to bear with the failings of the weak and not to please ourselves.",
    "Each of us should please his neighbor for his good, to build him up.",
    "For even Christ did not please himself but, as it is written: \"The insults of those who insult you have fallen on me.\"",
    "For everything that was written in the past was written to teach us, so that through endurance and the encouragement of the Scriptures we might have hope.",
    "May the God who gives endurance and encouragement give you a spirit of unity among yourselves as you follow Christ Jesus,",
    "so that with one heart and mouth you may glorify the God and Father of our Lord Jesus Christ.",
    "Accept one another, then, just as Christ accepted you, in order to bring praise to God.",
    "For I tell you that Christ has become a servant of the Jews on behalf of God's truth, to confirm the promises made to the patriarchs",
    "so that the Gentiles may glorify God for his mercy, as it is written: \"Therefore I will praise you among the Gentiles; I will sing hymns to your name.\"",
    "Again, it says, \"Rejoice, O Gentiles, with his people.\"",
    "And again, \"Praise the Lord, all you Gentiles, and sing praises to him, all you peoples.\"",
    "And again, Isaiah says, \"The Root of Jesse will spring up, one who will arise to rule over the nations; the Gentiles will hope in him.\"",
    "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.",
    "I myself am convinced, my brothers, that you yourselves are full of goodness, complete in knowledge and competent to instruct one another.",
    "I have written you quite boldly on some points, as if to remind you of them again, because of the grace God gave me",
    "to be a minister of Christ Jesus to the Gentiles with the priestly duty of proclaiming the gospel of God, so that the Gentiles might become an offering acceptable to God, sanctified by the Holy Spirit.",
    "Therefore I glory in Christ Jesus in my service to God.",
    "I will not venture to speak of anything except what Christ has accomplished through me in leading the Gentiles to obey God by what I have said and done--",
    "by the power of signs and miracles, through the power of the Spirit. So from Jerusalem all the way around to Illyricum, I have fully proclaimed the gospel of Christ.",
    "It has always been my ambition to preach the gospel where Christ was not known, so that I would not be building on someone else's foundation.",
    "Rather, as it is written: \"Those who were not told about him will see, and those who have not heard will understand.\"",
    "This is why I have often been hindered from coming to you.",
    "But now that there is no more place for me to work in these regions, and since I have been longing for many years to see you,",
    "I plan to do so when I go to Spain. I hope to visit you while passing through and to have you assist me on my journey there, after I have enjoyed your company for a while.",
    "Now, however, I am on my way to Jerusalem in the service of the saints there.",
    "For Macedonia and Achaia were pleased to make a contribution for the poor among the saints in Jerusalem.",
    "They were pleased to do it, and indeed they owe it to them. For if the Gentiles have shared in the Jews' spiritual blessings, they owe it to the Jews to share with them their material blessings.",
    "So after I have completed this task and have made sure that they have received this fruit, I will go to Spain and visit you on the way.",
    "I know that when I come to you, I will come in the full measure of the blessing of Christ.",
    "I urge you, brothers, by our Lord Jesus Christ and by the love of the Spirit, to join me in my struggle by praying to God for me.",
    "Pray that I may be rescued from the unbelievers in Judea and that my service in Jerusalem may be acceptable to the saints there,",
    "so that by God's will I may come to you with joy and together with you be refreshed.",
    "The God of peace be with you all. Amen."
  ],
  "Romans-15": [
    "I commend to you our sister Phoebe, a servant of the church in Cenchrea.",
    "I ask you to receive her in the Lord in a way worthy of the saints and to give her any help she may need from you, for she has been a great help to many people, including me.",
    "Greet Priscilla and Aquila, my fellow workers in Christ Jesus.",
    "They risked their lives for me. Not only I but all the churches of the Gentiles are grateful to them.",
    "Greet also the church that meets at their house. Greet my dear friend Epenetus, who was the first convert to Christ in the province of Asia.",
    "Greet Mary, who worked very hard for you.",
    "Greet Andronicus and Junias, my relatives who have been in prison with me. They are outstanding among the apostles, and they were in Christ before I was.",
    "Greet Ampliatus, whom I love in the Lord.",
    "Greet Urbanus, our fellow worker in Christ, and my dear friend Stachys.",
    "Greet Apelles, tested and approved in Christ. Greet those who belong to the household of Aristobulus.",
    "Greet Herodion, my relative. Greet those in the household of Narcissus who are in the Lord.",
    "Greet Tryphena and Tryphosa, those women who work hard in the Lord. Greet my dear friend Persis, another woman who has worked very hard in the Lord.",
    "Greet Rufus, chosen in the Lord, and his mother, who has been a mother to me, too.",
    "Greet Asyncritus, Phlegon, Hermes, Patrobas, Hermas and the brothers with them.",
    "Greet Philologus, Julia, Nereus and his sister, and Olympas and all the saints with them.",
    "Greet one another with a holy kiss. All the churches of Christ send greetings.",
    "I urge you, brothers, to watch out for those who cause divisions and put obstacles in your way that are contrary to the teaching you have learned. Keep away from them.",
    "For such people are not serving our Lord Christ, but their own appetites. By smooth talk and flattery they deceive the minds of naive people.",
    "Everyone has heard about your obedience, so I am full of joy over you; but I want you to be wise about what is good, and innocent about what is evil.",
    "The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus be with you.",
    "Timothy, my fellow worker, sends his greetings to you, as do Lucius, Jason and Sosipater, my relatives.",
    "I, Tertius, who wrote down this letter, greet you in the Lord.",
    "Gaius, whose hospitality I and the whole church here enjoy, sends you his greetings. Erastus, who is the city's director of public works, and our brother Quartus send you their greetings.",
    "[May the grace of our Lord Jesus Christ be with all of you. Amen.]",
    "Now to him who is able to establish you by my gospel and the proclamation of Jesus Christ, according to the revelation of the mystery hidden for long ages past,",
    "but now revealed and made known through the prophetic writings by the command of the eternal God, so that all nations might believe and obey him--",
    "to the only wise God be glory forever through Jesus Christ! Amen."
  ]
};