const Zechariah = {
  "Zechariah-0": [
    "In the eighth month of the second year of Darius, the word of the LORD came to the prophet Zechariah son of Berekiah, the son of Iddo:",
    "\"The LORD was very angry with your forefathers.",
    "Therefore tell the people: This is what the LORD Almighty says: 'Return to me,' declares the LORD Almighty, 'and I will return to you,' says the LORD Almighty.",
    "Do not be like your forefathers, to whom the earlier prophets proclaimed: This is what the LORD Almighty says: 'Turn from your evil ways and your evil practices.' But they would not listen or pay attention to me, declares the LORD.",
    "Where are your forefathers now? And the prophets, do they live forever?",
    "But did not my words and my decrees, which I commanded my servants the prophets, overtake your forefathers? \"Then they repented and said, 'The LORD Almighty has done to us what our ways and practices deserve, just as he determined to do.'\"",
    "On the twenty-fourth day of the eleventh month, the month of Shebat, in the second year of Darius, the word of the LORD came to the prophet Zechariah son of Berekiah, the son of Iddo.",
    "During the night I had a vision--and there before me was a man riding a red horse! He was standing among the myrtle trees in a ravine. Behind him were red, brown and white horses.",
    "I asked, \"What are these, my lord?\" The angel who was talking with me answered, \"I will show you what they are.\"",
    "Then the man standing among the myrtle trees explained, \"They are the ones the LORD has sent to go throughout the earth.\"",
    "And they reported to the angel of the LORD, who was standing among the myrtle trees, \"We have gone throughout the earth and found the whole world at rest and in peace.\"",
    "Then the angel of the LORD said, \"LORD Almighty, how long will you withhold mercy from Jerusalem and from the towns of Judah, which you have been angry with these seventy years?\"",
    "So the LORD spoke kind and comforting words to the angel who talked with me.",
    "Then the angel who was speaking to me said, \"Proclaim this word: This is what the LORD Almighty says: 'I am very jealous for Jerusalem and Zion,",
    "but I am very angry with the nations that feel secure. I was only a little angry, but they added to the calamity.'",
    "\"Therefore, this is what the LORD says: 'I will return to Jerusalem with mercy, and there my house will be rebuilt. And the measuring line will be stretched out over Jerusalem,' declares the LORD Almighty.",
    "\"Proclaim further: This is what the LORD Almighty says: 'My towns will again overflow with prosperity, and the LORD will again comfort Zion and choose Jerusalem.'\"",
    "Then I looked up--and there before me were four horns!",
    "I asked the angel who was speaking to me, \"What are these?\" He answered me, \"These are the horns that scattered Judah, Israel and Jerusalem.\"",
    "Then the LORD showed me four craftsmen.",
    "I asked, \"What are these coming to do?\" He answered, \"These are the horns that scattered Judah so that no one could raise his head, but the craftsmen have come to terrify them and throw down these horns of the nations who lifted up their horns against the land of Judah to scatter its people.\""
  ],
  "Zechariah-1": [
    "Then I looked up--and there before me was a man with a measuring line in his hand!",
    "I asked, \"Where are you going?\" He answered me, \"To measure Jerusalem, to find out how wide and how long it is.\"",
    "Then the angel who was speaking to me left, and another angel came to meet him",
    "and said to him: \"Run, tell that young man, 'Jerusalem will be a city without walls because of the great number of men and livestock in it.",
    "And I myself will be a wall of fire around it,' declares the LORD, 'and I will be its glory within.'",
    "\"Come! Come! Flee from the land of the north,\" declares the LORD, \"for I have scattered you to the four winds of heaven,\" declares the LORD.",
    "\"Come, O Zion! Escape, you who live in the Daughter of Babylon!\"",
    "For this is what the LORD Almighty says: \"After he has honored me and has sent me against the nations that have plundered you--for whoever touches you touches the apple of his eye--",
    "I will surely raise my hand against them so that their slaves will plunder them. Then you will know that the LORD Almighty has sent me.",
    "\"Shout and be glad, O Daughter of Zion. For I am coming, and I will live among you,\" declares the LORD.",
    "\"Many nations will be joined with the LORD in that day and will become my people. I will live among you and you will know that the LORD Almighty has sent me to you.",
    "The LORD will inherit Judah as his portion in the holy land and will again choose Jerusalem.",
    "Be still before the LORD, all mankind, because he has roused himself from his holy dwelling.\""
  ],
  "Zechariah-2": [
    "Then he showed me Joshua the high priest standing before the angel of the LORD, and Satan standing at his right side to accuse him.",
    "The LORD said to Satan, \"The LORD rebuke you, Satan! The LORD, who has chosen Jerusalem, rebuke you! Is not this man a burning stick snatched from the fire?\"",
    "Now Joshua was dressed in filthy clothes as he stood before the angel.",
    "The angel said to those who were standing before him, \"Take off his filthy clothes.\" Then he said to Joshua, \"See, I have taken away your sin, and I will put rich garments on you.\"",
    "Then I said, \"Put a clean turban on his head.\" So they put a clean turban on his head and clothed him, while the angel of the LORD stood by.",
    "The angel of the LORD gave this charge to Joshua:",
    "\"This is what the LORD Almighty says: 'If you will walk in my ways and keep my requirements, then you will govern my house and have charge of my courts, and I will give you a place among these standing here.",
    "\"'Listen, O high priest Joshua and your associates seated before you, who are men symbolic of things to come: I am going to bring my servant, the Branch.",
    "See, the stone I have set in front of Joshua! There are seven eyes on that one stone, and I will engrave an inscription on it,' says the LORD Almighty, 'and I will remove the sin of this land in a single day.",
    "\"'In that day each of you will invite his neighbor to sit under his vine and fig tree,' declares the LORD Almighty.\""
  ],
  "Zechariah-3": [
    "Then the angel who talked with me returned and wakened me, as a man is wakened from his sleep.",
    "He asked me, \"What do you see?\" I answered, \"I see a solid gold lampstand with a bowl at the top and seven lights on it, with seven channels to the lights.",
    "Also there are two olive trees by it, one on the right of the bowl and the other on its left.\"",
    "I asked the angel who talked with me, \"What are these, my lord?\"",
    "He answered, \"Do you not know what these are?\" \"No, my lord,\" I replied.",
    "So he said to me, \"This is the word of the LORD to Zerubbabel: 'Not by might nor by power, but by my Spirit,' says the LORD Almighty.",
    "\"What are you, O mighty mountain? Before Zerubbabel you will become level ground. Then he will bring out the capstone to shouts of 'God bless it! God bless it!'\"",
    "Then the word of the LORD came to me:",
    "\"The hands of Zerubbabel have laid the foundation of this temple; his hands will also complete it. Then you will know that the LORD Almighty has sent me to you.",
    "\"Who despises the day of small things? Men will rejoice when they see the plumb line in the hand of Zerubbabel. \"(These seven are the eyes of the LORD, which range throughout the earth.)\"",
    "Then I asked the angel, \"What are these two olive trees on the right and the left of the lampstand?\"",
    "Again I asked him, \"What are these two olive branches beside the two gold pipes that pour out golden oil?\"",
    "He replied, \"Do you not know what these are?\" \"No, my lord,\" I said.",
    "So he said, \"These are the two who are anointed to serve the Lord of all the earth.\""
  ],
  "Zechariah-4": [
    "I looked again--and there before me was a flying scroll!",
    "He asked me, \"What do you see?\" I answered, \"I see a flying scroll, thirty feet long and fifteen feet wide.\"",
    "And he said to me, \"This is the curse that is going out over the whole land; for according to what it says on one side, every thief will be banished, and according to what it says on the other, everyone who swears falsely will be banished.",
    "The LORD Almighty declares, 'I will send it out, and it will enter the house of the thief and the house of him who swears falsely by my name. It will remain in his house and destroy it, both its timbers and its stones.'\"",
    "Then the angel who was speaking to me came forward and said to me, \"Look up and see what this is that is appearing.\"",
    "I asked, \"What is it?\" He replied, \"It is a measuring basket.\" And he added, \"This is the iniquity of the people throughout the land.\"",
    "Then the cover of lead was raised, and there in the basket sat a woman!",
    "He said, \"This is wickedness,\" and he pushed her back into the basket and pushed the lead cover down over its mouth.",
    "Then I looked up--and there before me were two women, with the wind in their wings! They had wings like those of a stork, and they lifted up the basket between heaven and earth.",
    "\"Where are they taking the basket?\" I asked the angel who was speaking to me.",
    "He replied, \"To the country of Babylonia to build a house for it. When it is ready, the basket will be set there in its place.\""
  ],
  "Zechariah-5": [
    "I looked up again--and there before me were four chariots coming out from between two mountains--mountains of bronze!",
    "The first chariot had red horses, the second black,",
    "the third white, and the fourth dappled--all of them powerful.",
    "I asked the angel who was speaking to me, \"What are these, my lord?\"",
    "The angel answered me, \"These are the four spirits of heaven, going out from standing in the presence of the Lord of the whole world.",
    "The one with the black horses is going toward the north country, the one with the white horses toward the west, and the one with the dappled horses toward the south.\"",
    "When the powerful horses went out, they were straining to go throughout the earth. And he said, \"Go throughout the earth!\" So they went throughout the earth.",
    "Then he called to me, \"Look, those going toward the north country have given my Spirit rest in the land of the north.\"",
    "The word of the LORD came to me:",
    "\"Take silver and gold from the exiles Heldai, Tobijah and Jedaiah, who have arrived from Babylon. Go the same day to the house of Josiah son of Zephaniah.",
    "Take the silver and gold and make a crown, and set it on the head of the high priest, Joshua son of Jehozadak.",
    "Tell him this is what the LORD Almighty says: 'Here is the man whose name is the Branch, and he will branch out from his place and build the temple of the LORD.",
    "It is he who will build the temple of the LORD, and he will be clothed with majesty and will sit and rule on his throne. And he will be a priest on his throne. And there will be harmony between the two.'",
    "The crown will be given to Heldai, Tobijah, Jedaiah and Hen son of Zephaniah as a memorial in the temple of the LORD.",
    "Those who are far away will come and help to build the temple of the LORD, and you will know that the LORD Almighty has sent me to you. This will happen if you diligently obey the LORD your God.\""
  ],
  "Zechariah-6": [
    "In the fourth year of King Darius, the word of the LORD came to Zechariah on the fourth day of the ninth month, the month of Kislev.",
    "The people of Bethel had sent Sharezer and Regem-Melech, together with their men, to entreat the LORD",
    "by asking the priests of the house of the LORD Almighty and the prophets, \"Should I mourn and fast in the fifth month, as I have done for so many years?\"",
    "Then the word of the LORD Almighty came to me:",
    "\"Ask all the people of the land and the priests, 'When you fasted and mourned in the fifth and seventh months for the past seventy years, was it really for me that you fasted?",
    "And when you were eating and drinking, were you not just feasting for yourselves?",
    "Are these not the words the LORD proclaimed through the earlier prophets when Jerusalem and its surrounding towns were at rest and prosperous, and the Negev and the western foothills were settled?'\"",
    "And the word of the LORD came again to Zechariah:",
    "\"This is what the LORD Almighty says: 'Administer true justice; show mercy and compassion to one another.",
    "Do not oppress the widow or the fatherless, the alien or the poor. In your hearts do not think evil of each other.'",
    "\"But they refused to pay attention; stubbornly they turned their backs and stopped up their ears.",
    "They made their hearts as hard as flint and would not listen to the law or to the words that the LORD Almighty had sent by his Spirit through the earlier prophets. So the LORD Almighty was very angry.",
    "\"'When I called, they did not listen; so when they called, I would not listen,' says the LORD Almighty.",
    "'I scattered them with a whirlwind among all the nations, where they were strangers. The land was left so desolate behind them that no one could come or go. This is how they made the pleasant land desolate.'\""
  ],
  "Zechariah-7": [
    "Again the word of the LORD Almighty came to me.",
    "This is what the LORD Almighty says: \"I am very jealous for Zion; I am burning with jealousy for her.\"",
    "This is what the LORD says: \"I will return to Zion and dwell in Jerusalem. Then Jerusalem will be called the City of Truth, and the mountain of the LORD Almighty will be called the Holy Mountain.\"",
    "This is what the LORD Almighty says: \"Once again men and women of ripe old age will sit in the streets of Jerusalem, each with cane in hand because of his age.",
    "The city streets will be filled with boys and girls playing there.\"",
    "This is what the LORD Almighty says: \"It may seem marvelous to the remnant of this people at that time, but will it seem marvelous to me?\" declares the LORD Almighty.",
    "This is what the LORD Almighty says: \"I will save my people from the countries of the east and the west.",
    "I will bring them back to live in Jerusalem; they will be my people, and I will be faithful and righteous to them as their God.\"",
    "This is what the LORD Almighty says: \"You who now hear these words spoken by the prophets who were there when the foundation was laid for the house of the LORD Almighty, let your hands be strong so that the temple may be built.",
    "Before that time there were no wages for man or beast. No one could go about his business safely because of his enemy, for I had turned every man against his neighbor.",
    "But now I will not deal with the remnant of this people as I did in the past,\" declares the LORD Almighty.",
    "\"The seed will grow well, the vine will yield its fruit, the ground will produce its crops, and the heavens will drop their dew. I will give all these things as an inheritance to the remnant of this people.",
    "As you have been an object of cursing among the nations, O Judah and Israel, so will I save you, and you will be a blessing. Do not be afraid, but let your hands be strong.\"",
    "This is what the LORD Almighty says: \"Just as I had determined to bring disaster upon you and showed no pity when your fathers angered me,\" says the LORD Almighty,",
    "\"so now I have determined to do good again to Jerusalem and Judah. Do not be afraid.",
    "These are the things you are to do: Speak the truth to each other, and render true and sound judgment in your courts;",
    "do not plot evil against your neighbor, and do not love to swear falsely. I hate all this,\" declares the LORD.",
    "Again the word of the LORD Almighty came to me.",
    "This is what the LORD Almighty says: \"The fasts of the fourth, fifth, seventh and tenth months will become joyful and glad occasions and happy festivals for Judah. Therefore love truth and peace.\"",
    "This is what the LORD Almighty says: \"Many peoples and the inhabitants of many cities will yet come,",
    "and the inhabitants of one city will go to another and say, 'Let us go at once to entreat the LORD and seek the LORD Almighty. I myself am going.'",
    "And many peoples and powerful nations will come to Jerusalem to seek the LORD Almighty and to entreat him.\"",
    "This is what the LORD Almighty says: \"In those days ten men from all languages and nations will take firm hold of one Jew by the hem of his robe and say, 'Let us go with you, because we have heard that God is with you.'\" An Oracle"
  ],
  "Zechariah-8": [
    "The word of the LORD is against the land of Hadrach and will rest upon Damascus--for the eyes of men and all the tribes of Israel are on the LORD--",
    "and upon Hamath too, which borders on it, and upon Tyre and Sidon, though they are very skillful.",
    "Tyre has built herself a stronghold; she has heaped up silver like dust, and gold like the dirt of the streets.",
    "But the Lord will take away her possessions and destroy her power on the sea, and she will be consumed by fire.",
    "Ashkelon will see it and fear; Gaza will writhe in agony, and Ekron too, for her hope will wither. Gaza will lose her king and Ashkelon will be deserted.",
    "Foreigners will occupy Ashdod, and I will cut off the pride of the Philistines.",
    "I will take the blood from their mouths, the forbidden food from between their teeth. Those who are left will belong to our God and become leaders in Judah, and Ekron will be like the Jebusites.",
    "But I will defend my house against marauding forces. Never again will an oppressor overrun my people, for now I am keeping watch.",
    "Rejoice greatly, O Daughter of Zion! Shout, Daughter of Jerusalem! See, your king comes to you, righteous and having salvation, gentle and riding on a donkey, on a colt, the foal of a donkey.",
    "I will take away the chariots from Ephraim and the war-horses from Jerusalem, and the battle bow will be broken. He will proclaim peace to the nations. His rule will extend from sea to sea and from the River to the ends of the earth.",
    "As for you, because of the blood of my covenant with you, I will free your prisoners from the waterless pit.",
    "Return to your fortress, O prisoners of hope; even now I announce that I will restore twice as much to you.",
    "I will bend Judah as I bend my bow and fill it with Ephraim. I will rouse your sons, O Zion, against your sons, O Greece, and make you like a warrior's sword.",
    "Then the LORD will appear over them; his arrow will flash like lightning. The Sovereign LORD will sound the trumpet; he will march in the storms of the south,",
    "and the LORD Almighty will shield them. They will destroy and overcome with slingstones. They will drink and roar as with wine; they will be full like a bowl used for sprinkling the corners of the altar.",
    "The LORD their God will save them on that day as the flock of his people. They will sparkle in his land like jewels in a crown.",
    "How attractive and beautiful they will be! Grain will make the young men thrive, and new wine the young women."
  ],
  "Zechariah-9": [
    "Ask the LORD for rain in the springtime; it is the LORD who makes the storm clouds. He gives showers of rain to men, and plants of the field to everyone.",
    "The idols speak deceit, diviners see visions that lie; they tell dreams that are false, they give comfort in vain. Therefore the people wander like sheep oppressed for lack of a shepherd.",
    "\"My anger burns against the shepherds, and I will punish the leaders; for the LORD Almighty will care for his flock, the house of Judah, and make them like a proud horse in battle.",
    "From Judah will come the cornerstone, from him the tent peg, from him the battle bow, from him every ruler.",
    "Together they will be like mighty men trampling the muddy streets in battle. Because the LORD is with them, they will fight and overthrow the horsemen.",
    "\"I will strengthen the house of Judah and save the house of Joseph. I will restore them because I have compassion on them. They will be as though I had not rejected them, for I am the LORD their God and I will answer them.",
    "The Ephraimites will become like mighty men, and their hearts will be glad as with wine. Their children will see it and be joyful; their hearts will rejoice in the LORD.",
    "I will signal for them and gather them in. Surely I will redeem them; they will be as numerous as before.",
    "Though I scatter them among the peoples, yet in distant lands they will remember me. They and their children will survive, and they will return.",
    "I will bring them back from Egypt and gather them from Assyria. I will bring them to Gilead and Lebanon, and there will not be room enough for them.",
    "They will pass through the sea of trouble; the surging sea will be subdued and all the depths of the Nile will dry up. Assyria's pride will be brought down and Egypt's scepter will pass away.",
    "I will strengthen them in the LORD and in his name they will walk,\" declares the LORD."
  ],
  "Zechariah-10": [
    "Open your doors, O Lebanon, so that fire may devour your cedars!",
    "Wail, O pine tree, for the cedar has fallen; the stately trees are ruined! Wail, oaks of Bashan; the dense forest has been cut down!",
    "Listen to the wail of the shepherds; their rich pastures are destroyed! Listen to the roar of the lions; the lush thicket of the Jordan is ruined!",
    "This is what the LORD my God says: \"Pasture the flock marked for slaughter.",
    "Their buyers slaughter them and go unpunished. Those who sell them say, 'Praise the LORD, I am rich!' Their own shepherds do not spare them.",
    "For I will no longer have pity on the people of the land,\" declares the LORD. \"I will hand everyone over to his neighbor and his king. They will oppress the land, and I will not rescue them from their hands.\"",
    "So I pastured the flock marked for slaughter, particularly the oppressed of the flock. Then I took two staffs and called one Favor and the other Union, and I pastured the flock.",
    "In one month I got rid of the three shepherds. The flock detested me, and I grew weary of them",
    "and said, \"I will not be your shepherd. Let the dying die, and the perishing perish. Let those who are left eat one another's flesh.\"",
    "Then I took my staff called Favor and broke it, revoking the covenant I had made with all the nations.",
    "It was revoked on that day, and so the afflicted of the flock who were watching me knew it was the word of the LORD.",
    "I told them, \"If you think it best, give me my pay; but if not, keep it.\" So they paid me thirty pieces of silver.",
    "And the LORD said to me, \"Throw it to the potter\"--the handsome price at which they priced me! So I took the thirty pieces of silver and threw them into the house of the LORD to the potter.",
    "Then I broke my second staff called Union, breaking the brotherhood between Judah and Israel.",
    "Then the LORD said to me, \"Take again the equipment of a foolish shepherd.",
    "For I am going to raise up a shepherd over the land who will not care for the lost, or seek the young, or heal the injured, or feed the healthy, but will eat the meat of the choice sheep, tearing off their hoofs.",
    "\"Woe to the worthless shepherd, who deserts the flock! May the sword strike his arm and his right eye! May his arm be completely withered, his right eye totally blinded!\" An Oracle"
  ],
  "Zechariah-11": [
    "This is the word of the LORD concerning Israel. The LORD, who stretches out the heavens, who lays the foundation of the earth, and who forms the spirit of man within him, declares:",
    "\"I am going to make Jerusalem a cup that sends all the surrounding peoples reeling. Judah will be besieged as well as Jerusalem.",
    "On that day, when all the nations of the earth are gathered against her, I will make Jerusalem an immovable rock for all the nations. All who try to move it will injure themselves.",
    "On that day I will strike every horse with panic and its rider with madness,\" declares the LORD. \"I will keep a watchful eye over the house of Judah, but I will blind all the horses of the nations.",
    "Then the leaders of Judah will say in their hearts, 'The people of Jerusalem are strong, because the LORD Almighty is their God.'",
    "\"On that day I will make the leaders of Judah like a firepot in a woodpile, like a flaming torch among sheaves. They will consume right and left all the surrounding peoples, but Jerusalem will remain intact in her place.",
    "\"The LORD will save the dwellings of Judah first, so that the honor of the house of David and of Jerusalem's inhabitants may not be greater than that of Judah.",
    "On that day the LORD will shield those who live in Jerusalem, so that the feeblest among them will be like David, and the house of David will be like God, like the Angel of the LORD going before them.",
    "On that day I will set out to destroy all the nations that attack Jerusalem.",
    "\"And I will pour out on the house of David and the inhabitants of Jerusalem a spirit of grace and supplication. They will look on me, the one they have pierced, and they will mourn for him as one mourns for an only child, and grieve bitterly for him as one grieves for a firstborn son.",
    "On that day the weeping in Jerusalem will be great, like the weeping of Hadad Rimmon in the plain of Megiddo.",
    "The land will mourn, each clan by itself, with their wives by themselves: the clan of the house of David and their wives, the clan of the house of Nathan and their wives,",
    "the clan of the house of Levi and their wives, the clan of Shimei and their wives,",
    "and all the rest of the clans and their wives."
  ],
  "Zechariah-12": [
    "\"On that day a fountain will be opened to the house of David and the inhabitants of Jerusalem, to cleanse them from sin and impurity.",
    "\"On that day, I will banish the names of the idols from the land, and they will be remembered no more,\" declares the LORD Almighty. \"I will remove both the prophets and the spirit of impurity from the land.",
    "And if anyone still prophesies, his father and mother, to whom he was born, will say to him, 'You must die, because you have told lies in the LORD'S name.' When he prophesies, his own parents will stab him.",
    "\"On that day every prophet will be ashamed of his prophetic vision. He will not put on a prophet's garment of hair in order to deceive.",
    "He will say, 'I am not a prophet. I am a farmer; the land has been my livelihood since my youth.'",
    "If someone asks him, 'What are these wounds on your body?' he will answer, 'The wounds I was given at the house of my friends.'",
    "\"Awake, O sword, against my shepherd, against the man who is close to me!\" declares the LORD Almighty. \"Strike the shepherd, and the sheep will be scattered, and I will turn my hand against the little ones.",
    "In the whole land,\" declares the LORD, \"two-thirds will be struck down and perish; yet one-third will be left in it.",
    "This third I will bring into the fire; I will refine them like silver and test them like gold. They will call on my name and I will answer them; I will say, 'They are my people,' and they will say, 'The LORD is our God.'\""
  ],
  "Zechariah-13": [
    "A day of the LORD is coming when your plunder will be divided among you.",
    "I will gather all the nations to Jerusalem to fight against it; the city will be captured, the houses ransacked, and the women raped. Half of the city will go into exile, but the rest of the people will not be taken from the city.",
    "Then the LORD will go out and fight against those nations, as he fights in the day of battle.",
    "On that day his feet will stand on the Mount of Olives, east of Jerusalem, and the Mount of Olives will be split in two from east to west, forming a great valley, with half of the mountain moving north and half moving south.",
    "You will flee by my mountain valley, for it will extend to Azel. You will flee as you fled from the earthquake in the days of Uzziah king of Judah. Then the LORD my God will come, and all the holy ones with him.",
    "On that day there will be no light, no cold or frost.",
    "It will be a unique day, without daytime or nighttime--a day known to the LORD. When evening comes, there will be light.",
    "On that day living water will flow out from Jerusalem, half to the eastern sea and half to the western sea, in summer and in winter.",
    "The LORD will be king over the whole earth. On that day there will be one LORD, and his name the only name.",
    "The whole land, from Geba to Rimmon, south of Jerusalem, will become like the Arabah. But Jerusalem will be raised up and remain in its place, from the Benjamin Gate to the site of the First Gate, to the Corner Gate, and from the Tower of Hananel to the royal winepresses.",
    "It will be inhabited; never again will it be destroyed. Jerusalem will be secure.",
    "This is the plague with which the LORD will strike all the nations that fought against Jerusalem: Their flesh will rot while they are still standing on their feet, their eyes will rot in their sockets, and their tongues will rot in their mouths.",
    "On that day men will be stricken by the LORD with great panic. Each man will seize the hand of another, and they will attack each other.",
    "Judah too will fight at Jerusalem. The wealth of all the surrounding nations will be collected--great quantities of gold and silver and clothing.",
    "A similar plague will strike the horses and mules, the camels and donkeys, and all the animals in those camps.",
    "Then the survivors from all the nations that have attacked Jerusalem will go up year after year to worship the King, the LORD Almighty, and to celebrate the Feast of Tabernacles.",
    "If any of the peoples of the earth do not go up to Jerusalem to worship the King, the LORD Almighty, they will have no rain.",
    "If the Egyptian people do not go up and take part, they will have no rain. The LORD will bring on them the plague he inflicts on the nations that do not go up to celebrate the Feast of Tabernacles.",
    "This will be the punishment of Egypt and the punishment of all the nations that do not go up to celebrate the Feast of Tabernacles.",
    "On that day HOLY TO THE LORD will be inscribed on the bells of the horses, and the cooking pots in the LORD'S house will be like the sacred bowls in front of the altar.",
    "Every pot in Jerusalem and Judah will be holy to the LORD Almighty, and all who come to sacrifice will take some of the pots and cook in them. And on that day there will no longer be a Canaanite in the house of the LORD Almighty."
  ]
};